// mod8-clock.ts — DOES THE CLOCK COME FROM THE CLIFFORD ALGEBRA OR FROM THE CODE?
//
// THE QUESTION. `src/Core/CliffordPeriodicity.fs:168` (`halvesSeparateCleanly`) carries the repo's
// only computed "mod-8 clock": the even subalgebra preserves the boson/fermion halves ("what
// remains"), the odd part swaps them ("what acts"), and the two halves separate into independent
// blocks exactly when the even part lands on a split row of the Atiyah-Bott-Shapiro table. That
// function is keyed on a SIGNATURE LITERAL `(p,q)` and never looks at an adinkra. Meanwhile
// `regular-representation-defect.ts` builds real edge operators for every doubly-even code and
// never asks the clock question of them. Nothing joins the two, which is the gap this file closes.
//
// The live dispute is about ORIGIN. Two candidates, and they make opposite predictions:
//
//   ORIGIN A — the code.  A doubly-even self-dual binary code exists only at length divisible by
//     8 (Gleason; Mallows-Sloane). If the clock comes from there, it must vanish where the code
//     does.
//   ORIGIN B — the Clifford algebra.  Real Clifford algebras repeat with period 8 in the
//     signature (Cartan; Bott 1959; Atiyah-Bott-Shapiro 1964, "Clifford Modules"; the tabular form
//     is Budinich-Trautman, *The Spinorial Chessboard*, 1988). If the clock comes from there, it
//     is indifferent to the code.
//
// THE EXPERIMENT, and why its design matters. Comparing the coded tower against the codeless tower
// varies two things at once — the code, and every other way two different constructions differ. So
// the measurement below is done WITHIN ONE OBJECT: one adinkra, one code, and the only thing that
// varies is whether the code's support meets the colour set being measured. At N = 8 with the
// self-dual [8,4,4] code there are C(8,4) = 70 four-colour subsets, of which 56 miss every codeword
// and 14 carry one (`regular-representation-defect.test.ts`, "free over Cl(0,T) exactly when no
// nonzero codeword is supported inside T"). Those 56 and those 14 are the treatment and control
// groups, and they are already known to DIFFER on a different observable — freeness — which is what
// makes the experiment non-blind: if the clock also differed, we would see it.
//
// WHAT "A MOD-8 CLOCK" MEANS HERE, pinned down before anything is measured, because an unpinned
// quantity cannot be falsified:
//
//     clock(T) = ( dim A_T, dim Z(A_T), omega^2, dim A_T^0, dim Z(A_T^0), omega0^2, separates )
//
// for A_T the algebra generated by the edge operators of the colours in T, A_T^0 its even part,
// Z the centre, omega the top product, and `separates` := Z(A_T^0) is 2-dimensional with its
// nontrivial element squaring to +1 (so the two central idempotents (1 +/- omega0)/2 are real and
// the even algebra is a direct sum of two ideals). `separates` is the operator-level form of
// `halvesSeparateCleanly`.
//
// TWO ROUTES, SHARING NO INTERMEDIATE — the discipline `mod-eight-correspondence.ts` set for
// itself ("a check that `e^{i pi n/4} === 1` exactly when 8 divides n would be a tautology"):
//
//   ROUTE M (matrix). Composes the adinkra's ACTUAL signed-permutation operators and decides
//     commutation by comparing matrices entry by entry. Never evaluates a sign formula.
//   ROUTE B (blade). Works on bitmasks with `cliffordSign` and decides commutation from the
//     reordering parity. Never builds a matrix, never knows there is an adinkra.
//
// Neither route contains `n % 8` anywhere. The period is READ OFF the resulting table, not
// asserted — which is the only way this can come out other than as expected.
//
// Anchors (each used for what it actually entails): Atiyah, Bott & Shapiro, *Clifford Modules*,
// Topology 3 (1964) — the mod-8 periodicity of real Clifford algebras, the load-bearing citation
// for ORIGIN B; Bott (1959) for the periodicity theorem the above specialises; Cartan for the
// original classification of real Clifford algebras; Gleason / Mallows-Sloane for ORIGIN A's
// length-divisible-by-8 theorem, which is included because without it the two origins would not
// be distinguishable and the experiment would have nothing to decide; Doran, Faux, Gates, Huebsch,
// Iga & Landweber, arXiv:0806.0051, for the adinkra/doubly-even-code correspondence the operators
// are built from.

import {
  buildCodedAdinkra,
  cliffordSign,
  enumerateDoublyEvenCodes,
  type CodedAdinkra,
  type Mask,
} from "./regular-representation-defect.js";

/** The clock reading of a colour set. Every field is measured; none is derived from `N % 8`. */
export interface ClockReading {
  /** |T| — the number of colours measured. */
  readonly colours: number;
  /** dim of the algebra generated by { L_I : I in T }. */
  readonly algebraDim: number;
  /** dim of the centre of that algebra. */
  readonly centreDim: number;
  /**
   * The square of the top product `omega = prod_{I in T} L_I`, as +1 or -1, or 0 when `omega` is
   * not central (in which case it names no direct-sum decomposition).
   */
  readonly omegaSquare: number;
  /** dim of the even subalgebra (words of even length). */
  readonly evenDim: number;
  /** dim of the centre of the even subalgebra. */
  readonly evenCentreDim: number;
  /** The square of the even part's nontrivial central element, or 0 when there is none. */
  readonly evenOmegaSquare: number;
  /**
   * The operator-level form of `CliffordPeriodicity.halvesSeparateCleanly`: the even subalgebra
   * splits into two ideals, so "what remains" resolves into two independent blocks.
   */
  readonly separates: boolean;
}

function readingKey(r: ClockReading): string {
  return [
    r.algebraDim,
    r.centreDim,
    r.omegaSquare,
    r.evenDim,
    r.evenCentreDim,
    r.evenOmegaSquare,
    r.separates ? 1 : 0,
  ].join("|");
}

/** True when two readings agree in every field. Exported so tests compare by value, not by hand. */
export function readingsEqual(a: ClockReading, b: ClockReading): boolean {
  return readingKey(a) === readingKey(b);
}

// ─────────────────────────────────────────────────────────────────────────────────────────────
// ROUTE B — blades and bitmasks. No matrices.
// ─────────────────────────────────────────────────────────────────────────────────────────────

/** Enumerate every sub-mask of `t` (the blades supported inside the colour set). */
function subMasks(t: Mask): Mask[] {
  const out: Mask[] = [];
  for (let s = t; ; s = (s - 1) & t) {
    out.push(s);
    if (s === 0) break;
  }
  return out;
}

function popcount(x: number): number {
  let c = 0;
  let v = x;
  while (v !== 0) {
    v &= v - 1;
    c++;
  }
  return c;
}

/**
 * ROUTE B. The clock reading computed from the Clifford multiplication rule on bitmasks.
 *
 * Blades multiply as `gamma_A gamma_B = cliffordSign(A,B) gamma_{A xor B}`, and multiplication
 * permutes the blade basis up to sign. So an element `x = sum c_S gamma_S` is central exactly when
 * `c_S = 0` for every blade that fails to commute with some generator — the centre is spanned by
 * the COMMUTING BLADES, and its dimension is their count. Same argument inside the even part,
 * against the even generators.
 *
 * `t` is a bitmask naming the colour set. `square` is what each generator squares to.
 */
export function clockByBlades(t: Mask, square: 1 | -1): ClockReading {
  const colours: number[] = [];
  for (let i = 0; i < 32; i++) if ((t >> i) & 1) colours.push(i);
  const blades = subMasks(t);

  const commutesWith = (s: Mask, g: Mask): boolean =>
    cliffordSign(s, g, square) === cliffordSign(g, s, square);

  // generators of the algebra: the single colours. generators of the even part: gamma_{I0} gamma_{Ij}.
  const gens = colours.map((i) => 1 << i);
  const first = gens[0];
  const evenGens = first === undefined ? [] : gens.slice(1).map((g) => first ^ g);

  const centre = blades.filter((s) => gens.every((g) => commutesWith(s, g)));
  const evenBlades = blades.filter((s) => popcount(s) % 2 === 0);
  const evenCentre = evenBlades.filter((s) => evenGens.every((g) => commutesWith(s, g)));

  const squareOfCentre = (members: Mask[]): number => {
    const nontrivial = members.filter((s) => s !== 0);
    const w = nontrivial[0];
    if (nontrivial.length === 0 || w === undefined) return 0;
    return cliffordSign(w, w, square);
  };

  const evenOmegaSquare = squareOfCentre(evenCentre);
  return {
    colours: colours.length,
    algebraDim: blades.length,
    centreDim: centre.length,
    omegaSquare: squareOfCentre(centre),
    evenDim: evenBlades.length,
    evenCentreDim: evenCentre.length,
    evenOmegaSquare,
    separates: evenCentre.length === 2 && evenOmegaSquare === 1,
  };
}

// ─────────────────────────────────────────────────────────────────────────────────────────────
// ROUTE M — the adinkra's own operators, composed as matrices.
// ─────────────────────────────────────────────────────────────────────────────────────────────

interface SP {
  readonly to: Int32Array;
  readonly sign: Int8Array;
}

function compose(a: SP, b: SP, dim: number): SP {
  // (a . b)(v) = a(b(v))
  const to = new Int32Array(dim);
  const sign = new Int8Array(dim);
  for (let v = 0; v < dim; v++) {
    const bv = b.to[v] ?? 0;
    to[v] = a.to[bv] ?? 0;
    sign[v] = ((b.sign[v] ?? 0) * (a.sign[bv] ?? 0)) as number;
  }
  return { to, sign };
}

function identity(dim: number): SP {
  return { to: Int32Array.from({ length: dim }, (_, i) => i), sign: new Int8Array(dim).fill(1) };
}

function sameSP(a: SP, b: SP, dim: number): boolean {
  for (let v = 0; v < dim; v++) {
    if (a.to[v] !== b.to[v] || a.sign[v] !== b.sign[v]) return false;
  }
  return true;
}

function negated(a: SP, dim: number): SP {
  const sign = new Int8Array(dim);
  for (let v = 0; v < dim; v++) sign[v] = -(a.sign[v] ?? 0) as number;
  return { to: a.to, sign };
}

function isScalar(a: SP, dim: number): number {
  // returns +1 / -1 when `a` is that multiple of the identity, else 0
  const s = a.sign[0] ?? 0;
  for (let v = 0; v < dim; v++) {
    if (a.to[v] !== v || a.sign[v] !== s) return 0;
  }
  return s;
}

function key(a: SP, dim: number): string {
  const parts: string[] = [];
  for (let v = 0; v < dim; v++) parts.push(`${a.to[v]}:${a.sign[v]}`);
  return parts.join(",");
}

/**
 * ROUTE M. The clock reading computed by composing the adinkra's actual edge operators and
 * comparing matrices. `subset` lists colour indices.
 *
 * A word in the generators is again a signed permutation, and words over distinct blades are
 * linearly independent when their underlying permutations differ — which they do here, because the
 * colour operators act by distinct coset translations. So `dim A_T` is the number of distinct
 * words up to sign, and the centre is decided by literal matrix comparison rather than by any sign
 * rule. Nothing in this function knows what `cliffordSign` is.
 */
export function clockByMatrices(a: CodedAdinkra, subset: number[]): ClockReading {
  const dim = a.reps.length;
  const words = new Map<number, SP>(); // blade index (bit pattern over `subset`) -> operator
  for (let bits = 0; bits < 1 << subset.length; bits++) {
    let w = identity(dim);
    for (let t = 0; t < subset.length; t++) {
      if (((bits >> t) & 1) === 0) continue;
      const colour = subset[t];
      if (colour === undefined) continue;
      const op = a.L[colour];
      if (op === undefined) throw new Error(`no operator for colour ${colour}`);
      w = compose(op, w, dim);
    }
    words.set(bits, w);
  }

  // dim A_T: distinct words modulo sign — the span's dimension, measured on the matrices.
  const upToSign = new Set<string>();
  for (const w of words.values()) {
    const k1 = key(w, dim);
    const k2 = key(negated(w, dim), dim);
    upToSign.add(k1 < k2 ? k1 : k2);
  }

  const gens = subset.map((_, t) => 1 << t);
  const commutes = (x: SP, y: SP): boolean => sameSP(compose(x, y, dim), compose(y, x, dim), dim);

  const centre: number[] = [];
  for (const [bits, w] of words) {
    if (gens.every((g) => commutes(w, words.get(g) ?? identity(dim)))) centre.push(bits);
  }

  const evenBits = [...words.keys()].filter((b) => popcount(b) % 2 === 0);
  const firstGen = gens[0];
  const evenGens =
    firstGen === undefined ? [] : gens.slice(1).map((g) => words.get(firstGen ^ g) ?? identity(dim));
  const evenCentre = evenBits.filter((b) => {
    const w = words.get(b);
    return w !== undefined && evenGens.every((g) => commutes(w, g));
  });

  const sqOf = (members: number[]): number => {
    const nt = members.filter((b) => b !== 0);
    const b = nt[0];
    if (b === undefined) return 0;
    const w = words.get(b);
    if (w === undefined) return 0;
    return isScalar(compose(w, w, dim), dim);
  };

  const evenOmegaSquare = sqOf(evenCentre);
  return {
    colours: subset.length,
    algebraDim: upToSign.size,
    centreDim: centre.length,
    omegaSquare: sqOf(centre),
    evenDim: evenBits.length,
    evenCentreDim: evenCentre.length,
    evenOmegaSquare,
    separates: evenCentre.length === 2 && evenOmegaSquare === 1,
  };
}

// ─────────────────────────────────────────────────────────────────────────────────────────────
// The sweeps
// ─────────────────────────────────────────────────────────────────────────────────────────────

/** All `k`-subsets of `{0..n-1}`, as colour-index arrays. */
export function subsets(n: number, k: number): number[][] {
  const out: number[][] = [];
  const cur: number[] = [];
  const walk = (start: number): void => {
    if (cur.length === k) {
      out.push([...cur]);
      return;
    }
    for (let i = start; i < n; i++) {
      cur.push(i);
      walk(i + 1);
      cur.pop();
    }
  };
  walk(0);
  return out;
}

/** Does the code have a nonzero codeword supported inside the colour set? */
export function codeTouches(code: Mask[], subset: number[]): boolean {
  let mask = 0;
  for (const c of subset) mask |= 1 << c;
  return code.some((c) => c !== 0 && (c & ~mask) === 0);
}

export interface PeriodResult {
  /** `separates` at each `N`, index 0 unused so that `flags[N]` reads directly. */
  readonly flags: boolean[];
  /** The smallest `p >= 1` with `flags[N] === flags[N + p]` throughout the measured range. */
  readonly period: number;
  /** The `N` at which `separates` is true. */
  readonly separatingN: number[];
}

/**
 * Sweep the CODELESS tower and measure the period of `separates` directly, without ever asking
 * `N % 8`. The period is found by searching for the smallest shift under which the measured flag
 * sequence is invariant — so it can come out as anything, including "no period in range".
 */
export function separationPeriod(maxN: number, square: 1 | -1): PeriodResult {
  const flags: boolean[] = [false];
  for (let n = 1; n <= maxN; n++) {
    flags.push(clockByBlades((1 << n) - 1, square).separates);
  }
  let period = 0;
  for (let p = 1; p <= maxN; p++) {
    let ok = true;
    let compared = 0;
    for (let n = 1; n + p <= maxN; n++) {
      compared++;
      if (flags[n] !== flags[n + p]) {
        ok = false;
        break;
      }
    }
    // A shift with nothing to compare against is not evidence of a period.
    if (ok && compared >= p) {
      period = p;
      break;
    }
  }
  return {
    flags,
    period,
    separatingN: flags.map((f, n) => (f ? n : -1)).filter((n) => n > 0),
  };
}

/** Build the N = 8 self-dual adinkra used as the within-object experiment's single object. */
export function selfDualAdinkraN8(square: 1 | -1): CodedAdinkra {
  const codes = enumerateDoublyEvenCodes(8);
  const selfDual = codes.filter((g) => g.length === 4);
  const chosen = selfDual[0];
  if (chosen === undefined) throw new Error("no self-dual doubly-even code of length 8 found");
  return buildCodedAdinkra(8, chosen, square);
}

// ─────────────────────────────────────────────────────────────────────────────────────────────
// WHERE THE PERIOD-8 INVARIANT ACTUALLY LIVES
// ─────────────────────────────────────────────────────────────────────────────────────────────
//
// The separation clock above turns out to have period 4 on this family, not 8. The genuine
// period-8 Atiyah-Bott-Shapiro invariant is the MORITA GROUND — whether the simple module's
// endomorphism ring is R, C or H — and that is a different observable. `commutantDim` measures the
// quantity it is read from, and the measurement shows why the codeless tower cannot show it: for
// `k = 0` the vertex module IS the regular representation, whose endomorphism algebra is the whole
// algebra again (dimension 2^N), so the ground is hidden by construction. It becomes visible only
// once a code shrinks the module — which inverts the usual telling, in which the code only takes
// things away.

/**
 * `dim End_A(M)` — the dimension of the space of matrices commuting with every edge operator.
 *
 * Derivation of the recurrence, so the union-find below is not a magic trick. Writing the signed
 * permutation as `L_{to[j], j} = sign[j]`, the condition `L X = X L` reads
 *
 *     X[to[i]][to[j]] = sign[i] * sign[j] * X[i][j]
 *
 * — an orbit relation on index PAIRS carrying a sign. So the commutant's dimension is the number
 * of orbits on which the accumulated sign is consistent; an orbit that returns to itself with the
 * opposite sign forces its entries to zero and contributes nothing. Exact integer arithmetic, no
 * elimination, `O(|V|^2 * N)`.
 */
export function commutantDim(a: CodedAdinkra): number {
  const dim = a.reps.length;
  const total = dim * dim;
  const parent = new Int32Array(total);
  const parity = new Int8Array(total); // sign relative to the representative
  for (let i = 0; i < total; i++) {
    parent[i] = i;
    parity[i] = 1;
  }
  const find = (x: number): { root: number; sign: number } => {
    let r = x;
    let s = 1;
    while (parent[r] !== r) {
      s *= parity[r] ?? 1;
      r = parent[r] ?? r;
    }
    return { root: r, sign: s };
  };
  const inconsistent = new Set<number>();
  const union = (x: number, y: number, rel: number): void => {
    const fx = find(x);
    const fy = find(y);
    if (fx.root === fy.root) {
      if (fx.sign * fy.sign !== rel) inconsistent.add(fx.root);
      return;
    }
    parent[fy.root] = fx.root;
    parity[fy.root] = (rel * fx.sign * fy.sign) as number;
    if (inconsistent.delete(fy.root)) inconsistent.add(fx.root);
  };

  for (const op of a.L) {
    for (let i = 0; i < dim; i++) {
      for (let j = 0; j < dim; j++) {
        const ti = op.to[i] ?? 0;
        const tj = op.to[j] ?? 0;
        const rel = (op.sign[i] ?? 1) * (op.sign[j] ?? 1);
        union(i * dim + j, ti * dim + tj, rel);
      }
    }
  }
  const roots = new Set<number>();
  for (let i = 0; i < total; i++) roots.add(find(i).root);
  let free = 0;
  for (const r of roots) if (!inconsistent.has(r)) free++;
  return free;
}
