// src/Core.TypeScript/research/adinkra-ecc/regular-representation-defect.ts
//
// **The homoiconicity defect of a coded adinkra, computed by two independent routes.**
//
// Question (Aaron, 2026-08-18, continuing Lumen 2026-08-14 §2.1/§2.4): is there a CODED
// adinkra whose vertex module is still free of rank 1 over the algebra generated by its own
// edge operators — i.e. a nontrivial doubly-even code whose quotient is still a regular
// representation?
//
// This module answers it mechanically. For a doubly-even code C of length N and dimension k it
// builds the coded adinkra's edge operators L_1..L_N as explicit signed permutation matrices on
// the coset space GF(2)^N / C, then computes:
//
//   ROUTE A — dim of the algebra generated by {L_I}, by closing the LINEAR SPAN of words in the
//             generators under multiplication. Never mentions N, k, |C| or the coset count.
//   ROUTE V — dim of the module, by COUNTING COSETS of C in GF(2)^N. Never touches a matrix.
//
// A homoiconic pair (A, M, rho) needs rho : A -> M an isomorphism of A-modules, so it needs
// dim A == dim M. The DEFECT is dim(routeA) / dim(routeV). The prediction under test is that it
// equals |C| exactly — hence 1 iff the code is trivial, hence NO coded adinkra is homoiconic.
//
// The two routes share no intermediate quantity, so the comparison can fail. That is the point:
// `docs/FROZEN-CORE-AND-CONJECTURE-REGISTER.md` demoted six rows on 2026-08-01 for self-certifying
// harnesses, and `.claude/rules/toy-is-free-metered-must-be-earned.md` is the standing bar.
//
// ARITHMETIC HONESTY. Ranks are computed over the prime field F_p rather than over Q. Reduction
// mod p can only LOWER the rank of an integer matrix, so a computed rank of r proves rank_Q >= r.
// Every assertion below is of the form "rank equals its theoretical MAXIMUM", so the F_p lower
// bound settles it exactly; no probabilistic step enters. Two primes are used as a cross-check.
//
// Anchors (checked, used, not decorative):
//  - Doran, Faux, Gates, Hubsch, Iga, Landweber, arXiv:0806.0051 — adinkraic chromotopologies are
//    exactly GF(2)^N / C for C doubly-even. This is what licenses the coset construction below.
//  - Gleason / Mallows-Sloane — doubly-even self-orthogonal forces k <= N/2, with equality only at
//    N ≡ 0 (mod 8). Used by `selfOrthogonalBound` to place the self-dual point.

/** A codeword / blade / subset of {0..N-1}, as a bitmask. */
export type Mask = number;

export const PRIMES = [1000003, 999983] as const;

/** Population count of a bitmask. */
export function popcount(x: Mask): number {
  let c = 0;
  while (x !== 0) {
    x &= x - 1;
    c++;
  }
  return c;
}

/**
 * Sign of the Clifford product `gamma_A * gamma_B = sign * gamma_(A xor B)` in a real Clifford
 * algebra whose generators all square to `square` (+1 or -1).
 *
 * Two contributions: (-1)^{#{(i,j) : i in A, j in B, i > j}} from reordering, and
 * `square^{|A & B|}` from the pairs that collide.
 */
export function cliffordSign(a: Mask, b: Mask, square: 1 | -1): 1 | -1 {
  let swaps = 0;
  for (let i = 0; i < 32; i++) {
    if ((a >> i) & 1) {
      // count j in B with j < i
      const lower = b & ((1 << i) - 1);
      swaps += popcount(lower);
    }
  }
  const collide = popcount(a & b);
  const s = ((swaps & 1) === 0 ? 1 : -1) * (square === 1 ? 1 : (collide & 1) === 0 ? 1 : -1);
  return s as 1 | -1;
}

/** Enumerate the 2^k codewords spanned by `generators` (as bitmasks). */
export function enumerateCode(generators: Mask[]): Mask[] {
  const out: Mask[] = [0];
  for (const g of generators) {
    const cur = out.slice();
    for (const c of cur) if (!out.includes(c ^ g)) out.push(c ^ g);
  }
  return out.sort((x, y) => x - y);
}

export function isDoublyEven(code: Mask[]): boolean {
  return code.every((c) => popcount(c) % 4 === 0);
}

/** Self-orthogonality over GF(2): every pair of codewords meets in an even number of places. */
export function isSelfOrthogonal(code: Mask[]): boolean {
  for (const a of code) for (const b of code) if (popcount(a & b) % 2 !== 0) return false;
  return true;
}

/** Gleason/Mallows-Sloane: a doubly-even code is self-orthogonal, so k <= floor(N/2). */
export function selfOrthogonalBound(n: number): number {
  return Math.floor(n / 2);
}

/**
 * The signed code group. For a doubly-even code, the blades `gamma_c` (c in C) pairwise commute
 * and square to +1, but a PRODUCT of generator blades equals `eps(c) * gamma_c` for a sign
 * `eps(c)` that is not always +1. `eps` is what makes `E = <gamma_{c_1}..gamma_{c_k}>` an honest
 * elementary abelian 2-group of order 2^k rather than a group of order 2^{k+1} containing -1
 * (which would make the projector `e` vanish).
 *
 * Returns a map codeword -> sign, and throws if -1 is reachable (which would refute the
 * construction rather than the theorem, so it must be checked, not assumed).
 */
export function signedCodeGroup(generators: Mask[], square: 1 | -1): Map<Mask, 1 | -1> {
  const eps = new Map<Mask, 1 | -1>([[0, 1]]);
  for (const g of generators) {
    for (const [c, s] of [...eps]) {
      // (eps(c) gamma_c) * gamma_g = eps(c) * cliffordSign(c, g) * gamma_{c^g}
      const t = (s * cliffordSign(c, g, square)) as 1 | -1;
      const key = c ^ g;
      const prior = eps.get(key);
      if (prior !== undefined && prior !== t) {
        throw new Error(`signed code group contains -1 at codeword ${key}: projector would vanish`);
      }
      if (prior === undefined) eps.set(key, t);
    }
  }
  return eps;
}

export interface CodedAdinkra {
  readonly n: number;
  readonly k: number;
  readonly code: Mask[];
  /** Coset representatives, one per vertex; `vertexCount === code-index`. */
  readonly reps: Mask[];
  /** repOf[mask] = index into `reps` of the coset containing `mask`. */
  readonly repOf: Int32Array;
  /** L[i] is a signed permutation on the vertex space: L[i][v] = [targetVertex, sign]. */
  readonly L: { to: Int32Array; sign: Int8Array }[];
}

/**
 * Build the coded adinkra's edge operators.
 *
 * The vertex module is `M = Cl * e` where `e = prod_i (1 + eps(c_i) gamma_{c_i}) / 2`. A basis is
 * `v_R = gamma_R e` for R ranging over coset representatives, and left multiplication acts by
 *   gamma_I * v_R = cliffordSign(e_I, R) * gamma_{I^R} e
 *                 = cliffordSign(e_I, R) * eps(c) * cliffordSign(R', c) * v_{R'}
 * where R' is the representative of the coset of I^R and c = (I^R) ^ R'.
 */
export function buildCodedAdinkra(
  n: number,
  generators: Mask[],
  square: 1 | -1,
  /**
   * Scan order for picking coset representatives: masks are visited as `m XOR repSeed`, so a
   * nonzero seed selects a different representative from each coset. The verdict must not depend
   * on this choice, and the sweep exercises several seeds.
   *
   * HONEST MEASUREMENT, 2026-08-18. `eps` is -1 on 1254 of the 6042 codewords swept, but it is
   * +1 on **every value this construction actually consumes**, at every seed tried — because a
   * representative and its single-bit neighbour can only differ by a codeword that is reachable
   * in one step, and the composite codewords carrying `eps = -1` never arise that way. So
   * deleting `eps` is an EQUIVALENT MUTATION here: nothing in the sweep detects it. It is kept
   * because the derivation needs it in general (the projector `e` is built from the signed group,
   * not from bare blades), and it is covered by its own unit test rather than by the sweep.
   * Recording this because a surviving mutation left unexplained is indistinguishable from an
   * untested line — `.claude/rules/toy-is-free-metered-must-be-earned.md`.
   */
  repSeed = 0,
): CodedAdinkra {
  const code = enumerateCode(generators);
  if (!isDoublyEven(code)) throw new Error("code is not doubly even — not an adinkraic chromotopology");
  const eps = signedCodeGroup(generators, square);
  const size = 1 << n;

  // ROUTE V: cosets, counted combinatorially. No matrix is touched here.
  const repOf = new Int32Array(size).fill(-1);
  const reps: Mask[] = [];
  for (let i = 0; i < size; i++) {
    const m = i ^ repSeed;
    if (repOf[m] !== -1) continue;
    const idx = reps.length;
    reps.push(m);
    for (const c of code) repOf[m ^ c] = idx;
  }

  const L: SignedPerm[] = [];
  for (let i = 0; i < n; i++) {
    const bit = 1 << i;
    const to = new Int32Array(reps.length);
    const sign = new Int8Array(reps.length);
    for (let v = 0; v < reps.length; v++) {
      const R = reps[v] ?? 0;
      const S = R ^ bit;
      const s1 = cliffordSign(bit, R, square);
      const vp = repOf[S] ?? 0;
      const Rp = reps[vp] ?? 0;
      const c = S ^ Rp;
      const s2 = eps.get(c);
      if (s2 === undefined) throw new Error(`coset difference ${c} is not a codeword`);
      const s3 = cliffordSign(Rp, c, square);
      to[v] = vp;
      sign[v] = s1 * s2 * s3;
    }
    L.push({ to, sign });
  }
  return { n, k: generators.length, code, reps, repOf, L };
}

function modInverse(a: number, p: number): number {
  let [old_r, r] = [a % p, p];
  let [old_s, s] = [1, 0];
  while (r !== 0) {
    const q = Math.floor(old_r / r);
    [old_r, r] = [r, old_r - q * r];
    [old_s, s] = [s, old_s - q * s];
  }
  return ((old_s % p) + p) % p;
}

/**
 * Incremental row-reduced basis over F_p. `add` returns true when the vector was independent of
 * everything already held (and then keeps it).
 */
export class SpanBasis {
  private readonly pivots: number[] = [];
  private readonly rows: Int32Array[] = [];
  private readonly p: number;
  constructor(p: number) {
    this.p = p;
  }
  get size(): number {
    return this.rows.length;
  }
  add(vec: ArrayLike<number>): boolean {
    const p = this.p;
    const v = Int32Array.from(vec, (x) => ((x % p) + p) % p);
    for (let i = 0; i < this.rows.length; i++) {
      const pc = this.pivots[i] ?? 0;
      const f = v[pc] ?? 0;
      if (f === 0) continue;
      const row = this.rows[i];
      if (row === undefined) continue;
      for (let j = pc; j < v.length; j++) {
        const rj = row[j] ?? 0;
        if (rj === 0) continue;
        const nv = ((v[j] ?? 0) - f * rj) % p;
        v[j] = nv < 0 ? nv + p : nv;
      }
    }
    let pivot = -1;
    for (let j = 0; j < v.length; j++)
      if ((v[j] ?? 0) !== 0) {
        pivot = j;
        break;
      }
    if (pivot === -1) return false;
    const inv = modInverse(v[pivot] ?? 0, p);
    for (let j = pivot; j < v.length; j++) {
      const vj = v[j] ?? 0;
      if (vj !== 0) v[j] = (vj * inv) % p;
    }
    this.rows.push(v);
    this.pivots.push(pivot);
    return true;
  }
}

interface SignedPerm {
  to: Int32Array;
  sign: Int8Array;
}

function composeSigned(outer: SignedPerm, inner: SignedPerm, dim: number): SignedPerm {
  // (outer * inner) sends basis vector j -> inner takes j to inner.to[j] with inner.sign[j],
  // then outer takes that to outer.to[inner.to[j]].
  const to = new Int32Array(dim);
  const sign = new Int8Array(dim);
  for (let j = 0; j < dim; j++) {
    const mid = inner.to[j] ?? 0;
    to[j] = outer.to[mid] ?? 0;
    sign[j] = (inner.sign[j] ?? 0) * (outer.sign[mid] ?? 0);
  }
  return { to, sign };
}

// Keys are built by packing each column into one UTF-16 code unit and taking the string. That
// is ~20x faster than template-literal concatenation in a loop and is what keeps the exhaustive
// N=8 sweep inside a sane wall-clock budget (bunfig.toml: slow-by-nature carries its own
// timeout, slow-by-accident gets made fast).
function signedKey(sp: SignedPerm, dim: number): string {
  const buf = new Uint16Array(dim);
  for (let j = 0; j < dim; j++) buf[j] = ((sp.to[j] ?? 0) << 1) | ((sp.sign[j] ?? 0) > 0 ? 0 : 1);
  return String.fromCharCode.apply(null, Array.from(buf));
}

function permKey(sp: SignedPerm): string {
  return String.fromCharCode.apply(null, Array.from(sp.to));
}

/**
 * ROUTE A — the dimension of the algebra generated by the edge operators.
 *
 * Every word in the generators is again a SIGNED PERMUTATION, so the algebra is the linear span
 * of the finite group `G = <L_1..L_N>` of signed permutations. Two signed permutations with
 * DIFFERENT underlying permutations have disjoint supports, hence are automatically linearly
 * independent; two with the SAME underlying permutation differ only by a diagonal of signs. So
 *
 *     dim A = sum over underlying permutations pi of rank{ sign vectors of the elements over pi }.
 *
 * That makes the computation cheap and exact without ever forming a |V|^2-dimensional space.
 *
 * Reads only the matrices. Never touches N, k, |C| or the coset count — Route V's quantities.
 */
export function algebraDimension(a: CodedAdinkra, p: number): number {
  const dim = a.reps.length;
  const id: SignedPerm = { to: Int32Array.from({ length: dim }, (_, i) => i), sign: new Int8Array(dim).fill(1) };
  const seen = new Map<string, SignedPerm>([[signedKey(id, dim), id]]);
  const queue: SignedPerm[] = [id];
  while (queue.length > 0) {
    const m = queue.pop();
    if (m === undefined) break;
    for (const op of a.L) {
      const prod = composeSigned(op, m, dim);
      const key = signedKey(prod, dim);
      if (!seen.has(key)) {
        seen.set(key, prod);
        queue.push(prod);
      }
    }
  }
  const byPerm = new Map<string, SignedPerm[]>();
  for (const sp of seen.values()) {
    const k = permKey(sp);
    const bucket = byPerm.get(k);
    if (bucket) bucket.push(sp);
    else byPerm.set(k, [sp]);
  }
  let total = 0;
  for (const bucket of byPerm.values()) {
    const basis = new SpanBasis(p);
    for (const sp of bucket) basis.add(sp.sign);
    total += basis.size;
  }
  return total;
}

/**
 * The defining relations the edge operators MUST satisfy for the coset construction to be an
 * adinkra at all: `L_I L_J + L_J L_I = 2 delta_IJ * square * Id`. This is the garden-algebra
 * relation of Gates & Faux with `d_tau` normalised to 1 (Lumen 2026-08-14 §2.3).
 *
 * Checked rather than assumed. Without it the sweep below would still report ranks — of an
 * object that is not an adinkra — which is the vacuity class the register was burned by on
 * 2026-08-01. Dropping the `eps` sign correction in `buildCodedAdinkra` leaves every rank
 * assertion passing and breaks exactly this one; that is why it is here.
 */
export function cliffordRelationsHold(a: CodedAdinkra, square: 1 | -1): boolean {
  const dim = a.reps.length;
  for (let i = 0; i < a.n; i++) {
    const Li = a.L[i];
    for (let j = 0; j < a.n; j++) {
      const Lj = a.L[j];
      if (Li === undefined || Lj === undefined) return false;
      const ij = composeSigned(Li, Lj, dim);
      const ji = composeSigned(Lj, Li, dim);
      for (let v = 0; v < dim; v++) {
        if (i === j) {
          if (ij.to[v] !== v || ij.sign[v] !== square) return false;
        } else {
          // anticommute: same target, opposite signs, so the anticommutator vanishes
          if (ij.to[v] !== ji.to[v]) return false;
          if ((ij.sign[v] ?? 0) + (ji.sign[v] ?? 0) !== 0) return false;
        }
      }
    }
  }
  return true;
}

/** The group order |G| of the signed permutations generated by the edge operators. */
export function edgeGroupOrder(a: CodedAdinkra): number {
  const dim = a.reps.length;
  const id: SignedPerm = { to: Int32Array.from({ length: dim }, (_, i) => i), sign: new Int8Array(dim).fill(1) };
  const seen = new Set<string>([signedKey(id, dim)]);
  const queue: SignedPerm[] = [id];
  while (queue.length > 0) {
    const m = queue.pop();
    if (m === undefined) break;
    for (const op of a.L) {
      const prod = composeSigned(op, m, dim);
      const key = signedKey(prod, dim);
      if (!seen.has(key)) {
        seen.add(key);
        queue.push(prod);
      }
    }
  }
  return seen.size;
}

/**
 * The positive residue: is `M` free of rank 1 over the SUBALGEBRA generated by the colours in
 * `subset`, with the base point `v_0 = e`? Computes the rank of { L_S v_0 : S subset of `subset` }.
 * Free of rank 1 iff that rank is |V|, which also forces |subset| = N - k.
 */
export function freeOverSubalgebra(a: CodedAdinkra, subset: number[], p: number): number {
  const dim = a.reps.length;
  const zero = a.repOf[0] ?? 0;
  const basis = new SpanBasis(p);
  const cols = subset.length;
  for (let bits = 0; bits < 1 << cols; bits++) {
    const v = new Int32Array(dim);
    v[zero] = 1;
    // apply L_i for i in `subset`, in increasing colour order (one fixed word per blade)
    for (let t = 0; t < cols; t++) {
      if (((bits >> t) & 1) === 0) continue;
      const colour = subset[t];
      if (colour === undefined) continue;
      const op = a.L[colour];
      if (op === undefined) continue;
      const w = new Int32Array(dim);
      for (let j = 0; j < dim; j++) {
        const vj = v[j] ?? 0;
        if (vj === 0) continue;
        const tgt = op.to[j] ?? 0;
        const x = ((w[tgt] ?? 0) + (op.sign[j] ?? 0) * vj) % p;
        w[tgt] = x < 0 ? x + p : x;
      }
      v.set(w);
    }
    basis.add(v);
  }
  return basis.size;
}

const codeCache = new Map<number, Mask[][]>();

/**
 * All doubly-even self-orthogonal linear codes of length `n`, one generator-mask list per
 * distinct code. Memoised: the sweeps below call this once per test and it is the hot path.
 */
export function enumerateDoublyEvenCodes(n: number): Mask[][] {
  const hit = codeCache.get(n);
  if (hit) return hit;
  const computed = enumerateDoublyEvenCodesUncached(n);
  codeCache.set(n, computed);
  return computed;
}

function enumerateDoublyEvenCodesUncached(n: number): Mask[][] {
  const size = 1 << n;
  const de: Mask[] = [];
  for (let m = 1; m < size; m++) if (popcount(m) % 4 === 0) de.push(m);
  const out: Mask[][] = [[]];
  const seen = new Set<string>([""]);
  let frontier: Mask[][] = [[]];
  while (frontier.length > 0) {
    const next: Mask[][] = [];
    for (const gens of frontier) {
      const cur = enumerateCode(gens);
      for (const g of de) {
        if (cur.includes(g)) continue;
        const cand = [...gens, g];
        const code = enumerateCode(cand);
        if (!isDoublyEven(code) || !isSelfOrthogonal(code)) continue;
        const key = code.join(",");
        if (seen.has(key)) continue;
        seen.add(key);
        out.push(cand);
        next.push(cand);
      }
    }
    frontier = next;
  }
  return out;
}
