namespace Zeta.Core.FSharp.ZetaId

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

module GeneratedBitLayout =
    let VersionOffset = 123
    let VersionWidth = 5
    let TimestampOffset = 75
    let TimestampWidth = 48
    let ChromosomeOffset = 70
    let ChromosomeWidth = 5
    let CategoryOffset = 65
    let CategoryWidth = 4
    let FireflyOffset = 64
    let FireflyWidth = 1
    let AuthorityOffset = 59
    let AuthorityWidth = 5
    let PersonaOffset = 51
    let PersonaWidth = 8
    let MomentumOffset = 43
    let MomentumWidth = 8
    let LocationOffset = 35
    let LocationWidth = 8
    let RandomnessOffset = 0
    let RandomnessWidth = 32
