namespace Zeta.Core.FSharp.ZetaId

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

module GeneratedBitLayout =
    let VersionOffset = 123<bit>
    let VersionWidth = 5<bit>
    let TimestampOffset = 75<bit>
    let TimestampWidth = 48<bit>
    let ChromosomeOffset = 70<bit>
    let ChromosomeWidth = 5<bit>
    let CategoryOffset = 65<bit>
    let CategoryWidth = 4<bit>
    let FireflyOffset = 64<bit>
    let FireflyWidth = 1<bit>
    let AuthorityOffset = 59<bit>
    let AuthorityWidth = 5<bit>
    let PersonaOffset = 51<bit>
    let PersonaWidth = 8<bit>
    let MomentumOffset = 43<bit>
    let MomentumWidth = 8<bit>
    let LocationOffset = 35<bit>
    let LocationWidth = 8<bit>
    let RandomnessOffset = 0<bit>
    let RandomnessWidth = 32<bit>
