// Vocabulary single-file index builder (Aaron, 2026-06-09): "small enough to cache all
// over the place… build a single-file index of everything over and over as a cache."
// Regenerates docs/VOCAB-INDEX.md from the canonical homes — deterministic (same input
// -> byte-identical output), so it's a cheap, content-stable cache. Run with --check to
// fail if the committed index is stale (CI gate).
//   bun tools/hygiene/build-vocab-index.ts          (rewrite the index)
//   bun tools/hygiene/build-vocab-index.ts --check   (verify it's up to date; exit 1 if not)
import { readdirSync, lstatSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, basename, relative } from "node:path";

const DOCS = new URL("../../docs/", import.meta.url).pathname;
const OUT = join(DOCS, "VOCAB-INDEX.md");
const HOMES = ["grams", "letters", "shapes", "colors", "temperatures", "travelers"];

function walk(dir: string): string[] {
  const out: string[] = [];
  if (!existsSync(dir)) return out;
  for (const name of readdirSync(dir).sort()) {
    if (name === "README.md") continue;
    const p = join(dir, name);
    const st = lstatSync(p);
    if (st.isSymbolicLink()) continue;          // index canonical files only (symlinks are views)
    if (st.isDirectory()) out.push(...walk(p));
    else if (name.endsWith(".md")) out.push(p);
  }
  return out;
}

/** the carved sentence = first "> " line; else first non-heading line. */
function carved(file: string): string {
  const lines = readFileSync(file, "utf8").split("\n");
  const q = lines.find((l) => l.startsWith("> "));
  if (q) return q.slice(2).trim();
  const t = lines.find((l) => l.trim() && !l.startsWith("#"));
  return (t ?? "").trim();
}

const rows: { home: string; term: string; path: string; carved: string }[] = [];
for (const home of HOMES) {
  for (const f of walk(join(DOCS, home))) {
    rows.push({ home, term: basename(f, ".md"), path: relative(DOCS, f), carved: carved(f) });
  }
}
rows.sort((a, b) => (a.home + a.term).localeCompare(b.home + b.term));

let md = `# VOCAB-INDEX — single-file cache of every traveler (GENERATED)\n\n`;
md += `> Do NOT edit by hand. Regenerated by \`tools/hygiene/build-vocab-index.ts\` from the\n`;
md += `> canonical homes (grams/letters/shapes/colors/temperatures) + travelers/ intake.\n`;
md += `> Deterministic (content-stable) — it's a cache; rebuild over and over. ${rows.length} travelers.\n\n`;
let lastHome = "";
for (const r of rows) {
  if (r.home !== lastHome) { md += `\n## ${r.home}\n\n`; lastHome = r.home; }
  md += `- **${r.term}** — ${r.carved} \`(${r.path})\`\n`;
}

const check = process.argv.includes("--check");
const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (check) {
  if (current !== md) { console.error("VOCAB-INDEX.md is STALE — run: bun tools/hygiene/build-vocab-index.ts"); process.exit(1); }
  console.log(`VOCAB-INDEX: up to date (${rows.length} travelers).`);
} else {
  writeFileSync(OUT, md);
  console.log(`VOCAB-INDEX: wrote ${rows.length} travelers -> docs/VOCAB-INDEX.md`);
}
