// Reify the vocabulary as F# (Aaron, 2026-06-09: "get that F# soon so the math nerds can
// model everything based on this — nerds like F#, not TS"). Generates a clean, warning-free
// F# module from the canonical TYPE homes: a `TravelerId` DU (compiler-enforced membership —
// remove a traveler and exhaustive matches fail to COMPILE) + a `Traveler` record list + a
// lookup map. The hand-written F# code-gen step before a full type provider; deterministic,
// --check gates staleness. Output is an ISOLATED project (not in Zeta.sln) so the main build
// gate is never touched until the Core team promotes it.
//   bun tools/hygiene/build-vocab-fsharp.ts          (regenerate)
//   bun tools/hygiene/build-vocab-fsharp.ts --check   (verify fresh; exit 1 if stale)
import { readdirSync, lstatSync, existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename, relative, dirname } from "node:path";

const DOCS = new URL("../../docs/", import.meta.url).pathname;
const OUT = new URL("../vocab/Vocab.Generated.fs", import.meta.url).pathname;
const CANON = ["words", "letters", "shapes", "colors", "temperatures", "personas"];

function walk(dir: string): string[] {
  const out: string[] = [];
  if (!existsSync(dir)) return out;
  for (const n of readdirSync(dir).sort()) {
    if (n === "README.md" || n === "INDEX.md") continue;
    const p = join(dir, n); const st = lstatSync(p);
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) out.push(...walk(p));
    else if (n.endsWith(".md")) out.push(p);
  }
  return out;
}
const carved = (f: string) => (readFileSync(f, "utf8").split("\n").find((l) => l.startsWith("> ")) ?? "").slice(2).trim();
const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
// NOTE: ZetaId is a GOVERNED, structured primitive (Zeta.Core.{FSharp,CSharp,Rust}.ZetaId,
// TS zeta-id) with Category/Persona/etc. — NOT a hash we invent here. (A truncated SHA-256 is a
// Reticulum *destination*, explicitly NOT a ZetaId — see docs/PRIMITIVE-REGISTRY.md.) So this
// generator does NOT mint ZetaIds; travelers get their ZetaId from the governed generator (deferred).
type Row = { term: string; type: string; carved: string };
const rows: Row[] = [];
for (const home of CANON) for (const f of walk(join(DOCS, home)))
  rows.push({ term: basename(f, ".md"), type: home, carved: carved(f) });
rows.sort((a, b) => a.term.localeCompare(b.term));

let fs = `// GENERATED by tools/hygiene/build-vocab-fsharp.ts — DO NOT EDIT.\n`;
fs += `// Reified vocabulary (CoreDORA): ${rows.length} travelers, from docs/{${CANON.join(",")}}/.\n`;
fs += `// The math team models against these types; the DU gives compiler-enforced membership.\n`;
fs += `namespace Zeta.Vocab\n\n`;
fs += `/// Every traveler as a DU case (backtick-quoted). Exhaustive matches fail to compile if the vocab changes.\n`;
fs += `[<RequireQualifiedAccess>]\n`;
fs += `type TravelerId =\n`;
for (const r of rows) fs += `    | \`\`${r.term}\`\`\n`;
fs += `\n/// A traveler's reified data. Equality model (matches the filesystem symlinks):\n`;
fs += `///  - TravelerId is a nullary DU => a SINGLETON: TravelerId.\`\`x\`\` is ONE instance everywhere\n`;
fs += `///    (.NET reference equality for free) — like a symlink resolving to one inode.\n`;
fs += `///  - Traveler is INTERNED below (all/byId/byTerm hold the one instance per Id), so going\n`;
fs += `///    through them gives Object.ReferenceEquals = true for the "same" traveler (the symlink\n`;
fs += `///    sameness). Structural (value) equality also holds; content-addressing makes them coincide.\n`;
fs += `///  - ZetaId is DEFERRED: it is a GOVERNED, structured primitive (Zeta.Core.*.ZetaId), minted by\n`;
fs += `///    the governed generator — NOT a hash invented here. Every interface sharing a traveler's\n`;
fs += `///    name INHERITS that traveler's 128-bit ZetaId (name -> ZetaId binding). Wire it via the\n`;
fs += `///    governed generator; do not fake it.\n`;
fs += `type Traveler = { Id: TravelerId; Term: string; Type: string; Carved: string }\n\n`;
fs += `module Travelers =\n`;
fs += `    /// All travelers, sorted by term — the reified master index (the interned instances).\n`;
fs += `    let all : Traveler list =\n`;
fs += `        [\n`;
for (const r of rows) fs += `            { Id = TravelerId.\`\`${r.term}\`\`; Term = "${esc(r.term)}"; Type = "${r.type}"; Carved = "${esc(r.carved)}" }\n`;
fs += `        ]\n\n`;
fs += `    /// Lookup by Id — returns the interned instance (reference equality across the codebase).\n`;
fs += `    let byId : Map<TravelerId, Traveler> = all |> List.map (fun t -> t.Id, t) |> Map.ofList\n`;
fs += `    /// Lookup by term string — returns the same interned instance.\n`;
fs += `    let byTerm : Map<string, Traveler> = all |> List.map (fun t -> t.Term, t) |> Map.ofList\n`;

const check = process.argv.includes("--check");
const cur = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
if (check) {
  if (cur !== fs) { console.error("Vocab.Generated.fs is STALE — run: bun tools/hygiene/build-vocab-fsharp.ts"); process.exit(1); }
  console.log(`vocab-fsharp: up to date (${rows.length} travelers).`);
} else {
  mkdirSync(dirname(OUT), { recursive: true });
  writeFileSync(OUT, fs);
  console.log(`vocab-fsharp: wrote ${rows.length} travelers -> ${relative(DOCS + "..", OUT)}`);
}
