using System;
using System.Collections.Generic;
using Xunit;
using Zeta.Core.CSharp;

namespace Zeta.Tests.CSharp;

/// <summary>
/// Tests for <see cref="SchemaCodegen"/> (approach B — the C#-native codegen tool): a zeta
/// <see cref="TypeSchema"/> renders to a deterministic, byte-lockable C# record source.
/// </summary>
public class SchemaCodegenTests
{
    private static readonly TypeSchema ImdbName = new(
        "Zeta.Generated",
        "ImdbName",
        new List<SchemaField>
        {
            new("Nconst", "string"),
            new("PrimaryName", "string"),
            new("BirthYear", "int?"),
            new("DeathYear", "int?"),
        });

    [Fact]
    public void GeneratesExpectedRecordSource()
    {
        string src = SchemaCodegen.Generate(ImdbName);
        const string Expected =
            "// <auto-generated/> Generated by Zeta.Core.CSharp.SchemaCodegen from a zeta type schema. Do not edit.\n"
            + "#nullable enable\n"
            + "namespace Zeta.Generated;\n\n"
            + "public sealed record ImdbName(string Nconst, string PrimaryName, int? BirthYear, int? DeathYear);\n";
        Assert.Equal(Expected, src);
    }

    [Fact]
    public void IsDeterministic()
    {
        Assert.Equal(SchemaCodegen.Generate(ImdbName), SchemaCodegen.Generate(ImdbName));
    }

    [Fact]
    public void PreservesFieldOrderAndNullability()
    {
        string src = SchemaCodegen.Generate(ImdbName);
        Assert.Contains(
            "string Nconst, string PrimaryName, int? BirthYear, int? DeathYear",
            src,
            StringComparison.Ordinal);
    }

    [Fact]
    public void SingleFieldSchemaRenders()
    {
        var schema = new TypeSchema("Zeta.Generated", "Tconst", new List<SchemaField> { new("Id", "string") });
        Assert.Contains("public sealed record Tconst(string Id);", SchemaCodegen.Generate(schema), StringComparison.Ordinal);
    }
}
