// Zeta pre-cluster SSH Certificate Authority + cert signing — the forward-compatible
// "Option B" slice of the unified key-onboarding flow (workitem
// 081KVM1TK3Z08QG0R0002959G6 §"Trust distribution" + §"Pre-cluster bootstrap"). It
// SHIPS THE MECHANISM ONLY; it generates NO real CA and commits NO real CA key.
//
// THE TRUST MODEL (why a CA at all):
//   Today every node carries a LIST of trusted pubkeys
//   (full-ai-cluster/nixos/modules/operator-ssh-keys.nix → authorizedKeys.keys) — the
//   N×M trap: every node must list every dev machine. The SSH-CA replaces that list:
//   nodes trust ONE CA pubkey (`TrustedUserCAKeys`); each dev machine's device key is
//   SIGNED into a cert carrying `principal=<user>` + machine id + a validity window
//   (the rolling-keys discipline). N-trust-1, not N×M; revocation is per-machine.
//   git is the DISTRIBUTION channel for the CA *public* key — never the secret store.
//   Migration (no model change): this git-distributed CA pubkey → Vault custody +
//   cert-manager issuance/rotation later (same shape).
//
// SECURITY INVARIANTS (security-class slice — honesty over green):
//  1. The CA PRIVATE key + any seed NEVER touch argv / stdout / git. The CA keypair is
//     generated by the injected `CaEffects.genCa` door, which writes the private key to a
//     local file under umask 077 (the runner's job) and returns ONLY the PUBLIC key text.
//     Private bytes never cross this module's boundary, are never printed, never returned.
//  2. Only the CA PUBLIC key and CERTS (certs are public) are publishable. `ensureCa`
//     writes ONLY the public key to maintainers/<ca>/ssh-ca.pub; `signMachineCert` writes
//     ONLY a `-cert.pub` (a public certificate). This module commits NOTHING.
//  3. `--dry-run` generates NOTHING and writes NOTHING — returns "would-*".
//  4. CA-keypair GENERATION is OPERATOR-RUN. This PR ships the mechanism; the operator runs
//     `ca` later to produce the real CA + the real ssh-ca.pub. No real CA key is committed.
//
// Noninterference (manifesto §13): the host environment (filesystem, ssh-keygen runner)
// enters ONLY through the injected `CaEffects` — so the dry-run + the temp-dir tests are
// deterministic and never touch a real CA, real keys, or the network.
//
// Anchors (Beacon): OpenSSH certificate authorities — `ssh-keygen(1)` `-s`/`-I`/`-n`/`-V`,
// `sshd(8)` `TrustedUserCAKeys`, OpenSSH `PROTOCOL.certkeys`. ed25519 keys — Bernstein et
// al. (Ed25519, 2011). The "one CA, N machines" model = SSH host/user-CA prior art
// (Facebook/Netflix BLESS-style short-lived SSH certs). Vault SSH secrets engine + Jetstack
// cert-manager = the in-cluster migration target (same trust model, upgraded custody).
import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
// SHARED biometric-approval gate — the agent EXECUTES keygen/sign; the operator's Touch ID /
// Windows Hello is the AUTHORIZATION (Aaron 2026-06-21). Both sensitive ops (generate CA key,
// sign a cert with the CA private key) are gated FAIL-CLOSED behind a biometric confirm.
import { requireBiometric, type BiometricAuth, type BiometricResult } from "./biometric.ts";
import {
  assertGatedCeremony,
  ceremonyPromptLine,
  realBriefEffects,
  renderCeremonyBrief,
  requestedBy,
  type CeremonyBrief,
  type CeremonyBriefEffects,
} from "./ceremony-brief.ts";
export type { BiometricAuth, BiometricResult } from "./biometric.ts";

/** The host-environment doors — the ONLY channel for ambient influence (noninterference).
 *  Every door is PUBLIC-safe by construction: `genCa`/`signCert` return only public text,
 *  the private/CA key is written to a local file by the runner and never read back here. */
export interface CaEffects extends CeremonyBriefEffects {
  /** True iff a path exists (presence checks — never reads the contents of a secret). */
  readonly exists: (path: string) => boolean;
  /** Read a PUBLIC text artifact (a pubkey / a cert). Never used on a private path. */
  readonly readText: (path: string) => string;
  /** Write a PUBLIC text artifact (the CA public key, or a public certificate). */
  readonly writeText: (path: string, content: string) => void;
  /** Create a directory (recursive). */
  readonly mkdirp: (path: string) => void;
  /**
   * Generate an SSH CA ed25519 keypair at `caKeyPath` (private) + `caKeyPath.pub` (public).
   * The runner writes the PRIVATE key under umask 077; this door returns ONLY the PUBLIC key
   * text — the private bytes NEVER cross this boundary.
   */
  readonly genCa: (caKeyPath: string, comment: string) => string;
  /**
   * Sign `req.devicePubPath` (a per-machine device PUBLIC key) into a certificate using the
   * CA private key at `req.caKeyPath`. Writes ONLY the public `<devicePubPath base>-cert.pub`
   * and returns its text (a cert is public). The CA private key is consumed by the runner
   * (ssh-keygen -s); it is never read into this process and never returned.
   */
  readonly signCert: (req: SignCertRequest) => SignCertOutput;
}

/** A cert-signing request — all PUBLIC inputs (a device PUBLIC key + cert metadata) plus the
 *  LOCAL path to the CA private key (consumed by the runner, never read across the boundary). */
export interface SignCertRequest {
  /** Local path to the CA PRIVATE key (consumed by ssh-keygen -s; never read here). */
  readonly caKeyPath: string;
  /** Path to the per-machine device PUBLIC key to be signed. */
  readonly devicePubPath: string;
  /** Certificate identity (`-I`) — a MACHINE-ONLY label (the host id; #8969 made the Key ID
   *  machine-only — NEVER a `user@machine` composite, the #8926 N×M lesson). */
  readonly certId: string;
  /** The principals (`-n`) the cert authorizes — the USER LIST it binds to (e.g.
   *  `["aaron", "addison"]` for a co-owned machine). A single-owner cert is a one-element list.
   *  The (user × machine) pairing lives HERE, in the list — never in a composite key/id. */
  readonly principals: readonly string[];
  /** Validity window (`-V`), OpenSSH form (e.g. "+52w"); the rolling-keys discipline. */
  readonly validity: string;
}

/** Join a user list into the OpenSSH `-n` principals value: comma-separated, no spaces
 *  (`aaron,addison`). The list IS the authorization-binding; the pairing never becomes a
 *  composite identifier (the #8926 / Key-ID N×M lesson). */
export function joinPrincipals(users: readonly string[]): string {
  return users.join(",");
}

/** The result of a sign — the written cert path + its (public) text. No private material. */
export interface SignCertOutput {
  /** Path the `-cert.pub` was written to (next to the device pubkey). */
  readonly certPath: string;
  /** The certificate text (public — safe to print / publish / commit). */
  readonly certText: string;
}

/** Default validity window for a signed device cert — the rolling-keys discipline
 *  (a cert expires; you re-sign). 52 weeks is a conservative pre-cluster default. */
export const DEFAULT_CERT_VALIDITY = "+52w";

/** Where the CA PRIVATE key lives locally (operator-held; NEVER published, NEVER committed). */
export function caPrivateKeyPath(home: string = homedir()): string {
  return join(home, ".config", "zeta", "ca", "ssh_ca_ed25519");
}

/** Where the CA PUBLIC key is committed for git-distribution → fed to `TrustedUserCAKeys`.
 *  This path is REFERENCED by ssh-ca.nix; it LANDS only when the operator runs `ca`. */
export function caPublicKeyPath(repoRoot: string, ca: string): string {
  return join(repoRoot, "maintainers", ca, "ssh-ca.pub");
}

/**
 * The CA dependency disposition for THIS host — the realize-vs-route decision setup-machine
 * makes BEFORE touching anything (Aaron 2026-06-21: setup must REALIZE missing deps, but must
 * NEVER fabricate a SECOND CA when one already exists elsewhere — route to its holder instead).
 * It is a pure function of two facts:
 *
 *   - `localCaPrivateExists` — is the CA PRIVATE key present on THIS host (`~/.config/zeta/ca/`)?
 *   - `committedTrustRoots`  — the committed CA PUBLIC trust roots already in the repo
 *                              (`maintainers/<ca>/ssh-ca.pub`), if any.
 *
 * The three dispositions (fail-SAFE — when in doubt we ROUTE, never fabricate):
 *
 *   - "present"  — THIS host holds the CA private key. The cert can be signed here directly.
 *   - "realize"  — NO local CA private AND NO committed anchor anywhere ⇒ this is a solo /
 *                  first node, so REALIZE its CA here (call `ensureCa`) — and then COMMIT its
 *                  public key, which is what makes it attested (see the trust model below).
 *   - "route"    — NO local CA private BUT a committed anchor EXISTS (that CA lives on ANOTHER
 *                  host) ⇒ DO NOT mint a second CA here. Route: the device cert must be signed
 *                  by the anchor's holder, because the anchor is the key peers already trust.
 *
 * ── THE TRUST MODEL (Aaron 2026-08-01 — correcting an earlier mis-framing in this file) ───────
 * There is NO single trust root in Zeta. The model is fully decentralized: **every node is its
 * own CA.** So a second CA existing is NOT, by itself, a fault — it is the design.
 *
 * What makes a node's CA usable by peers is that it has been **ATTESTED**: its CA public key is
 * COMMITTED to the repo (`maintainers/<ca>/ssh-ca.pub`). The committed key IS the attestation, and
 * the repo (any git remote, or none) carries it — this is git-native, not host-specific. Whoever
 * gates *who may commit an anchor* is the access-control layer, and that is a **forge-host plugin**
 * concern (`src/Core.TypeScript/forge-host/`: github | gitlab | gitea | bitbucket | sourcehut |
 * codeberg), deliberately swappable and never named here.
 * (Same shape as the cert conventions we mirror: git's `allowed_signers` for commit signing,
 * k8s/cert-manager trust bundles, SSH CAs.)
 *
 * So the ACTUAL failure mode this guard prevents is NOT "splitting a trust root" — there is no
 * root to split. It is minting an **UNATTESTED** CA: a key nobody bootstrapped through the
 * GitHub channel, so no peer can verify certs signed by it. That host would hold an orphan
 * identity — invisible to the web of trust, and silently so.
 *
 * Naming caveat: `committedTrustRoots` are **bootstrap anchors**, not PKI roots in the
 * single-root sense. Read the name as "the CA public keys already attested via the repo".
 * Prior art for bootstrapping decentralized identity off a centralized IdP: Sigstore/Fulcio
 * (OIDC identity ⇒ short-lived signing certs), SPIFFE/SPIRE (workload identity), TOFU and the
 * PGP web-of-trust, Zooko's triangle (the tradeoff this pattern navigates).
 *
 * ── TRAJECTORY: NEVER GitHub — the forge is a PLUGIN (Aaron 2026-08-01) ──────────────────────
 * **SPIFFE/SPIRE is the long-term target shape** (workload identity: short-lived SVIDs against
 * trust bundles). Zeta must reach it WITHOUT privileging any host. Aaron: *"never github — we
 * call this a forgehost plugin; we want to be able to run with just cron processes basically one
 * day, or just browser tabs, or completely with github, git-native, or zetadb-native only,
 * decentralized."*
 *
 * **The forge seam already exists and is genuinely host-agnostic:**
 * `src/Core.TypeScript/forge-host/` — a `registerAdapter(pattern, factory)` registry, a
 * `ForgeHost` interface, and `ForgeType` already spanning github | gitlab | gitea | bitbucket |
 * sourcehut | codeberg | unknown, with github AND gitlab adapters shipped. GitHub is one plugin
 * among six, not a dependency.
 *
 * **Where THIS file actually sits — better than "GitHub-bootstrapped":** `resolveCaDisposition`
 * reads `maintainers/<ca>/ssh-ca.pub` **from the working tree**. That is already **git-native**:
 * any git host, a bare remote, or a sneakernet clone satisfies it. The only borrowed authority is
 * **push access control** (who may commit an anchor) — and that is a forge-host plugin concern,
 * not a property of this logic. So do not describe this as "GitHub bootstrap"; describe it as
 * *committed-anchor attestation, with access control delegated to whatever forge plugin is in use*.
 *
 * **Two independent axes to keep separate:**
 *   - *Anchor attestation:* committed anchors (today, git-native) → a Z-set trust fold
 *     (zetadb-native: grant +1 / revoke −1 retraction; current trust = the consolidated fold,
 *     never a desired-state map). ORDER-INDEPENDENCE is what lets that converge with **no
 *     coordinator** — it is precisely the property that removes the central authority. The
 *     primitive is already proven: `SchemaLog` (work-item 081KYWE8Q4008QG0R000H558SH) shows
 *     order-independence, prefix-replay, retraction-cancels, honest idempotency on a ±1 event log.
 *   - *Execution substrate:* a forge's CI → plain **cron processes** → **browser tabs** → nothing
 *     but peers. The trust logic must not assume ANY of these.
 *
 * **Constraint to hold now (already satisfied — keep it that way):** `resolveCaDisposition` is a
 * pure function of (local private key, attested anchors). It names no forge, performs no network
 * IO, and no `ForgeHost` type appears in this file. Swapping the anchor SOURCE (committed file →
 * git object → Z-set fold) must stay a change of caller, never a change of this function.
 * Work-item 081KYXQ3SZN08QG0R002X3DTQM tracks the fold rung.
 *
 * This is the honest seam: the ONLY ambiguous case ("is THIS host the CA holder?") is resolved
 * by the presence of the LOCAL CA private key — a fact this host can see for itself — and we
 * bias to ROUTE (the safe choice) whenever a trust root already exists but the private key does
 * not. No network probe, no guess: realize only when there is provably no CA anywhere yet.
 */
export type CaDisposition = "present" | "realize" | "route";

/** The resolved CA disposition + the facts it was derived from (for an auditable readout). */
export interface CaDispositionResult {
  readonly disposition: CaDisposition;
  /** True iff the CA PRIVATE key is present on THIS host. */
  readonly localCaPrivateExists: boolean;
  /** The committed CA PUBLIC trust-root identities found in the repo (maintainers/<ca>/). */
  readonly committedTrustRoots: readonly string[];
  /** Local path the CA PRIVATE key lives at (never its contents). */
  readonly caPrivatePath: string;
  /** A one-line human-readable rationale for the chosen disposition. */
  readonly rationale: string;
}

/**
 * Resolve the CA disposition for this host — PURE over the two injected facts (the local
 * CA-private presence + the committed trust roots). No IO here; the caller (CLI) gathers the
 * facts through its injected effects and the test injects them directly.
 */
export function resolveCaDisposition(opts: {
  readonly localCaPrivateExists: boolean;
  readonly committedTrustRoots: readonly string[];
  readonly home?: string;
}): CaDispositionResult {
  const caPrivatePath = opts.home === undefined ? caPrivateKeyPath() : caPrivateKeyPath(opts.home);
  const roots = opts.committedTrustRoots;
  if (opts.localCaPrivateExists) {
    return {
      disposition: "present",
      localCaPrivateExists: true,
      committedTrustRoots: roots,
      caPrivatePath,
      rationale: "CA private key present on THIS host — sign the device cert here directly.",
    };
  }
  if (roots.length > 0) {
    return {
      disposition: "route",
      localCaPrivateExists: false,
      committedTrustRoots: roots,
      caPrivatePath,
      rationale:
        `a committed CA trust root exists (${roots.join(", ")}) but no local CA private key — ` +
        "the CA lives on ANOTHER host; ROUTE the cert to the CA holder (do NOT fabricate a 2nd CA).",
    };
  }
  return {
    disposition: "realize",
    localCaPrivateExists: false,
    committedTrustRoots: roots,
    caPrivatePath,
    rationale:
      "no local CA private key AND no committed trust root anywhere — this is a solo / first " +
      "node, so REALIZE the cluster CA here (bootstrap the trust root).",
  };
}

/** Where committed CA PUBLIC trust roots live: maintainers/<ca>/ssh-ca.pub. The realizer scans
 *  this to detect "a CA already exists somewhere" (→ route, never fabricate a second CA). */
export function maintainersDirPath(repoRoot: string): string {
  return join(repoRoot, "maintainers");
}

/** Where a signed device certificate is written — next to the device pubkey it certifies. */
export function certPath(devicePubPath: string): string {
  // ssh-keygen -s names the cert "<base>-cert.pub" where base is the pubkey minus ".pub".
  const base = devicePubPath.endsWith(".pub") ? devicePubPath.slice(0, -4) : devicePubPath;
  return base + "-cert.pub";
}

/** What a `ca` (generate-CA) run did (or, with dryRun, WOULD do). No private material here. */
export interface CaResult {
  readonly dryRun: boolean;
  /** "generated" | "exists" (idempotent: an existing CA is a no-op) | "would-generate"
   *  | "aborted-biometric" (the operator did NOT approve → fail-closed, NOTHING generated). */
  readonly action: "generated" | "exists" | "would-generate" | "aborted-biometric";
  /** Local path the CA PRIVATE key lives at (never its contents). */
  readonly caPrivatePath: string;
  /** Repo path the CA PUBLIC key would/did get written to (when `commitPub`). */
  readonly caPublicPath: string;
  /** The CA PUBLIC key text, when present/generated (safe to print). Undefined on dry-run. */
  readonly caPublicKey?: string;
  /** True iff we wrote the CA public key to the repo path (never true on dry-run). */
  readonly committedPub: boolean;
  /** The biometric approval outcome (present only when the gate was invoked — i.e. a real
   *  keygen was attempted; absent on dry-run, on the idempotent `exists` no-op, and never
   *  carries a secret). */
  readonly biometric?: BiometricResult;
}

/**
 * Generate (or, idempotently, recognise) the SSH CA keypair — AGENT-RUN, OPERATOR-APPROVED.
 * The agent EXECUTES the keygen; a biometric confirm (Touch ID / Windows Hello) is the
 * operator's AUTHORIZATION. Generates ONLY a CA keypair via the injected `genCa` door (private
 * written locally under umask 077 by the runner; only the PUBLIC key returned). With
 * `commitPub`, writes ONLY the CA PUBLIC key to maintainers/<ca>/ssh-ca.pub (no git commit).
 *
 * BIOMETRIC GATE + FAIL-CLOSED: when a real keygen is about to happen (the CA does NOT already
 * exist and it is not a dry-run), `biometricAuth()` MUST return ok:true first. On ok:false the
 * run aborts ("aborted-biometric") and `genCa` is NEVER invoked — NO CA key is created. The
 * idempotent `exists` no-op (no private material created) and `--dry-run` (creates nothing) do
 * NOT prompt.
 *
 * @param biometricAuth the SHARED approval gate (biometric.ts). Tests inject a fake; the CLI
 *                      injects `realBiometric()`. Required only for the real-keygen path.
 * @param commitPub when true, write the CA PUBLIC key to the repo path (the operator then
 *                  commits it; the CA public key is the git-distributed trust root).
 * @param dryRun    when true, NOTHING is generated, written, or prompted — "would-generate".
 */
export async function ensureCa(
  fx: CaEffects,
  opts: {
    /** The CA identity (the maintainers/<ca>/ subdir; e.g. the operator persona). */
    readonly ca: string;
    readonly repoRoot: string;
    readonly home?: string;
    readonly commitPub?: boolean;
    readonly dryRun?: boolean;
    /** SHARED biometric approval door — required for the real keygen path (fail-closed). */
    readonly biometricAuth?: BiometricAuth;
  },
): Promise<CaResult> {
  const caPrivatePath = opts.home === undefined ? caPrivateKeyPath() : caPrivateKeyPath(opts.home);
  const caPublicPath = caPublicKeyPath(opts.repoRoot, opts.ca);
  const dryRun = opts.dryRun === true;
  const wantCommit = opts.commitPub === true;
  const alreadyExists = fx.exists(caPrivatePath);

  if (dryRun) {
    return {
      dryRun: true,
      action: alreadyExists ? "exists" : "would-generate",
      caPrivatePath,
      caPublicPath,
      committedPub: false,
    };
  }

  let caPublicKey: string;
  let action: CaResult["action"];
  let biometric: BiometricResult | undefined;
  if (alreadyExists) {
    // Idempotent: an existing CA is a no-op (no private material created → no gate). Read
    // back its PUBLIC half only.
    caPublicKey = fx.readText(caPrivatePath + ".pub").trim();
    action = "exists";
  } else {
    // BIOMETRIC GATE — fail-closed. A real keygen creates private material; require approval.
    //
    // WHAT THIS REPLACED: `Approve: generate SSH CA keypair for ${opts.ca}` — which named the
    // CA and nothing else. It did not say that a PRIVATE key was about to be written, where,
    // that this is the trust anchor every device cert in the fleet chains to, or that
    // declining leaves the machine exactly as it was. `caPrivatePath` was in scope and the
    // operator was not told the path being created.
    //
    // `assertGatedCeremony` is the OTHER half of this file's job: it refuses to raise a
    // prompt for an operation `ceremony-gate.ts` classifies as routine. It cannot fire here
    // (root-key generation is gated) and it is present so that a future RECLASSIFICATION of
    // this operation stops the prompt instead of silently leaving a routine one in place.
    assertGatedCeremony("generate-node-root-key");
    const brief: CeremonyBrief = {
      operation: "generate-node-root-key",
      summary: "Create a NEW SSH certificate-authority keypair (private key written to disk)",
      subjects: [
        { label: "CA name", value: opts.ca },
        { label: "private key", value: caPrivatePath },
        { label: "public key", value: caPrivatePath + ".pub" },
      ],
      ifDeclined:
        "no keypair is generated and no file is written; this command exits reporting " +
        "'aborted-biometric' and the machine is exactly as it was. Nothing that already " +
        "trusts an existing CA is affected.",
      ...requestedBy(fx.requester),
    };
    fx.notify?.(renderCeremonyBrief(brief));
    biometric = await requireBiometric(opts.biometricAuth, ceremonyPromptLine(brief));
    if (!biometric.ok) {
      return {
        dryRun: false,
        action: "aborted-biometric",
        caPrivatePath,
        caPublicPath,
        committedPub: false,
        biometric,
      };
    }
    caPublicKey = fx.genCa(caPrivatePath, `${opts.ca} (zeta-ssh-ca)`).trim();
    action = "generated";
  }

  const bio = biometric !== undefined ? { biometric } : {};
  if (wantCommit) {
    fx.mkdirp(dirOf(caPublicPath));
    fx.writeText(caPublicPath, caPublicKey.endsWith("\n") ? caPublicKey : caPublicKey + "\n");
    return { dryRun: false, action, caPrivatePath, caPublicPath, caPublicKey, committedPub: true, ...bio };
  }

  return { dryRun: false, action, caPrivatePath, caPublicPath, caPublicKey, committedPub: false, ...bio };
}

/** What a `cert` (sign-device-key) run did (or, with dryRun, WOULD do). Public only. */
export interface CertResult {
  readonly dryRun: boolean;
  /** "signed" | "would-sign" | "no-ca" (CA private absent) | "no-device-key" (pubkey absent)
   *  | "aborted-biometric" (operator did NOT approve → fail-closed, NOTHING signed). */
  readonly action: "signed" | "would-sign" | "no-ca" | "no-device-key" | "aborted-biometric";
  readonly caPrivatePath: string;
  readonly devicePubPath: string;
  readonly certPath: string;
  readonly certId: string;
  /** The authorized user LIST (the `-n` principals) — `["aaron"]` for a single owner,
   *  `["aaron","addison"]` for a co-owned machine. The structured form of the binding. */
  readonly principals: readonly string[];
  /** The comma-joined principals (`aaron,addison`) — the exact `-n` value, for readouts. */
  readonly principal: string;
  readonly validity: string;
  /** The certificate text, when signed (public — safe to print). Undefined otherwise. */
  readonly certText?: string;
  /** The biometric approval outcome (present only when the gate was invoked — i.e. a real
   *  sign was attempted; absent on dry-run + clean skips; never carries a secret). */
  readonly biometric?: BiometricResult;
}

/**
 * Sign a per-machine device PUBLIC key into a certificate (`principal=<user>` + machine id +
 * a validity window) via the injected `signCert` door (ssh-keygen -s under the hood) — AGENT-RUN,
 * OPERATOR-APPROVED. The agent EXECUTES the sign; a biometric confirm is the operator's
 * AUTHORIZATION (signing CONSUMES the CA private key, so it must be approved). The CA private
 * key is consumed by the runner; it is never read into this process.
 *
 * Reads the machine's PUBLIC key from `devicePubPath` (the machine.ts registry seam —
 * `machines/<host>.pub`, the USER-INDEPENDENT machine registry). This cert is the ONLY place
 * the (user × machine) pair is named: a PURE machine key (host-only) signed with
 * `principal=<user>` (pure-key model, Aaron 2026-06-21). Fail-closed: a missing CA or device
 * key returns a typed `no-ca` / `no-device-key` (no partial work) and NEVER prompts.
 * `--dry-run` signs NOTHING and never prompts.
 *
 * BIOMETRIC GATE + FAIL-CLOSED: when a real sign is about to happen (CA + device key present,
 * not dry-run), `biometricAuth()` MUST return ok:true first. On ok:false the run aborts
 * ("aborted-biometric") and `signCert` is NEVER invoked — NO cert is produced.
 *
 * @param biometricAuth the SHARED approval gate (biometric.ts). Required for the real-sign path.
 */
export async function signMachineCert(
  fx: CaEffects,
  opts: {
    /** The USER the cert binds to (the `-n` principal — trust anchored at the user). A single
     *  owner; for a co-owned machine pass `users` instead (this is the one-element shorthand). */
    readonly user?: string;
    /** The authorized USER LIST for a (possibly multi-owner) machine — `["aaron","addison"]`.
     *  Takes precedence over `user`; the comma-joined value becomes the `-n` principals. A
     *  one-element list is the single-owner path. EXACTLY ONE of `user` / `users` is required;
     *  `users` must be non-empty. The (user × machine) pairing lives in this LIST — never a
     *  composite identifier (the #8926 / Key-ID N×M lesson). */
    readonly users?: readonly string[];
    /** A machine id for the cert identity (`-I`), e.g. the sanitized hostname. */
    readonly machineId: string;
    /** Path to the per-machine device PUBLIC key to sign (the registry `machines/<host>.pub`). */
    readonly devicePubPath: string;
    readonly home?: string;
    /** Validity window (OpenSSH `-V` form). Defaults to DEFAULT_CERT_VALIDITY. */
    readonly validity?: string;
    readonly dryRun?: boolean;
    /** SHARED biometric approval door — required for the real sign path (fail-closed). */
    readonly biometricAuth?: BiometricAuth;
  },
): Promise<CertResult> {
  const caPrivatePath = opts.home === undefined ? caPrivateKeyPath() : caPrivateKeyPath(opts.home);
  const validity = opts.validity ?? DEFAULT_CERT_VALIDITY;
  // Resolve the authorized user LIST: `users` (multi-owner) wins; else the single `user`. The
  // (user × machine) binding is this LIST, never a composite id. Fail-closed on a degenerate
  // request (neither given, or an empty `users`) — we never sign a cert with NO principal.
  const users: readonly string[] =
    opts.users !== undefined && opts.users.length > 0 ? opts.users : opts.user !== undefined ? [opts.user] : [];
  if (users.length === 0) {
    throw new Error("signMachineCert: provide a non-empty `users` list or a single `user`.");
  }
  const principal = joinPrincipals(users); // the exact `-n` value (`aaron,addison`)
  // Key ID names the certified SUBJECT = the machine key, so it is the machine id ALONE — NOT
  // `user@machine`. A composite user×machine Key ID is the N×M smell (Aaron, 2026-06-21; same
  // shape as the #8926 hybrid-key error): it would mint a distinct cert per (user, machine) pair
  // → O(N×M) certs. The user binding lives in the PRINCIPAL (`-n`, below), so one cert per machine
  // (Key ID = machine, principals = authorized user(s)) keeps it O(N+M). Multi-user on a shared
  // box = re-sign the one machine cert with more principals (still one cert per machine).
  const certId = opts.machineId;
  const outPath = certPath(opts.devicePubPath);
  const dryRun = opts.dryRun === true;

  const base = {
    caPrivatePath,
    devicePubPath: opts.devicePubPath,
    certPath: outPath,
    certId,
    principals: users,
    principal,
    validity,
  };

  // Fail-closed presence checks (BEFORE any work, BEFORE any prompt) — a missing CA or device
  // key is a typed no-op, never a partial sign. (Checked even on dry-run so the plan is honest.)
  if (!fx.exists(caPrivatePath)) {
    return { ...base, dryRun, action: "no-ca" };
  }
  if (!fx.exists(opts.devicePubPath)) {
    return { ...base, dryRun, action: "no-device-key" };
  }

  if (dryRun) {
    return { ...base, dryRun: true, action: "would-sign" };
  }

  // BIOMETRIC GATE — fail-closed. A real sign consumes the CA private key; require approval.
  // The cert-signing brief. `principal` and `validity` below are the SAME values handed to
  // `fx.signCert` — the prompt is derived from them, never authored beside them.
  //
  // NOTE THE CLASSIFICATION, and do not "fix" it by relabelling: signing a leaf certificate
  // under a CA this node already holds IS `issue-leaf-svid`, which `ceremony-gate.ts`
  // classifies UNATTENDED — "adds no party and no capability". So this call site raises a
  // biometric prompt for work the repo's own policy says needs no human, and the brief will
  // say so out loud on the prompt (the NOT GATED / MISMATCH arm of `renderCeremonyBrief`).
  //
  // That is deliberate. Prompting for routine work is the mechanism that teaches an operator
  // to approve reflexively, and the honest label is what makes the mismatch reviewable
  // instead of invisible. Whether to keep the prompt, or drop it and let the certificate be
  // issued unattended under the one approval the CALLER already took, is a policy call for
  // whoever owns this gate — not something a display layer may quietly decide.
  const certBrief: CeremonyBrief = {
    operation: "issue-leaf-svid",
    summary: "Sign a device certificate with the CA private key",
    subjects: [
      { label: "machine", value: opts.machineId },
      { label: "principals", value: principal },
      { label: "device key", value: opts.devicePubPath },
      { label: "signing CA", value: caPrivatePath },
      { label: "validity", value: validity },
    ],
    ifDeclined:
      "no certificate is signed and nothing is written; this command exits reporting " +
      "'aborted-biometric'. Any certificate this machine already holds keeps working.",
    ...requestedBy(fx.requester),
  };
  fx.notify?.(renderCeremonyBrief(certBrief));
  const biometric = await requireBiometric(opts.biometricAuth, ceremonyPromptLine(certBrief));
  if (!biometric.ok) {
    return { ...base, dryRun: false, action: "aborted-biometric", biometric };
  }

  const out = fx.signCert({
    caKeyPath: caPrivatePath,
    devicePubPath: opts.devicePubPath,
    certId,
    principals: users,
    validity,
  });
  return { ...base, dryRun: false, action: "signed", certText: out.certText, biometric };
}

function dirOf(p: string): string {
  const i = p.lastIndexOf("/");
  return i >= 0 ? p.slice(0, i) : ".";
}

/** The REAL host effects (used by the CLI). ssh-keygen generates the CA in-process; the CA
 *  PRIVATE key file is created under umask 077 by ssh-keygen and is never read by us. */
export function realEffects(): CaEffects {
  return {
    ...realBriefEffects(),
    exists: (p) => existsSync(p),
    readText: (p) => readFileSync(p, "utf8"),
    writeText: (p, c) => writeFileSync(p, c, { mode: 0o644 }),
    mkdirp: (p) => mkdirSync(p, { recursive: true }),
    genCa: (caKeyPath, comment) => {
      mkdirSync(dirOf(caKeyPath), { recursive: true, mode: 0o700 });
      const prevUmask = process.umask(0o077); // CA private key must not be group/other readable
      try {
        // ssh-keygen generates the CA key itself — no secret on argv. -N "" = no passphrase
        // (the operator may add one); the private file stays LOCAL under umask 077.
        const r = spawnSync("ssh-keygen", ["-t", "ed25519", "-N", "", "-f", caKeyPath, "-C", comment], {
          encoding: "utf8",
          stdio: ["ignore", "pipe", "pipe"],
        });
        if (r.status !== 0) {
          throw new Error(`ssh-keygen (CA) failed (status ${r.status ?? "signal"}): ${r.stderr ?? ""}`);
        }
      } finally {
        process.umask(prevUmask);
      }
      // Read back ONLY the public half.
      return readFileSync(caKeyPath + ".pub", "utf8");
    },
    signCert: (req) => {
      // ssh-keygen -s <ca> -I <id> -n aaron,addison -V <validity> <devicePub>
      // The `-n` value is the comma-joined principals LIST (one OpenSSH cert authorizing all
      // listed users); Key ID (`-I`) is machine-only. Writes "<devicePub base>-cert.pub" (public).
      // The CA private key is read by ssh-keygen, never by us; the cert is public output.
      const r = spawnSync(
        "ssh-keygen",
        [
          "-s",
          req.caKeyPath,
          "-I",
          req.certId,
          "-n",
          joinPrincipals(req.principals),
          "-V",
          req.validity,
          req.devicePubPath,
        ],
        { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] },
      );
      if (r.status !== 0) {
        throw new Error(`ssh-keygen -s (sign) failed (status ${r.status ?? "signal"}): ${r.stderr ?? ""}`);
      }
      const out = certPath(req.devicePubPath);
      return { certPath: out, certText: readFileSync(out, "utf8") };
    },
  };
}
