; chsh-band-gate-agreement-lemma.smt2
; Proves: the ChshBand conviction line is EXACTLY the calibrated-oracle union predicate.
;
; Claim (AntiSybil.classifyBand / bandConvictsArithmetically, spec obligation 1):
;   for all valid delta in (0,1), n > 0, s :
;     bandConvictsArithmetically (classifyBand delta n s)  <=>  |s| > 2 + chshMargin(delta, n)
;
; i.e. band >= Quantum can NEVER disagree with chshSybilCalibrated's union
; predicate `|S| > 2 + eps`. This is the BP-16 SECOND tool for the property;
; the FIRST is the FsCheck witness
;   tests/Tests.FSharp/ChshBand.Property.Tests.fs
;   "(1) bandConvictsArithmetically(classifyBand) IFF |s| > 2 + chshMargin".
;
; classifyBand's elif ladder (AntiSybil.fs ~l.488), soundness-biased (ties fall
; to the WEAKER band via `<=`), modeled exactly:
;   a = |s|;  classical=2 ;  tsirelson = 2*sqrt2 + 1e-12 ;  eps = chshMargin
;     a <= 2            -> Classical    (rank 0, never convicts)
;     a <= 2 + eps      -> SoundMargin  (rank 1, never convicts)
;     a <= tsirelson    -> Quantum      (rank 2, convicts)
;     else              -> SuperQuantum (rank 3, convicts)
;   bandConvictsArithmetically = band >= Quantum = (Quantum or SuperQuantum).
;
; Why the biconditional holds: given eps >= 0, `a <= 2` implies `a <= 2 + eps`,
; so the two non-convicting bands together cover EXACTLY `a <= 2 + eps`; their
; complement (the convicting bands) is EXACTLY `a > 2 + eps`. The Tsirelson
; constant only splits Quantum from SuperQuantum -- both convict -- so the
; conviction line is INDEPENDENT of the tsirelson value. The strict `>` in the
; RHS predicate mirrors classifyBand's non-strict `<=` at the SoundMargin edge:
; at a = 2 + eps exactly, band = SoundMargin (no conviction) and RHS is false --
; they agree AT the tie. This single UNSAT covers every a incl. that boundary.
;
; eps is abstracted as ANY non-negative real, so this proof is STRONGER than the
; specific chshMargin formula: it certifies gate-agreement for every margin
; function that returns a non-negative value -- covering both the i.i.d.
; `chshMargin` (classifyBand + the FsCheck witness) AND the autocorrelation
; margin `chshMarginAutocorr` that shipped `chshSybilCalibrated` actually uses
; (same non-negative sqrt form over n_eff <= n).
;
; DEGENERATE eps = +infinity (n <= 0 or delta not in (0,1)): outside QF_NRA.
; Proven by inspection: 2 + inf = inf, so band = SoundMargin for all a > 2
; (never convicts) and RHS `a > inf` is false -- both false, biconditional holds.
;
; Generated by: Soraya routing (formal-verification-expert), 2026-08-08.
; Status: PROVEN (unsat = the conviction line and the union predicate never disagree).

(set-logic QF_NRA)

(declare-const s Real)      ; raw signed CHSH statistic S-hat
(declare-const eps Real)    ; chshMargin(delta, n): finite, non-negative on the valid domain
(declare-const sqrt2 Real)  ; pinned to the positive square root of 2

; a = |s|, exactly as classifyBand's `let a = abs s`.
(define-fun a () Real (ite (>= s 0.0) s (- s)))

; Valid-domain constraint: chshMargin = sqrt(32*ln(1/delta)/n) >= 0 for delta in (0,1), n > 0.
(assert (>= eps 0.0))

; Pin the Tsirelson constant: sqrt2 = +sqrt(2), tsirelson = 2*sqrt2 + 1e-12.
(assert (>= sqrt2 0.0))
(assert (= (* sqrt2 sqrt2) 2.0))
(define-fun tsirelson () Real (+ (* 2.0 sqrt2) 0.000000000001))

; classifyBand's elif ladder, then bandConvictsArithmetically = band >= Quantum.
(define-fun convicts () Bool
  (let ((b_classical (<= a 2.0)))
  (let ((b_sound (and (not b_classical) (<= a (+ 2.0 eps)))))
  (let ((b_quantum (and (not b_classical) (not b_sound) (<= a tsirelson))))
  (let ((b_super   (and (not b_classical) (not b_sound) (not b_quantum))))
    (or b_quantum b_super))))))

; The calibrated-oracle union predicate (strict), from chshSybilCalibrated.
(define-fun unionPredicate () Bool (> a (+ 2.0 eps)))

; Negate the biconditional for refutation: a state where they DISAGREE.
(assert (not (= convicts unionPredicate)))

(check-sat)
; Expected: unsat -- band>=Quantum and `|s| > 2 + eps` never disagree, for any
; s, any non-negative margin eps, and the true Tsirelson constant.
