; chsh-band-gate-agreement-lemma.smt2
; Proves: the ChshBand conviction line is EXACTLY the calibrated-oracle union predicate.
;
; Claim (AntiSybil.classifyBand / bandConvictsArithmetically, spec obligation 1):
;   for all valid delta in (0,1), n > 0, s :
;     bandConvictsArithmetically (classifyBand delta n s)  <=>  |s| > 2 + chshMargin(delta, n)
;
; i.e. band >= Quantum can NEVER disagree with chshSybilCalibrated's union
; predicate `|S| > 2 + eps`. This is the BP-16 SECOND tool for the property;
; the FIRST is the FsCheck witness
;   tests/Tests.FSharp/ChshBand.Property.Tests.fs
;   "(1) bandConvictsArithmetically(classifyBand) IFF |s| > 2 + chshMargin".
;
; classifyBand's elif ladder (AntiSybil.fs ~l.488), soundness-biased (ties fall
; to the WEAKER band via `<=`), modeled exactly:
;   a = |s|;  classical=2 ;  tsirelson = 2*sqrt2 + 1e-12 ;  eps = chshMargin
;     a <= 2            -> Classical    (rank 0, never convicts)
;     a <= 2 + eps      -> SoundMargin  (rank 1, never convicts)
;     a <= tsirelson    -> Quantum      (rank 2, convicts)
;     else              -> SuperQuantum (rank 3, convicts)
;   bandConvictsArithmetically = band >= Quantum = (Quantum or SuperQuantum).
;
; Why the biconditional holds: given eps >= 0, `a <= 2` implies `a <= 2 + eps`,
; so the two non-convicting bands together cover EXACTLY `a <= 2 + eps`; their
; complement (the convicting bands) is EXACTLY `a > 2 + eps`. The Tsirelson
; constant only splits Quantum from SuperQuantum -- both convict -- so the
; conviction line is INDEPENDENT of the tsirelson value. The strict `>` in the
; RHS predicate mirrors classifyBand's non-strict `<=` at the SoundMargin edge:
; at a = 2 + eps exactly, band = SoundMargin (no conviction) and RHS is false --
; they agree AT the tie. This single UNSAT covers every a incl. that boundary.
;
; eps is abstracted as ANY non-negative real, so this proof is STRONGER than the
; specific chshMargin formula: it certifies gate-agreement for every margin
; function that returns a non-negative value -- covering both the i.i.d.
; `chshMargin` (classifyBand + the FsCheck witness) AND the autocorrelation
; margin `chshMarginAutocorr` that shipped `chshSybilCalibrated` actually uses
; (same non-negative sqrt form over n_eff <= n).
;
; DEGENERATE eps = +infinity (n <= 0 or delta not in (0,1)): outside QF_NRA.
; Proven by inspection: 2 + inf = inf, so band = SoundMargin for all a > 2
; (never convicts) and RHS `a > inf` is false -- both false, biconditional holds.
;
; Generated by: Soraya routing (formal-verification-expert), 2026-08-08.
; Status: PROVEN (unsat = the conviction line and the union predicate never disagree).

(set-logic QF_NRA)

(declare-const s Real)      ; raw signed CHSH statistic S-hat
(declare-const eps Real)    ; chshMargin(delta, n): finite, non-negative on the valid domain
(declare-const sqrt2 Real)  ; pinned to the positive square root of 2

; a = |s|, exactly as classifyBand's `let a = abs s`.
(define-fun a () Real (ite (>= s 0.0) s (- s)))

; Valid-domain constraint: chshMargin = sqrt(32*ln(1/delta)/n) >= 0 for delta in (0,1),
; n > 0. NOT asserted globally -- it is the hypothesis the non-vacuity probe ablates,
; so it is asserted inside G1 and negated inside V. (Retrofit 2026-08-13,
; work-item 081KZYYKHX1087G0R0036E9RH9.)
(define-fun validDomain () Bool (>= eps 0.0))

; Pin the Tsirelson constant: sqrt2 = +sqrt(2), tsirelson = 2*sqrt2 + 1e-12.
(assert (>= sqrt2 0.0))
(assert (= (* sqrt2 sqrt2) 2.0))
(define-fun tsirelson () Real (+ (* 2.0 sqrt2) 0.000000000001))

; classifyBand's elif ladder, then bandConvictsArithmetically = band >= Quantum.
(define-fun convicts () Bool
  (let ((b_classical (<= a 2.0)))
  (let ((b_sound (and (not b_classical) (<= a (+ 2.0 eps)))))
  (let ((b_quantum (and (not b_classical) (not b_sound) (<= a tsirelson))))
  (let ((b_super   (and (not b_classical) (not b_sound) (not b_quantum))))
    (or b_quantum b_super))))))

; The calibrated-oracle union predicate (strict), from chshSybilCalibrated.
(define-fun unionPredicate () Bool (> a (+ 2.0 eps)))

; The refutation goal, named ONCE and shared by both blocks below. Sharing is
; deliberate: a mutation that collapsed `unionPredicate` into `convicts` (making
; G1 a restatement rather than a theorem) propagates into V, which then flips
; from `sat` to `unsat` and turns the runner red. A probe written over a private
; copy of these definitions would not catch that, and would be a probe about
; itself.
(define-fun disagree () Bool (not (= convicts unionPredicate)))

; --- G1  THE THEOREM ---------------------------------------------------------
; Negate the biconditional for refutation: a state where they DISAGREE.
; SCOPED in (push)/(pop) so that the NON-VACUITY PROBE below is a separate query.
; (Retrofit 2026-08-13, work-item 081KZYYKHX1087G0R0036E9RH9. Before the scoping
; this assertion was GLOBAL, which would have made every later block trivially
; `unsat` regardless of its content -- the vacuity trap, one level up.)
(push)
(assert validDomain)
(assert disagree)
(check-sat)
; Expected: unsat -- band>=Quantum and `|s| > 2 + eps` never disagree, for any
; s, any non-negative margin eps, and the true Tsirelson constant.
(pop)

; --- V  NON-VACUITY PROBE ----------------------------------------------------
; The whole point of this block. G1 alone is indistinguishable from a tautology:
; a lemma whose premises contain its conclusion also returns `unsat`, and a runner
; asserting all-unsat could not tell the difference. This block is G1 with exactly
; ONE hypothesis ABLATED -- `validDomain`, i.e. `eps >= 0` -- and negated, so a
; model is a genuine disagreement between the gate and the predicate.
;
; `sat` here proves two things:
;   1. `eps >= 0` is LOAD-BEARING, not decorative -- it must be discharged at the
;      call site (chshMargin's sqrt form is non-negative on the valid domain; the
;      degenerate n <= 0 / delta outside (0,1) case is handled by the +infinity
;      argument in the header, not by this encoding);
;   2. therefore G1's `unsat` is a theorem ABOUT that hypothesis, not a tautology.
;
; The witness shape: with eps < 0 the SoundMargin rung is empty, so the ladder
; convicts exactly on `a > 2` while the union predicate fires on `a > 2 + eps`;
; any `a` strictly between them is a disagreement.
(push)
(assert (not validDomain))   ; <-- the ABLATED hypothesis, negated
(assert disagree)
(check-sat)   ; expect: sat  => the gate and the predicate CAN disagree once
              ; eps is allowed negative; G1 is a theorem, not a tautology.
(get-model)
(pop)

; Verdict sequence: unsat sat  (G1 proved, V is the non-vacuity witness).
