# infra/nixos/hosts/control-plane/configuration.nix
#
# Zeta cluster control-plane node. Runs K3S server + embedded etcd, and
# auto-applies the bootstrap manifests that install ArgoCD and the
# root Application of Applications.
#
# After install, ArgoCD takes over and reconciles everything else from
# this same Git repo. The control-plane node is intentionally minimal —
# heavy AI workloads run on worker-gpu-* nodes.

{ config, pkgs, lib, ... }:

{
  imports = [
    # hardware-configuration.nix is per-machine and generated by
    # `nixos-generate-config --root /mnt` on the target during install.
    # Commit it alongside this file once the target machine is known
    # and its hardware shouldn't drift.
    ./hardware-configuration.nix

    # Shared baseline.
    ../../modules/common.nix

    # K3S control-plane role.
    ../../modules/k3s-server.nix
  ];

  # ---------------------------------------------------------------------------
  # Identity
  # ---------------------------------------------------------------------------
  networking.hostName = "control-plane";
  # Static IP recommended for control-plane so worker-gpu-* nodes can
  # join via a stable serverAddr. Per-site override here:
  #   networking.interfaces.eth0.ipv4.addresses = [{
  #     address = "192.168.1.10";
  #     prefixLength = 24;
  #   }];
  #   networking.defaultGateway = "192.168.1.1";
  #   networking.nameservers = [ "1.1.1.1" "9.9.9.9" ];

  # ---------------------------------------------------------------------------
  # SSH keys for the zeta admin user. Add maintainer keys here:
  # ---------------------------------------------------------------------------
  users.users.zeta.openssh.authorizedKeys.keys = [
    # "ssh-ed25519 AAAAC3Nz... aaron@zeta"
    # "ssh-ed25519 AAAAC3Nz... addison@zeta"
  ];

  # ---------------------------------------------------------------------------
  # Control-plane has no GPU; nothing to import from gpu.nix.
  # ---------------------------------------------------------------------------
}
