/**
 * discovery/lossy-broadcast-mesh.ts — a DETERMINISTIC lossy/duplicating/delayed
 * broadcast mesh, for tests that need a hostile wire without needing a network.
 *
 * Every attached node satisfies `DiscoveryTransport & BroadcastTransport`, so a
 * subject written against the real UDP transports runs against this unchanged.
 * The hostility is generated by a Knuth-multiplicative counter rather than by a
 * clock or an RNG, so a run replays byte-identically from the same call order —
 * the §7 DST requirement, and the reason this is not `Math.random()`:
 *
 *   - ~29% of sends are DROPPED
 *   - ~20% of the survivors are DUPLICATED at twice the wire delay
 *   - delivery is deferred by `delayMs` of simulated time and only happens when
 *     the caller `advance()`s the clock, so no test depends on a real timer
 *
 * Time is a parameter, never ambient: `advance(ms)` is the only clock, which is
 * `.claude/rules/local-time-never-enters-the-shared-fold.md` observed at the
 * smallest possible scale.
 *
 * ── PROVENANCE ──────────────────────────────────────────────────────────────
 * Lifted verbatim (behaviour-identical) out of
 * `observe/udp-lossy-loop.test.ts`, which had itself copied it from
 * `gossip-salon.proof.test.ts`. Two copies of a wire simulator is one copy too
 * many, and it belongs beside the transports it imitates rather than inside one
 * of its callers.
 */

import type { DiscoveryTransport } from "./discovery-beacon.ts";
import type { BroadcastTransport } from "./llmtv-broadcast.ts";

export interface LossyBroadcastMesh {
  /** Join the mesh under `id`. Messages reach every node EXCEPT the sender. */
  attach(id: string): DiscoveryTransport & BroadcastTransport;
  /** Advance simulated time by `ms`, delivering everything that comes due. */
  advance(ms: number): Promise<void>;
}

export function createLossyDupMesh(delayMs: number): LossyBroadcastMesh {
  const nodes: {
    id: string;
    handlers: ((t: string, f: string) => void)[];
  }[] = [];
  let clock = 0;
  let dropCounter = 0;
  const pending: { at: number; text: string; fromId: string }[] = [];

  const deliverDue = (upTo: number): void => {
    for (;;) {
      const idx = pending.findIndex((d) => d.at <= upTo);
      if (idx < 0) return;
      const [d] = pending.splice(idx, 1);
      if (!d) return;
      for (const n of nodes) if (n.id !== d.fromId) for (const h of n.handlers) h(d.text, d.fromId);
    }
  };

  return {
    attach(id: string): DiscoveryTransport & BroadcastTransport {
      const self = { id, handlers: [] as ((t: string, f: string) => void)[] };
      nodes.push(self);
      const send = (text: string): void => {
        dropCounter += 1;
        const w = (dropCounter * 2654435761) % 4294967296;
        if (w % 7 === 0 || w % 7 === 1) return; // ~29% drop
        pending.push({ at: clock + delayMs, text, fromId: id });
        if (w % 5 === 3) pending.push({ at: clock + delayMs * 2, text, fromId: id }); // ~20% dup
      };
      return {
        broadcast: send,
        publish: send,
        onMessage: (h) => self.handlers.push(h),
        onFrame: (h) => self.handlers.push(h),
      };
    },
    async advance(ms: number): Promise<void> {
      const target = clock + ms;
      for (;;) {
        let nextDelivery = Infinity;
        for (const d of pending) nextDelivery = Math.min(nextDelivery, d.at);
        if (nextDelivery > target) {
          await new Promise<void>((resolve) => {
            setTimeout(resolve, 0);
          });
          nextDelivery = Infinity;
          for (const d of pending) nextDelivery = Math.min(nextDelivery, d.at);
          if (nextDelivery > target) break;
        }
        clock = nextDelivery;
        deliverDue(clock);
      }
      clock = target;
      deliverDue(clock);
    },
  };
}
