using Microsoft.CodeAnalysis;
using System.Linq;

namespace Zeta.Generators;

[Generator]
public class ZSetWRingGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Register post-initialization output to generate C#-side wrappers for all the struct rings
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ZSetW_IntegerRing.g.cs", GenerateRingWrapper(
                "Zeta.Core.IntegerRing",
                "long",
                isRing: true
            ));

            ctx.AddSource("ZSetW_IntervalRing.g.cs", GenerateRingWrapper(
                "Zeta.Core.IntervalRing",
                "Zeta.Core.IntervalWeight",
                isRing: false
            ));

            ctx.AddSource("ZSetW_TropicalSemiring.g.cs", GenerateRingWrapper(
                "Zeta.Core.TropicalSemiring",
                "Zeta.Core.TropicalWeight",
                isRing: false
            ));

            ctx.AddSource("ZSetW_RationalRing.g.cs", GenerateRingWrapper(
                "Zeta.Core.ProbabilitySemiring.RationalRing",
                "Zeta.Core.ProbabilitySemiring.Rational",
                isRing: true
            ));
        });
    }

    private static string GenerateRingWrapper(string ringType, string weightType, bool isRing)
    {
        var shortName = ringType.Split('.').Last();

        var methods = $@"        public static ZSetW<K, {weightType}> Singleton<K>(K key, {weightType} weight) where K : System.IComparable<K>
        {{
            return ZSetWModule.SingletonBy<{ringType}, {weightType}, K>(default({ringType}), key, weight);
        }}

        public static ZSetW<K, {weightType}> OfSeq<K>(System.Collections.Generic.IEnumerable<System.ValueTuple<K, {weightType}>> xs) where K : System.IComparable<K>
        {{
            var fsharpTuples = System.Linq.Enumerable.Select(xs, x => System.Tuple.Create(x.Item1, x.Item2));
            return ZSetWModule.OfSeqBy<{ringType}, {weightType}, K>(default({ringType}), fsharpTuples);
        }}

        public static ZSetW<K, {weightType}> Sum<K>(ZSetW<K, {weightType}> a, ZSetW<K, {weightType}> b) where K : System.IComparable<K>
        {{
            return ZSetWModule.SumBy<{ringType}, {weightType}, K>(default({ringType}), a, b);
        }}

        public static ZSetW<K, {weightType}> Scale<K>({weightType} scalar, ZSetW<K, {weightType}> a) where K : System.IComparable<K>
        {{
            return ZSetWModule.ScaleBy<{ringType}, {weightType}, K>(default({ringType}), scalar, a);
        }}";

        if (isRing)
        {
            methods += $@"

        public static ZSetW<K, {weightType}> Negate<K>(ZSetW<K, {weightType}> a) where K : System.IComparable<K>
        {{
            return ZSetWModule.NegateBy<{ringType}, {weightType}, K>(default({ringType}), a);
        }}

        public static ZSetW<K, {weightType}> Difference<K>(ZSetW<K, {weightType}> a, ZSetW<K, {weightType}> b) where K : System.IComparable<K>
        {{
            return ZSetWModule.DifferenceBy<{ringType}, {weightType}, K>(default({ringType}), a, b);
        }}";
        }

        return $@"// <auto-generated/>
using Zeta.Core;

namespace Zeta.Core
{{
    public static class ZSetW_{shortName}
    {{
{methods}
    }}
}}
";
    }
}
