package zeta_id

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

const (
	VersionOffset    = 123
	VersionWidth     = 5
	TimestampOffset  = 75
	TimestampWidth   = 48
	ChromosomeOffset = 70
	ChromosomeWidth  = 5
	CategoryOffset   = 65
	CategoryWidth    = 4
	FireflyOffset    = 64
	FireflyWidth     = 1
	AuthorityOffset  = 59
	AuthorityWidth   = 5
	PersonaOffset    = 51
	PersonaWidth     = 8
	MomentumOffset   = 43
	MomentumWidth    = 8
	LocationOffset   = 35
	LocationWidth    = 8
	RandomnessOffset = 0
	RandomnessWidth  = 32
)
