package zeta_id

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

type Bits uint32

const (
	VersionOffset    Bits = 123
	VersionWidth     Bits = 5
	TimestampOffset  Bits = 75
	TimestampWidth   Bits = 48
	ChromosomeOffset Bits = 70
	ChromosomeWidth  Bits = 5
	CategoryOffset   Bits = 65
	CategoryWidth    Bits = 4
	FireflyOffset    Bits = 64
	FireflyWidth     Bits = 1
	AuthorityOffset  Bits = 59
	AuthorityWidth   Bits = 5
	PersonaOffset    Bits = 51
	PersonaWidth     Bits = 8
	MomentumOffset   Bits = 43
	MomentumWidth    Bits = 8
	LocationOffset   Bits = 35
	LocationWidth    Bits = 8
	RandomnessOffset Bits = 0
	RandomnessWidth  Bits = 32
)
