#!/usr/bin/env bash
#
# tools/setup/common/shellenv.sh — emits a managed PATH file at
# $HOME/.config/zeta/shellenv.sh, sourced from the user's shell rc
# files AND from $GITHUB_ENV / $GITHUB_PATH under CI. Single source
# of truth for PATH — see docs/research/build-machine-setup.md.
#
# On re-run, the file is regenerated idempotently (same content every
# time given the same tool set), so the "second run mutates nothing"
# contract holds.

set -euo pipefail

ZETA_ENV_DIR="$HOME/.config/zeta"
ZETA_ENV_FILE="$ZETA_ENV_DIR/shellenv.sh"
mkdir -p "$ZETA_ENV_DIR"

# Build the env file from known PATH contributors. Skip lines whose
# target directory doesn't exist so a clean machine doesn't pollute
# PATH with dead entries.
{
  echo "# Zeta managed shellenv — regenerated by tools/setup/common/shellenv.sh."
  echo "# Do not edit by hand; changes are overwritten on next install."
  echo

  if command -v brew >/dev/null 2>&1; then
    echo "eval \"\$($(command -v brew) shellenv)\""
  fi

  if [ -d "$HOME/.elan/bin" ]; then
    echo "export PATH=\"\$HOME/.elan/bin:\$PATH\""
  fi

  if [ -d "$HOME/.dotnet/tools" ]; then
    echo "export PATH=\"\$HOME/.dotnet/tools:\$PATH\""
  fi

  if [ -d "$HOME/.local/bin" ]; then
    echo "export PATH=\"\$HOME/.local/bin:\$PATH\""
  fi

  if command -v mise >/dev/null 2>&1; then
    echo "eval \"\$(mise activate bash --shims)\""
  fi
} > "$ZETA_ENV_FILE"

echo "✓ shellenv at $ZETA_ENV_FILE"

# Under GitHub Actions, also write to $GITHUB_ENV / $GITHUB_PATH so
# the rest of the job inherits the same PATH without needing to
# source the file. This is the CI-local parity hook.
if [ -n "${GITHUB_ENV:-}" ] && [ -n "${GITHUB_PATH:-}" ]; then
  if [ -d "$HOME/.elan/bin" ];     then echo "$HOME/.elan/bin" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.dotnet/tools" ]; then echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.local/bin" ];    then echo "$HOME/.local/bin" >> "$GITHUB_PATH"; fi
  # Mise shims directory — where mise-installed `dotnet`, `python`,
  # etc. live. Without this on GITHUB_PATH, subsequent `run:` steps
  # can't see the toolchain install.sh just provisioned.
  MISE_SHIM_DIR="$HOME/.local/share/mise/shims"
  if [ -d "$MISE_SHIM_DIR" ];      then echo "$MISE_SHIM_DIR" >> "$GITHUB_PATH"; fi
  echo "✓ GITHUB_PATH updated for the remainder of the CI job"
fi

# Suggest sourcing the file from common shell rc files on first run.
# We do NOT auto-edit .zshrc / .bashrc — that's a user-visible edit
# and should be opt-in. The doc tells users how to wire it.
cat <<EOF

Next step (one-time, local dev only):
  Add this line to your ~/.zshrc (or ~/.bashrc on Linux):
    [ -f "\$HOME/.config/zeta/shellenv.sh" ] && . "\$HOME/.config/zeta/shellenv.sh"
EOF
