#!/usr/bin/env bash
#
# tools/setup/common/shellenv.sh — emits a managed PATH file at
# $HOME/.config/zeta/shellenv.sh, sourced from the user's shell rc
# files AND from $GITHUB_ENV / $GITHUB_PATH under CI. Single source
# of truth for PATH — see docs/research/build-machine-setup.md.
#
# On re-run, the file is regenerated idempotently (same content every
# time given the same tool set), so the "second run mutates nothing"
# contract holds.

set -euo pipefail

ZETA_ENV_DIR="$HOME/.config/zeta"
ZETA_ENV_FILE="$ZETA_ENV_DIR/shellenv.sh"
mkdir -p "$ZETA_ENV_DIR"

# Build the env file from known PATH contributors. Skip lines whose
# target directory doesn't exist so a clean machine doesn't pollute
# PATH with dead entries. Shape borrowed from SQLSharp's proven-
# green `setup-github-unix-shell-env.sh` — including BASH_ENV so
# every subsequent bash step auto-sources this file.
{
  echo "# Zeta managed shellenv — regenerated by tools/setup/common/shellenv.sh."
  echo "# Do not edit by hand; changes are overwritten on next install."
  echo

  if command -v brew >/dev/null 2>&1; then
    echo "eval \"\$($(command -v brew) shellenv)\""
  fi

  # Workaround: .NET 10 Server GC crashes on Apple Silicon ARM64
  # macOS. Three crash reports captured 2026-04-24 (intermittent
  # SIGSEGV in SVR::gc_heap::{plan_phase, background_mark_phase,
  # find_first_object} with "possible pointer authentication
  # failure" = ARM64 PAC memory-corruption detection). Workstation
  # GC is stable; small build-time perf cost. Apply only on Apple
  # Silicon HARDWARE under Darwin; Linux / Intel macOS / Windows
  # see no change. The hardware probe is `sysctl -n
  # hw.optional.arm64` (returns "1" on Apple Silicon regardless of
  # whether the current process runs natively or under Rosetta 2 —
  # `uname -m` reports "x86_64" under Rosetta, which would falsely
  # skip the workaround even though the OS is on the affected
  # hardware). Remove once upstream `dotnet/runtime` ships a fix.
  # Per Otto-248 DST discipline: flakes are bugs; this is the
  # mitigation layer while the upstream fix lands.
  # HOST TIERS (workitem 081KTWQZY7F): tools pinned in .mise.full.toml resolve ONLY when
  # MISE_ENV=full is in the environment — install-time tier decides, the managed shellenv
  # PERSISTS it so every later shell (and CI step via BASH_ENV/GITHUB_ENV) resolves the
  # full-tier shims (k3d/kubectl/helm/kubeconform). Without this, install succeeds and the
  # first `kubectl` says "No version is set for shim".
  # shellcheck disable=SC1091
  . "$(cd "$(dirname "$0")" && pwd)/host-tier.sh"
  if zeta_tier_allows full; then
    echo "export MISE_ENV=full  # host tier: full ($ZETA_HOST_TIER_SOURCE) — merges .mise.full.toml"
  fi

  echo "if [ \"\$(uname -s)\" = \"Darwin\" ] && [ \"\$(sysctl -n hw.optional.arm64 2>/dev/null || echo 0)\" = \"1\" ]; then"
  echo "  # .NET 10 Server GC workaround — Apple Silicon crash (Otto-248)"
  echo "  export DOTNET_gcServer=0"
  echo "fi"

  # Round-34 flip: dotnet SDK comes from mise (see .mise.toml
  # `[tools] dotnet`). Mise shims put `dotnet` on PATH via
  # `mise activate --shims` below. We still add
  # `$HOME/.dotnet/tools` because `dotnet tool install -g` always
  # lands globals there — that's a .NET convention independent
  # of where the SDK lives.
  if [ -d "$HOME/.dotnet/tools" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.dotnet/tools\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.dotnet/tools\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  if [ -d "$HOME/.elan/bin" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.elan/bin\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.elan/bin\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  if [ -d "$HOME/.local/bin" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.local/bin\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.local/bin\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  # Pure PATH activation (no --shims) — points PATH directly at
  # real tool binaries; mise's own docs call this ~10x faster
  # than shims. Works in a local non-interactive bash test with
  # BASH_ENV sourcing; CI will be the tiebreaker across the
  # Ubuntu + macOS matrix. If CI surfaces a step that needs
  # shims, flip back to `mise activate bash --shims` and file
  # a DEBT entry explaining which step failed and why.
  #
  # PROJECT-SCOPED RESOLUTION IS INTENTIONAL HERE — NOT A GAP TO CLOSE
  # (Aaron 2026-08-22). `mise activate` without `--shims` rewrites PATH per
  # directory from the nearest .mise.toml, so a tool pinned there resolves
  # INSIDE the repo and deliberately does NOT resolve from `~`. Aaron, shown
  # that `op` was "command not found" from his home directory: *"it's like
  # local scoped dotnet or npm or other similar tools, that works great we
  # don't need to global … i see op when i'm in zeta"*. That is the same
  # contract as a local `dotnet tool` manifest or node_modules/.bin — the
  # pinned version travels with the project — and this file is the
  # DEVELOPER WORKSTATION surface, where a checkout is always present. The
  # `--shims` escape hatch above is for a CI STEP that needs shims, never
  # for global reach on a workstation.
  # Measured 2026-08-22 (100 × `op --version`, Aaron's Mac): direct 1.47s vs
  # shim 5.98s — ~4x, same direction as the ~10x the docs claim.
  #
  # THE OTHER HOST CLASS IS DIFFERENT, so do not generalise this comment. On
  # LINUX CLUSTER HARDWARE there is no checkout to scope to — a node
  # bootstrapping shared secrets is a login shell in $HOME or a systemd
  # unit — and Aaron 2026-08-22: *"for the linux real hardware we might need
  # it global for op"*. That case is handled in
  # full-ai-cluster/nixos/modules/common.nix (shims on PATH +
  # MISE_GLOBAL_CONFIG_FILE pointed at the node's own checkout, so the pin
  # is still .mise.toml's). Two host classes, two correct answers; the
  # falsifier that keeps them apart is
  # full-ai-cluster/nixos/modules/mise-node-path-wiring.test.ts.
  echo "export MISE_PYTHON_GITHUB_ATTESTATIONS=\"\${MISE_PYTHON_GITHUB_ATTESTATIONS:-0}\""
  # Trust this checkout's .mise.toml by default. `mise activate` reads the
  # nearest config and REFUSES untrusted files (QEMU 6.95-picker, 2026-08-23:
  # "Config files in ~/Zeta/.mise.toml are not trusted"). A HOME-local
  # `mise trust` store is not durable across install-time /mnt/home/zeta →
  # post-reboot $HOME. MISE_TRUSTED_CONFIG_PATHS is the env-var contract
  # install.sh already uses; persist it here so every later shell inherits
  # it. Must emit BEFORE `mise activate` below.
  _zeta_repo_root="$(cd "$(dirname "$0")/../../.." && pwd)"
  echo "case \":\${MISE_TRUSTED_CONFIG_PATHS:-}:\" in"
  echo "  *:\"$_zeta_repo_root\":*) ;;"
  echo "  *) export MISE_TRUSTED_CONFIG_PATHS=\"\${MISE_TRUSTED_CONFIG_PATHS:+\$MISE_TRUSTED_CONFIG_PATHS:}$_zeta_repo_root\" ;;"
  echo "esac"
  if command -v mise >/dev/null 2>&1; then
    echo "if [ -n \"\${ZSH_VERSION:-}\" ]; then"
    echo "  eval \"\$(mise activate zsh)\""
    echo "else"
    echo "  eval \"\$(mise activate bash)\""
    echo "fi"
  fi

  # NO SECRETS ENV LINE HERE, BY DESIGN (081M00VMWTB087G0R0026XSWT6).
  #
  # This block used to emit a line sourcing ~/.config/zeta/secrets-env.sh, which
  # holds a Keychain-fetch that exports the 1Password service-account token. The
  # effect was an 852-byte credential in the environment of every interactive
  # shell and every process descended from one.
  #
  # An environment variable crosses `exec` regardless of the child's code
  # identity. A code signature, a keychain ACL, an IMA appraisal and a TPM seal
  # all bind a secret to a CALLER; an inherited variable has already escaped the
  # question of who the caller is. So this is the one exposure in the custody
  # stack that no signing work can reach, and removing the line is the whole fix.
  # (§13 noninterference, Goguen & Meseguer 1982, stated for credentials.)
  #
  # Replacement: fetch at point of use, never export.
  #   src/Core.TypeScript/secrets/credential.ts  — withCredential / spawnWithCredential
  # Guard: src/Core.TypeScript/hygiene/lint-no-ambient-credential-hoist.ts fails CI
  # if any tracked executable surface re-introduces a hoist.

  # ZETA_FIRST_SESSION_MARKER — the observe loop checks this to know whether the
  # first-session credential adventure is complete. Points at a stable user-level
  # path ($HOME/.config/zeta/first-session-complete) so it survives across repo
  # checkouts + agent reboots. load-node-session.ts: if the file exists, nodeSession
  # channel is unwired (adventure done). install.sh provisions the file on success.
  echo "export ZETA_FIRST_SESSION_MARKER=\"\$HOME/.config/zeta/first-session-complete\""
} > "$ZETA_ENV_FILE"

echo "✓ shellenv at $ZETA_ENV_FILE"

# Under GitHub Actions, also write to $GITHUB_ENV / $GITHUB_PATH so
# the rest of the job inherits the same PATH without needing to
# source the file. This is the CI-local parity hook.
if [ -n "${GITHUB_ENV:-}" ] && [ -n "${GITHUB_PATH:-}" ]; then
  # SQLSharp-proven pattern: put BASH_ENV + ENV into $GITHUB_ENV
  # so every subsequent bash step auto-sources this shellenv file.
  # Stronger than piecewise $GITHUB_PATH echoes because the file
  # runs real shell logic (brew shellenv, mise activate, etc.).
  echo "BASH_ENV=$ZETA_ENV_FILE" >> "$GITHUB_ENV"
  echo "ENV=$ZETA_ENV_FILE" >> "$GITHUB_ENV"

  # GITHUB_PATH gets the resolvable dirs as a belt-and-braces
  # fallback for non-bash shells. dotnet itself comes from mise
  # shims (round-34 flip), not $HOME/.dotnet.
  if [ -d "$HOME/.dotnet/tools" ]; then echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.elan/bin" ];     then echo "$HOME/.elan/bin" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.local/bin" ];    then echo "$HOME/.local/bin" >> "$GITHUB_PATH"; fi

  # mise shims (dotnet + python + java + bun + uv all live here).
  # Using --shims (not pure PATH activation) for CI reliability:
  # each `bash -c` step on a runner is a fresh subshell without a
  # prompt hook to trigger dynamic PATH update. Shims work
  # without hooks. On a dev laptop, a user can opt into the
  # ~10x-faster `mise activate` (no --shims) in their own rc file.
  for shim_dir in \
      "$HOME/.local/share/mise/shims" \
      "/opt/homebrew/opt/mise/shims" \
      "/opt/homebrew/share/mise/shims"; do
    if [ -d "$shim_dir" ]; then
      echo "$shim_dir" >> "$GITHUB_PATH"
      break
    fi
  done

  echo "✓ BASH_ENV + ENV + GITHUB_PATH updated for the remainder of the CI job"
fi

# Suggest sourcing the file from common shell rc files on first run.
# We do NOT auto-edit .zshrc / .bashrc — that's a user-visible edit
# and should be opt-in. The doc tells users how to wire it.
cat <<'EOF'

Next step (one-time, local dev only):
  Paste the line below into all of the following files that
  exist on your system so every shell variant finds the
  Zeta toolchain. The block is idempotent — adding it twice
  is harmless (the `-f` guard skips if the file isn't there).

    [ -f "$HOME/.config/zeta/shellenv.sh" ] && . "$HOME/.config/zeta/shellenv.sh"

  Target files:
    ~/.zshrc        (zsh interactive shells; macOS default)
    ~/.bashrc       (bash interactive shells; Linux default)
    ~/.bash_profile (bash login shells on macOS)
    ~/.profile      (POSIX fallback; SSH non-interactive)

  Opt-in auto-edit of these files via the install script is
  BACKLOGged (see docs/BACKLOG.md "Opt-in auto-edit of shell
  rc files on install"). Until then, paste manually — we
  deliberately don't touch user rc files without consent.
EOF
