#!/usr/bin/env bash
#
# tools/setup/common/shellenv.sh — emits a managed PATH file at
# $HOME/.config/zeta/shellenv.sh, sourced from the user's shell rc
# files AND from $GITHUB_ENV / $GITHUB_PATH under CI. Single source
# of truth for PATH — see docs/research/build-machine-setup.md.
#
# On re-run, the file is regenerated idempotently (same content every
# time given the same tool set), so the "second run mutates nothing"
# contract holds.

set -euo pipefail

ZETA_ENV_DIR="$HOME/.config/zeta"
ZETA_ENV_FILE="$ZETA_ENV_DIR/shellenv.sh"
mkdir -p "$ZETA_ENV_DIR"

# Build the env file from known PATH contributors. Skip lines whose
# target directory doesn't exist so a clean machine doesn't pollute
# PATH with dead entries. Shape borrowed from SQLSharp's proven-
# green `setup-github-unix-shell-env.sh` — including BASH_ENV so
# every subsequent bash step auto-sources this file.
{
  echo "# Zeta managed shellenv — regenerated by tools/setup/common/shellenv.sh."
  echo "# Do not edit by hand; changes are overwritten on next install."
  echo

  if command -v brew >/dev/null 2>&1; then
    echo "eval \"\$($(command -v brew) shellenv)\""
  fi

  # Round-34 flip: dotnet SDK comes from mise (see .mise.toml
  # `[tools] dotnet`). Mise shims put `dotnet` on PATH via
  # `mise activate --shims` below. We still add
  # `$HOME/.dotnet/tools` because `dotnet tool install -g` always
  # lands globals there — that's a .NET convention independent
  # of where the SDK lives.
  if [ -d "$HOME/.dotnet/tools" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.dotnet/tools\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.dotnet/tools\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  if [ -d "$HOME/.elan/bin" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.elan/bin\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.elan/bin\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  if [ -d "$HOME/.local/bin" ]; then
    echo "case \":\${PATH:-}:\" in"
    echo "  *:\"\$HOME/.local/bin\":*) ;;"
    echo "  *) export PATH=\"\$HOME/.local/bin\${PATH:+:\$PATH}\" ;;"
    echo "esac"
  fi

  # Pure PATH activation (no --shims) — points PATH directly at
  # real tool binaries; mise's own docs call this ~10x faster
  # than shims. Works in a local non-interactive bash test with
  # BASH_ENV sourcing; CI will be the tiebreaker across the
  # Ubuntu + macOS matrix. If CI surfaces a step that needs
  # shims, flip back to `mise activate bash --shims` and file
  # a DEBT entry explaining which step failed and why.
  if command -v mise >/dev/null 2>&1; then
    echo "eval \"\$(mise activate bash)\""
  fi
} > "$ZETA_ENV_FILE"

echo "✓ shellenv at $ZETA_ENV_FILE"

# Under GitHub Actions, also write to $GITHUB_ENV / $GITHUB_PATH so
# the rest of the job inherits the same PATH without needing to
# source the file. This is the CI-local parity hook.
if [ -n "${GITHUB_ENV:-}" ] && [ -n "${GITHUB_PATH:-}" ]; then
  # SQLSharp-proven pattern: put BASH_ENV + ENV into $GITHUB_ENV
  # so every subsequent bash step auto-sources this shellenv file.
  # Stronger than piecewise $GITHUB_PATH echoes because the file
  # runs real shell logic (brew shellenv, mise activate, etc.).
  echo "BASH_ENV=$ZETA_ENV_FILE" >> "$GITHUB_ENV"
  echo "ENV=$ZETA_ENV_FILE" >> "$GITHUB_ENV"

  # GITHUB_PATH gets the resolvable dirs as a belt-and-braces
  # fallback for non-bash shells. dotnet itself comes from mise
  # shims (round-34 flip), not $HOME/.dotnet.
  if [ -d "$HOME/.dotnet/tools" ]; then echo "$HOME/.dotnet/tools" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.elan/bin" ];     then echo "$HOME/.elan/bin" >> "$GITHUB_PATH"; fi
  if [ -d "$HOME/.local/bin" ];    then echo "$HOME/.local/bin" >> "$GITHUB_PATH"; fi

  # mise shims (dotnet + python + java + bun + uv all live here).
  # Using --shims (not pure PATH activation) for CI reliability:
  # each `bash -c` step on a runner is a fresh subshell without a
  # prompt hook to trigger dynamic PATH update. Shims work
  # without hooks. On a dev laptop, a user can opt into the
  # ~10x-faster `mise activate` (no --shims) in their own rc file.
  for shim_dir in \
      "$HOME/.local/share/mise/shims" \
      "/opt/homebrew/opt/mise/shims" \
      "/opt/homebrew/share/mise/shims"; do
    if [ -d "$shim_dir" ]; then
      echo "$shim_dir" >> "$GITHUB_PATH"
      break
    fi
  done

  echo "✓ BASH_ENV + ENV + GITHUB_PATH updated for the remainder of the CI job"
fi

# Suggest sourcing the file from common shell rc files on first run.
# We do NOT auto-edit .zshrc / .bashrc — that's a user-visible edit
# and should be opt-in. The doc tells users how to wire it.
cat <<EOF

Next step (one-time, local dev only):
  Add this line to your ~/.zshrc (or ~/.bashrc on Linux):
    [ -f "\$HOME/.config/zeta/shellenv.sh" ] && . "\$HOME/.config/zeta/shellenv.sh"
EOF
