/**
 * codegen-law-tests.ts — Generate property tests from structured IR laws.
 *
 * Reads the `laws` field from a zeta-ir-v2-interface JSON and emits
 * property-based tests that CHECK those laws hold for a given instance.
 *
 * Named schemas (the 90%):
 * - associative: f(f(a,b),c) = f(a,f(b,c))
 * - commutative: f(a,b) = f(b,a)
 * - identity: f(a, e) = a
 * - inverse: f(a, inv(a)) = e
 * - idempotent: f(a,a) = a
 * - distributive: mul(a, add(b,c)) = add(mul(a,b), mul(a,c))
 * - involutive: f(f(a)) = a
 * - roundTrip: decode(encode(a)) = a
 *
 * Each generated test runs N random inputs (property-based), not just golden vectors.
 * The test FAILS if any input violates the law — this is falsification, not proof.
 * Proof lives in Z3/Lean and is referenced by the `proof` field.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

interface LawSchema {
  id: string;
  schema: string;
  op?: string;
  mul?: string;
  add?: string;
  element?: string;
  inverse?: string;
  identity?: string;
  over?: string;
  status: "open" | "proven" | "conjectured";
  proof?: string;
  guard?: string; // optional predicate (for tower-level laws)
  doc?: string;
}

interface InterfaceIr {
  schema: string;
  name: string;
  typeParams: { name: string; variance: string }[];
  members: { name: string; kind: string; type?: string; params?: { name: string; type: string }[] }[];
  laws: LawSchema[];
}

// ─── Generate TS property tests from laws ────────────────────────────────

export function generateLawTests(ir: InterfaceIr, instanceExpr: string): string {
  const tests = ir.laws.map(law => {
    const inputBindings = generateInputBindings(law);
    const testBody = generateTestBody(law);
    const statusComment = law.status === "proven"
      ? `// PROVEN: ${law.proof}`
      : law.status === "conjectured"
        ? `// CONJECTURED (property test = falsification only)`
        : `// OPEN (not yet proven — property test may find counterexample)`;
    const guardComment = law.guard
      ? `\n    // GUARDED: only holds when ${law.guard}`
      : "";

    return `  test("${law.id}: ${law.doc ?? law.schema}", () => {
    ${statusComment}${guardComment}
    for (let i = 0; i < N; i++) {
${inputBindings}
${testBody}
    }
  });`;
  }).join("\n\n");

  return `// GENERATED by codegen-law-tests.ts — property tests for ${ir.name}
// These tests FALSIFY (find counterexamples), not PROVE.
// Proof references are in each law's "proof" field in the IR.
import { describe, test, expect } from "bun:test";

const N = 1000; // property test iterations
const r = ${instanceExpr};
const gen = () => Math.random() * 200 - 100; // random numbers in [-100, 100]
const eq = (a: number, b: number) => Math.abs(a - b) < 1e-9;

describe("${ir.name} — algebraic law property tests (generated)", () => {
${tests}
});
`;
}

function generateInputBindings(law: LawSchema): string {
  // Declare ONLY the inputs the generated body actually references — `requiredInputs`
  // is per-schema and can over-declare for a specific law, which emits unused-var
  // (TS6133/6199) lint errors in the generated file. Filter against the body.
  const body = generateTestBody(law);
  const inputs = requiredInputs(law).filter((v) => new RegExp(`\\b${v}\\b`).test(body));
  if (inputs.length === 0) {
    return "      // No random inputs required for this schema.";
  }

  return inputs.map(input => `      const ${input} = gen();`).join("\n");
}

function requiredInputs(law: LawSchema): readonly string[] {
  switch (law.schema) {
    case "associative":
    case "distributive":
      return ["a", "b", "c"];

    case "commutative":
      return ["a", "b"];

    case "identity":
    case "inverse":
    case "idempotent":
    case "involutive":
    case "roundTrip":
      return ["a"];

    default:
      return [];
  }
}

function generateTestBody(law: LawSchema): string {
  switch (law.schema) {
    case "associative":
      return `      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.op!)}(a, b), c), r.${lcFirst(law.op!)}(a, r.${lcFirst(law.op!)}(b, c)))).toBe(true);`;

    case "commutative":
      return `      expect(eq(r.${lcFirst(law.op!)}(a, b), r.${lcFirst(law.op!)}(b, a))).toBe(true);`;

    case "identity":
      return `      expect(eq(r.${lcFirst(law.op!)}(a, r.${lcFirst(law.element!)}), a)).toBe(true);\n      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.element!)}, a), a)).toBe(true);`;

    case "inverse":
      return `      expect(eq(r.${lcFirst(law.op!)}(a, r.${lcFirst(law.inverse!)}(a)), r.${lcFirst(law.identity!)})).toBe(true);`;

    case "idempotent":
      return `      expect(eq(r.${lcFirst(law.op!)}(a, a), a)).toBe(true);`;

    case "distributive":
      return `      expect(eq(r.${lcFirst(law.mul!)}(a, r.${lcFirst(law.add!)}(b, c)), r.${lcFirst(law.add!)}(r.${lcFirst(law.mul!)}(a, b), r.${lcFirst(law.mul!)}(a, c)))).toBe(true);`;

    case "involutive":
      return `      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.op!)}(a)), a)).toBe(true);`;

    case "homomorphism":
      return `      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.over!)}(a, b)), r.${lcFirst(law.over!)}(r.${lcFirst(law.op!)}(a), r.${lcFirst(law.op!)}(b)))).toBe(true);`;

    case "antihomomorphism":
      return `      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.over!)}(a, b)), r.${lcFirst(law.over!)}(r.${lcFirst(law.op!)}(b), r.${lcFirst(law.op!)}(a)))).toBe(true);`;

    case "multiplicative":
      return `      // |f(a)*f(b)| approx= |f(a*b)| (norm-multiplicativity)\n      // Skipped for scalar gen — needs vector/complex input`;

    case "fixpoint":
      return `      expect(eq(r.${lcFirst(law.op!)}(r.${lcFirst(law.element!)}), r.${lcFirst(law.element!)})).toBe(true);`;

    case "roundTrip":
      return `      expect(r.decode(r.encode(a))).toEqual(a);`;

    default:
      return `      // Unknown schema: ${law.schema}`;
  }
}

function lcFirst(s: string): string {
  return s.length === 0 ? s : s.charAt(0).toLowerCase() + s.slice(1);
}

// ─── Verify law statuses (the CI gate) ──────────────────────────────────

export interface LawVerification {
  id: string;
  status: string;
  proofExists: boolean;
  proofPath?: string;
}

export function verifyLawStatuses(ir: InterfaceIr, repoRoot: string): LawVerification[] {
  return ir.laws.map(law => {
    if (law.status !== "proven" || !law.proof) {
      return { id: law.id, status: law.status, proofExists: false };
    }
    // Check if the referenced proof file exists
    const proofPath = law.proof.split(":")[0] ?? law.proof; // "file:test-name" format
    try {
      readFileSync(join(repoRoot, proofPath));
      return { id: law.id, status: law.status, proofExists: true, proofPath };
    } catch {
      return { id: law.id, status: law.status, proofExists: false, proofPath };
    }
  });
}

// ─── CLI ─────────────────────────────────────────────────────────────────

if (import.meta.main) {
  const [irPath, instanceExpr, outPath] = process.argv.slice(2);
  if (!irPath || !instanceExpr) {
    console.error("Usage: bun codegen-law-tests.ts <ir.json> <instance-expr> [out.ts]");
    process.exit(1);
  }
  const ir: InterfaceIr = JSON.parse(readFileSync(irPath, "utf-8"));
  const code = generateLawTests(ir, instanceExpr);
  if (outPath) {
    writeFileSync(outPath, code);
    console.log(`[codegen-law-tests] wrote ${outPath}`);
  } else {
    console.log(code);
  }
}
