/**
 * codegen-from-ir.ts — multi-language codegen from zeta-ir-v1.
 *
 * Reads a zeta-ir-v1 artifact (JSON) and emits runnable oracle scripts in each
 * target language. The generated scripts are TOTAL INTERPRETERS of the IR —
 * they don't hardcode the algorithm, they fold the IR's op list over inputs.
 *
 * This is Phase B of the gen(gen)===gen trajectory: proving the generator
 * reproduces what humans already byte-locked, by generating code that produces
 * identical golden-vector output.
 *
 * Targets: TypeScript, F#, C#, Rust
 *
 * Usage:
 *   bun tests/cross-verification/_harness/codegen-from-ir.ts <ir.json> <output-dir>
 *
 * The generated scripts read the IR at runtime (as data, not compiled-in) and
 * fold it over the canonical input set, emitting <lang>-output.json.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";

// ─── IR types ────────────────────────────────────────────────────────────────

interface IrOp {
  op: "mul" | "xorshr";
  k?: number | bigint;
  s?: number;
}

interface ZetaIrV1 {
  schema: string;
  generator: string;
  version: number;
  width: number;
  ops: IrOp[];
}

/**
 * Parse a zeta-ir-v1 JSON string with BigInt-safe integer handling.
 * JSON.parse loses precision on int64s; we use regex replacement to preserve them.
 */
function parseIrJson(text: string): ZetaIrV1 {
  // Replace integer values in "k": <big-number> with string form for safe parsing
  const safe = text.replace(/"k"\s*:\s*(-?\d+)/g, '"k": "$1"');
  const parsed = JSON.parse(safe);
  // Convert k strings back to bigint
  if (parsed.ops) {
    for (const op of parsed.ops) {
      if (op.k !== undefined) op.k = BigInt(op.k);
    }
  }
  return parsed;
}

// ─── Canonical inputs (shared across all targets) ────────────────────────────

const CANONICAL_INPUTS: [string, string][] = [
  ["x-0", "0"],
  ["x-1", "1"],
  ["x-2", "2"],
  ["x-10", "10"],
  ["x-255", "255"],
  ["x-u64max", "18446744073709551615"],
  ["x-golden", "11400714819323198485"],
  ["x-2pow63", "9223372036854775808"],
  ["x-12345678901234567890", "12345678901234567890"],
  ["x-1e18", "1000000000000000000"],
];

// ─── Code generators ─────────────────────────────────────────────────────────

function emitTypeScript(ir: ZetaIrV1): string {
  // Serialize ops with BigInt-safe string constants (avoid JSON.stringify precision loss)
  const opsLiteral = ir.ops.map(op => {
    if (op.op === "mul") return `{ op: "mul", k: "${op.k}" }`;
    return `{ op: "xorshr", s: ${op.s} }`;
  }).join(", ");

  return `// GENERATED by codegen-from-ir.ts — DO NOT EDIT
// IR-driven total interpreter for ${ir.generator} (zeta-ir-v1, width=${ir.width})
import { writeFileSync } from "node:fs";
import { join, dirname } from "node:path";

const MASK = (1n << 64n) - 1n;
const u64 = (x: bigint): bigint => x & MASK;

const OPS = [${opsLiteral}] as const;

function mix(x: bigint): bigint {
  return OPS.reduce((z: bigint, step) => {
    if (step.op === "mul") return u64(z * u64(BigInt(step.k)));
    if (step.op === "xorshr") return u64(z ^ (z >> BigInt(step.s)));
    throw new Error(\`unknown op: \${step.op}\`);
  }, u64(x));
}

const inputs: [string, string][] = ${JSON.stringify(CANONICAL_INPUTS)};
const out: Record<string, string> = { _source: "generated-from-ir" };
for (const [id, x] of inputs) out[id] = mix(BigInt(x)).toString();

const target = join(dirname(import.meta.dir), "ts-output.json");
writeFileSync(target, JSON.stringify(out, null, 2) + "\\n");
console.log("wrote ts-output.json (generated-from-ir)");
`;
}

function emitFSharp(ir: ZetaIrV1): string {
  // Generate the mix function as a pipeline of operations
  const steps = ir.ops.map((op) => {
    if (op.op === "mul") {
      // Convert signed i64 to unsigned u64 for F#
      const unsigned = BigInt(op.k!) & ((1n << 64n) - 1n);
      return `    z <- z * ${unsigned}UL`;
    }
    return `    z <- z ^^^ (z >>> ${op.s})`;
  });

  return `// GENERATED by codegen-from-ir.ts — DO NOT EDIT
// IR-driven total interpreter for ${ir.generator} (zeta-ir-v1, width=${ir.width})
open System.IO
open System.Text

let mix (x: uint64) : uint64 =
    let mutable z = x
${steps.join("\n")}
    z

let inputs =
    [ ${CANONICAL_INPUTS.map(([id, x]) => `"${id}", ${x}UL`).join("\n      ")} ]

let sb = StringBuilder()
sb.AppendLine("{") |> ignore
sb.AppendLine("  \\"_source\\": \\"generated-from-ir\\",") |> ignore
inputs
|> List.iteri (fun i (id, x) ->
    let comma = if i < inputs.Length - 1 then "," else ""
    sb.AppendLine(sprintf "  \\"%s\\": \\"%d\\"%s" id (mix x) comma) |> ignore)
sb.AppendLine("}") |> ignore

let here = __SOURCE_DIRECTORY__
let target = Path.Combine(Path.GetDirectoryName(here), "fsharp-output.json")
File.WriteAllText(target, sb.ToString())
printfn "wrote fsharp-output.json (generated-from-ir)"
`;
}

function emitCSharp(ir: ZetaIrV1): string {
  const steps = ir.ops.map((op) => {
    if (op.op === "mul") {
      const unsigned = BigInt(op.k!) & ((1n << 64n) - 1n);
      return `        z = z * 0x${unsigned.toString(16).toUpperCase()}UL;`;
    }
    return `        z = z ^ (z >> ${op.s});`;
  });

  return `// GENERATED by codegen-from-ir.ts — DO NOT EDIT
// IR-driven total interpreter for ${ir.generator} (zeta-ir-v1, width=${ir.width})
using System;
using System.IO;
using System.Text;

static ulong Mix(ulong x)
{
    unchecked
    {
        ulong z = x;
${steps.join("\n")}
        return z;
    }
}

var inputs = new (string Id, ulong X)[]
{
${CANONICAL_INPUTS.map(([id, x]) => `    ("${id}", ${x}UL),`).join("\n")}
};

var sb = new StringBuilder();
sb.AppendLine("{");
sb.AppendLine("  \\"_source\\": \\"generated-from-ir\\",");
for (int i = 0; i < inputs.Length; i++)
{
    var (id, x) = inputs[i];
    var comma = i < inputs.Length - 1 ? "," : "";
    sb.AppendLine($"  \\"{id}\\": \\"{Mix(x)}\\"{comma}");
}
sb.AppendLine("}");

var here = Path.GetDirectoryName(Path.GetFullPath("gen.csx"))!;
var target = Path.Combine(Directory.GetParent(here)!.FullName, "cs-output.json");
File.WriteAllText(target, sb.ToString());
Console.WriteLine("wrote cs-output.json (generated-from-ir)");
`;
}

function emitRust(ir: ZetaIrV1): string {
  const steps = ir.ops.map((op) => {
    if (op.op === "mul") {
      const unsigned = BigInt(op.k!) & ((1n << 64n) - 1n);
      return `    z = z.wrapping_mul(0x${unsigned.toString(16).toUpperCase()});`;
    }
    return `    z = z ^ (z >> ${op.s});`;
  });

  return `// GENERATED by codegen-from-ir.ts — DO NOT EDIT
// IR-driven total interpreter for ${ir.generator} (zeta-ir-v1, width=${ir.width})
use std::fs;
use std::path::Path;

fn mix(x: u64) -> u64 {
    let mut z = x;
${steps.join("\n")}
    z
}

fn main() {
    let inputs: [(&str, u64); ${CANONICAL_INPUTS.length}] = [
${CANONICAL_INPUTS.map(([id, x]) => `        ("${id}", ${x}),`).join("\n")}
    ];
    let mut s = String::from("{\\n");
    s.push_str("  \\"_source\\": \\"generated-from-ir\\",\\n");
    for (i, (id, x)) in inputs.iter().enumerate() {
        let comma = if i < inputs.len() - 1 { "," } else { "" };
        s.push_str(&format!("  \\"{}\\": \\"{}\\"{}\\n", id, mix(*x), comma));
    }
    s.push_str("}\\n");
    let target = Path::new("..").join("rust-output.json");
    fs::write(target, s).expect("write rust-output.json");
    println!("wrote rust-output.json (generated-from-ir)");
}
`;
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main(): number {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.error("Usage: codegen-from-ir.ts <ir.json> <output-dir>");
    return 1;
  }

  const irPath = args[0]!;
  const outDir = args[1]!;

  const ir: ZetaIrV1 = parseIrJson(readFileSync(irPath, "utf-8"));

  if (ir.schema !== "zeta-ir-v1") {
    console.error(`ERROR: expected schema "zeta-ir-v1", got "${ir.schema}"`);
    return 1;
  }

  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, "gen.ts"), emitTypeScript(ir));
  writeFileSync(join(outDir, "gen.fsx"), emitFSharp(ir));
  writeFileSync(join(outDir, "gen.csx"), emitCSharp(ir));
  writeFileSync(join(outDir, "gen.rs"), emitRust(ir));

  console.log(`[codegen] emitted 4 oracle scripts from ${basename(irPath)} → ${outDir}`);
  console.log(`  gen.ts  — TypeScript (BigInt wrapping)`);
  console.log(`  gen.fsx — F# (uint64 wrapping)`);
  console.log(`  gen.csx — C# (unchecked ulong)`);
  console.log(`  gen.rs  — Rust (wrapping_mul)`);
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}

export { emitTypeScript, emitFSharp, emitCSharp, emitRust, parseIrJson, type ZetaIrV1 };
