import { describe, test, expect } from "bun:test";
import { emitCSharp, emitTypeScript, emitRust, emitFSharp, emitPython, emitGo, emitQSharp } from "./codegen-interface";
import { readFileSync } from "node:fs";
import { join } from "node:path";
const irDir = join(import.meta.dir, "../zeta-ir-v2/interfaces");
const semiring = JSON.parse(readFileSync(join(irDir, "semiring.ir.json"), "utf-8"));
const starRing = JSON.parse(readFileSync(join(irDir, "star-ring.ir.json"), "utf-8"));
describe("codegen-interface — ISemiring", () => {
    test("C# emits correct interface with inheritance", () => {
        const cs = emitCSharp(semiring);
        expect(cs).toContain("public interface ISemiring<TWeight>");
        expect(cs).toContain("TWeight Zero { get; }");
        expect(cs).toContain("TWeight Add(TWeight a, TWeight b)");
        expect(cs).toContain("TWeight Negate(TWeight a)");
        expect(cs).toContain("namespace Zeta.Core");
    });
    test("TypeScript emits correct interface", () => {
        const ts = emitTypeScript(semiring);
        expect(ts).toContain("export interface ISemiring<TWeight>");
        expect(ts).toContain("readonly Zero: TWeight");
        expect(ts).toContain("Add(a: TWeight, b: TWeight): TWeight");
    });
    test("Rust emits correct trait", () => {
        const rs = emitRust(semiring);
        expect(rs).toContain("pub trait ISemiring<TWeight>");
        expect(rs).toContain("fn zero(&self) -> TWeight");
        expect(rs).toContain("fn add(&self, a: TWeight, b: TWeight) -> TWeight");
    });
    test("F# emits correct abstract type", () => {
        const fsx = emitFSharp(semiring);
        expect(fsx).toContain("type ISemiring<'TWeight>");
        expect(fsx).toContain("abstract member Zero: 'TWeight");
        expect(fsx).toContain("abstract member Add: 'TWeight * 'TWeight -> 'TWeight");
    });
    test("Python emits correct Protocol with TypeVar", () => {
        const py = emitPython(semiring);
        expect(py).toContain('TWeight = TypeVar("TWeight")');
        expect(py).toContain("class ISemiring(Protocol, Generic[TWeight])");
        expect(py).toContain("def add(self, a: TWeight, b: TWeight) -> TWeight");
    });
    test("Go emits correct interface with generics", () => {
        const go = emitGo(semiring);
        expect(go).toContain("type ISemiring[TWeight any] interface");
        expect(go).toContain("Add(a TWeight, b TWeight) TWeight");
    });
    test("all 7 targets contain the GENERATED marker", () => {
        const all = [emitCSharp, emitTypeScript, emitRust, emitFSharp, emitPython, emitGo, emitQSharp];
        for (const emit of all) {
            expect(emit(semiring)).toContain("GENERATED by codegen-interface.ts");
        }
    });
});
describe("codegen-interface — IStarRing (with inheritance + laws)", () => {
    test("C# includes variance annotation (invariant = no prefix)", () => {
        const cs = emitCSharp(starRing);
        // Invariant means no `out`/`in` prefix
        expect(cs).toContain("IStarRing<TWeight>");
        expect(cs).not.toContain("out TWeight");
        expect(cs).not.toContain("in TWeight");
    });
    test("C# includes extends clause", () => {
        const cs = emitCSharp(starRing);
        expect(cs).toContain(": ISemiring<TWeight>");
    });
    test("C# includes laws as XML remarks", () => {
        const cs = emitCSharp(starRing);
        expect(cs).toContain("Conj is involutive");
        expect(cs).toContain("anti-homomorphism");
    });
    test("TypeScript includes extends clause", () => {
        const ts = emitTypeScript(starRing);
        expect(ts).toContain("extends ISemiring<TWeight>");
    });
    test("Rust includes supertrait bound", () => {
        const rs = emitRust(starRing);
        expect(rs).toContain(": ISemiring");
    });
    test("Go includes embedded interface", () => {
        const go = emitGo(starRing);
        expect(go).toContain("ISemiring[TWeight]");
    });
    test("Conj method present in all targets", () => {
        expect(emitCSharp(starRing)).toContain("Conj");
        expect(emitTypeScript(starRing)).toContain("Conj");
        expect(emitRust(starRing)).toContain("conj");
        expect(emitFSharp(starRing)).toContain("Conj");
        expect(emitPython(starRing)).toContain("conj");
        expect(emitGo(starRing)).toContain("Conj");
        expect(emitQSharp(starRing)).toContain("Conj");
    });
});
describe("codegen-interface — variance (covariant interface)", () => {
    const covariantIr = {
        schema: "zeta-ir-v2-interface",
        name: "IFunctor",
        typeParams: [{ name: "T", variance: "covariant" }],
        members: [
            { name: "Map", kind: "method", params: [{ name: "f", type: "(T) => T" }], returns: "IFunctor<T>", doc: "Lift a function over the container." }
        ],
        doc: "Functor — covariant container.",
    };
    test("C# emits 'out T' for covariant", () => {
        const cs = emitCSharp(covariantIr);
        expect(cs).toContain("IFunctor<out T>");
    });
    test("Python emits TypeVar with covariant=True", () => {
        const py = emitPython(covariantIr);
        expect(py).toContain('T = TypeVar("T", covariant=True)');
    });
    test("Rust/Go/F# don't have explicit variance syntax (structural)", () => {
        // These languages handle variance structurally, not declaratively
        const rs = emitRust(covariantIr);
        const go = emitGo(covariantIr);
        // Just verify they compile without variance annotations in the trait/interface
        expect(rs).toContain("pub trait IFunctor<T>");
        expect(go).toContain("type IFunctor[T any] interface");
    });
});
describe("codegen-interface — contravariant interface", () => {
    const contraIr = {
        schema: "zeta-ir-v2-interface",
        name: "IConsumer",
        typeParams: [{ name: "T", variance: "contravariant" }],
        members: [
            { name: "Accept", kind: "method", params: [{ name: "value", type: "T" }], returns: "void", doc: "Consume a value." }
        ],
        doc: "Contravariant consumer.",
    };
    test("C# emits 'in T' for contravariant", () => {
        const cs = emitCSharp(contraIr);
        expect(cs).toContain("IConsumer<in T>");
    });
    test("Python emits TypeVar with contravariant=True", () => {
        const py = emitPython(contraIr);
        expect(py).toContain('T = TypeVar("T", contravariant=True)');
    });
});
