import { describe, test, expect } from "bun:test";
import {
  emitCSharp, emitTypeScript, emitRust, emitFSharp, emitPython, emitGo, emitQSharp,
  type InterfaceIr
} from "./codegen-interface";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const irDir = join(import.meta.dir, "../zeta-ir-v2/interfaces");
const semiring: InterfaceIr = JSON.parse(readFileSync(join(irDir, "semiring.ir.json"), "utf-8"));
const ring: InterfaceIr = JSON.parse(readFileSync(join(irDir, "ring.ir.json"), "utf-8"));
const starRing: InterfaceIr = JSON.parse(readFileSync(join(irDir, "star-ring.ir.json"), "utf-8"));
const zsetIsa: InterfaceIr = JSON.parse(readFileSync(join(irDir, "zset-isa.ir.json"), "utf-8"));
const gset: InterfaceIr = JSON.parse(readFileSync(join(irDir, "gset.ir.json"), "utf-8"));
const zset: InterfaceIr = JSON.parse(readFileSync(join(irDir, "zset.ir.json"), "utf-8"));
const boundedGset: InterfaceIr = JSON.parse(readFileSync(join(irDir, "bounded-gset.ir.json"), "utf-8"));
const boundedZset: InterfaceIr = JSON.parse(readFileSync(join(irDir, "bounded-zset.ir.json"), "utf-8"));
const heatSink: InterfaceIr = JSON.parse(readFileSync(join(irDir, "heat-sink.ir.json"), "utf-8"));
const database: InterfaceIr = JSON.parse(readFileSync(join(irDir, "database.ir.json"), "utf-8"));

describe("codegen-interface — ISemiring", () => {
  test("C# emits correct interface with inheritance", () => {
    const cs = emitCSharp(semiring);
    expect(cs).toContain("public interface ISemiring<TWeight>");
    expect(cs).toContain("TWeight Zero { get; }");
    expect(cs).toContain("TWeight Add(TWeight a, TWeight b)");
    expect(cs).not.toContain("TWeight Negate(TWeight a)"); // 081KWG9JQ9H: Negate lives in IRing
    expect(cs).toContain("namespace Zeta.Core");
  });

  test("TypeScript emits correct interface", () => {
    const ts = emitTypeScript(semiring);
    expect(ts).toContain("export interface ISemiring<TWeight>");
    expect(ts).toContain("readonly Zero: TWeight");
    expect(ts).toContain("Add(a: TWeight, b: TWeight): TWeight");
  });

  test("Rust emits correct trait", () => {
    const rs = emitRust(semiring);
    expect(rs).toContain("pub trait ISemiring<TWeight>");
    expect(rs).toContain("fn zero(&self) -> TWeight");
    expect(rs).toContain("fn add(&self, a: TWeight, b: TWeight) -> TWeight");
  });

  test("F# emits correct abstract type", () => {
    const fsx = emitFSharp(semiring);
    expect(fsx).toContain("type ISemiring<'TWeight>");
    expect(fsx).toContain("abstract member Zero: 'TWeight");
    expect(fsx).toContain("abstract member Add: 'TWeight * 'TWeight -> 'TWeight");
  });

  test("Python emits correct Protocol with TypeVar", () => {
    const py = emitPython(semiring);
    expect(py).toContain('TWeight = TypeVar("TWeight")');
    expect(py).toContain("class ISemiring(Protocol, Generic[TWeight])");
    expect(py).toContain("def add(self, a: TWeight, b: TWeight) -> TWeight");
  });

  test("Go emits correct interface with generics", () => {
    const go = emitGo(semiring);
    expect(go).toContain("type ISemiring[TWeight any] interface");
    expect(go).toContain("Add(a TWeight, b TWeight) TWeight");
  });

  test("all 7 targets contain the GENERATED marker", () => {
    const all = [emitCSharp, emitTypeScript, emitRust, emitFSharp, emitPython, emitGo, emitQSharp];
    for (const emit of all) {
      expect(emit(semiring)).toContain("GENERATED by codegen-interface.ts");
    }
  });
});

describe("codegen-interface — IRing", () => {
  test("C# emits ring interface extending ISemiring with Negate", () => {
    const cs = emitCSharp(ring);
    expect(cs).toContain("public interface IRing<TWeight> : ISemiring<TWeight>");
    expect(cs).toContain("TWeight Negate(TWeight a)");
  });

  test("TypeScript emits ring interface extending ISemiring", () => {
    const ts = emitTypeScript(ring);
    expect(ts).toContain("export interface IRing<TWeight> extends ISemiring<TWeight>");
    expect(ts).toContain("Negate(a: TWeight): TWeight");
  });
});

describe("codegen-interface — IStarRing (with inheritance + laws)", () => {
  test("C# includes variance annotation (invariant = no prefix)", () => {
    const cs = emitCSharp(starRing);
    // Invariant means no `out`/`in` prefix
    expect(cs).toContain("IStarRing<TWeight>");
    expect(cs).not.toContain("out TWeight");
    expect(cs).not.toContain("in TWeight");
  });

  test("C# includes extends clause", () => {
    const cs = emitCSharp(starRing);
    expect(cs).toContain(": IRing<TWeight>"); // 081KWG9JQ9H rebase
  });

  test("C# includes laws as XML remarks", () => {
    const cs = emitCSharp(starRing);
    expect(cs).toContain("Conj(Conj(a)) = a");
    expect(cs).toContain("reverses order");
  });

  test("TypeScript includes extends clause", () => {
    const ts = emitTypeScript(starRing);
    expect(ts).toContain("extends IRing<TWeight>"); // 081KWG9JQ9H rebase
  });

  test("Rust includes supertrait bound", () => {
    const rs = emitRust(starRing);
    expect(rs).toContain(": IRing"); // 081KWG9JQ9H rebase
  });

  test("Go includes embedded interface", () => {
    const go = emitGo(starRing);
    expect(go).toContain("IRing[TWeight]"); // 081KWG9JQ9H rebase
  });

  test("Conj method present in all targets", () => {
    expect(emitCSharp(starRing)).toContain("Conj");
    expect(emitTypeScript(starRing)).toContain("Conj");
    expect(emitRust(starRing)).toContain("conj");
    expect(emitFSharp(starRing)).toContain("Conj");
    expect(emitPython(starRing)).toContain("conj");
    expect(emitGo(starRing)).toContain("Conj");
    expect(emitQSharp(starRing)).toContain("Conj");
  });
});

describe("codegen-interface — variance (covariant interface)", () => {
  const covariantIr: InterfaceIr = {
    schema: "zeta-ir-v2-interface",
    name: "IFunctor",
    typeParams: [{ name: "T", variance: "covariant" }],
    members: [
      { name: "Map", kind: "method", params: [{ name: "f", type: "(T) => T" }], returns: "IFunctor<T>", doc: "Lift a function over the container." }
    ],
    doc: "Functor — covariant container.",
  };

  test("C# emits 'out T' for covariant", () => {
    const cs = emitCSharp(covariantIr);
    expect(cs).toContain("IFunctor<out T>");
  });

  test("Python emits TypeVar with covariant=True", () => {
    const py = emitPython(covariantIr);
    expect(py).toContain('T = TypeVar("T", covariant=True)');
  });

  test("Rust/Go/F# don't have explicit variance syntax (structural)", () => {
    // These languages handle variance structurally, not declaratively
    const rs = emitRust(covariantIr);
    const go = emitGo(covariantIr);
    // Just verify they compile without variance annotations in the trait/interface
    expect(rs).toContain("pub trait IFunctor<T>");
    expect(go).toContain("type IFunctor[T any] interface");
  });
});

describe("codegen-interface — contravariant interface", () => {
  const contraIr: InterfaceIr = {
    schema: "zeta-ir-v2-interface",
    name: "IConsumer",
    typeParams: [{ name: "T", variance: "contravariant" }],
    members: [
      { name: "Accept", kind: "method", params: [{ name: "value", type: "T" }], returns: "void", doc: "Consume a value." }
    ],
    doc: "Contravariant consumer.",
  };

  test("C# emits 'in T' for contravariant", () => {
    const cs = emitCSharp(contraIr);
    expect(cs).toContain("IConsumer<in T>");
  });

  test("Python emits TypeVar with contravariant=True", () => {
    const py = emitPython(contraIr);
    expect(py).toContain('T = TypeVar("T", contravariant=True)');
  });
});

describe("codegen-interface — IZSetIsa (the 6 Z-set/Quantum ISA operators)", () => {
  test("generates expected methods in TypeScript", () => {
    const ts = emitTypeScript(zsetIsa);
    expect(ts).toContain("export interface IZSetIsa<TState, TEvent, TWeight>");
    expect(ts).toContain("Emit(event: TEvent, weight: TWeight): void;");
    expect(ts).toContain("Retract(event: TEvent, weight: TWeight): void;");
    expect(ts).toContain("Branch(name: string): void;");
    expect(ts).toContain("Join(remote: string): void;");
    expect(ts).toContain("Merge(sourceRef: string): void;");
    expect(ts).toContain("Fold(initial: TState): TState;");
  });

  test("generates expected methods in C#", () => {
    const cs = emitCSharp(zsetIsa);
    expect(cs).toContain("public interface IZSetIsa<TState, TEvent, TWeight>");
    expect(cs).toContain("public void Emit(TEvent event, TWeight weight);");
    expect(cs).toContain("public void Retract(TEvent event, TWeight weight);");
    expect(cs).toContain("public void Branch(string name);");
  });

  test("generates expected methods in F#", () => {
    const fsx = emitFSharp(zsetIsa);
    expect(fsx).toContain("type IZSetIsa<'TState, 'TEvent, 'TWeight> =");
    expect(fsx).toContain("abstract member Emit: 'TEvent * 'TWeight -> unit");
  });
});

describe("codegen-interface — first-class collections & heat-sink", () => {
  test("generates IGSet", () => {
    const ts = emitTypeScript(gset);
    expect(ts).toContain("export interface IGSet<T> extends ILattice<T>");
    expect(ts).toContain("Add(item: T): boolean;");
    expect(ts).toContain("Contains(item: T): boolean;");
    expect(ts).toContain("readonly Count: number;");

    const cs = emitCSharp(gset);
    expect(cs).toContain("public interface IGSet<T> : ILattice<T>");
    expect(cs).toContain("public bool Add(T item);");

    const fsx = emitFSharp(gset);
    expect(fsx).toContain("type IGSet<'T> =");
    expect(fsx).toContain("abstract member Add: 'T -> bool");
  });

  test("generates IZSet", () => {
    const ts = emitTypeScript(zset);
    expect(ts).toContain("export interface IZSet<T, TWeight>");
    expect(ts).toContain("Add(item: T, weight: TWeight): void;");
    expect(ts).toContain("Weight(item: T): TWeight;");
    expect(ts).toContain("Support(): IGSet<T>;");

    const cs = emitCSharp(zset);
    expect(cs).toContain("public interface IZSet<T, TWeight>");
    expect(cs).toContain("public void Add(T item, TWeight weight);");

    const fsx = emitFSharp(zset);
    expect(fsx).toContain("type IZSet<'T, 'TWeight> =");
    expect(fsx).toContain("abstract member Add: 'T * 'TWeight -> unit");
  });

  test("generates IBoundedGSet", () => {
    const ts = emitTypeScript(boundedGset);
    expect(ts).toContain("export interface IBoundedGSet<T> extends IGSet<T>");
    expect(ts).toContain("readonly Capacity: number;");
    expect(ts).toContain("readonly IsSaturated: boolean;");

    const cs = emitCSharp(boundedGset);
    expect(cs).toContain("public interface IBoundedGSet<T> : IGSet<T>");
    expect(cs).toContain("public int Capacity { get; }");

    const fsx = emitFSharp(boundedGset);
    expect(fsx).toContain("type IBoundedGSet<'T> =");
    expect(fsx).toContain("inherit IGSet<'T>");
    expect(fsx).toContain("abstract member Capacity: int");
  });

  test("generates IBoundedZSet", () => {
    const ts = emitTypeScript(boundedZset);
    expect(ts).toContain("export interface IBoundedZSet<T, TWeight> extends IZSet<T, TWeight>");

    const cs = emitCSharp(boundedZset);
    expect(cs).toContain("public interface IBoundedZSet<T, TWeight> : IZSet<T, TWeight>");

    const fsx = emitFSharp(boundedZset);
    expect(fsx).toContain("type IBoundedZSet<'T, 'TWeight> =");
    expect(fsx).toContain("inherit IZSet<'T, 'TWeight>");
  });

  test("generates IHeatSink", () => {
    const ts = emitTypeScript(heatSink);
    expect(ts).toContain("export interface IHeatSink");
    expect(ts).toContain("Emit(source: string, kind: string, units: number, massPpm: number, detail: string): boolean;");

    const cs = emitCSharp(heatSink);
    expect(cs).toContain("public interface IHeatSink");
    expect(cs).toContain("public bool Emit(string source, string kind, int units, long massPpm, string detail);");

    const fsx = emitFSharp(heatSink);
    expect(fsx).toContain("type IHeatSink =");
    expect(fsx).toContain("abstract member Emit: string * string * int * int64 * string -> bool");
  });

  test("generates IDatabase", () => {
    const ts = emitTypeScript(database);
    expect(ts).toContain("export interface IDatabase");
    expect(ts).toContain("CreateFile(path: string, value: string): boolean;");
    expect(ts).toContain("ReadGSet(path: string): IGSet<string>;");
    expect(ts).toContain("ReadZSet(path: string): IZSet<string, number>;");

    const cs = emitCSharp(database);
    expect(cs).toContain("public interface IDatabase");
    expect(cs).toContain("public bool CreateFile(string path, string value);");
    expect(cs).toContain("public IGSet<string> ReadGSet(string path);");
    expect(cs).toContain("public IZSet<string, long> ReadZSet(string path);");

    const fsx = emitFSharp(database);
    expect(fsx).toContain("type IDatabase =");
    expect(fsx).toContain("abstract member CreateFile: string * string -> bool");
    expect(fsx).toContain("abstract member ReadGSet: string -> IGSet<string>");
    expect(fsx).toContain("abstract member ReadZSet: string -> IZSet<string, int64>");
  });
});

