import { describe, test, expect } from "bun:test";
import { interpretClifford, emitCliffordTS, type Multivector } from "./codegen-clifford";
import { readFileSync } from "node:fs";
import { join } from "node:path";

// Load a small IR for testing (4-bit, simple ops)
const smallIr = {
  schema: "zeta-ir-v2",
  generator: "test.clifford",
  version: 1,
  width: 4,
  ops: [
    { op: "mul", k: 3 },
    { op: "xorshr", s: 1 },
  ],
};

// Load splitmix64 for the full test
const goldenFile = JSON.parse(readFileSync(
  join(import.meta.dir, "../zeta-ir-v1/zeta-ir-v1.golden.json"), "utf-8"
));
const sm64Raw = goldenFile["rng.splitmix64"] as string;
const sm64Safe = sm64Raw.replace(/"k"\s*:\s*(-?\d+)/g, '"k_bigint": "$1"');
const sm64 = JSON.parse(sm64Safe);

describe("codegen-clifford — geometric algebra lens", () => {
  test("interpretClifford produces a valid multivector (8 components)", () => {
    const result = interpretClifford(smallIr, 5);
    expect(result).toHaveLength(8);
    // All components are numbers
    for (const v of result) {
      expect(typeof v).toBe("number");
      expect(Number.isFinite(v)).toBe(true);
    }
  });

  test("scalar input → mul produces scaled scalar (grade-0 only)", () => {
    const mulOnly = { ...smallIr, ops: [{ op: "mul", k: 3 }] };
    const result = interpretClifford(mulOnly, 5);
    // Scalar in, mul by scalar = scalar out: 5 * 3 = 15
    expect(result[0]).toBe(15);
    // All other components should be 0 (no grade promotion)
    for (let i = 1; i < 8; i++) {
      expect(result[i]).toBe(0);
    }
  });

  test("xorshr produces a reflection (flips sign of certain components)", () => {
    // Start with a non-scalar state to see the reflection
    const xorOnly = { ...smallIr, ops: [{ op: "xorshr", s: 0 }] }; // reflect through e1
    // Input 1: scalar multivector [1,0,0,0,0,0,0,0]
    const result = interpretClifford(xorOnly, 1);
    // Sandwich by e1: e1 * scalar * e1 = scalar (scalars commute)
    expect(result[0]).toBe(1);
  });

  test("reflection through e1 negates e2 and e3 components", () => {
    // Manually construct a state with vector components to verify reflection
    // For this test we verify the geometric product is correct
    const xorOnly = { ...smallIr, ops: [{ op: "mul", k: 1 }, { op: "xorshr", s: 0 }] };
    const result = interpretClifford(xorOnly, 1);
    // Pure scalar through two ops should remain scalar
    expect(result[0]).toBe(1);
  });

  test("emitCliffordTS produces valid TS code with comments", () => {
    const code = emitCliffordTS(smallIr);
    expect(code).toContain("GENERATED by codegen-clifford.ts");
    expect(code).toContain("geometric product with scalar 3");
    expect(code).toContain("reflection through");
    expect(code).toContain("cliffordMix");
    expect(code).toContain("Multivector");
  });

  test("emitCliffordTS for splitmix64 includes all 6 steps", () => {
    const code = emitCliffordTS(sm64);
    expect(code).toContain("Step 0");
    expect(code).toContain("Step 5");
    // 3 mul + 3 xorshr
    const mulCount = (code.match(/geometric product with scalar/g) || []).length;
    const xorCount = (code.match(/reflection through/g) || []).length;
    expect(mulCount).toBe(3);
    expect(xorCount).toBe(3);
  });

  test("Clifford interpretation is deterministic", () => {
    const r1 = interpretClifford(smallIr, 7);
    const r2 = interpretClifford(smallIr, 7);
    expect(r1).toEqual(r2);
  });

  test("different inputs produce different multivectors", () => {
    const r1 = interpretClifford(smallIr, 1);
    const r2 = interpretClifford(smallIr, 2);
    expect(r1).not.toEqual(r2);
  });
});
