/**
 * codegen-clifford-remaining.ts — Clifford lens emitters for F#, C#, Rust, Go, Python, Q#.
 * Extends codegen-clifford.ts to cover all 7 languages.
 *
 * Each emitter produces a standalone Cl(3,0) multivector interpreter
 * that maps IR ops to geometric algebra operations.
 */

interface IrOp { op: string; k?: number; s?: number; k_bigint?: string }
interface ZetaIrV2 { schema: string; generator: string; version: number; width: number; ops: IrOp[] }

function getK(op: IrOp, width: number): bigint {
  const raw = op.k_bigint ? BigInt(op.k_bigint) : BigInt(op.k ?? 0);
  return raw & ((1n << BigInt(width)) - 1n);
}

// ─── Python Clifford ────────────────────────────────────────────────────

export function emitCliffordPython(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `    # Step ${i}: mul(${getK(op, ir.width)}) → scale by scalar\n    state = scale(state, ${getK(op, ir.width)})`;
    if (op.op === "xorshr") return `    # Step ${i}: xorshr(${op.s}) → reflect through e${((op.s ?? 0) % 3) + 1}\n    state = sandwich(basis_vector(${(op.s ?? 0) % 3}), state)`;
    return `    # Step ${i}: ${op.op} (passthrough)`;
  }).join("\n");

  return `# GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
# Cl(3,0): 8D graded algebra. mul→scale, xorshr→reflection.
import numpy as np

Multivector = np.ndarray  # shape (8,)

def geo_product(a: Multivector, b: Multivector) -> Multivector:
    """Geometric product in Cl(3,0) via bitmask product."""
    result = np.zeros(8)
    for i in range(8):
        if a[i] == 0: continue
        for j in range(8):
            if b[j] == 0: continue
            mask = i ^ j
            sign = reorder_sign(i, j)
            result[mask] += sign * a[i] * b[j]
    return result

def reorder_sign(a: int, b: int) -> int:
    swaps = 0
    mask = a >> 1
    while mask > 0:
        swaps += bin(mask & b).count('1')
        mask >>= 1
    return 1 if swaps % 2 == 0 else -1

def scale(mv: Multivector, s: int) -> Multivector:
    return mv * float(s)

def basis_vector(axis: int) -> Multivector:
    mv = np.zeros(8)
    mv[1 << axis] = 1.0
    return mv

def sandwich(reflector: Multivector, state: Multivector) -> Multivector:
    return geo_product(geo_product(reflector, state), reflector)

def clifford_mix(x: float) -> Multivector:
    state = np.zeros(8)
    state[0] = x
${ops}
    return state
`;
}

// ─── F# Clifford ────────────────────────────────────────────────────────

export function emitCliffordFSharp(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `    let state = Cl3.scale (float ${getK(op, ir.width)}) state // Step ${i}: mul → scale`;
    if (op.op === "xorshr") return `    let state = Cl3.sandwich (Cl3.basisVector ${(op.s ?? 0) % 3}) state // Step ${i}: xorshr → reflect`;
    return `    // Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
// Uses Zeta.Core.Cl3 module (the source of truth for Cl(3,0))
open Zeta.Core

let cliffordMix (x: float) =
    let mutable state = Cl3.scalar x
${ops}
    state
`;
}

// ─── C# Clifford ────────────────────────────────────────────────────────

export function emitCliffordCSharp(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `        state = Cl3.Scale(state, ${getK(op, ir.width)}d); // Step ${i}: mul → scale`;
    if (op.op === "xorshr") return `        state = Cl3.Sandwich(Cl3.BasisVector(${(op.s ?? 0) % 3}), state); // Step ${i}: xorshr → reflect`;
    return `        // Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
// Cl(3,0): 8D multivector. mul→scale, xorshr→reflection.
using Zeta.Core;

public static Multivector CliffordMix(double x)
{
    var state = Cl3.Scalar(x);
${ops}
    return state;
}
`;
}

// ─── Rust Clifford ──────────────────────────────────────────────────────

export function emitCliffordRust(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `    state = cl3::scale(&state, ${getK(op, ir.width)}.0); // Step ${i}: mul → scale`;
    if (op.op === "xorshr") return `    state = cl3::sandwich(&cl3::basis_vector(${(op.s ?? 0) % 3}), &state); // Step ${i}: xorshr → reflect`;
    return `    // Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
// Cl(3,0): 8D multivector. mul→scale, xorshr→reflection.
use crate::cl3;

pub fn clifford_mix(x: f64) -> cl3::Multivector {
    let mut state = cl3::scalar(x);
${ops}
    state
}
`;
}

// ─── Go Clifford ────────────────────────────────────────────────────────

export function emitCliffordGo(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `\tstate = cl3.Scale(state, ${getK(op, ir.width)}.0) // Step ${i}: mul → scale`;
    if (op.op === "xorshr") return `\tstate = cl3.Sandwich(cl3.BasisVector(${(op.s ?? 0) % 3}), state) // Step ${i}: xorshr → reflect`;
    return `\t// Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
// Cl(3,0): 8D multivector. mul→scale, xorshr→reflection.
package main

import "zeta/cl3"

func CliffordMix(x float64) cl3.Multivector {
\tstate := cl3.Scalar(x)
${ops}
\treturn state
}
`;
}

// ─── Q# Clifford ────────────────────────────────────────────────────────

export function emitCliffordQSharp(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `        // Step ${i}: mul → Rz rotation (phase = scale factor)`;
    if (op.op === "xorshr") return `        // Step ${i}: xorshr → reflection through axis ${(op.s ?? 0) % 3} (Pauli gate)`;
    return `        // Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-clifford.ts — Clifford lens for ${ir.generator}
// In Q#: Clifford operations ARE the native gate set (Pauli + H + CNOT).
// mul → Rz (phase rotation), xorshr → Pauli reflection.
namespace Zeta.Clifford {
    operation CliffordMix(qs : Qubit[]) : Unit is Adj + Ctl {
${ops}
    }
}
`;
}
