import { describe, test, expect } from "bun:test";
import { emitTypeScriptRx, emitPythonRx, emitCSharpRx } from "./codegen-rx";
import { readFileSync } from "node:fs";
import { join } from "node:path";
// Load the sample branching IR
const branchIr = JSON.parse(readFileSync(join(import.meta.dir, "../zset-isa-v2/sample-circuit.ir.json"), "utf-8"));
// Simulate loading splitmix64 from the golden file
const goldenFile = JSON.parse(readFileSync(join(import.meta.dir, "../zeta-ir-v1/zeta-ir-v1.golden.json"), "utf-8"));
const sm64Raw = goldenFile["rng.splitmix64"];
// Parse with BigInt safety
const sm64Str = sm64Raw;
const sm64 = JSON.parse(sm64Str.replace(/"k"\s*:\s*(-?\d+)/g, '"k_bigint": "$1"'));
describe("codegen-rx — Rx pipeline emission", () => {
    test("TypeScript Rx: deterministic IR uses map only (no mergeMap in pipe)", () => {
        // splitmix64 has only mul/xorshr — should only have map() in the pipe, no mergeMap()
        const ts = emitTypeScriptRx(sm64);
        expect(ts).toContain("map((z: bigint)");
        // mergeMap is in the import but NOT used in the pipe
        const pipeSection = ts.split("pipe(")[1]?.split(");")[0] ?? "";
        expect(pipeSection).not.toContain("mergeMap");
        expect(ts).toContain("rng_splitmix64_pipeline");
    });
    test("TypeScript Rx: branching IR uses mergeMap for branch ops", () => {
        const ts = emitTypeScriptRx(branchIr);
        expect(ts).toContain("mergeMap");
        expect(ts).toContain("from([z,");
    });
    test("TypeScript Rx: correct multiplier constants (BigInt-safe)", () => {
        const ts = emitTypeScriptRx(sm64);
        // The three SplitMix64 multipliers (unsigned)
        expect(ts).toContain("11400714819323198485n");
        expect(ts).toContain("13787848793156543929n");
        expect(ts).toContain("10723151780598845931n");
    });
    test("Python Rx: deterministic IR uses ops.map only", () => {
        const py = emitPythonRx(sm64);
        expect(py).toContain("ops.map(lambda z:");
        expect(py).not.toContain("ops.flat_map");
        expect(py).toContain("rx.pipe(");
    });
    test("Python Rx: branching IR uses ops.flat_map", () => {
        const py = emitPythonRx(branchIr);
        expect(py).toContain("ops.flat_map");
    });
    test("C# Rx: deterministic IR uses .Select only", () => {
        const cs = emitCSharpRx(sm64);
        expect(cs).toContain(".Select(z =>");
        expect(cs).not.toContain(".SelectMany");
        expect(cs).toContain("IObservable<ulong>");
    });
    test("C# Rx: branching IR uses .SelectMany", () => {
        const cs = emitCSharpRx(branchIr);
        expect(cs).toContain(".SelectMany");
    });
    test("all targets include GENERATED marker", () => {
        expect(emitTypeScriptRx(sm64)).toContain("GENERATED by codegen-rx.ts");
        expect(emitPythonRx(sm64)).toContain("GENERATED by codegen-rx.ts");
        expect(emitCSharpRx(sm64)).toContain("GENERATED by codegen-rx.ts");
    });
    test("Rx lens maps ISA ops correctly", () => {
        const ts = emitTypeScriptRx(branchIr);
        // branch → mergeMap (fork)
        // join → map with conditional (CNOT)
        // mul → map (multiply)
        const lines = ts.split("\n");
        const pipeLines = lines.filter(l => l.trim().startsWith("map(") || l.trim().startsWith("mergeMap("));
        // Should have: 1 mergeMap (branch) + 2 map (join + mul)
        expect(pipeLines.length).toBe(3);
    });
});
