/**
 * codegen-interface.ts — Emit language-specific interfaces from IR descriptions.
 *
 * The IR describes an interface as DATA (a JSON object with name, type params,
 * members, variance annotations, and inheritance). The codegen reads this and
 * emits the interface in all 7 target languages using the GCF+specialize principle:
 * richest shared structure + per-language extras (variance in C#, trait bounds in Rust, etc).
 *
 * Design: interfaces ARE IR nodes. Same schema, different dimension.
 * The generator that emits StarRing code can also emit StarRing's interface definition.
 */

// ─── IR Schema for Interface Descriptions ──────────────────────────────────

export interface InterfaceMember {
  name: string;
  kind: "property" | "method";
  // For properties: type is the return type
  // For methods: params + returns
  type?: string;
  params?: { name: string; type: string }[];
  returns?: string;
  doc?: string;
}

export interface InterfaceIr {
  schema: "zeta-ir-v2-interface";
  name: string;
  typeParams: { name: string; variance: "invariant" | "covariant" | "contravariant" }[];
  extends?: string[];
  members: InterfaceMember[];
  doc?: string;
  laws?: string[]; // Documentation of algebraic laws (not machine-checked here)
}

// ─── Emit C# ──────────────────────────────────────────────────────────────

export function emitCSharp(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => {
    const prefix = tp.variance === "covariant" ? "out " :
                   tp.variance === "contravariant" ? "in " : "";
    return `${prefix}${tp.name}`;
  }).join(", ");

  const extendsClause = ir.extends?.length
    ? ` : ${ir.extends.map(e => `${e}<${ir.typeParams.map(t => t.name).join(", ")}>`).join(", ")}`
    : "";

  const members = ir.members.map(m => {
    const doc = m.doc ? `    /// <summary>${m.doc}</summary>\n` : "";
    if (m.kind === "property") {
      return `${doc}    public ${m.type} ${m.name} { get; }`;
    } else {
      const params = (m.params || []).map(p => `${p.type} ${p.name}`).join(", ");
      return `${doc}    public ${m.returns} ${m.name}(${params});`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `/// <summary>\n/// ${ir.doc}\n/// </summary>\n` : "";
  const laws = ir.laws?.length
    ? `/// <remarks>\n/// Laws:\n${ir.laws.map(l => `/// - ${l}`).join("\n")}\n/// </remarks>\n`
    : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT
namespace Zeta.Core;

${doc}${laws}public interface ${ir.name}<${typeParams}>${extendsClause}
{
${members}
}
`;
}

// ─── Emit TypeScript ──────────────────────────────────────────────────────

export function emitTypeScript(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => tp.name).join(", ");
  const extendsClause = ir.extends?.length
    ? ` extends ${ir.extends.map(e => `${e}<${ir.typeParams.map(t => t.name).join(", ")}>`).join(", ")}`
    : "";

  const members = ir.members.map(m => {
    const doc = m.doc ? `  /** ${m.doc} */\n` : "";
    if (m.kind === "property") {
      return `${doc}  readonly ${m.name}: ${tsType(m.type!)};`;
    } else {
      const params = (m.params || []).map(p => `${p.name}: ${tsType(p.type)}`).join(", ");
      return `${doc}  ${m.name}(${params}): ${tsType(m.returns!)};`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `/** ${ir.doc} */\n` : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT

${doc}export interface ${ir.name}<${typeParams}>${extendsClause} {
${members}
}
`;
}

function tsType(t: string): string {
  // Keep type param names as-is (they match the generic declaration)
  return t.replace(/\bbool\b/g, "boolean");
}

// ─── Emit Rust ───────────────────────────────────────────────────────────

export function emitRust(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => tp.name).join(", ");
  const bounds = ir.extends?.length
    ? `: ${ir.extends.join(" + ")}`
    : "";

  const members = ir.members.map(m => {
    const doc = m.doc ? `    /// ${m.doc}\n` : "";
    if (m.kind === "property") {
      return `${doc}    fn ${toSnake(m.name)}(&self) -> ${rustType(m.type!)};`;
    } else {
      const params = (m.params || []).map(p => `${toSnake(p.name)}: ${rustType(p.type)}`).join(", ");
      return `${doc}    fn ${toSnake(m.name)}(&self, ${params}) -> ${rustType(m.returns!)};`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `/// ${ir.doc}\n` : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT

${doc}pub trait ${ir.name}<${typeParams}>${bounds} {
${members}
}
`;
}

function rustType(t: string): string {
  // Keep type param names as declared in the IR
  return t;
}

function toSnake(s: string): string {
  return s.replace(/([A-Z])/g, "_$1").toLowerCase().replace(/^_/, "");
}

// ─── Emit F# ────────────────────────────────────────────────────────────

export function emitFSharp(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => `'${tp.name}`).join(", ");
  const inherits = ir.extends?.length
    ? ir.extends.map(e => `    inherit ${e}<${ir.typeParams.map(t => `'${t.name}`).join(", ")}>`).join("\n") + "\n"
    : "";

  const members = ir.members.map(m => {
    const doc = m.doc ? `    /// ${m.doc}\n` : "";
    if (m.kind === "property") {
      return `${doc}    abstract member ${m.name}: ${fsharpType(m.type!)}`;
    } else {
      const paramTypes = (m.params || []).map(p => fsharpType(p.type)).join(" * ");
      return `${doc}    abstract member ${m.name}: ${paramTypes} -> ${fsharpType(m.returns!)}`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `/// ${ir.doc}\n` : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT
namespace Zeta.Core

${doc}[<Interface>]
type ${ir.name}<${typeParams}> =
${inherits}${members}
`;
}

function fsharpType(t: string): string {
  // F# type params are prefixed with '
  return t.replace(/\bTWeight\b/g, "'TWeight");
}

// ─── Emit Python ─────────────────────────────────────────────────────────

export function emitPython(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => {
    const variance = tp.variance === "covariant" ? ", covariant=True" :
                     tp.variance === "contravariant" ? ", contravariant=True" : "";
    return `${tp.name} = TypeVar("${tp.name}"${variance})`;
  }).join("\n");

  const bases = ir.extends?.length
    ? ir.extends.map(e => `${e}[${ir.typeParams.map(t => t.name).join(", ")}]`).join(", ")
    : "Protocol";

  const members = ir.members.map(m => {
    const doc = m.doc ? `        \"\"\"${m.doc}\"\"\"\n` : "";
    if (m.kind === "property") {
      return `    @property\n    @abstractmethod\n    def ${toSnake(m.name)}(self) -> ${pythonType(m.type!)}:\n${doc}        ...`;
    } else {
      const params = (m.params || []).map(p => `${toSnake(p.name)}: ${pythonType(p.type)}`).join(", ");
      return `    @abstractmethod\n    def ${toSnake(m.name)}(self, ${params}) -> ${pythonType(m.returns!)}:\n${doc}        ...`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `    \"\"\"${ir.doc}\"\"\"\n\n` : "";

  return `# GENERATED by codegen-interface.ts — DO NOT EDIT
from __future__ import annotations
from abc import abstractmethod
from typing import TypeVar, Protocol, Generic

${typeParams}


class ${ir.name}(${bases}, Generic[${ir.typeParams.map(t => t.name).join(", ")}]):
${doc}${members}
`;
}

function pythonType(t: string): string {
  return t;
}

// ─── Emit Go ─────────────────────────────────────────────────────────────

export function emitGo(ir: InterfaceIr): string {
  const typeParams = ir.typeParams.map(tp => `${tp.name} any`).join(", ");
  const embeds = ir.extends?.length
    ? ir.extends.map(e => `    ${e}[${ir.typeParams.map(t => t.name).join(", ")}]`).join("\n") + "\n"
    : "";

  const members = ir.members.map(m => {
    const doc = m.doc ? `    // ${m.doc}\n` : "";
    if (m.kind === "property") {
      return `${doc}    ${m.name}() ${goType(m.type!)}`;
    } else {
      const params = (m.params || []).map(p => `${p.name} ${goType(p.type)}`).join(", ");
      return `${doc}    ${m.name}(${params}) ${goType(m.returns!)}`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `// ${ir.doc}\n` : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT
package algebra

${doc}type ${ir.name}[${typeParams}] interface {
${embeds}${members}
}
`;
}

function goType(t: string): string {
  return t;
}

// ─── Emit Q# ─────────────────────────────────────────────────────────────

export function emitQSharp(ir: InterfaceIr): string {
  // Q# doesn't have interfaces — emit as a newtype + function signatures
  const typeParams = ir.typeParams.map(tp => `'${tp.name}`).join(", ");

  const functions = ir.members.map(m => {
    const doc = m.doc ? `    /// ${m.doc}\n` : "";
    if (m.kind === "property") {
      return `${doc}    function ${m.name}() : ${qsharpType(m.type!)} { ... }`;
    } else {
      const params = (m.params || []).map(p => `${p.name} : ${qsharpType(p.type)}`).join(", ");
      return `${doc}    function ${m.name}(${params}) : ${qsharpType(m.returns!)} { ... }`;
    }
  }).join("\n\n");

  const doc = ir.doc ? `    /// ${ir.doc}\n` : "";

  return `// GENERATED by codegen-interface.ts — DO NOT EDIT
// Q# doesn't have interfaces — this is a specification (function signatures)
namespace Zeta.Core {
${doc}
    // ${ir.name} specification:
${functions}
}
`;
}

function qsharpType(t: string): string {
  // Q# doesn't have generics in the same way — use Int as the concrete type
  return t.replace(/\bTWeight\b/g, "Int");
}

// ─── Main: read IR JSON, emit all 7 ──────────────────────────────────────

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

export function emitAll(ir: InterfaceIr, outDir: string): void {
  mkdirSync(outDir, { recursive: true });

  const files: [string, string, string][] = [
    ["cs", `I${ir.name}.cs`, emitCSharp(ir)],
    ["ts", `${ir.name}.ts`, emitTypeScript(ir)],
    ["rs", `${toSnake(ir.name)}.rs`, emitRust(ir)],
    ["fsx", `${ir.name}.fsx`, emitFSharp(ir)],
    ["py", `${toSnake(ir.name)}.py`, emitPython(ir)],
    ["go", `${toSnake(ir.name)}.go`, emitGo(ir)],
    ["qs", `${ir.name}.qs`, emitQSharp(ir)],
  ];

  for (const [ext, filename, content] of files) {
    writeFileSync(join(outDir, filename), content);
  }

  console.log(`[codegen-interface] emitted ${files.length} interface files from ${ir.name} → ${outDir}`);
  for (const [ext, filename] of files) {
    console.log(`  ${filename}`);
  }
}

// ─── CLI entry point ─────────────────────────────────────────────────────

if (import.meta.main) {
  const [irPath, outDir] = process.argv.slice(2);
  if (!irPath || !outDir) {
    console.error("Usage: bun codegen-interface.ts <ir.json> <out-dir>");
    process.exit(1);
  }
  const ir: InterfaceIr = JSON.parse(readFileSync(irPath, "utf-8"));
  if (ir.schema !== "zeta-ir-v2-interface") {
    console.error(`ERROR: expected schema "zeta-ir-v2-interface", got "${ir.schema}"`);
    process.exit(1);
  }
  emitAll(ir, outDir);
}
