/**
 * codegen-v2-ring.ts — unified v2 codegen: emits ring-generic scripts from zeta-ir-v2.
 *
 * Unlike codegen-from-ir.ts (classical only, hardcoded arithmetic), this emitter
 * produces scripts that IMPORT the StarRing interface and use the ring-generic
 * interpreter. The emitted code handles ALL v2 ops (including branch/join/emit/retract).
 *
 * The emitted scripts are parameterized by ring instance at runtime:
 *   - Pass realRing → Bayesian behavior (no interference)
 *   - Pass complexRing → Quantum behavior (interference)
 *
 * Targets: TS (first, as proof of concept — others follow the same template)
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, basename } from "node:path";
import { emitRingGenericFSharp, emitRingGenericCSharp, emitRingGenericRust, emitRingGenericGo, emitRingGenericQSharp } from "./codegen-v2-remaining";

// ─── IR types ────────────────────────────────────────────────────────────────

interface IrOp {
  op: string;
  k?: number | bigint;
  s?: number;
  bit?: number;
  control?: number;
  target?: number;
}

interface ZetaIrV2 {
  schema: string;
  generator: string;
  version: number;
  width: number;
  ops: IrOp[];
}

function parseIrJson(text: string): ZetaIrV2 {
  const safe = text.replace(/"k"\s*:\s*(-?\d+)/g, '"k": "$1"');
  const parsed = JSON.parse(safe);
  if (parsed.ops) {
    for (const op of parsed.ops) {
      if (op.k !== undefined) op.k = BigInt(op.k);
    }
  }
  return parsed;
}

// ─── TS emitter (ring-generic, handles all v2 ops) ───────────────────────────

function emitRingGenericTS(ir: ZetaIrV2): string {
  const opsJson = ir.ops.map(op => {
    const parts: string[] = [`op: "${op.op}"`];
    if (op.k !== undefined) parts.push(`k: "${op.k}"`);
    if (op.s !== undefined) parts.push(`s: ${op.s}`);
    if (op.bit !== undefined) parts.push(`bit: ${op.bit}`);
    if (op.control !== undefined) parts.push(`control: ${op.control}`);
    if (op.target !== undefined) parts.push(`target: ${op.target}`);
    return `{ ${parts.join(", ")} }`;
  }).join(",\n    ");

  return `// GENERATED by codegen-v2-ring.ts — ring-generic interpreter for ${ir.generator}
// Handles ALL v2 ops: mul, xorshr, branch, emit, retract, join, merge.
// Import the StarRing and run with any ring instance.
import { softMixGeneric, type ZetaIrV1 } from "../../../src/Core.TypeScript/algebra/soft-mix";
import { complexRing, realRing, type Complex, type WEntry } from "../../../src/Core.TypeScript/algebra/star-ring";

const IR: ZetaIrV1 = {
  schema: "${ir.schema}",
  generator: "${ir.generator}",
  version: ${ir.version},
  width: ${ir.width},
  ops: [
    ${opsJson}
  ],
};

const MASK = (1n << ${ir.width}n) - 1n;
const EPS = 1e-12;
const isZeroC = (w: Complex) => w.re * w.re + w.im * w.im < EPS;
const isZeroR = (w: number) => Math.abs(w) < EPS;

// Run with complex ring (quantum lane — interference enabled)
export function runQuantum(x: bigint): WEntry<bigint, Complex>[] {
  return softMixGeneric(IR, complexRing, isZeroC, [{ key: x & MASK, weight: complexRing.one }]);
}

// Run with real ring (bayesian lane — no interference)
export function runBayesian(x: bigint): WEntry<bigint, number>[] {
  return softMixGeneric(IR, realRing, isZeroR, [{ key: x & MASK, weight: 1.0 }]);
}

// Self-test: run on a sample input and print results
if (typeof Bun !== "undefined" && import.meta.main) {
  const input = 5n;
  const qResult = runQuantum(input);
  const bResult = runBayesian(input);
  console.log(\`[${ir.generator}] input=\${input}\`);
  console.log(\`  quantum:  support=\${qResult.length}, states=[\${qResult.map(e => e.key).join(",")}]\`);
  console.log(\`  bayesian: support=\${bResult.length}, states=[\${bResult.map(e => e.key).join(",")}]\`);
}
`;
}

// ─── Python emitter (ring-generic) ───────────────────────────────────────────

function emitRingGenericPython(ir: ZetaIrV2): string {
  const ops = ir.ops.map(op => {
    if (op.op === "mul") {
      const unsigned = BigInt(op.k!) & ((1n << BigInt(ir.width)) - 1n);
      return `    ("mul", ${unsigned}, 0, 0, 0)`;
    } else if (op.op === "xorshr") {
      return `    ("xorshr", 0, ${op.s}, 0, 0)`;
    } else if (op.op === "branch") {
      return `    ("branch", 0, 0, ${op.bit ?? op.s ?? 0}, 0)`;
    } else if (op.op === "join") {
      return `    ("join", 0, 0, ${op.control ?? 0}, ${op.target ?? 1})`;
    } else if (op.op === "emit") {
      return `    ("emit", 0, 0, 0, 0)`;
    } else if (op.op === "retract") {
      return `    ("retract", 0, 0, 0, 0)`;
    }
    return `    ("${op.op}", 0, 0, 0, 0)`;
  }).join(",\n");

  return `#!/usr/bin/env python3
# GENERATED by codegen-v2-ring.ts — ring-generic interpreter for ${ir.generator}
# Handles ALL v2 ops. Ring-parameterized: complex = quantum, real = bayesian.
import json, os

MASK = (1 << ${ir.width}) - 1
EPS = 1e-12
OPS = [
${ops}
]

def consolidate_complex(frames):
    grouped = {}
    for state, re, im in frames:
        if state in grouped:
            grouped[state] = (grouped[state][0] + re, grouped[state][1] + im)
        else:
            grouped[state] = (re, im)
    return [(k, r, i) for k, (r, i) in grouped.items() if r*r + i*i > EPS]

def run_quantum(x):
    """Ring-generic soft-mix with complex ring (interference enabled)."""
    ens = [(x & MASK, 1.0, 0.0)]
    for op_type, k_val, s_val, bit_val, tgt_val in OPS:
        new_ens = []
        for state, re, im in ens:
            if op_type == "mul":
                new_ens.append(((state * k_val) & MASK, re, im))
            elif op_type == "xorshr":
                new_ens.append(((state ^ (state >> s_val)) & MASK, re, im))
            elif op_type == "branch":
                new_ens.append((state, re, im))
                new_ens.append(((state ^ (1 << bit_val)) & MASK, re, im))
            elif op_type == "join":
                ctrl_set = (state >> bit_val) & 1
                if ctrl_set:
                    new_ens.append(((state ^ (1 << tgt_val)) & MASK, re, im))
                else:
                    new_ens.append((state, re, im))
            elif op_type == "emit":
                new_ens.append((state, re + 1.0, im))
            elif op_type == "retract":
                new_ens.append((state, re - 1.0, im))
            else:
                new_ens.append((state, re, im))
        ens = consolidate_complex(new_ens)
    return ens

if __name__ == "__main__":
    x = 5
    result = run_quantum(x)
    print(f"[${ir.generator}] input={x}")
    print(f"  quantum: support={len(result)}, states={[s for s,_,_ in result]}")
`;
}

// ─── Main ────────────────────────────────────────────────────────────────────

function main(): number {
  const args = process.argv.slice(2);
  if (args.length < 2) {
    console.error("Usage: codegen-v2-ring.ts <ir.json> <output-dir>");
    return 1;
  }

  const ir = parseIrJson(readFileSync(args[0]!, "utf-8"));
  const outDir = args[1]!;
  mkdirSync(outDir, { recursive: true });

  writeFileSync(join(outDir, "ring-generic.ts"), emitRingGenericTS(ir));
  writeFileSync(join(outDir, "ring-generic.py"), emitRingGenericPython(ir));
  writeFileSync(join(outDir, "ring-generic.fsx"), emitRingGenericFSharp(ir));
  writeFileSync(join(outDir, "ring-generic.csx"), emitRingGenericCSharp(ir));
  writeFileSync(join(outDir, "ring-generic.rs"), emitRingGenericRust(ir));
  writeFileSync(join(outDir, "ring-generic.go"), emitRingGenericGo(ir));
  writeFileSync(join(outDir, "ring-generic.qs"), emitRingGenericQSharp(ir));

  console.log(`[codegen-v2-ring] emitted 7 ring-generic scripts from ${basename(args[0]!)} → ${outDir}`);
  console.log(`  ring-generic.ts   — TypeScript (import StarRing)`);
  console.log(`  ring-generic.py   — Python (inline complex ring)`);
  console.log(`  ring-generic.fsx  — F# (IStarRing + benchmark)`);
  console.log(`  ring-generic.csx  — C# (IStarRing + benchmark)`);
  console.log(`  ring-generic.rs   — Rust (StarRing trait + benchmark)`);
  console.log(`  ring-generic.go   — Go (StarRing interface + benchmark)`);
  console.log(`  ring-generic.qs   — Q# (Int masking + verify)`);
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}

export { emitRingGenericTS, emitRingGenericPython, parseIrJson, type ZetaIrV2 };
