/**
 * codegen-rx.ts — Emit IR as a reactive observable pipeline (Rx lens).
 *
 * Each IR op becomes an Rx operator. The ZSet interpretation:
 * - mul/xorshr → map (transform each element)
 * - branch → flatMap (one input → multiple outputs, grows stream)
 * - join → filter+map (conditional transform)
 * - merge → merge (combine streams)
 * - emit/retract → of/map(negate) (source/negate weight)
 *
 * The emitted code uses language-idiomatic Rx libraries:
 * - TS: rxjs (pipe, map, mergeMap)
 * - Python: rx (operators.map, operators.flat_map)
 * - C#: System.Reactive (Select, SelectMany)
 * - F#: FSharp.Control.Reactive
 * - Go: channels + goroutines (native Rx pattern)
 * - Rust: futures::stream (map, flat_map)
 * - Q#: not applicable (quantum is already "all paths at once")
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

interface IrOp {
  op: string;
  k?: number;
  s?: number;
  bit?: number;
  control?: number;
  target?: number;
}

interface ZetaIrV2 {
  schema: string;
  generator: string;
  version: number;
  width: number;
  ops: IrOp[];
}

// ─── Parse IR (BigInt-safe) ──────────────────────────────────────────────

function parseIr(raw: string): ZetaIrV2 {
  // Replace integer k values with BigInt-safe strings before JSON.parse
  const bigIntSafe = raw.replace(/"k"\s*:\s*(-?\d+)/g, '"k_str": "$1"');
  const parsed = JSON.parse(bigIntSafe);
  // Convert k_str back to ops with BigInt-derived k
  if (parsed.ops) {
    for (const op of parsed.ops) {
      if (op.k_str !== undefined) {
        // Store as string for BigInt conversion in emitters
        op.k_bigint = op.k_str;
        delete op.k_str;
      }
    }
  }
  return parsed;
}

function getKUnsigned(op: IrOp, width: number): bigint {
  const raw = (op as any).k_bigint ? BigInt((op as any).k_bigint) : BigInt(op.k ?? 0);
  return raw & ((1n << BigInt(width)) - 1n);
}

// ─── Emit TypeScript Rx (rxjs) ───────────────────────────────────────────

export function emitTypeScriptRx(ir: ZetaIrV2): string {
  const mask = ir.width === 64 ? "(1n << 64n) - 1n" : `(1n << ${ir.width}n) - 1n`;
  const u = (expr: string) => `(${expr}) & MASK`;

  const pipeOps = ir.ops.map(op => {
    if (op.op === "mul") {
      const k = getKUnsigned(op, ir.width);
      return `    map((z: bigint) => ${u(`z * ${k}n`)})`;
    } else if (op.op === "xorshr") {
      return `    map((z: bigint) => ${u(`z ^ (z >> ${op.s}n)`)})`;
    } else if (op.op === "branch") {
      return `    mergeMap((z: bigint) => from([z, ${u(`z ^ (1n << ${op.bit}n)`)}]))`;
    } else if (op.op === "join") {
      return `    map((z: bigint) => {\n      const ctrl = (z >> ${op.control}n) & 1n;\n      return ctrl ? ${u(`z ^ (1n << ${op.target}n)`)} : z;\n    })`;
    } else {
      return `    // unknown op: ${op.op}`;
    }
  });

  return `// GENERATED by codegen-rx.ts — DO NOT EDIT
// IR-driven Rx pipeline for ${ir.generator} (zeta-ir-v2, width=${ir.width})
import { from, pipe, map, mergeMap, toArray, lastValueFrom } from "rxjs";

const MASK = ${mask};

/** The ${ir.generator} pipeline as an Rx observable chain. */
export const ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline = pipe(
${pipeOps.join(",\n")}
);

// Usage: from([input]).pipe(pipeline).subscribe(result => ...)
// For deterministic ops: 1 input → 1 output (same as classical)
// For branching ops: 1 input → N outputs (stream grows)

async function main() {
  const inputs = [0n, 1n, 2n, 10n, 255n];
  for (const x of inputs) {
    const results = await lastValueFrom(from([x]).pipe(${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline, toArray()));
    console.log(\`x=\${x} → [\${results.join(", ")}] (support=\${results.length})\`);
  }
}

main();
`;
}

// ─── Emit Python Rx ──────────────────────────────────────────────────────

export function emitPythonRx(ir: ZetaIrV2): string {
  const mask = ir.width === 64 ? "(1 << 64) - 1" : `(1 << ${ir.width}) - 1`;

  const ops = ir.ops.map(op => {
    if (op.op === "mul") {
      const k = getKUnsigned(op, ir.width);
      return `    ops.map(lambda z: (z * ${k}) & MASK)`;
    } else if (op.op === "xorshr") {
      return `    ops.map(lambda z: (z ^ (z >> ${op.s})) & MASK)`;
    } else if (op.op === "branch") {
      return `    ops.flat_map(lambda z: rx.of(z, (z ^ (1 << ${op.bit})) & MASK))`;
    } else if (op.op === "join") {
      return `    ops.map(lambda z: ((z ^ (1 << ${op.target})) & MASK) if ((z >> ${op.control}) & 1) else z)`;
    } else {
      return `    # unknown op: ${op.op}`;
    }
  });

  return `# GENERATED by codegen-rx.ts — DO NOT EDIT
# IR-driven Rx pipeline for ${ir.generator} (zeta-ir-v2, width=${ir.width})
import rx
from rx import operators as ops

MASK = ${mask}

def ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline():
    """The ${ir.generator} pipeline as an Rx observable chain."""
    return rx.pipe(
${ops.join(",\n")}
    )

# Usage: rx.of(input).pipe(pipeline()).subscribe(on_next=print)

if __name__ == "__main__":
    inputs = [0, 1, 2, 10, 255]
    for x in inputs:
        results = []
        rx.of(x).pipe(${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline()).subscribe(on_next=results.append)
        print(f"x={x} → {results} (support={len(results)})")
`;
}

// ─── Emit C# Rx (System.Reactive) ───────────────────────────────────────

export function emitCSharpRx(ir: ZetaIrV2): string {
  const ops = ir.ops.map(op => {
    if (op.op === "mul") {
      const k = getKUnsigned(op, ir.width);
      return `    .Select(z => unchecked(z * ${k}UL))`;
    } else if (op.op === "xorshr") {
      return `    .Select(z => z ^ (z >> ${op.s}))`;
    } else if (op.op === "branch") {
      return `    .SelectMany(z => new[] { z, z ^ (1UL << ${op.bit}) })`;
    } else if (op.op === "join") {
      return `    .Select(z => ((z >> ${op.control}) & 1) == 1 ? z ^ (1UL << ${op.target}) : z)`;
    } else {
      return `    // unknown op: ${op.op}`;
    }
  });

  return `// GENERATED by codegen-rx.ts — DO NOT EDIT
// IR-driven Rx pipeline for ${ir.generator} (zeta-ir-v2, width=${ir.width})
using System.Reactive.Linq;

public static class ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_Pipeline
{
    /// <summary>The ${ir.generator} pipeline as an IObservable chain.</summary>
    public static IObservable<ulong> Apply(IObservable<ulong> source) =>
        source
${ops.join("\n")};
}
`;
}

// ─── Main ────────────────────────────────────────────────────────────────

export function emitAll(ir: ZetaIrV2, outDir: string): void {
  mkdirSync(outDir, { recursive: true });
  const name = ir.generator.replace(/[^a-zA-Z0-9]/g, "-");

  const files: [string, string][] = [
    [`${name}-rx.ts`, emitTypeScriptRx(ir)],
    [`${name}-rx.py`, emitPythonRx(ir)],
    [`${name}-rx.csx`, emitCSharpRx(ir)],
  ];

  for (const [filename, content] of files) {
    writeFileSync(join(outDir, filename), content);
  }

  console.log(`[codegen-rx] emitted ${files.length} Rx pipeline scripts from ${ir.generator} → ${outDir}`);
  for (const [filename] of files) {
    console.log(`  ${filename}`);
  }
}

if (import.meta.main) {
  const [irPath, outDir] = process.argv.slice(2);
  if (!irPath || !outDir) {
    console.error("Usage: bun codegen-rx.ts <ir.json> <out-dir>");
    process.exit(1);
  }
  const raw = readFileSync(irPath, "utf-8");
  const ir = parseIr(raw);
  emitAll(ir, outDir);
}
