/**
 * codegen-rx-remaining.ts — Rx pipeline emitters for F#, Rust, Go, Q#.
 * Extends codegen-rx.ts to cover all 7 languages.
 */

interface IrOp { op: string; k?: number; s?: number; bit?: number; control?: number; target?: number; k_bigint?: string }
interface ZetaIrV2 { schema: string; generator: string; version: number; width: number; ops: IrOp[] }

function getK(op: IrOp, width: number): bigint {
  const raw = op.k_bigint ? BigInt(op.k_bigint) : BigInt(op.k ?? 0);
  return raw & ((1n << BigInt(width)) - 1n);
}

// ─── F# Rx (FSharp.Control.Reactive) ────────────────────────────────────

export function emitFSharpRx(ir: ZetaIrV2): string {
  const ops = ir.ops.map(op => {
    if (op.op === "mul") return `    |> Observable.map (fun z -> z * ${getK(op, ir.width)}UL)`;
    if (op.op === "xorshr") return `    |> Observable.map (fun z -> z ^^^ (z >>> ${op.s}))`;
    if (op.op === "branch") return `    |> Observable.flatMap (fun z -> Observable.ofSeq [z; z ^^^ (1UL <<< ${op.bit ?? 0})])`;
    if (op.op === "join") return `    |> Observable.map (fun z -> if (z >>> ${op.control ?? 0}) &&& 1UL = 1UL then z ^^^ (1UL <<< ${op.target ?? 1}) else z)`;
    return `    // unknown: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-rx.ts — F# Rx pipeline for ${ir.generator}
open System
open FSharp.Control.Reactive

let ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline (source: IObservable<uint64>) =
    source
${ops}
`;
}

// ─── Rust Rx (futures::stream) ──────────────────────────────────────────

export function emitRustRx(ir: ZetaIrV2): string {
  const ops = ir.ops.map(op => {
    if (op.op === "mul") return `        .map(|z| z.wrapping_mul(${`0x${getK(op, ir.width).toString(16).toUpperCase()}`}))`;
    if (op.op === "xorshr") return `        .map(|z| z ^ (z >> ${op.s}))`;
    if (op.op === "branch") return `        .flat_map(|z| futures::stream::iter(vec![z, z ^ (1u64 << ${op.bit ?? 0})]))`;
    if (op.op === "join") return `        .map(|z| if (z >> ${op.control ?? 0}) & 1 == 1 { z ^ (1u64 << ${op.target ?? 1}) } else { z })`;
    return `        // unknown: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-rx.ts — Rust stream pipeline for ${ir.generator}
use futures::stream::{self, StreamExt};

fn ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline(input: impl futures::Stream<Item = u64>) -> impl futures::Stream<Item = u64> {
    input
${ops}
}
`;
}

// ─── Go Rx (channels + goroutines) ──────────────────────────────────────

export function emitGoRx(ir: ZetaIrV2): string {
  const steps = ir.ops.map((op, i) => {
    if (op.op === "mul") {
      return `\t// Step ${i}: mul
\tch${i + 1} := make(chan uint64, cap)
\tgo func() {
\t\tdefer close(ch${i + 1})
\t\tfor z := range ch${i} {
\t\t\tch${i + 1} <- z * ${`0x${getK(op, ir.width).toString(16).toUpperCase()}`}
\t\t}
\t}()`;
    } else if (op.op === "xorshr") {
      return `\t// Step ${i}: xorshr(${op.s})
\tch${i + 1} := make(chan uint64, cap)
\tgo func() {
\t\tdefer close(ch${i + 1})
\t\tfor z := range ch${i} {
\t\t\tch${i + 1} <- z ^ (z >> ${op.s})
\t\t}
\t}()`;
    } else if (op.op === "branch") {
      return `\t// Step ${i}: branch (fork)
\tch${i + 1} := make(chan uint64, cap*2)
\tgo func() {
\t\tdefer close(ch${i + 1})
\t\tfor z := range ch${i} {
\t\t\tch${i + 1} <- z
\t\t\tch${i + 1} <- z ^ (1 << ${op.bit ?? 0})
\t\t}
\t}()`;
    } else if (op.op === "join") {
      return `\t// Step ${i}: join (CNOT)
\tch${i + 1} := make(chan uint64, cap)
\tgo func() {
\t\tdefer close(ch${i + 1})
\t\tfor z := range ch${i} {
\t\t\tif (z>>${op.control ?? 0})&1 == 1 {
\t\t\t\tch${i + 1} <- z ^ (1 << ${op.target ?? 1})
\t\t\t} else {
\t\t\t\tch${i + 1} <- z
\t\t\t}
\t\t}
\t}()`;
    }
    return `\t// Step ${i}: ${op.op} (unknown)`;
  }).join("\n\n");

  const lastCh = `ch${ir.ops.length}`;

  return `// GENERATED by codegen-rx.ts — Go channel pipeline for ${ir.generator}
package main

func ${ir.generator.replace(/[^a-zA-Z0-9]/g, "_")}_pipeline(input <-chan uint64) <-chan uint64 {
\tconst cap = 64
\tch0 := input

${steps}

\treturn ${lastCh}
}
`;
}

// ─── Q# Rx (quantum = all paths at once, expressed as operation sequence) ─

export function emitQSharpRx(ir: ZetaIrV2): string {
  const ops = ir.ops.map((op, i) => {
    if (op.op === "mul") return `        // Step ${i}: mul — scale amplitude by ${getK(op, ir.width)}`;
    if (op.op === "xorshr") return `        // Step ${i}: xorshr(${op.s}) — reflect through basis vector`;
    if (op.op === "branch") return `        // Step ${i}: branch — Hadamard on bit ${op.bit ?? 0} (superpose)`;
    if (op.op === "join") return `        // Step ${i}: join — CNOT(control=${op.control ?? 0}, target=${op.target ?? 1})`;
    return `        // Step ${i}: ${op.op}`;
  }).join("\n");

  return `// GENERATED by codegen-rx.ts — Q# pipeline for ${ir.generator}
// Q# IS the Rx lens — quantum computes all paths simultaneously.
// Each "observable element" is a basis state; "subscribe" is measurement.
namespace Zeta.Rx {
    /// The ${ir.generator} pipeline expressed as a quantum operation sequence.
    /// "Observable" = superposition. "Subscribe" = measure.
    operation Pipeline(qs : Qubit[]) : Unit {
${ops}
    }
}
`;
}
