// GENERATED by codegen-law-tests.ts — property tests for IRing
// These tests FALSIFY (find counterexamples), not PROVE.
// Proof references are in each law's "proof" field in the IR.
import { describe, test, expect } from "bun:test";

const N = 1000; // property test iterations
const r = require('../../../src/Core.TypeScript/algebra/interfaces').numberSemiring;
const gen = () => Math.random() * 200 - 100; // random numbers in [-100, 100]
const eq = (a: number, b: number) => Math.abs(a - b) < 1e-9;

describe("IRing — algebraic law property tests (generated)", () => {
  test("add-inverse: Add(a, Negate(a)) = Zero", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:negate-is-additive-inverse
    for (let i = 0; i < N; i++) {
      const a = gen();
      expect(eq(r.add(a, r.negate(a)), r.zero)).toBe(true);
    }
  });
});
