// GENERATED by codegen-law-tests.ts — property tests for IKleeneAlgebra
// These tests FALSIFY (find counterexamples), not PROVE.
// Proof references are in each law's "proof" field in the IR.
import { describe, test, expect } from "bun:test";

const N = 1000; // property test iterations
const r = require('../../../src/Core.TypeScript/algebra/kleene').tropicalKleene;
const gen = () => Math.random() * 200 - 100; // random numbers in [-100, 100]
const eq = (a: number, b: number) => Math.abs(a - b) < 1e-9;

describe("IKleeneAlgebra — algebraic law property tests (generated)", () => {
  test("add-assoc: Add(Add(a,b),c) = Add(a,Add(b,c)) — a semiring axiom, holds in every Kleene algebra.", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:add-is-associative
    for (let i = 0; i < N; i++) {
      const a = gen();
      const b = gen();
      const c = gen();
      expect(eq(r.add(r.add(a, b), c), r.add(a, r.add(b, c)))).toBe(true);
    }
  });

  test("add-comm: Add(a,b) = Add(b,a).", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:add-is-commutative
    for (let i = 0; i < N; i++) {
      const a = gen();
      const b = gen();
      expect(eq(r.add(a, b), r.add(b, a))).toBe(true);
    }
  });

  test("add-identity: Add(a, Zero) = a.", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:zero-is-additive-identity
    for (let i = 0; i < N; i++) {
      const a = gen();
      expect(eq(r.add(a, r.zero), a)).toBe(true);
      expect(eq(r.add(r.zero, a), a)).toBe(true);
    }
  });

  test("mul-identity: Mul(a, One) = a = Mul(One, a).", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:one-is-multiplicative-identity
    for (let i = 0; i < N; i++) {
      const a = gen();
      expect(eq(r.mul(a, r.one), a)).toBe(true);
      expect(eq(r.mul(r.one, a), a)).toBe(true);
    }
  });

  test("mul-distributes-add: Mul(a, Add(b,c)) = Add(Mul(a,b), Mul(a,c)).", () => {
    // PROVEN: src/Core.TypeScript/algebra/interfaces.test.ts:mul-distributes-over-add
    for (let i = 0; i < N; i++) {
      const a = gen();
      const b = gen();
      const c = gen();
      expect(eq(r.mul(a, r.add(b, c)), r.add(r.mul(a, b), r.mul(a, c)))).toBe(true);
    }
  });

  test("add-idempotent: Add(a, a) = a — the DISTINGUISHING Kleene axiom (idempotent addition). Documented, NOT scalar-cross-verified: it does NOT hold over native +/* arithmetic (only for 0), so the scalar harness must skip it; it holds in the idempotent carriers (boolean ∨, tropical min). Proven in F# on the concrete instances.", () => {
    // PROVEN: tests/Tests.FSharp/Algebra/KleeneClosure.Tests.fs:BooleanKleene is a lawful Kleene algebra (∨/∧, star = true)
    for (let i = 0; i < N; i++) {
      const a = gen();
      expect(eq(r.add(a, a), a)).toBe(true);
    }
  });

  test("star-left-unfold: Star(a) = One ⊕ (a ⊗ Star(a)). Documented (star has no finite scalar encoding — over reals it diverges); proven in F# on BooleanKleene and the tropical instance.", () => {
    // PROVEN: tests/Tests.FSharp/Algebra/KleeneClosure.Tests.fs:BooleanKleene is a lawful Kleene algebra (∨/∧, star = true)
    for (let i = 0; i < N; i++) {
      // No random inputs required for this schema.
      // Unknown schema: star-unfold
    }
  });

  test("star-right-unfold: Star(a) = One ⊕ (Star(a) ⊗ a). Documented; proven in F#.", () => {
    // PROVEN: tests/Tests.FSharp/Algebra/KleeneClosure.Tests.fs:BooleanKleene is a lawful Kleene algebra (∨/∧, star = true)
    for (let i = 0; i < N; i++) {
      // No random inputs required for this schema.
      // Unknown schema: star-unfold
    }
  });

  test("matrix-star-is-closure: The matrix star over a Kleene algebra computes the all-pairs reflexive-transitive closure — boolean ⇒ reachability (= BFS), tropical ⇒ all-pairs shortest paths (Lehmann 1977). Documented (a matrix/graph-level law); proven in F# against a naive BFS oracle.", () => {
    // PROVEN: tests/Tests.FSharp/Algebra/KleeneClosure.Tests.fs:LAW: reachability closure = the naive reachable-set (BFS) on random DAGs+cycles
    for (let i = 0; i < N; i++) {
      // No random inputs required for this schema.
      // Unknown schema: closure-equivalence
    }
  });
});
