/-
  `CliffordReflectionE8` — the abstract Clifford-reflection certificate for the
  E8-via-Clifford route (route B) of work-item 081KYXCM1WK08QG0R003B9KVP4.

  Dechant's construction realises the E8 root system inside the even Clifford
  algebra of a 3-D space: each root is a grade-1 vector, and the Weyl group
  W(E8) is generated by the *versor sandwich* reflections `v ↦ −a v a⁻¹`.  The
  whole apparatus rests on three algebraic facts, and all three are already in
  Mathlib.  This file certifies them ABSTRACTLY, for a general
  `CliffordAlgebra Q` over a commutative ring — we do NOT port the F# adinkra /
  root-vector types; we style-match `MenoBraidedRMatrix.lean` (abstract lemmas
  against Mathlib, concrete types left on the F# side).

    L-A  (`ι_sq_eq_Q_smul_one`)  root² = scalar.  A grade-1 vector squares to a
         scalar: `ι a * ι a = Q a • 1`.  This is what makes a unit-norm root a
         *versor* (an invertible element whose inverse is a scalar multiple of
         itself).  Thin wrapper of `CliffordAlgebra.ι_sq_scalar`.

    L-B  (`neg_versor_sandwich_eq_ι_reflection`)  sandwich = reflection — THE
         crux.  The versor sandwich `−(ι a · ι b · (ι a)⁻¹)` equals `ι` of the
         Euclidean reflection of `b` in the hyperplane ⟂ `a`:

             reflect a b  =  b − (⟨a,b⟩·2 / Q a) • a
                          =  b − (⅟(Q a) · polar Q a b) • a

         (the numerator `polar Q a b = Q(a+b) − Q a − Q b = 2·B(a,b)` is exactly
         `2⟨a,b⟩`, so `⅟(Q a) · polar Q a b` is the classical `2⟨a,b⟩/⟨a,a⟩`).
         Mathlib's `CliffordAlgebra.ι_mul_ι_mul_invOf_ι` gives
             ι a · ι b · ⅟(ι a) = ι ((⅟(Q a) · polar Q a b) • a − b),
         whose argument is `−(reflect a b)`; negating both sides gives the
         reflection on the nose.  `reflect_self` is the sanity check that the
         mirror negates its own normal: `reflect a a = −a`.

    L-C  (`conj_smul_ι_mem_range_ι`)  conjugation preserves the vector subspace.
         Conjugation by any element of the Lipschitz group carries `ι`-vectors
         back into `range ι` — i.e. the versor group acts on the space of roots,
         which is what lets the sandwich reflections compose into W(E8).  Thin
         wrapper of `CliffordAlgebra.lipschitzGroup.conjAct_smul_ι_mem_range_ι`.

  OUT OF SCOPE (documented conjecture, not attempted here): L-F, the group
  presentation isomorphism `G/{±1} ≅ W(E8)`.  Mathlib currently lacks a concrete
  E8 root system together with a `weylGroup ≅ CoxeterGroup` bridge, so the final
  identification of the versor group modulo scalars with the abstract Weyl group
  is left as a conjecture on the E8 route-B ferry.

  Anchors: P.-P. Dechant, *The E8 geometry from a Clifford perspective*
  (Advances in Applied Clifford Algebras, 2016) — versor/sandwich reflections and
  the Clifford realisation of E8; W. K. Clifford (1878); É. Cartan / C. Chevalley
  (spinors, the Lipschitz–Clifford group).  Mathlib: `CliffordAlgebra.ι_sq_scalar`,
  `CliffordAlgebra.ι_mul_ι_mul_invOf_ι`, `QuadraticMap.polar`,
  `CliffordAlgebra.lipschitzGroup.conjAct_smul_ι_mem_range_ι`.
  Work-item 081KYXCM1WK08QG0R003B9KVP4.
-/
import Mathlib.LinearAlgebra.CliffordAlgebra.Basic
import Mathlib.LinearAlgebra.CliffordAlgebra.Inversion
import Mathlib.LinearAlgebra.CliffordAlgebra.SpinGroup

namespace Zeta.CliffordReflectionE8

open CliffordAlgebra QuadraticMap

variable {R M : Type*} [CommRing R] [AddCommGroup M] [Module R M]
variable {Q : QuadraticForm R M}

/-! ## L-A — root² = scalar. -/

/-- **L-A (root² = scalar).**  A grade-1 vector squares to a scalar:
    `ι a · ι a = Q a • 1`.  This is why a root of nonzero norm is invertible
    (a *versor*): `(ι a)⁻¹ = ⅟(Q a) • ι a`.  Wrapper of `ι_sq_scalar`. -/
theorem ι_sq_eq_Q_smul_one (a : M) :
    ι Q a * ι Q a = Q a • (1 : CliffordAlgebra Q) := by
  rw [ι_sq_scalar, Algebra.algebraMap_eq_smul_one]

/-! ## L-B — the versor sandwich is a reflection (the crux). -/

/-- The Euclidean reflection of `b` in the hyperplane orthogonal to `a`,
    written with the polar form: `reflect a b = b − (⅟(Q a) · polar Q a b) • a`.
    Since `polar Q a b = 2·B(a,b) = 2⟨a,b⟩`, the coefficient `⅟(Q a) · polar Q a b`
    is the classical `2⟨a,b⟩ / ⟨a,a⟩`. -/
def reflect (Q : QuadraticForm R M) (a b : M) [Invertible (Q a)] : M :=
  b - (⅟(Q a) * polar Q a b) • a

/-- The mirror negates its own normal: `reflect a a = −a`.  Sanity check that
    `reflect` is the genuine reflection fixing the hyperplane ⟂ `a`. -/
theorem reflect_self (a : M) [Invertible (Q a)] : reflect Q a a = -a := by
  have hcoeff : (⅟(Q a) * polar Q a a) = (2 : R) := by
    rw [polar_self, nsmul_eq_mul, ← mul_assoc, mul_comm (⅟(Q a)) ((2 : ℕ) : R),
      mul_assoc, invOf_mul_self, mul_one, Nat.cast_ofNat]
  rw [reflect, hcoeff]
  module

/-- **L-B (sandwich = reflection) — THE crux.**  The (negated) versor sandwich
    `−(ι a · ι b · (ι a)⁻¹)` equals `ι` of the reflection of `b` in the
    hyperplane orthogonal to `a`.  Built directly on Mathlib's
    `ι_mul_ι_mul_invOf_ι`, whose right-hand argument is exactly `−(reflect a b)`;
    negating both sides lands the reflection.  This is the algebraic heart of the
    Weyl-group-as-versors construction. -/
theorem neg_versor_sandwich_eq_ι_reflection (a b : M)
    [Invertible (ι Q a)] [Invertible (Q a)] :
    -(ι Q a * ι Q b * ⅟(ι Q a)) = ι Q (reflect Q a b) := by
  rw [ι_mul_ι_mul_invOf_ι, ← map_neg, reflect]
  congr 1
  abel

/-! ## L-C — conjugation preserves the vector subspace. -/

/-- **L-C (conjugation preserves `range ι`).**  Conjugation by an element of the
    Lipschitz group keeps `ι`-vectors inside `range ι`: the versor group acts on
    the space of roots.  Wrapper of `lipschitzGroup.conjAct_smul_ι_mem_range_ι`
    (requires `2` invertible, as in Mathlib). -/
theorem conj_smul_ι_mem_range_ι [Invertible (2 : R)]
    {x : (CliffordAlgebra Q)ˣ} (hx : x ∈ lipschitzGroup Q) (m : M) :
    ConjAct.toConjAct x • ι Q m ∈ LinearMap.range (ι Q) :=
  lipschitzGroup.conjAct_smul_ι_mem_range_ι hx m

end Zeta.CliffordReflectionE8
