/-
  `MenoBalancedTwist` — the abstract certificate for the Meno balanced-structure verdict
  about `<V>`, the braided monoidal subcategory generated by `MenoBraided.braidR`.

  Three claims, each machine-checked for ALL `n` in an arbitrary braided monoidal category:
  the coherence **obstruction** to a balanced structure **vanishes** (this is the general-`n`
  content of Garside's full twist); the balanced structure is **unique** once fixed on the
  generator; and `θ_V = id` is **not** a degeneracy.  A fourth claim — that `<V>` itself is
  such a category, so the structure actually EXISTS on it — is NOT certified here; see
  "what it does not" below.

  Companion to `Lean4.MenoBraidedRMatrix`, which certifies that `braidR` is a braiding
  (Yang–Baxter) and is *not* a symmetry (`R² ≠ id`).  Work-item
  081KZZVC3DD087G0R0035SZN58.

  ## The claim, and the error it corrects

  Two prior reviews concluded that `<V>` cannot be balanced, reasoning: the twist on the
  generator must be `θ_V = ρ(Δ₁²) = id` (because `B₁` is trivial), and "therefore"
  `θ_{V⊗V} = θ_V ⊗ θ_V = id`, forcing `c² = id`, i.e. symmetry — contradicting
  `braidR_not_symmetric_perm3`.

  That reasoning uses the WRONG axiom.  The balanced axiom (Joyal–Street 1993) is

      θ_{A⊗B}  =  (θ_A ⊗ θ_B) ∘ c_{B,A} ∘ c_{A,B}

  and NOT `θ_{A⊗B} = θ_A ⊗ θ_B`.  With the correct axiom, `θ_V = id` forces
  `θ_{V⊗V} = c²` — it does not force `c² = id`.  Both halves of that sentence are
  machine-checked below (`twist_tensor_of_id`, `misread_axiom_forces_symmetry`,
  `twist_tensor_ne_id_of_dbl_ne_id`).

  ## What this file certifies, and what it does not

  CERTIFIED (general, `sorry`-free, in an arbitrary braided monoidal category):

  * `dbl_cocycle` — the double braiding `D_{X,Y} = c_{Y,X} ∘ c_{X,Y}` satisfies the
    2-cocycle identity `(D_{X,Y} ⊗ 1_Z) ≫ D_{X⊗Y,Z} = (1_X ⊗ D_{Y,Z}) ≫ D_{X,Y⊗Z}`
    (modulo the associator).  This is the condition under which a family `θ` obeying
    `θ_{m+n} = (θ_m ⊗ θ_n)·D_{m,n}` is consistently definable — i.e. the condition that
    makes `Δ²` a *coboundary* of `D`, which is what Garside's relation
    `Δ_{m+n}² = (Δ_m² ⊗ Δ_n²)·c_{n,m}·c_{m,n}` asserts in `Bₙ`.  Obtained categorically,
    for ALL `m` and `n`, from the hexagon axioms alone — no Garside normal-form machinery
    (which Mathlib does not carry) is needed.  It is the coherence obstruction to a
    balanced structure, and it VANISHES.
  * `twist_assoc_consistent` — consequently the balanced axiom is associatively
    consistent: the two ways of computing `θ` on a triple tensor agree.  There is no
    obstruction to defining `θ` on tensor words.
  * `twist_eq_of_eq_on_gen` / `twist_eq_on_Vpow` — UNIQUENESS, all `n`: two balanced
    structures agreeing on `V` agree on every tensor power of `V`.
  * `twist_Vpow_succ` — the forcing recursion `θ_{n+1} = (θ_n ⊗ θ_1) ∘ c ∘ c`, all `n`.
    This is the "uniqueness recursion" row of the work-item's checked table, now general.
  * `symmetricTwist` — the structure is INHABITED (identity twist on a symmetric
    category), so none of the above is vacuous.

  NOT certified here (the honest gap, see §5):

  * That `<V>` *is* a braided monoidal category in Lean with `Hom(Vⁿ,Vⁿ) = ρ(Bₙ)`.  That
    needs the braid groupoid as the free braided monoidal category on one object
    (Joyal–Street 1993 §2) plus faithfulness of the Artin action (Artin 1925); neither is
    in Mathlib, and the standing boundary of `MenoBraidedRMatrix` is that we do NOT port
    the ZSet monoidal category into Lean.  So `θ`'s NATURALITY — equivalently, centrality
    of `Δₙ²` in `Bₙ` (Chow 1948) — is assumed as a field of `Twist`, not derived.

  Anchors: Joyal & Street 1993, *Braided Tensor Categories* (Adv. Math. 102);
  Garside 1969, *The braid group and other groups*; Chow 1948; Artin 1925;
  Kassel, *Quantum Groups* XIII.
-/
import Mathlib.CategoryTheory.Monoidal.Braided.Basic
import Mathlib.GroupTheory.SpecificGroups.Dihedral
import Lean4.MenoBraidedRMatrix

namespace Zeta.MenoBalanced

open CategoryTheory MonoidalCategory BraidedCategory

universe v u

variable {C : Type u} [Category.{v} C] [MonoidalCategory C] [BraidedCategory C]

/-! ## Part 1 — the double braiding `D_{X,Y} = c_{Y,X} ∘ c_{X,Y}`.

In the braid category, `D_{V^m, V^n} = c_{n,m}·c_{m,n}` is the positive braid in which the
`m`-cable and the `n`-cable make one full turn around each other.  Garside's identity says
the full twist `Δ²` is a *coboundary* of `D`; the content of Part 2 is that `D` is the
corresponding *cocycle*. -/

/-- The double braiding `D_{X,Y} : X ⊗ Y ⟶ X ⊗ Y`.  In `<V>` with `X = Vᵐ`, `Y = Vⁿ`
    this is the braid word `c_{n,m}·c_{m,n}`. -/
def dbl (X Y : C) : X ⊗ Y ⟶ X ⊗ Y := (β_ X Y).hom ≫ (β_ Y X).hom

/-- `D` is natural — it commutes past any pair of morphisms.  (In `<V>` this is why the
    twist family is a natural transformation once its components are central.) -/
@[reassoc]
theorem dbl_naturality {X X' Y Y' : C} (f : X ⟶ X') (g : Y ⟶ Y') :
    (f ⊗ₘ g) ≫ dbl X' Y' = dbl X Y ≫ (f ⊗ₘ g) := by
  simp [dbl]

/-- In a SYMMETRIC category the double braiding collapses to the identity — this is the
    degenerate case, and it is exactly the case `braidR` is proved to avoid
    (`Zeta.MenoBraided.braidR_not_symmetric_perm3`). -/
theorem dbl_eq_id_of_symmetric {D : Type u} [Category.{v} D] [MonoidalCategory D]
    [SymmetricCategory D] (X Y : D) : dbl X Y = 𝟙 (X ⊗ Y) := by
  simp only [dbl]; exact SymmetricCategory.symmetry X Y

/-! ## Part 2 — the coherence obstruction, and why it vanishes.

`yb_core` is Mathlib's `yang_baxter` with the outer associators cancelled, in the shape the
cocycle proof rewrites with.  `dbl_cocycle` then follows by four applications of Yang–Baxter
— two on each side, meeting at the common word `c₁ c₂ c₁ c₁ c₂ c₁` (the full twist). -/

/-- Yang–Baxter with the two outer associators cancelled. -/
@[reassoc]
theorem yb_core (U V W : C) :
    (β_ U V).hom ▷ W ≫ (α_ V U W).hom ≫ V ◁ (β_ U W).hom ≫ (α_ V W U).inv ≫ (β_ V W).hom ▷ U
      = (α_ U V W).hom ≫ U ◁ (β_ V W).hom ≫ (α_ U W V).inv ≫ (β_ U W).hom ▷ V ≫
        (α_ W U V).hom ≫ W ◁ (β_ U V).hom ≫ (α_ W V U).inv := by
  rw [← cancel_epi (α_ U V W).inv, ← cancel_mono (α_ W V U).hom]
  simpa using yang_baxter U V W

set_option maxHeartbeats 1000000 in
-- Four Yang-Baxter rewrites over six-letter braid words in a non-strict monoidal category:
-- the associator bookkeeping alone exceeds the default heartbeat budget.
/-- **THE GARSIDE IDENTITY, categorically, for all `m` and `n`.**

    `(D_{X,Y} ⊗ 1_Z) ≫ D_{X⊗Y,Z} = (1_X ⊗ D_{Y,Z}) ≫ D_{X,Y⊗Z}` (modulo the associator).

    Read in the braid category with `X = Vᵐ`, `Y = Vⁿ`, `Z = Vᵖ`, this is the compatibility
    among nested full twists that Garside 1969's relation encodes — the same compatibility
    whose *bounded* instances (`m+n ≤ 7`) were verified computationally by two independent
    Artin-action implementations, and whose general case the work-item flagged as needing
    Garside normal-form machinery.  It does not: it is a consequence of the hexagon axioms
    alone, via four Yang–Baxter moves.

    It is the 2-cocycle condition for `D`, hence exactly the obstruction to a balanced
    structure existing on tensor words.  It vanishes. -/
@[reassoc]
theorem dbl_cocycle (X Y Z : C) :
    (dbl X Y ▷ Z) ≫ dbl (X ⊗ Y) Z
      = (α_ X Y Z).hom ≫ (X ◁ dbl Y Z) ≫ dbl X (Y ⊗ Z) ≫ (α_ X Y Z).inv := by
  simp only [dbl, braiding_tensor_left_hom, braiding_tensor_right_hom,
    comp_whiskerRight, whiskerLeft_comp, Category.assoc]
  rw [← cancel_epi (α_ X Y Z).inv, ← cancel_mono (α_ X Y Z).hom]
  simp only [Category.assoc, Iso.inv_hom_id, Category.comp_id, Iso.inv_hom_id_assoc]
  rw [yb_core_assoc Y X Z]
  simp only [Iso.hom_inv_id_assoc]
  rw [yb_core_assoc X Y Z]
  simp only [Iso.inv_hom_id_assoc]
  rw [← yang_baxter_assoc X Z Y]
  rw [yb_core_assoc Z Y X]
  simp

/-! ## Part 3 — balanced structures (twists), with the CORRECT axiom. -/

/-- A **balanced structure** (twist) on a braided monoidal category: a natural family of
    endomorphisms satisfying `θ_{A⊗B} = (θ_A ⊗ θ_B) ∘ c_{B,A} ∘ c_{A,B}`.

    Note the axiom carefully: the double braiding `dbl A B` is composed FIRST.  The
    variant `θ_{A⊗B} = θ_A ⊗ θ_B` — which two reviews of the Meno verdict used — is a
    different and strictly stronger condition; see `misread_axiom_forces_symmetry`. -/
structure Twist (C : Type u) [Category.{v} C] [MonoidalCategory C] [BraidedCategory C] where
  /-- The twist component at each object. -/
  θ : ∀ X : C, X ⟶ X
  /-- Naturality.  In `<V>` this is equivalent to `θ_{Vⁿ}` being CENTRAL in `Bₙ`
      (Chow 1948), because `Hom(Vⁿ,Vⁿ) = ρ(Bₙ)` and `ρ` is faithful (Artin 1925). -/
  naturality : ∀ {X Y : C} (f : X ⟶ Y), θ X ≫ f = f ≫ θ Y
  /-- The balanced axiom. -/
  tensor : ∀ X Y : C, θ (X ⊗ Y) = dbl X Y ≫ (θ X ⊗ₘ θ Y)

attribute [reassoc] Twist.naturality

/-- **Non-vacuity guard.**  `Twist` is inhabited: on any SYMMETRIC monoidal category the
    identity family is a balanced structure.  Without this, every theorem below would be
    vacuously true of an empty structure. -/
def symmetricTwist (C : Type u) [Category.{v} C] [MonoidalCategory C] [SymmetricCategory C] :
    Twist C where
  θ X := 𝟙 X
  naturality f := by simp
  tensor X Y := by simp [dbl_eq_id_of_symmetric]

/-! ## Part 4 — the disambiguation these theorems exist to settle. -/

/-- **The headline.**  If `θ_V = id` (forced, since `B₁` is trivial), the correct balanced
    axiom gives `θ_{V⊗V} = c²` — the double braiding — and NOT `c² = id`.

    In `<V>`, `c² = ρ(σ₁²) = ρ(Δ₂²)`: the Garside full twist on two strands. -/
theorem twist_tensor_of_id (t : Twist C) {V : C} (hV : t.θ V = 𝟙 V) :
    t.θ (V ⊗ V) = dbl V V := by
  rw [t.tensor, hV]; simp

/-- **The error, isolated.**  Under the MISREAD axiom `θ_{A⊗B} = θ_A ⊗ θ_B`, `θ_V = id`
    really does force `c² = id`, i.e. symmetry.  So the two reviews' inference was valid —
    from a false premise.  This theorem is what makes the diagnosis precise rather than
    merely asserted: the collapse is a consequence of the misreading, not of the geometry. -/
theorem misread_axiom_forces_symmetry (t : Twist C) {V : C} (hV : t.θ V = 𝟙 V)
    (misread : t.θ (V ⊗ V) = t.θ V ⊗ₘ t.θ V) :
    dbl V V = 𝟙 (V ⊗ V) := by
  rw [← twist_tensor_of_id t hV, misread, hV]; simp

/-- **`θ_V = id` is not a degeneracy.**  Whenever the braiding on `V` is genuinely braided
    (`c² ≠ id`), the twist at `V ⊗ V` is likewise `≠ id`, even though `θ_V = id`.  The
    family is therefore nonconstant, and the balanced structure is not the trivial one. -/
theorem twist_tensor_ne_id_of_dbl_ne_id (t : Twist C) {V : C} (hV : t.θ V = 𝟙 V)
    (hc : dbl V V ≠ 𝟙 (V ⊗ V)) :
    t.θ (V ⊗ V) ≠ 𝟙 (V ⊗ V) := by
  rw [twist_tensor_of_id t hV]; exact hc

/-- Converse direction: a twist that IS constantly the identity forces every double
    braiding to collapse.  So in a braided-not-symmetric category the identity family is
    NOT a balanced structure — the twist must be nontrivial somewhere. -/
theorem dbl_eq_id_of_twist_id (t : Twist C) (h : ∀ X : C, t.θ X = 𝟙 X) (X Y : C) :
    dbl X Y = 𝟙 (X ⊗ Y) := by
  have := t.tensor X Y
  rw [h, h, h] at this
  simpa using this.symm

/-! ## Part 5 — consistency (existence) and uniqueness on tensor powers.

`twist_assoc_consistent` is the existence half that `dbl_cocycle` buys: the balanced axiom
can be propagated over tensor words without contradiction.  What it does NOT supply is a
`Twist` INSTANCE on `<V>` — that additionally needs `<V>` itself as a Lean braided category
(braid groupoid + faithfulness of `ρ`), which is out of scope by the standing boundary. -/

/-- **Associative consistency of the balanced axiom.**  Computing `θ` on `(X⊗Y)⊗Z` by
    expanding the balanced axiom outer-first and inner-first gives the same answer, for
    arbitrary candidate components `tX, tY, tZ`.  Immediate from `dbl_cocycle` plus
    naturality of `D` and of the associator.

    This is the statement "there is no coherence obstruction to a balanced structure",
    which in `<V>` is "the family `θ_{Vⁿ} = ρ(Δₙ²)` is well defined for every `n`". -/
theorem twist_assoc_consistent {X Y Z : C} (tX : X ⟶ X) (tY : Y ⟶ Y) (tZ : Z ⟶ Z) :
    dbl (X ⊗ Y) Z ≫ ((dbl X Y ≫ (tX ⊗ₘ tY)) ⊗ₘ tZ)
      = (α_ X Y Z).hom ≫ dbl X (Y ⊗ Z) ≫ (tX ⊗ₘ (dbl Y Z ≫ (tY ⊗ₘ tZ))) ≫
          (α_ X Y Z).inv := by
  rw [← whiskerRight_comp_tensorHom (dbl X Y) (tX ⊗ₘ tY) tZ,
      ← whiskerLeft_comp_tensorHom tX (dbl Y Z) (tY ⊗ₘ tZ),
      ← MonoidalCategory.tensorHom_id (dbl X Y) Z,
      ← MonoidalCategory.id_tensorHom X (dbl Y Z)]
  simp only [Category.assoc]
  rw [← dbl_naturality_assoc (dbl X Y) (𝟙 Z), ← dbl_naturality_assoc (𝟙 X) (dbl Y Z),
      MonoidalCategory.tensorHom_id (dbl X Y) Z,
      MonoidalCategory.id_tensorHom X (dbl Y Z),
      dbl_cocycle_assoc X Y Z, ← associator_inv_naturality tX tY tZ]

/-- The `(n+1)`-fold left-associated tensor power `V ⊗ V ⊗ … ⊗ V`.  Index convention:
    `Vpow V 0 = V`, so `Vpow V n` has `n+1` factors (this keeps the base case an equality
    rather than a unitor). -/
def Vpow (V : C) : ℕ → C
  | 0 => V
  | (n + 1) => Vpow V n ⊗ V

/-- **The forcing recursion, all `n`.**  With `θ_V = id`, the balanced axiom determines
    every higher component from the previous one:

        θ_{n+1} = (θ_n ⊗ θ_1) ∘ c ∘ c

    which is precisely the recursion the work-item verified reproduces `Δₙ²` for `n ≤ 7`.
    Here it is a theorem for every `n`. -/
theorem twist_Vpow_succ (t : Twist C) {V : C} (hV : t.θ V = 𝟙 V) (n : ℕ) :
    t.θ (Vpow V (n + 1)) = dbl (Vpow V n) V ≫ (t.θ (Vpow V n) ▷ V) := by
  change t.θ (Vpow V n ⊗ V) = _
  rw [t.tensor, hV]
  simp

/-- `θ` at two strands is the double braiding — the base case of the recursion, and the
    concrete statement `θ_{V⊗V} = ρ(Δ₂²) = ρ(σ₁²)`. -/
theorem twist_Vpow_one (t : Twist C) {V : C} (hV : t.θ V = 𝟙 V) :
    t.θ (Vpow V 1) = dbl V V := twist_tensor_of_id t hV

/-- **UNIQUENESS, all `n`.**  Two balanced structures that agree on `V` agree on every
    tensor power of `V`.  Since `θ_V` is forced (`B₁` is trivial ⇒ `θ_V = id`), the
    balanced structure on `<V>` is unique if it exists. -/
theorem twist_eq_on_Vpow (t t' : Twist C) {V : C} (h : t.θ V = t'.θ V) (n : ℕ) :
    t.θ (Vpow V n) = t'.θ (Vpow V n) := by
  induction n with
  | zero => exact h
  | succ n ih =>
      change t.θ (Vpow V n ⊗ V) = t'.θ (Vpow V n ⊗ V)
      rw [t.tensor, t'.tensor, ih, h]

/-- Agreement of two balanced structures is closed under `⊗` — the general form of
    uniqueness, independent of the `Vpow` indexing. -/
theorem twist_eq_tensor (t t' : Twist C) {X Y : C} (hX : t.θ X = t'.θ X)
    (hY : t.θ Y = t'.θ Y) : t.θ (X ⊗ Y) = t'.θ (X ⊗ Y) := by
  rw [t.tensor, t'.tensor, hX, hY]

/-- The uniqueness statement in the form the work-item states it: `θ₁ = id` forces the
    whole family. -/
theorem twist_eq_of_eq_on_gen (t t' : Twist C) {V : C} (hV : t.θ V = 𝟙 V)
    (hV' : t'.θ V = 𝟙 V) (n : ℕ) : t.θ (Vpow V n) = t'.θ (Vpow V n) :=
  twist_eq_on_Vpow t t' (hV.trans hV'.symm) n

/-! ## Part 6 — the concrete cross-check, and the negative controls.

Everything above is abstract.  This part re-derives the same facts by EXHAUSTIVE evaluation
of the Artin action of `B₃` through the shipped `braidR`, on all `6³ = 216` triples of a
concrete non-abelian group — a second, independent route, in the spirit of
`Zeta.MenoBraided.braidR_yangBaxter_perm3_exhaustive`.

The group used is `DihedralGroup 3 ≅ S₃` (isomorphic to the `Equiv.Perm (Fin 3)` of the
companion file; chosen only because its `DecidableEq` reduces far faster, keeping every
`decide` below in seconds rather than segfaulting the kernel).

EPISTEMIC DIRECTION, stated because it is easy to get backwards.  The `braidR` action on
`G³` is a REPRESENTATION of `B₃`, and it is not faithful.  Therefore:

  * a `≠` result here is SOUND: it exhibits a triple on which two braid words act
    differently, so the words differ in `B₃`.  All four mutant rejections below are of this
    kind, and they are proofs.
  * a `=` result here is NOT a proof of equality in `B₃` — only evidence.  So
    `garside_relation_dihedral3` is labelled a CROSS-CHECK, not the source of the positive
    result.  The positive result is `dbl_cocycle`, proved abstractly for all objects.

The mutants are the four the work-item's F#-side check already rejected; re-deriving the
same four rejections here, in a different language on a different model, is the BP-16
two-tool cross-check. -/

open Zeta.MenoBraided in
/-- Act by a braid word on `G³`, in DIAGRAM order (leftmost letter applied first).
    `true = σ₁` (braids strands 1,2), `false = σ₂` (braids strands 2,3). -/
def act {G : Type*} [Group G] : List Bool → (G × G × G) → (G × G × G)
  | [], p => p
  | (true :: w), p => act w (braidR12 p)
  | (false :: w), p => act w (braidR23 p)

/-- The concrete model group: `DihedralGroup 3 ≅ S₃`, the smallest non-abelian group. -/
abbrev G3 := DihedralGroup 3

/-- `Δ₂²` embedded in `B₃` as `σ₁²` — the twist at two strands. -/
def d2sq : List Bool := [true, true]

/-- The double braiding `D_{2,1} = c_{1,2}·c_{2,1} = σ₂σ₁²σ₂` (diagram order). -/
def dbl21 : List Bool := [false, true, true, false]

/-- `Δ₃² = (σ₁σ₂)³` — the Garside full twist on three strands. -/
def d3sq : List Bool := [true, false, true, false, true, false]

set_option maxRecDepth 20000 in
/-- **Positive control on the instrument itself.**  `act` really is a `B₃`-action: the
    braid relation `σ₁σ₂σ₁ = σ₂σ₁σ₂` holds on all 216 triples.  Without this, an `act` that
    (say) ignored its word would still make every mutant below "reject", and the whole of
    Part 6 would be measuring nothing. -/
theorem act_braid_relation_dihedral3 :
    ∀ x y z : G3, act [true, false, true] (x, y, z) = act [false, true, false] (x, y, z) := by
  decide

set_option maxRecDepth 20000 in
/-- **Second positive control: `act` is not the trivial action.**  `σ₁` moves something.
    Together with the previous theorem this pins `act` down as a genuine, nondegenerate
    braid action before any of its verdicts are believed. -/
theorem act_nontrivial_dihedral3 : ¬ (∀ x y z : G3, act [true] (x, y, z) = (x, y, z)) := by
  decide

set_option maxRecDepth 20000 in
/-- **Cross-check (evidence, not proof — see the epistemic note above).**  The Garside
    relation `Δ₃² = (Δ₂² ⊗ Δ₁²) ∘ c_{1,2} ∘ c_{2,1}` holds in the `braidR` action on all
    216 triples.  Word order follows the balanced axiom: `D` first, then `Δ₂²`.  The proof
    of the general statement is `dbl_cocycle`; this is the independent route that must
    agree with it, and does. -/
theorem garside_relation_dihedral3 :
    ∀ x y z : G3, act d3sq (x, y, z) = act (dbl21 ++ d2sq) (x, y, z) := by
  decide

/-- **Mutant 1 — `θ = id` everywhere (the two reviews' reading): REJECTED.**
    If `θ₂ = id` the balanced axiom would demand `θ₃ = D_{2,1}`, and `D_{2,1} ≠ id`. -/
theorem mutant_theta_id_rejected :
    ¬ (∀ x y z : G3, act [] (x, y, z) = act (dbl21 ++ []) (x, y, z)) := by
  intro h
  have := h 1 (DihedralGroup.r 1) (DihedralGroup.sr 0)
  revert this; decide

/-- **Mutant 2 — half twist `θ = Δ` instead of `Δ²`: REJECTED.** -/
theorem mutant_half_twist_rejected :
    ¬ (∀ x y z : G3,
        act [true, false, true] (x, y, z) = act (dbl21 ++ [true]) (x, y, z)) := by
  intro h
  have := h 1 (DihedralGroup.r 1) (DihedralGroup.sr 0)
  revert this; decide

/-- **Mutant 3 — a single `c_{A,B}` instead of `c_{B,A}·c_{A,B}`: REJECTED.**
    This is the mutant that would survive if the balanced axiom used one braiding rather
    than the double braiding. -/
theorem mutant_single_braiding_rejected :
    ¬ (∀ x y z : G3, act d3sq (x, y, z) = act ([true, false] ++ d2sq) (x, y, z)) := by
  intro h
  have := h 1 (DihedralGroup.r 1) (DihedralGroup.sr 0)
  revert this; decide

/-- **Mutant 4 — `θ = Δ⁴` (double the full twist): REJECTED.** -/
theorem mutant_delta_fourth_rejected :
    ¬ (∀ x y z : G3,
        act (d3sq ++ d3sq) (x, y, z) = act (dbl21 ++ d2sq ++ d2sq) (x, y, z)) := by
  intro h
  have := h 1 (DihedralGroup.r 1) (DihedralGroup.sr 0)
  revert this; decide

/-- **The tie back to the shipped operator.**  `Zeta.MenoBraided.braidR_not_symmetric_perm3`
    says `R ∘ R ≠ id` over `S₃`.  Read through `twist_tensor_of_id`, that is exactly
    `θ_{V⊗V} ≠ id`: the balanced structure on `<V>` is genuinely nontrivial, and `θ_V = id`
    is forced by `B₁` being trivial rather than by any collapse. -/
theorem braidR_double_ne_id :
    ¬ Zeta.MenoBraided.IsSymmetric (Zeta.MenoBraided.braidR (G := Equiv.Perm (Fin 3))) :=
  Zeta.MenoBraided.braidR_not_symmetric_perm3

end Zeta.MenoBalanced
