#!/usr/bin/env bun
/**
 * train-priors.ts — deterministic headless training: play a cart, snapshot
 * the society, emit a priors module for `src/Core.TypeScript/chip8/priors/`.
 *
 * Because every random draw flows from COMMON_SEED, the same invocation
 * always produces the identical file — a committed prior is REPRODUCIBLE, so
 * a reviewer can re-run the trainer and diff. (`--verify` does exactly that:
 * trains twice and compares.)
 *
 * The emitted artifact is a `.ts` module rather than raw JSON so the browser
 * bundle imports it with zero tsconfig ceremony, and it stays text in the
 * repo (no binary in any lineage).
 *
 * Usage:
 *   bun src/Core.TypeScript/chip8/train-priors.ts --cart mutual-sim --ticks 1200
 *   bun src/Core.TypeScript/chip8/train-priors.ts --cart mutual-sim --verify
 */

import { compositeInto, create, loadRom, step, type Frame } from "./chip8";
import { BnnSocietyPredictor, desiredKeyOf } from "../bayesian/bnn-key-predictor";
import { romFingerprint, type GamePriorsFile } from "./game-priors";
import { buildMutualSimRom } from "./games/mutual-sim";
import {
  buildGlyphBoardRom,
  buildModeFlipRom,
  buildMoverAndWallRom,
  buildSingleMoverRom,
} from "./games/curriculum";

const STEPS_PER_TICK = 10; // mirror the worker

const CARTS: Record<string, () => Uint8Array> = {
  "mutual-sim": buildMutualSimRom,
  "single-mover": buildSingleMoverRom,
  "mover-and-wall": buildMoverAndWallRom,
  "glyph-board": buildGlyphBoardRom,
  "mode-flip": buildModeFlipRom,
};

export function trainPriors(cartName: string, ticks: number): GamePriorsFile {
  const buildRom = CARTS[cartName];
  if (!buildRom) throw new Error(`unknown cart "${cartName}" (have: ${Object.keys(CARTS).join(", ")})`);
  const rom = buildRom();
  const frame: Frame = create();
  loadRom(rom, frame);
  const predictor = new BnnSocietyPredictor(3);

  let lastKey: number | undefined;
  for (let t = 0; t < ticks; t++) {
    const composite = new Array(64 * 32).fill(0);
    for (let i = 0; i < STEPS_PER_TICK; i++) {
      step(frame);
      if (frame.fault) break;
      compositeInto(composite, frame);
    }
    if (frame.fault) break;
    predictor.predict(composite, lastKey);
    // Press the key the policy's own steering layer names — commitment, so
    // exploration probes land and the mode policy is actually exercised (a
    // probability-threshold argmax leaves the trainee idle most ticks).
    frame.keys.fill(false);
    const key = desiredKeyOf(predictor);
    if (key !== undefined) {
      frame.keys[key] = true;
      lastKey = key;
    } else {
      lastKey = undefined;
    }
  }

  return {
    schema: "zeta.chip8.game-priors.v1",
    fingerprint: romFingerprint(rom),
    cart: cartName,
    trainedTicks: ticks,
    seed: 4, // COMMON_SEED — recorded for provenance
    snapshot: predictor.exportSnapshot(),
  };
}

function emitModule(p: GamePriorsFile): string {
  const ident = p.cart.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
  return `// GENERATED by train-priors.ts — do not hand-edit.
// Reproduce (byte-identical, COMMON_SEED end to end):
//   bun src/Core.TypeScript/chip8/train-priors.ts --cart ${p.cart} --ticks ${p.trainedTicks}
import type { GamePriorsFile } from "../game-priors";

export const ${ident}Priors: GamePriorsFile = ${JSON.stringify(p, null, 2)};
`;
}

async function main(): Promise<number> {
  const args = process.argv.slice(2);
  const get = (flag: string): string | undefined => {
    const i = args.indexOf(flag);
    return i >= 0 ? args[i + 1] : undefined;
  };
  const cart = get("--cart") ?? "mutual-sim";
  const ticks = Number(get("--ticks") ?? 1200);
  const verify = args.includes("--verify");

  const first = trainPriors(cart, ticks);
  if (verify) {
    const second = trainPriors(cart, ticks);
    const a = JSON.stringify(first);
    const b = JSON.stringify(second);
    if (a !== b) {
      console.error(`[train-priors] NON-DETERMINISM: two runs of ${cart}@${ticks} differ.`);
      return 1;
    }
    console.log(`[train-priors] verified: two runs of ${cart}@${ticks} are byte-identical.`);
  }

  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  const outDir = path.join(import.meta.dir, "priors");
  await fs.mkdir(outDir, { recursive: true });
  const outPath = path.join(outDir, `${cart}.priors.ts`);
  await fs.writeFile(outPath, emitModule(first), "utf8");
  console.log(
    `[train-priors] ${cart}: fingerprint=${first.fingerprint} ticks=${first.trainedTicks} → ${outPath}`,
  );
  return 0;
}

if (import.meta.main) {
  main().then(
    (code) => process.exit(code),
    (e) => {
      console.error(e);
      process.exit(1);
    },
  );
}

// Re-exported for tests.
export { CARTS };
