# Tempo — distributed traces.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: tempo
  namespace: argocd
  finalizers: [ resources-finalizer.argocd.argoproj.io ]
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo
    targetRevision: 1.18.0
    helm:
      releaseName: tempo
      valuesObject:
        tempo:
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
        persistence:
          enabled: true
          storageClassName: longhorn
          size: 50Gi
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated: { prune: false, selfHeal: true }
    syncOptions: [ CreateNamespace=true, ServerSideApply=true ]
