-- =============================================================================
-- Inventory — Phase 3 pre-seed cleanup (SQL editor / privileged owner path)
-- Run ONCE in the Supabase SQL editor, BEFORE the Phase 3 seed import.
--
-- WHY THIS IS OWNER-RUN (not a client/REST operation):
--   The proof runs (Phase 1 proof B + Phase 2 negative-control) left a throwaway
--   item id=2 ('__client_proof_item__') plus its immutable change_log rows. The
--   seed assigns EXPLICIT ids 1..211 (skip 8), so item id=2 must be gone first or
--   the seed insert collides on the items PK. But:
--     - items has NO DELETE policy (archive-only) -> even an admin cannot DELETE an
--       item via the client/REST path (RLS returns 0 rows).
--     - change_log is immutable: no UPDATE/DELETE policy AND a BEFORE UPDATE/DELETE
--       trigger (change_log_no_mutate) that RAISEs for EVERYONE incl. the owner.
--   So the only correct mechanism is this owner-run script that briefly disables the
--   immutability trigger, removes the proof rows, re-enables it, and resets the id
--   sequence. (service_role is NOT used or required — the SQL editor runs as the
--   table owner/postgres.)
--
-- AUDIT OF THE DELETION IS PRESERVED (owner-approved Decision 1, 2026-05-31):
--   1. This committed script + the PROGRESS.md Decisions entry are the durable
--      git-record (who/what/when/why).
--   2. Before re-enabling the immutability trigger, we INSERT one documentary row
--      into change_log (item_id=NULL, action='ADMIN_CLEANUP'). Append-only INSERT
--      does NOT violate immutability (only UPDATE/DELETE are blocked); item_id=NULL
--      avoids ever colliding with / misattaching to seed item #2.
--
-- SAFETY: runs in ONE transaction that COMMITS. A pre-flight guard ABORTS (RAISE)
--   the whole transaction if the DB does not look like the expected post-proof
--   state (e.g. real seed data already present, or item id=2 is not the throwaway
--   proof item). Re-running after a successful run is a no-op-with-abort (guard
--   sees 0 rows to clean) — safe.
-- =============================================================================

begin;

do $$
declare
  v_item_name   text;
  v_items_total bigint;
  v_log_for_2   bigint;
begin
  -- ---- GUARD 1: there must be EXACTLY the proof artifacts, not real seed data.
  -- After Phases 1-2 the only item that should exist is the throwaway id=2.
  select count(*) into v_items_total from public.items;
  if v_items_total <> 1 then
    raise exception
      'ABORT: expected exactly 1 item (the throwaway id=2) before cleanup, found %.  '
      'Refusing to run so we never delete real data. Inspect public.items manually.',
      v_items_total;
  end if;

  -- ---- GUARD 2: item id=2 must be the throwaway proof item, by name.
  select name into v_item_name from public.items where id = 2;
  if v_item_name is null then
    raise exception 'ABORT: no item with id=2 found. Nothing matching the known proof artifact; refusing to guess.';
  end if;
  if v_item_name <> '__client_proof_item__' then
    raise exception
      'ABORT: item id=2 is named %, not the expected throwaway ''__client_proof_item__''. '
      'Refusing to delete an unexpected row.', v_item_name;
  end if;

  -- (informational) how many change_log rows point at item 2 (expected: 2 -> ids 2,3)
  select count(*) into v_log_for_2 from public.change_log where item_id = 2;
  raise notice 'Pre-clean: item id=2 = %, change_log rows for item 2 = % (expected 2: INSERT + UPDATE notes).',
    v_item_name, v_log_for_2;

  -- ---- DO THE CLEANUP (immutability trigger briefly disabled for the child-row delete).
  alter table public.change_log disable trigger change_log_immutable;

  delete from public.change_log where item_id = 2;        -- removes proof rows (ids 2,3)
  delete from public.items      where id = 2;             -- now unblocked (no child FK rows)

  -- ---- DOCUMENTARY AUDIT ROW (Decision 1): append-only INSERT, item_id NULL.
  insert into public.change_log (item_id, actor, action, field, old_value, new_value)
  values (
    null,
    auth.uid(),                               -- NULL in SQL editor (no JWT) — that's fine + honest
    'ADMIN_CLEANUP',
    null,
    'deleted item id=2 (__client_proof_item__) + its change_log rows (ids 2,3)',
    'pre-seed PK-collision cleanup; see inventory/sql/phase3_cleanup.sql (Phase 3, owner-approved)'
  );

  -- ---- restore the immutability guard for everyone.
  alter table public.change_log enable trigger change_log_immutable;
end
$$;

-- ---- Reset the items id sequence so post-seed auto-ids continue AFTER 211.
-- "generated by default as identity" lets the seed set explicit ids 1..211; this
-- bumps the sequence so the next default-generated id (Phase 4 inserts) is 212.
select setval(pg_get_serial_sequence('public.items', 'id'), 211, true);

-- ---- Show what remains so the owner can eyeball before COMMIT.
select 'items_remaining'      as what, count(*)::text as value from public.items
union all
select 'change_log_total'     as what, count(*)::text from public.change_log
union all
select 'admin_cleanup_rows'   as what, count(*)::text from public.change_log where action = 'ADMIN_CLEANUP'
union all
select 'next_item_id (seq+1)' as what, (currval(pg_get_serial_sequence('public.items','id')) + 1)::text;

commit;

-- Expected after COMMIT:
--   items_remaining       0
--   change_log_total      1     (only the ADMIN_CLEANUP documentary row)
--   admin_cleanup_rows    1
--   next_item_id (seq+1)  212
--
-- After this, run the Phase 3 seed import (Claude, REST as editor). The audit row
-- with action='ADMIN_CLEANUP' (item_id NULL) is now permanently in change_log and
-- can no longer be UPDATEd/DELETEd (immutability re-enabled).
-- =============================================================================
