using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Zeta.Core.CSharp.TypeProvider;

/// <summary>
/// Approach A — a literal Roslyn <see cref="IIncrementalGenerator"/> that emits a C#
/// <c>sealed record</c> per <c>*.zetaschema.json</c> file at <b>compile time</b>. This is the
/// "magical" type-provider analogue: a consumer project that adds a schema as an
/// <c>&lt;AdditionalFiles&gt;</c> and references this assembly with
/// <c>OutputItemType="Analyzer"</c> can simply <i>use</i> the generated record — no codegen step,
/// no committed <c>.cs</c> output.
/// <para>
/// The emitted shape (header + <c>#nullable enable</c> + <c>namespace X;</c> +
/// <c>public sealed record T(csType name, ...);</c>) deliberately matches approach B
/// (<c>Zeta.Core.CSharp.SchemaCodegen</c>) so the two legs are directly comparable. The schema JSON
/// shape is <c>{ "namespace": "...", "typeName": "...", "fields": [ { "name": "...", "csType": "..." } ] }</c>.
/// </para>
/// <para>
/// Pure + deterministic: the same schema text produces byte-identical source. Line endings are
/// explicit <c>\n</c> so output is byte-lockable across machines (DST / four-oracle byte-lock).
/// </para>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SchemaSourceGenerator : IIncrementalGenerator
{
    private const string SchemaSuffix = ".zetaschema.json";

    /// <summary>Wire the pipeline: every <c>*.zetaschema.json</c> additional file becomes a record.</summary>
    /// <param name="context">The incremental-generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<(string HintName, string? Source, Diagnostic? Error)> schemas =
            context.AdditionalTextsProvider
                .Where(static text => text.Path.EndsWith(SchemaSuffix, StringComparison.OrdinalIgnoreCase))
                .Select(static (text, cancellationToken) =>
                {
                    SourceText? content = text.GetText(cancellationToken);
                    string fileName = System.IO.Path.GetFileName(text.Path);
                    return RenderSchema(fileName, content?.ToString() ?? string.Empty);
                });

        context.RegisterSourceOutput(schemas, static (productionContext, result) =>
        {
            if (result.Error is not null)
            {
                productionContext.ReportDiagnostic(result.Error);
                return;
            }

            if (result.Source is not null)
            {
                productionContext.AddSource(result.HintName, SourceText.From(result.Source, Encoding.UTF8));
            }
        });
    }

    private static (string HintName, string? Source, Diagnostic? Error) RenderSchema(string fileName, string json)
    {
        ParsedSchema? schema;
        string? parseError;
        if (!TryParse(json, out schema, out parseError) || schema is null)
        {
            return (
                fileName,
                null,
                Diagnostic.Create(InvalidSchema, Location.None, fileName, parseError ?? "unknown error"));
        }

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/> Generated by Zeta.Core.CSharp.TypeProvider from a zeta type schema. Do not edit.\n");
        sb.Append("#nullable enable\n");
        sb.Append("namespace ").Append(schema.Namespace).Append(";\n\n");
        sb.Append("public sealed record ").Append(schema.TypeName).Append('(');

        for (var i = 0; i < schema.Fields.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            ParsedField field = schema.Fields[i];
            sb.Append(field.CsType).Append(' ').Append(field.Name);
        }

        sb.Append(");\n");

        // Hint name must be unique + a valid file id; key off the type so two schemas never collide.
        string hint = schema.TypeName + ".g.cs";
        return (hint, sb.ToString(), null);
    }

    private static readonly DiagnosticDescriptor InvalidSchema = new(
        id: "ZTP001",
        title: "Invalid zeta type schema",
        messageFormat: "'{0}' is not a valid .zetaschema.json: {1}",
        category: "Zeta.TypeProvider",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    // A deliberately tiny, dependency-free JSON reader for the fixed schema shape. We avoid
    // System.Text.Json so the generator carries no extra design-time assembly to load inside the
    // compiler, and stays trivially deterministic. It accepts the exact shape approach B's
    // TypeSchema serializes to; anything else yields a ZTP001 diagnostic rather than a crash.
    private static bool TryParse(string json, out ParsedSchema? schema, out string? error)
    {
        schema = null;
        error = null;
        try
        {
            var reader = new MiniJsonReader(json);
            object? root = reader.ParseValue();
            if (root is not Dictionary<string, object?> obj)
            {
                error = "root must be a JSON object";
                return false;
            }

            string? ns = GetString(obj, "namespace");
            string? typeName = GetString(obj, "typeName");
            if (string.IsNullOrWhiteSpace(ns))
            {
                error = "missing or empty 'namespace'";
                return false;
            }

            if (string.IsNullOrWhiteSpace(typeName))
            {
                error = "missing or empty 'typeName'";
                return false;
            }

            if (!obj.TryGetValue("fields", out object? fieldsObj) || fieldsObj is not List<object?> fieldsList)
            {
                error = "missing 'fields' array";
                return false;
            }

            if (!TryParseFields(fieldsList, out List<ParsedField> fields, out error))
            {
                return false;
            }

            schema = new ParsedSchema(ns!, typeName!, fields);
            return true;
        }
#pragma warning disable CA1031 // any malformed input becomes a ZTP001 diagnostic, never a generator crash
        catch (Exception ex)
#pragma warning restore CA1031
        {
            error = ex.Message;
            return false;
        }
    }

    private static bool TryParseFields(List<object?> fieldsList, out List<ParsedField> fields, out string? error)
    {
        error = null;
        fields = new List<ParsedField>(fieldsList.Count);
        foreach (object? item in fieldsList)
        {
            if (item is not Dictionary<string, object?> fieldObj)
            {
                error = "each field must be a JSON object";
                return false;
            }

            string? name = GetString(fieldObj, "name");
            string? csType = GetString(fieldObj, "csType");
            if (string.IsNullOrWhiteSpace(name) || string.IsNullOrWhiteSpace(csType))
            {
                error = "each field needs non-empty 'name' and 'csType'";
                return false;
            }

            fields.Add(new ParsedField(name!, csType!));
        }

        return true;
    }

    private static string? GetString(Dictionary<string, object?> obj, string key)
        => obj.TryGetValue(key, out object? value) && value is string s ? s : null;

    private sealed class ParsedSchema
    {
        public ParsedSchema(string ns, string typeName, IReadOnlyList<ParsedField> fields)
        {
            Namespace = ns;
            TypeName = typeName;
            Fields = fields;
        }

        public string Namespace { get; }

        public string TypeName { get; }

        public IReadOnlyList<ParsedField> Fields { get; }
    }

    private sealed class ParsedField
    {
        public ParsedField(string name, string csType)
        {
            Name = name;
            CsType = csType;
        }

        public string Name { get; }

        public string CsType { get; }
    }

    /// <summary>
    /// Minimal recursive-descent JSON reader supporting objects, arrays, strings, numbers, bools,
    /// and null — enough for the fixed schema shape, with no external dependency.
    /// </summary>
    private sealed class MiniJsonReader
    {
        private readonly string _s;
        private int _i;

        public MiniJsonReader(string s)
        {
            _s = s;
            _i = 0;
        }

        public object? ParseValue()
        {
            SkipWhitespace();
            if (_i >= _s.Length)
            {
                throw new FormatException("unexpected end of input");
            }

            char c = _s[_i];
            return c switch
            {
                '{' => ParseObject(),
                '[' => ParseArray(),
                '"' => ParseString(),
                't' or 'f' => ParseBool(),
                'n' => ParseNull(),
                _ => ParseNumber(),
            };
        }

        private Dictionary<string, object?> ParseObject()
        {
            var result = new Dictionary<string, object?>(StringComparer.Ordinal);
            _i++; // consume '{'
            SkipWhitespace();
            if (Peek() == '}')
            {
                _i++;
                return result;
            }

            while (true)
            {
                SkipWhitespace();
                string key = ParseString();
                SkipWhitespace();
                Expect(':');
                object? value = ParseValue();
                result[key] = value;
                SkipWhitespace();
                char c = Next();
                if (c == '}')
                {
                    break;
                }

                if (c != ',')
                {
                    throw new FormatException("expected ',' or '}' in object");
                }
            }

            return result;
        }

        private List<object?> ParseArray()
        {
            var result = new List<object?>();
            _i++; // consume '['
            SkipWhitespace();
            if (Peek() == ']')
            {
                _i++;
                return result;
            }

            while (true)
            {
                object? value = ParseValue();
                result.Add(value);
                SkipWhitespace();
                char c = Next();
                if (c == ']')
                {
                    break;
                }

                if (c != ',')
                {
                    throw new FormatException("expected ',' or ']' in array");
                }
            }

            return result;
        }

        private string ParseString()
        {
            SkipWhitespace();
            Expect('"');
            var sb = new StringBuilder();
            while (true)
            {
                if (_i >= _s.Length)
                {
                    throw new FormatException("unterminated string");
                }

                char c = _s[_i++];
                if (c == '"')
                {
                    break;
                }

                if (c == '\\')
                {
                    char esc = Next();
                    switch (esc)
                    {
                        case '"': sb.Append('"'); break;
                        case '\\': sb.Append('\\'); break;
                        case '/': sb.Append('/'); break;
                        case 'b': sb.Append('\b'); break;
                        case 'f': sb.Append('\f'); break;
                        case 'n': sb.Append('\n'); break;
                        case 'r': sb.Append('\r'); break;
                        case 't': sb.Append('\t'); break;
                        case 'u':
                            string hex = _s.Substring(_i, 4);
                            _i += 4;
                            sb.Append((char)ushort.Parse(hex, NumberStyles.HexNumber, CultureInfo.InvariantCulture));
                            break;
                        default: throw new FormatException("invalid escape sequence");
                    }
                }
                else
                {
                    sb.Append(c);
                }
            }

            return sb.ToString();
        }

        private bool ParseBool()
        {
            if (string.CompareOrdinal(_s, _i, "true", 0, 4) == 0)
            {
                _i += 4;
                return true;
            }

            if (string.CompareOrdinal(_s, _i, "false", 0, 5) == 0)
            {
                _i += 5;
                return false;
            }

            throw new FormatException("invalid literal");
        }

        private object? ParseNull()
        {
            if (string.CompareOrdinal(_s, _i, "null", 0, 4) == 0)
            {
                _i += 4;
                return null;
            }

            throw new FormatException("invalid literal");
        }

        private double ParseNumber()
        {
            int start = _i;
            while (_i < _s.Length && (char.IsDigit(_s[_i]) || "+-.eE".IndexOf(_s[_i]) >= 0))
            {
                _i++;
            }

            string token = _s.Substring(start, _i - start);
            return double.Parse(token, CultureInfo.InvariantCulture);
        }

        private void SkipWhitespace()
        {
            while (_i < _s.Length && char.IsWhiteSpace(_s[_i]))
            {
                _i++;
            }
        }

        private char Peek() => _i < _s.Length ? _s[_i] : '\0';

        private char Next()
        {
            if (_i >= _s.Length)
            {
                throw new FormatException("unexpected end of input");
            }

            return _s[_i++];
        }

        private void Expect(char c)
        {
            if (Next() != c)
            {
                throw new FormatException("expected '" + c + "'");
            }
        }
    }
}
