namespace Zeta.Core.CSharp.ZetaId;

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

public static class GeneratedBitLayout
{
    public const int VersionOffset = 123;
    public const int VersionWidth = 5;
    public const int TimestampOffset = 75;
    public const int TimestampWidth = 48;
    public const int ChromosomeOffset = 70;
    public const int ChromosomeWidth = 5;
    public const int CategoryOffset = 65;
    public const int CategoryWidth = 4;
    public const int FireflyOffset = 64;
    public const int FireflyWidth = 1;
    public const int AuthorityOffset = 59;
    public const int AuthorityWidth = 5;
    public const int PersonaOffset = 51;
    public const int PersonaWidth = 8;
    public const int MomentumOffset = 43;
    public const int MomentumWidth = 8;
    public const int LocationOffset = 35;
    public const int LocationWidth = 8;
    public const int RandomnessOffset = 0;
    public const int RandomnessWidth = 32;
}
