namespace Zeta.Core.CSharp.ZetaId;

// Auto-generated by src/Core.TypeScript/zeta-id/zeta-id-generator.ts. Do not edit.

#pragma warning disable MA0048 // File name does not match type name since we bundle UoM types here

public readonly struct Bits : System.IEquatable<Bits>
{
    public int Value { get; }
    public Bits(int value) => Value = value;
    public override bool Equals(object? obj) => obj is Bits other && Equals(other);
    public bool Equals(Bits other) => Value == other.Value;
    public override int GetHashCode() => Value;
    public static bool operator ==(Bits left, Bits right) => left.Equals(right);
    public static bool operator !=(Bits left, Bits right) => !left.Equals(right);
    public static Bits operator +(Bits a, Bits b) => new Bits(a.Value + b.Value);
    public static Bits operator -(Bits a, Bits b) => new Bits(a.Value - b.Value);
    public override string ToString() => Value.ToString(System.Globalization.CultureInfo.InvariantCulture);
}

public static class GeneratedBitLayout
{
    public static readonly Bits VersionOffset = new Bits(123);
    public static readonly Bits VersionWidth = new Bits(5);
    public static readonly Bits TimestampOffset = new Bits(75);
    public static readonly Bits TimestampWidth = new Bits(48);
    public static readonly Bits ChromosomeOffset = new Bits(70);
    public static readonly Bits ChromosomeWidth = new Bits(5);
    public static readonly Bits CategoryOffset = new Bits(65);
    public static readonly Bits CategoryWidth = new Bits(4);
    public static readonly Bits FireflyOffset = new Bits(64);
    public static readonly Bits FireflyWidth = new Bits(1);
    public static readonly Bits AuthorityOffset = new Bits(59);
    public static readonly Bits AuthorityWidth = new Bits(5);
    public static readonly Bits PersonaOffset = new Bits(51);
    public static readonly Bits PersonaWidth = new Bits(8);
    public static readonly Bits MomentumOffset = new Bits(43);
    public static readonly Bits MomentumWidth = new Bits(8);
    public static readonly Bits LocationOffset = new Bits(35);
    public static readonly Bits LocationWidth = new Bits(8);
    public static readonly Bits RandomnessOffset = new Bits(0);
    public static readonly Bits RandomnessWidth = new Bits(32);
}
