import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

// Define the Field interface representing a bitfield
interface Field {
  name: string;
  offset: number;
  width: number;
  type: string;
}

function valueAfterColon(line: string): string {
  const colon = line.indexOf(':');
  if (colon < 0) {
    throw new Error(`Expected YAML key/value line with colon: ${line}`);
  }
  return line.slice(colon + 1).trim();
}

// Simple robust parser for docs/zeta-id-v1-layout.yaml
function parseYaml(filePath: string): Field[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const fields: Field[] = [];
  let currentField: Partial<Field> | null = null;
  const lines = content.split('\n');
  let inFields = false;

  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith('fields:')) {
      inFields = true;
      continue;
    }
    if (trimmed.startsWith('reserved_bits:')) {
      break;
    }
    if (!inFields) {
      continue;
    }

    if (trimmed.startsWith('- name:')) {
      if (currentField && currentField.name !== undefined && currentField.offset !== undefined && currentField.width !== undefined) {
        fields.push(currentField as Field);
      }
      currentField = { name: valueAfterColon(trimmed) };
    } else if (currentField) {
      if (trimmed.startsWith('offset:')) {
        currentField.offset = parseInt(valueAfterColon(trimmed), 10);
      } else if (trimmed.startsWith('width:')) {
        currentField.width = parseInt(valueAfterColon(trimmed), 10);
      } else if (trimmed.startsWith('type:')) {
        currentField.type = valueAfterColon(trimmed);
      }
    }
  }
  if (currentField && currentField.name !== undefined && currentField.offset !== undefined && currentField.width !== undefined) {
    fields.push(currentField as Field);
  }
  return fields;
}

function generateTS(fields: Field[]): string {
  let out = `// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

export const BIT_MASKS = {
`;
  for (const field of fields) {
    const key = field.name.toLowerCase();
    out += `  ${key}: { offset: ${field.offset}n, width: ${field.width}n },\n`;
  }
  out += `};\n`;
  return out;
}

function generateFSharp(fields: Field[]): string {
  let out = `namespace Zeta.Core.FSharp.ZetaId

// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

module GeneratedBitLayout =
`;
  for (const field of fields) {
    out += `    let ${field.name}Offset = ${field.offset}\n`;
    out += `    let ${field.name}Width = ${field.width}\n`;
  }
  return out;
}

function generateCSharp(fields: Field[]): string {
  let out = `namespace Zeta.Core.CSharp.ZetaId;

// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

public static class GeneratedBitLayout
{
`;
  for (const field of fields) {
    out += `    public const int ${field.name}Offset = ${field.offset};\n`;
    out += `    public const int ${field.name}Width = ${field.width};\n`;
  }
  out += `}\n`;
  return out;
}

function generateRust(fields: Field[]): string {
  let out = `// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

`;
  for (const field of fields) {
    const uppercase = field.name.toUpperCase();
    out += `/// Bit offset of the ${field.name} field.\n`;
    out += `pub const ${uppercase}_OFFSET: u32 = ${field.offset};\n`;
    out += `/// Bit width of the ${field.name} field.\n`;
    out += `pub const ${uppercase}_WIDTH: u32 = ${field.width};\n`;
  }
  return out;
}

function generateGo(fields: Field[]): string {
  let out = `package zeta_id

// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

const (
`;
  for (const field of fields) {
    out += `	${field.name}Offset = ${field.offset}\n`;
    out += `	${field.name}Width  = ${field.width}\n`;
  }
  out += `)\n`;
  return out;
}

function generatePython(fields: Field[]): string {
  let out = `# Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

`;
  for (const field of fields) {
    const uppercase = field.name.toUpperCase();
    out += `${uppercase}_OFFSET = ${field.offset}\n`;
    out += `${uppercase}_WIDTH = ${field.width}\n`;
  }
  return out;
}

function main() {
  const rootDir = path.resolve(__dirname, '../..');
  const yamlPath = path.join(rootDir, 'docs/zeta-id-v1-layout.yaml');
  const fields = parseYaml(yamlPath);

  console.log(`Parsed ${fields.length} fields from ${yamlPath}`);

  // Write TS
  const tsPath = path.join(rootDir, 'src/Core.TypeScript/zeta-id/zeta-id.gen.ts');
  fs.writeFileSync(tsPath, generateTS(fields), 'utf-8');
  console.log(`Wrote TS to ${tsPath}`);

  // Write F#
  const fsPath = path.join(rootDir, 'src/Core.FSharp.ZetaId/GeneratedBitLayout.fs');
  fs.writeFileSync(fsPath, generateFSharp(fields), 'utf-8');
  console.log(`Wrote F# to ${fsPath}`);

  // Write C#
  const csPath = path.join(rootDir, 'src/Core.CSharp.ZetaId/GeneratedBitLayout.cs');
  fs.writeFileSync(csPath, generateCSharp(fields), 'utf-8');
  console.log(`Wrote C# to ${csPath}`);

  // Write Rust
  const rsPath = path.join(rootDir, 'src/Core.Rust.ZetaId/src/bit_layout.gen.rs');
  fs.writeFileSync(rsPath, generateRust(fields), 'utf-8');
  console.log(`Wrote Rust to ${rsPath}`);

  // Write Go
  const goPath = path.join(rootDir, 'src/Core.Go/zeta_id/zeta_id.gen.go');
  fs.writeFileSync(goPath, generateGo(fields), 'utf-8');
  console.log(`Wrote Go to ${goPath}`);

  // Write Python
  const pyPath = path.join(rootDir, 'src/Core.Python/src/zeta/zeta_id_gen.py');
  fs.writeFileSync(pyPath, generatePython(fields), 'utf-8');
  console.log(`Wrote Python to ${pyPath}`);

  console.log('Running formatters on generated code...');
  try {
    execSync(`npx prettier --write "${tsPath}"`);
    execSync(`go fmt "${goPath}"`);
    execSync(`cargo fmt --manifest-path "${path.join(rootDir, 'src/Core.Rust.ZetaId/Cargo.toml')}"`);
    const pyVenvRuff = path.join(rootDir, 'src/Core.Python/.venv/bin/ruff');
    if (fs.existsSync(pyVenvRuff)) {
      execSync(`"${pyVenvRuff}" format "${pyPath}"`);
    }
  } catch (err) {
    console.warn('Warning: Layout formatters had issues:', err);
  }

  console.log('Codegen successfully completed across 6 languages.');
}

main();
