CREATE TABLE IF NOT EXISTS agentic_org_work_schedule_blocks (
  work_schedule_block_id STRING PRIMARY KEY,
  organization_id STRING NOT NULL,
  project_id STRING NOT NULL,
  team_id STRING,
  work_item_id STRING NOT NULL,
  discussion_anchor_id STRING,
  assigned_agent_id STRING NOT NULL,
  assigned_hat_assignment_id STRING NOT NULL,
  block_type STRING NOT NULL CONSTRAINT agentic_org_work_schedule_blocks_type_check CHECK (block_type IN ('free_time', 'meeting', 'memory_maintenance', 'prioritized_work', 'prompt_flow_execution', 'reflection', 'reporting', 'review')),
  state STRING NOT NULL CONSTRAINT agentic_org_work_schedule_blocks_state_check CHECK (state IN ('active', 'canceled', 'completed', 'missed', 'paused', 'scheduled')),
  title STRING NOT NULL,
  purpose STRING NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  scheduled_by_agent_id STRING NOT NULL,
  scheduled_by_hat_assignment_id STRING NOT NULL,
  scheduled_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  version INT8 NOT NULL,
  correlation_id STRING NOT NULL,
  causation_id STRING NOT NULL,
  trace_id STRING NOT NULL
);
