CREATE TABLE IF NOT EXISTS agentic_org_memory_state (
  memory_id STRING PRIMARY KEY,
  organization_id STRING NOT NULL,
  tier STRING NOT NULL,
  scope STRING NOT NULL,
  key STRING NOT NULL,
  phase STRING NOT NULL,
  confidence FLOAT8 NOT NULL,
  weight FLOAT8 NOT NULL,
  freshness_at TIMESTAMPTZ NOT NULL,
  reinforcement_count INT8 NOT NULL,
  protected BOOL NOT NULL,
  written_by STRING NOT NULL,
  written_at TIMESTAMPTZ NOT NULL,
  context_hint STRING NULL,
  outcome JSONB NOT NULL,
  utility JSONB NOT NULL,
  cross_scope JSONB NOT NULL,
  archived_at TIMESTAMPTZ NULL,
  CONSTRAINT agentic_org_memory_state_tier_check CHECK (tier IN ('org', 'department', 'hat', 'agent', 'work')),
  CONSTRAINT agentic_org_memory_state_phase_check CHECK (phase IN ('draft', 'active', 'reinforced', 'stale', 'demoted', 'promoted', 'conflicted', 'archived')),
  INDEX memory_state_by_org_scope (organization_id, scope),
  INDEX memory_state_by_org_phase (organization_id, phase),
  INDEX memory_state_by_org_weight (organization_id, weight DESC)
);
CREATE TABLE IF NOT EXISTS agentic_org_memory_injection (
  injection_id STRING PRIMARY KEY,
  organization_id STRING NOT NULL,
  memory_id STRING NOT NULL,
  work_item_id STRING NOT NULL,
  hat_id STRING NOT NULL,
  agent_id STRING NOT NULL,
  prompt_flow_run_id STRING NOT NULL,
  weight_at_injection FLOAT8 NOT NULL,
  cited BOOL NOT NULL,
  injected_at TIMESTAMPTZ NOT NULL,
  INDEX memory_injection_by_memory (memory_id, injected_at),
  INDEX memory_injection_by_work (work_item_id, injected_at),
  INDEX memory_injection_by_run (prompt_flow_run_id, injected_at)
);
