CREATE TABLE IF NOT EXISTS agentic_org_context_pack_snapshots (
  context_pack_id STRING PRIMARY KEY,
  organization_id STRING NOT NULL,
  run_id STRING NOT NULL,
  scope STRING NOT NULL,
  hat_assignment_id STRING NOT NULL,
  hat_id STRING NOT NULL,
  agent_id STRING NULL,
  project_id STRING NULL,
  team_id STRING NULL,
  work_item_id STRING NULL,
  status STRING NOT NULL,
  phase STRING NULL,
  generated_at TIMESTAMPTZ NOT NULL,
  freshness_deadline TIMESTAMPTZ NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL,
  source_graph_version STRING NOT NULL,
  policy_version STRING NOT NULL,
  trace_id STRING NOT NULL,
  correlation_id STRING NOT NULL,
  causation_id STRING NOT NULL,
  context_json JSONB NOT NULL,
  INDEX context_pack_snapshots_by_org_recorded (organization_id, recorded_at DESC),
  INDEX context_pack_snapshots_by_scope (organization_id, project_id, team_id, work_item_id, recorded_at DESC),
  INDEX context_pack_snapshots_by_hat (organization_id, hat_assignment_id, recorded_at DESC),
  INDEX context_pack_snapshots_by_status (organization_id, status, recorded_at DESC)
);
