CREATE TABLE IF NOT EXISTS agentic_org_context_pack_advisory_promotion_decisions (
  decision_id STRING PRIMARY KEY,
  decision_key STRING NOT NULL UNIQUE,
  organization_id STRING NOT NULL,
  status STRING NOT NULL,
  policy_version STRING NOT NULL,
  lifecycle_blocker STRING NOT NULL,
  item_kind STRING NOT NULL,
  summary_hash STRING NOT NULL,
  citation_refs JSONB NOT NULL,
  source_pointer_keys JSONB NOT NULL,
  evidence_refs JSONB NOT NULL,
  hat_id STRING NULL,
  hat_assignment_id STRING NULL,
  project_id STRING NULL,
  team_id STRING NULL,
  work_item_id STRING NULL,
  curation_profile_id STRING NULL,
  decided_by_hat_id STRING NOT NULL,
  decided_by_hat_assignment_id STRING NOT NULL,
  decided_by_agent_id STRING NULL,
  decided_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  trace_id STRING NOT NULL,
  correlation_id STRING NOT NULL,
  causation_id STRING NOT NULL,
  CONSTRAINT agentic_org_context_pack_advisory_promotion_decisions_status_check CHECK (status IN ('approved', 'revoked')),
  CONSTRAINT agentic_org_context_pack_advisory_promotion_decisions_item_kind_check CHECK (item_kind IN ('synthesis_gap_hypothesis')),
  CONSTRAINT agentic_org_context_pack_advisory_promotion_decisions_blocker_check CHECK (length(trim(lifecycle_blocker)) > 0),
  INDEX advisory_promotion_decisions_by_scope (organization_id, hat_id, hat_assignment_id, project_id, team_id, work_item_id, curation_profile_id, status, policy_version),
  INDEX advisory_promotion_decisions_by_fingerprint (organization_id, item_kind, summary_hash, status, policy_version),
  INDEX advisory_promotion_decisions_by_curator (organization_id, decided_by_hat_id, updated_at DESC)
);
