// Auto-generated by tools/codegen/zeta-id-generator.ts. Do not edit.

export const BIT_MASKS = {
  version: { offset: 123n, width: 5n },
  timestamp: { offset: 75n, width: 48n },
  chromosome: { offset: 70n, width: 5n },
  category: { offset: 65n, width: 4n },
  firefly: { offset: 64n, width: 1n },
  authority: { offset: 59n, width: 5n },
  persona: { offset: 51n, width: 8n },
  momentum: { offset: 43n, width: 8n },
  location: { offset: 35n, width: 8n },
  randomness: { offset: 0n, width: 32n },
};
