<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Zeta.Cli</RootNamespace>
    <AssemblyName>zeta</AssemblyName>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ZetaShell.fs" />
    <Compile Include="StoreSelect.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core.FSharp.Git\Zeta.Core.FSharp.Git.fsproj" />
    <ProjectReference Include="..\Core.FSharp.Blake3\Zeta.Core.FSharp.Blake3.fsproj" />
    <ProjectReference Include="..\Core\Core.fsproj" />
  </ItemGroup>
</Project>
