#!/usr/bin/env python3
"""Is there an operator algebra in the folds? Compute it, don't assert it.

Shared layer  : BeliefConvergence.observe l b = pointwise multiply  -> diagonal operators
Local layer   : TwoTimescaleFold.localStep    -> next[t] += sum(v)  -> L_t = I + e_t 1^T
Adinkra layer : gamma matrices, {g_i,g_j} = 2 delta_ij

Question: which of these has (a) a nonzero commutator at all, (b) a CENTRAL element
(the thing a canonical commutation relation / an hbar needs).
"""
import itertools
from fractions import Fraction

D = 4  # dimension of the belief vector


def zeros(n=D):
    return [[0] * n for _ in range(n)]


def ident(n=D):
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]


def mul(A, B):
    n = len(A)
    return [[sum(A[i][k] * B[k][j] for k in range(n)) for j in range(n)] for i in range(n)]


def sub(A, B):
    return [[A[i][j] - B[i][j] for j in range(len(A))] for i in range(len(A))]


def add(A, B):
    return [[A[i][j] + B[i][j] for j in range(len(A))] for i in range(len(A))]


def comm(A, B):
    return sub(mul(A, B), mul(B, A))


def anticomm(A, B):
    return add(mul(A, B), mul(B, A))


def is_zero(A):
    return all(all(x == 0 for x in r) for r in A)


def scal(A, c):
    return [[c * x for x in r] for r in A]


def trace(A):
    return sum(A[i][i] for i in range(len(A)))


def rank(A):
    M = [[Fraction(x) for x in row] for row in A]
    n, m = len(M), len(M[0])
    r = 0
    for c in range(m):
        piv = next((i for i in range(r, n) if M[i][c] != 0), None)
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        M[r] = [x / pv for x in M[r]]
        for i in range(n):
            if i != r and M[i][c] != 0:
                f = M[i][c]
                M[i] = [a - f * b for a, b in zip(M[i], M[r])]
        r += 1
    return r


print("=" * 72)
print("SHARED LAYER — BeliefConvergence.observe (pointwise multiply = diagonal ops)")
print("=" * 72)
diags = []
for pattern in [(2, 1, 1, 1), (1, 3, 1, 1), (1, 1, 5, 1), (7, 2, 3, 5)]:
    M = zeros()
    for i, v in enumerate(pattern):
        M[i][i] = v
    diags.append((pattern, M))
maxcomm = 0
for (p1, A), (p2, B) in itertools.combinations(diags, 2):
    C = comm(A, B)
    maxcomm = max(maxcomm, max(abs(x) for r in C for x in r))
print("max |[A,B]| over all pairs of observe-operators :", maxcomm)
print("=> the shared fold's operators COMMUTE identically. No commutator, no algebra, no hbar.")

print()
print("=" * 72)
print("LOCAL LAYER — TwoTimescaleFold.localStep:  next[t] += sum(v)   =>  L_t = I + e_t 1^T")
print("=" * 72)
L = []
for t in range(D):
    M = ident()
    for j in range(D):
        M[t][j] += 1
    L.append(M)

# sanity: L_t really reproduces localStep
v = [3, 5, 7, 11]
for t in range(D):
    expect = list(v)
    expect[t] += sum(v)
    got = [sum(L[t][i][j] * v[j] for j in range(D)) for i in range(D)]
    assert got == expect, (t, got, expect)
print("L_t matches localStep semantics on a sample vector :", True)

nonzero = []
for i, j in itertools.combinations(range(D), 2):
    C = comm(L[i], L[j])
    nonzero.append((i, j, C))
print("[L_0,L_1] =", comm(L[0], L[1]))
print("  rank    :", rank(comm(L[0], L[1])), " trace:", trace(comm(L[0], L[1])),
      " (commutators are traceless — sanity check)")
Z01 = comm(L[0], L[1])
print("  [L_0,L_1]^2 == 0 (nilpotent of index 2):", is_zero(mul(Z01, Z01)))
print("all pairs i<j have NONZERO commutator      :", all(not is_zero(C) for _, _, C in nonzero))
print("number of independent commutator pairs C(4,2):", len(nonzero))

# is any commutator a multiple of the identity (a canonical commutation relation)?
def is_multiple_of_identity(A):
    c = A[0][0]
    return all(A[i][j] == (c if i == j else 0) for i in range(len(A)) for j in range(len(A)))


print("any [L_i,L_j] proportional to I (CCR)?     :",
      any(is_multiple_of_identity(C) for _, _, C in nonzero))

# is the derived ideal CENTRAL? compute [L_k, Z_ij]
print()
print("Is the commutator CENTRAL (what an hbar requires)?")
central = True
for (i, j, Z) in nonzero:
    for k in range(D):
        B = comm(L[k], Z)
        if not is_zero(B):
            central = False
print("  Z_ij central in the algebra              :", central)
print("  [L_0, Z_01] =", comm(L[0], Z01), " == -Z_01 ?",
      comm(L[0], Z01) == scal(Z01, -1))
print("  => derived ideal is an EIGENVECTOR of ad, not a centre: the 'ax+b' (affine)")
print("     solvable shape. Solvable, non-nilpotent, NO central element.")

# dimension of the Lie algebra generated by the L_t
def flatten(A):
    return tuple(x for r in A for x in r)


def span_dim(mats):
    rows = [list(flatten(m)) for m in mats]
    return rank(rows) if rows else 0


gen = list(L)
algebra = list(L)
for _ in range(6):
    new = []
    for A, B in itertools.combinations(algebra, 2):
        C = comm(A, B)
        if not is_zero(C):
            new.append(C)
    before = span_dim(algebra)
    algebra = algebra + new
    if span_dim(algebra) == before:
        break
print("  dim of Lie algebra generated by {L_t}    :", span_dim(algebra))
print("  dim of derived subalgebra [g,g]          :", span_dim([C for _, _, C in nonzero]))

print()
print("=" * 72)
print("ADINKRA LAYER — gamma matrices, {g_i,g_j} = 2 delta_ij  (the contrast)")
print("=" * 72)
# real 4x4 rep of Cl(3,0)-like anticommuting generators via Kronecker of Pauli-real forms
def kron(A, B):
    n, m = len(A), len(B)
    return [[A[i // m][j // m] * B[i % m][j % m] for j in range(n * m)] for i in range(n * m)]


I2 = [[1, 0], [0, 1]]
X = [[0, 1], [1, 0]]
Zp = [[1, 0], [0, -1]]
Y = [[0, -1], [1, 0]]  # real antisymmetric; Y^2 = -I
g = [kron(X, I2), kron(Zp, I2), kron(Y, X), kron(Y, Zp)]
print("generators                                  :", len(g), "(4x4 real)")
sq = [mul(m, m) for m in g]
print("g_i^2 = +/- I for every i                    :",
      all(is_multiple_of_identity(s) for s in sq), [s[0][0] for s in sq])
ok = True
for i, j in itertools.combinations(range(4), 2):
    if not is_zero(anticomm(g[i], g[j])):
        ok = False
print("{g_i,g_j} = 0 for all i != j (anticommuting) :", ok)
print("[g_i,g_j] != 0 for all i != j                :",
      all(not is_zero(comm(g[i], g[j])) for i, j in itertools.combinations(range(4), 2)))
print("g_i^2 is a MULTIPLE OF THE IDENTITY          :", all(is_multiple_of_identity(s) for s in sq))
print("   ^^ this is the central element the tick needs: Q^2 = d_tau, and d_tau is CENTRAL.")
print()
print("DISCRIMINATOR (the invariant, not the count):")
print("  shared fold : commutator = 0            -> no algebra at all")
print("  local fold  : commutator != 0, NO centre -> algebra, but no tick to be central")
print("  adinkra     : commutator != 0, HAS centre (g_i^2 = +/-I) -> a tick can be central")
