// Falsifiers for the memory LIMITS on the components the KubeVirt and CDI
// operators deploy -- virt-api / virt-controller / virt-handler and
// cdi-deployment / cdi-apiserver / cdi-uploadproxy.
//
// THE DEFECT: those pods are generated by the operators with a memory REQUEST and
// no LIMIT, and no manifest in this tree names them, so no render-based check could
// ever see that they are unbounded. The only handle is the CR's
// `customizeComponents.patches`. Before this change both CRs carried
// `customizeComponents: {}`, so every assertion below fails on the old tree.
//
// WHAT MAKES A WRONG PATCH DANGEROUS, and is pinned directly: these are STRATEGIC
// merges keyed on container name. A patch naming a container that does not exist
// does not fail -- it ADDS a container with no image, and the rollout wedges. So the
// container name must equal the workload name (true of all six; checked against the
// KubeVirt v1.8.4 and CDI v1.65.0 sources), and the patch must touch nothing but
// `limits.memory`.
//
// NOT PROVEN HERE: that these numbers are right. They are reservations sized well
// above each component's own request and are labelled unmetered in the CR headers;
// the first OOMKill on a loaded node is the measurement that moves one.

import { describe, expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { parse as parseYaml } from "yaml";

const REPO_ROOT = join(import.meta.dir, "..", "..", "..");
const APPS = join(REPO_ROOT, "full-ai-cluster/k8s/applications");

type Doc = Record<string, any>;

interface Patch {
  resourceType: string;
  resourceName: string;
  type: string;
  patch: string;
}

function patchesOf(path: string): Patch[] {
  const cr = parseYaml(readFileSync(join(APPS, path), "utf8")) as Doc;
  return (cr.spec.customizeComponents?.patches ?? []) as Patch[];
}

const SUITES: ReadonlyArray<{
  readonly name: string;
  readonly file: string;
  readonly expected: ReadonlyArray<{ readonly resourceName: string; readonly resourceType: string }>;
}> = [
  {
    name: "kubevirt",
    file: "kubevirt/kubevirt-cr.yaml",
    expected: [
      { resourceName: "virt-api", resourceType: "Deployment" },
      { resourceName: "virt-controller", resourceType: "Deployment" },
      { resourceName: "virt-handler", resourceType: "DaemonSet" },
    ],
  },
  {
    name: "cdi",
    file: "cdi/cdi-cr.yaml",
    expected: [
      { resourceName: "cdi-deployment", resourceType: "Deployment" },
      { resourceName: "cdi-apiserver", resourceType: "Deployment" },
      { resourceName: "cdi-uploadproxy", resourceType: "Deployment" },
    ],
  },
];

for (const suite of SUITES) {
  describe(`${suite.name}: every operator-deployed component is memory-bounded`, () => {
    const patches = patchesOf(suite.file);

    test("there is a patch for exactly each component, no more and no fewer", () => {
      expect(patches.map((p) => `${p.resourceType}/${p.resourceName}`).sort()).toEqual(
        suite.expected.map((e) => `${e.resourceType}/${e.resourceName}`).sort(),
      );
    });

    for (const expected of suite.expected) {
      test(`${expected.resourceName}: a strategic merge that sets ONLY limits.memory on the container of the same name`, () => {
        const p = patches.find((x) => x.resourceName === expected.resourceName);
        expect(p).toBeDefined();
        expect(p!.resourceType).toBe(expected.resourceType);
        expect(p!.type).toBe("strategic");

        const body = JSON.parse(p!.patch) as Doc;
        const containers = body.spec.template.spec.containers as Doc[];
        // One container, named like the workload. A mismatch would ADD an imageless one.
        expect(containers).toHaveLength(1);
        expect(containers[0]!.name).toBe(expected.resourceName);

        // Limits only: the operator's own requests stay in force, and no CPU limit
        // (a CFS quota throttles a controller into missing its liveness probe).
        const resources = containers[0]!.resources as Doc;
        expect(Object.keys(resources)).toEqual(["limits"]);
        expect(Object.keys(resources.limits)).toEqual(["memory"]);
        expect(resources.limits.memory).toMatch(/^\d+(Mi|Gi)$/);

        // Nothing else in the pod template is touched.
        expect(Object.keys(body.spec.template.spec)).toEqual(["containers"]);
        expect(Object.keys(body.spec.template)).toEqual(["spec"]);
        expect(Object.keys(body.spec)).toEqual(["template"]);
        expect(Object.keys(body)).toEqual(["spec"]);
      });
    }
  });
}

describe("limits are sane against what each component asks for", () => {
  // The upstream REQUESTS (KubeVirt v1.8.4 components/{deployments,daemonsets}.go;
  // CDI v1.65.0 resources/namespaced/*.go). A limit below the request is rejected by
  // the API server; one barely above it OOMKills on the first burst. Require headroom.
  const REQUEST_MIB: Record<string, number> = {
    "virt-api": 150,
    "virt-controller": 275,
    "virt-handler": 325,
    "cdi-deployment": 150,
    "cdi-apiserver": 150,
    "cdi-uploadproxy": 150,
  };

  function mib(quantity: string): number {
    const m = /^(\d+)(Mi|Gi)$/.exec(quantity)!;
    return Number(m[1]) * (m[2] === "Gi" ? 1024 : 1);
  }

  for (const suite of SUITES) {
    for (const p of patchesOf(suite.file)) {
      test(`${p.resourceName}: limit is at least 2x its request`, () => {
        const body = JSON.parse(p.patch) as Doc;
        const limit = mib(body.spec.template.spec.containers[0].resources.limits.memory);
        expect(limit).toBeGreaterThanOrEqual(REQUEST_MIB[p.resourceName]! * 2);
      });
    }
  }
});

describe("the CDI CR names its scratch space class instead of inheriting the default", () => {
  test("scratchSpaceStorageClass is a storage capability that exists", () => {
    const cr = parseYaml(readFileSync(join(APPS, "cdi/cdi-cr.yaml"), "utf8")) as Doc;
    expect(cr.spec.config.scratchSpaceStorageClass).toBe("zeta-block-local");
  });
});

describe("virt-operator and cdi-operator are NOT reachable by these patches, and the CRs do not pretend otherwise", () => {
  test("each CR header states the gap rather than leaving it to be rediscovered", () => {
    const kubevirt = readFileSync(join(APPS, "kubevirt/kubevirt-cr.yaml"), "utf8");
    const cdi = readFileSync(join(APPS, "cdi/cdi-cr.yaml"), "utf8");
    expect(kubevirt).toContain("virt-operator keeps its");
    expect(kubevirt).toContain("a stated gap, not an oversight");
    expect(cdi).toContain("cdi-operator");
    expect(cdi).toContain("out of reach of this field");
  });
});
