import { describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import {
  METAL_NOT_SEEDED,
  applicationNamespace,
  auditMetalSecretProduction,
  collectCnpgClusters,
  collectMetalSeededSecrets,
  collectOperatorGeneratedSecrets,
} from "./metal-secret-production.ts";

describe("metal-secret-production — every Secret the catalogue names exists on a fresh metal install", () => {
  const audit = auditMetalSecretProduction();

  test("finds seeded references at all, so the audit cannot pass vacuously", () => {
    // A parser that matched no `kubectl create secret` step would push every
    // seeded credential into `unproduced`, and a broken namespace lookup would
    // do the same -- both loud. This pins the other direction: the collector
    // really sees the seeding manifest.
    expect(collectMetalSeededSecrets().size).toBeGreaterThan(5);
    expect(audit.seeded.length).toBeGreaterThan(5);
  });

  test("no Application names a Secret that nothing on metal produces", () => {
    // RED on 2026-09-27 origin/main: temporal|temporal-default-store and
    // temporal|temporal-visibility-store -- the live USB install's
    // CreateContainerConfigError, reproduced from the tree.
    expect(audit.unproduced.map((r) => `${r.app}|${String(r.namespace)}/${r.secretName}`)).toEqual([]);
  });

  test("every exemption still matches a reference (a lifted exemption goes STALE)", () => {
    expect(audit.staleExemptions).toEqual([]);
  });

  test("every exemption carries a reason", () => {
    for (const [key, reason] of METAL_NOT_SEEDED) {
      expect(reason.trim().length, key).toBeGreaterThan(0);
    }
  });

  test("temporal's store Secret is GENERATED by CNPG in temporal's namespace, and NOT also seeded", () => {
    // 2026-09-27: the seeded `temporal-{default,visibility}-store` pair was a password
    // no database role carried. The Secret is now the CNPG Cluster's `-app` Secret,
    // produced by the same act that sets the role's password -- one source of truth.
    const ns = applicationNamespace("temporal");
    expect(ns).toBe("temporal");
    expect(collectOperatorGeneratedSecrets().has("temporal/temporal-postgres-app")).toBe(true);
    const seeded = collectMetalSeededSecrets();
    expect([...seeded].filter((k) => k.startsWith("temporal/"))).toEqual([]);
  });
});

describe("collectCnpgClusters — the operator-generated producer is derived, not listed", () => {
  function fixture(files: Record<string, string>): string {
    const root = mkdtempSync(join(tmpdir(), "cnpg-fixture-"));
    for (const [rel, text] of Object.entries(files)) {
      mkdirSync(dirname(join(root, rel)), { recursive: true });
      writeFileSync(join(root, rel), text);
    }
    return root;
  }
  const app = (path: string, include: string): string =>
    [
      "apiVersion: argoproj.io/v1alpha1",
      "kind: Application",
      "metadata: { name: db }",
      "spec:",
      "  source:",
      "    repoURL: https://example.invalid/repo",
      `    path: ${path}`,
      `    directory: { include: '${include}' }`,
      "  destination: { namespace: dbns }",
      "",
    ].join("\n");
  const cluster = (bootstrap: string): string =>
    `apiVersion: postgresql.cnpg.io/v1\nkind: Cluster\nmetadata: { name: pg }\nspec:\n  instances: 1\n${bootstrap}`;

  test("an initdb Cluster yields <name>-app in the Application's namespace, owner and databases", () => {
    const dir = "full-ai-cluster/k8s/applications/db";
    const root = fixture({
      [`${dir}/Application.yaml`]: app(dir, "{cluster,database}.yaml"),
      [`${dir}/cluster.yaml`]: cluster("  bootstrap: { initdb: { database: main, owner: svc } }\n"),
      [`${dir}/database.yaml`]:
        "apiVersion: postgresql.cnpg.io/v1\nkind: Database\nmetadata: { name: d2 }\nspec: { cluster: { name: pg }, name: second, owner: svc }\n",
    });
    const [c, ...rest] = collectCnpgClusters(root);
    expect(rest).toEqual([]);
    expect(c?.appSecret).toBe("pg-app");
    expect(c?.namespace).toBe("dbns");
    expect(c?.owner).toBe("svc");
    expect(c?.rwHosts).toContain("pg-rw.dbns.svc");
    expect([...(c?.databases ?? new Map())]).toEqual([
      ["main", "svc"],
      ["second", "svc"],
    ]);
  });

  test("a Cluster no Application applies produces nothing (the operator never sees it)", () => {
    const dir = "full-ai-cluster/k8s/applications/db";
    const root = fixture({
      [`${dir}/Application.yaml`]: app(dir, "other.yaml"),
      [`${dir}/cluster.yaml`]: cluster(""),
    });
    expect(collectCnpgClusters(root)).toEqual([]);
  });

  test("a recovery-bootstrapped Cluster generates no -app Secret", () => {
    const dir = "full-ai-cluster/k8s/applications/db";
    const root = fixture({
      [`${dir}/Application.yaml`]: app(dir, "cluster.yaml"),
      [`${dir}/cluster.yaml`]: cluster("  bootstrap: { recovery: { source: x } }\n"),
    });
    expect(collectCnpgClusters(root).map((c) => c.appSecret)).toEqual([null]);
  });
});
