// Zeta schema-codegen — TypeScript leg.
//
// Emits a TypeScript `interface` from the SAME language-neutral TypeSchema IR that the C#
// `SchemaCodegen` and Rust `RustSchemaCodegen` consume — the third oracle in "one IR, a typed
// surface per language." The schema's `csType` field carries the neutral (C#-baseline) type
// vocabulary; this leg maps it to TS idioms: camelCase field names, `T | null` for nullable,
// `bigint` for 64-bit ints, and a PascalCase interface name. Pure + deterministic (explicit
// `\n` line endings → byte-lockable).
const TS_TYPES = {
    string: "string",
    int: "number",
    "int?": "number | null",
    long: "bigint",
    "long?": "bigint | null",
    bool: "boolean",
    "bool?": "boolean | null",
    double: "number",
    "double?": "number | null",
};
/**
 * Parse a shared `.zetaschema.json` IR file (the single source of truth all codegen legs read:
 * C#, Rust, this TS leg, and the Roslyn generator). Validates the structure and narrows the
 * `unknown` JSON to a {@link TypeSchema}.
 */
export function loadSchema(json) {
    const raw = JSON.parse(json);
    if (typeof raw !== "object" || raw === null) {
        throw new Error("zetaschema: root must be an object");
    }
    const obj = raw;
    const namespace = obj["namespace"];
    const typeName = obj["typeName"];
    const fieldsRaw = obj["fields"];
    if (typeof namespace !== "string" || typeof typeName !== "string" || !Array.isArray(fieldsRaw)) {
        throw new Error("zetaschema: missing or malformed namespace/typeName/fields");
    }
    const fields = fieldsRaw.map((f) => {
        if (typeof f !== "object" || f === null) {
            throw new Error("zetaschema: each field must be an object");
        }
        const fo = f;
        const name = fo["name"];
        const csType = fo["csType"];
        if (typeof name !== "string" || typeof csType !== "string") {
            throw new Error("zetaschema: each field needs string name + csType");
        }
        return { name, csType };
    });
    return { namespace, typeName, fields };
}
/** PascalCase identifier to camelCase (e.g. `BirthYear` → `birthYear`, `Nconst` → `nconst`). */
function toCamelCase(name) {
    if (name.length === 0) {
        return name;
    }
    return name[0].toLowerCase() + name.slice(1);
}
/** Generate a TypeScript `interface` declaration for the schema's type. */
export function generate(schema) {
    const lines = [
        "// @generated by zeta schema-codegen (TypeScript leg) from a zeta type schema. Do not edit.",
        `export interface ${schema.typeName} {`,
    ];
    for (const field of schema.fields) {
        const tsType = TS_TYPES[field.csType];
        if (tsType === undefined) {
            throw new Error(`No TypeScript mapping for type token '${field.csType}' (field '${field.name}'). Extend TS_TYPES.`);
        }
        lines.push(`  ${toCamelCase(field.name)}: ${tsType};`);
    }
    lines.push("}");
    return lines.join("\n") + "\n";
}
