import { test, expect } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { generate, loadSchema, type TypeSchema } from "./schema-codegen";

// Shared single-source IR: the TS leg reads the SAME committed schemas/imdb/*.zetaschema.json
// that the C# / Rust / Roslyn legs read. One file, every oracle.
const sharedImdbNamePath = join(import.meta.dir, "../../../schemas/imdb/name-basics.zetaschema.json");

test("loads the shared committed .zetaschema.json and generates the real IMDb interface", () => {
  const schema = loadSchema(readFileSync(sharedImdbNamePath, "utf8"));
  expect(schema.typeName).toBe("ImdbName");
  const ts = generate(schema);
  expect(ts).toContain("export interface ImdbName {");
  expect(ts).toContain("nconst: string;");
  expect(ts).toContain("birthYear: number | null;");
  expect(ts).toContain("knownForTitles: string;");
});

test("loadSchema rejects a malformed schema", () => {
  expect(() => loadSchema('{ "namespace": "X", "typeName": "Y" }')).toThrow();
});

// TypeScript leg of "one IR, a typed surface per oracle": the SAME TypeSchema the C#
// SchemaCodegen renders to a record and the Rust RustSchemaCodegen renders to a struct
// renders here to a TS interface — with TS idioms (camelCase fields, `T | null`).

const imdbName: TypeSchema = {
  namespace: "Zeta.Generated",
  typeName: "ImdbName",
  fields: [
    { name: "Nconst", csType: "string" },
    { name: "PrimaryName", csType: "string" },
    { name: "BirthYear", csType: "int?" },
    { name: "DeathYear", csType: "int?" },
  ],
};

test("generates the expected TypeScript interface", () => {
  const expected =
    "// @generated by zeta schema-codegen (TypeScript leg) from a zeta type schema. Do not edit.\n" +
    "export interface ImdbName {\n" +
    "  nconst: string;\n" +
    "  primaryName: string;\n" +
    "  birthYear: number | null;\n" +
    "  deathYear: number | null;\n" +
    "}\n";
  expect(generate(imdbName)).toBe(expected);
});

test("is deterministic", () => {
  expect(generate(imdbName)).toBe(generate(imdbName));
});

test("maps nullable to `| null` and camelCases the field", () => {
  const schema: TypeSchema = {
    namespace: "Zeta.Generated",
    typeName: "Title",
    fields: [{ name: "StartYear", csType: "int?" }],
  };
  expect(generate(schema)).toContain("startYear: number | null;");
});

test("maps long to bigint (precision-preserving for i64)", () => {
  const schema: TypeSchema = {
    namespace: "Zeta.Generated",
    typeName: "Counter",
    fields: [{ name: "Total", csType: "long" }],
  };
  expect(generate(schema)).toContain("total: bigint;");
});

test("throws on an unknown type token", () => {
  const schema: TypeSchema = {
    namespace: "Zeta.Generated",
    typeName: "Bad",
    fields: [{ name: "X", csType: "decimal" }],
  };
  expect(() => generate(schema)).toThrow();
});
