// Zeta schema-codegen — TypeScript leg.
//
// Emits a TypeScript `interface` from the SAME language-neutral TypeSchema IR that the C#
// `SchemaCodegen` and Rust `RustSchemaCodegen` consume — the third oracle in "one IR, a typed
// surface per language." The schema's `csType` field carries the neutral (C#-baseline) type
// vocabulary; this leg maps it to TS idioms: camelCase field names, `T | null` for nullable,
// `bigint` for 64-bit ints, and a PascalCase interface name. Pure + deterministic (explicit
// `\n` line endings → byte-lockable).

/** One field in a {@link TypeSchema}: a name and a neutral (C#-baseline) type token. */
export interface SchemaField {
  readonly name: string;
  /** Neutral type token: string | int | int? | long | long? | bool | bool? | double | double?. */
  readonly csType: string;
}

/** A zeta type schema (IR) — the same shape the C#/Rust legs and the `.zetaschema.json` consume. */
export interface TypeSchema {
  readonly namespace: string;
  readonly typeName: string;
  readonly fields: readonly SchemaField[];
}

const TS_TYPES: Readonly<Record<string, string>> = {
  string: "string",
  int: "number",
  "int?": "number | null",
  long: "bigint",
  "long?": "bigint | null",
  bool: "boolean",
  "bool?": "boolean | null",
  double: "number",
  "double?": "number | null",
};

/** PascalCase identifier to camelCase (e.g. `BirthYear` → `birthYear`, `Nconst` → `nconst`). */
function toCamelCase(name: string): string {
  if (name.length === 0) {
    return name;
  }
  return name[0]!.toLowerCase() + name.slice(1);
}

/** Generate a TypeScript `interface` declaration for the schema's type. */
export function generate(schema: TypeSchema): string {
  const lines: string[] = [
    "// @generated by zeta schema-codegen (TypeScript leg) from a zeta type schema. Do not edit.",
    `export interface ${schema.typeName} {`,
  ];

  for (const field of schema.fields) {
    const tsType = TS_TYPES[field.csType];
    if (tsType === undefined) {
      throw new Error(
        `No TypeScript mapping for type token '${field.csType}' (field '${field.name}'). Extend TS_TYPES.`,
      );
    }
    lines.push(`  ${toCamelCase(field.name)}: ${tsType};`);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}
