#!/usr/bin/env bun
/**
 * memory-migrator.ts
 * 
 * Autonomous background loop tool to migrate user-scope memory
 * (~/.claude/projects/[slug]/memory/) into the in-repo git-memory (docs/memory/).
 * 
 * Uses Cartography principles: navigates local paths and creates PRs
 * automatically with the active persona's git identity.
 */

import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, cpSync, mkdtempSync, rmSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { homedir, tmpdir } from "node:os";

// We try to import persona-registry; if it fails due to paths, we mock it.
let getPersona: any;
try {
  const registry = require("../service/persona-registry");
  getPersona = registry.getPersona;
} catch {
  getPersona = (_name: string) => null;
}

function run(cmd: string, args: readonly string[], cwd?: string) {
  const r = spawnSync(cmd, args as string[], { cwd, encoding: "utf8" });
  return { ok: r.status === 0, stdout: r.stdout ?? "", stderr: r.stderr ?? "" };
}

function isoUtcTimestamp() {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth() + 1)}${pad(d.getUTCDate())}-${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}`;
}

function main() {
  const claudeProjects = join(homedir(), ".claude", "projects");
  if (!existsSync(claudeProjects)) {
    console.log(`memory-migrator: no ${claudeProjects} found.`);
    return 0;
  }

  // Find all projects with a memory folder
  const projects = readdirSync(claudeProjects, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => join(claudeProjects, d.name, "memory"))
    .filter(p => existsSync(p));

  if (projects.length === 0) {
    console.log("memory-migrator: no memory folders found.");
    return 0;
  }

  // Create worktree
  const wt = mkdtempSync(join(tmpdir(), "zeta-mem-migrator-"));
  run("git", ["fetch", "origin", "main"]);
  run("git", ["worktree", "add", wt, "origin/main"]);

  const branch = `migrate/memory-${isoUtcTimestamp()}`;
  run("git", ["switch", "-c", branch, "origin/main"], wt);

  let changes = false;
  const targetMemoryDir = join(wt, "docs", "memory");
  if (!existsSync(targetMemoryDir)) {
      mkdirSync(targetMemoryDir, { recursive: true });
  }

  // Copy memory files
  for (const src of projects) {
    console.log(`memory-migrator: auditing ${src}...`);
    cpSync(src, targetMemoryDir, { recursive: true, force: true });
    // Quick diff check
    const status = run("git", ["status", "--porcelain"], wt);
    if (status.stdout.trim().length > 0) {
      changes = true;
    }
  }

  if (!changes) {
    console.log("memory-migrator: no substantive substrate changes.");
    run("git", ["worktree", "remove", "--force", wt]);
    rmSync(wt, { recursive: true, force: true });
    return 0;
  }

  // Commit
  run("git", ["add", "docs/memory/"], wt);

  let authorFlag = null;
  const activePersonaName = process.env.ZETA_PERSONA;
  if (activePersonaName) {
    const p = getPersona(activePersonaName);
    if (p && p.gitAuthorName && p.gitAuthorEmail) {
      authorFlag = `--author=${p.gitAuthorName} <${p.gitAuthorEmail}>`;
    }
  }

  const commitMsg = `docs(memory): sync local user-scope memory substrate to git\n\nGenerated by memory-migrator.ts loop.\nCo-Authored-By: Zeta Universal Grammar <noreply@zeta.lucent-financial-group.com>`;
  const commitArgs = ["commit", "-m", commitMsg];
  if (authorFlag) commitArgs.push(authorFlag);

  run("git", commitArgs, wt);
  run("git", ["push", "-u", "origin", branch], wt);

  const prCreate = run("gh", ["pr", "create", "--head", branch, "--base", "main", "--title", "docs(memory): sync local user-scope memory to git", "--body", "Automated sync of \`~/.claude/projects/*/memory/\` to \`docs/memory/\`."], wt);
  console.log(`memory-migrator: PR created: ${prCreate.stdout}`);

  run("git", ["worktree", "remove", "--force", wt]);
  rmSync(wt, { recursive: true, force: true });
  return 0;
}

if (import.meta.main) {
  process.exit(main());
}
