-- ============================================================================
-- inventory · Phase 1 · Schema + RLS + audit trigger
-- File: inventory/db/0001_phase1_schema_rls_audit.sql
--
-- HOW TO APPLY (owner-run; no service_role / secret key needed):
--   Supabase Dashboard → SQL Editor → New query → paste this whole file → Run.
--
-- SAFETY: the entire migration is wrapped in a single transaction (BEGIN/COMMIT).
-- Postgres DDL is transactional, so if ANY statement fails, NOTHING is applied
-- (all-or-nothing) — you can fix and re-run with no half-built state.
-- If you run it twice after success you'll get an "already exists" error; that
-- is harmless (it just means it's already applied) and the tx rolls back.
--
-- Role mechanism: Option 1 (approved) — role lives in public.profiles and is
-- read by BOTH the UI and RLS via the SECURITY DEFINER function
-- public.current_user_role(). One source of truth; no JWT-claim staleness.
-- ============================================================================

begin;

-- ── 1. Enums ────────────────────────────────────────────────────────────────
create type public.app_role as enum ('viewer', 'editor', 'admin');

create type public.item_status as enum (
  'Active/In Use', 'In Storage', 'Needs Attention', 'In Repair',
  'Retired(Archived)', 'Disposed', 'Missing'
);

-- ── 2. Tables ───────────────────────────────────────────────────────────────
create table public.profiles (
  user_id      uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role         public.app_role not null default 'viewer',   -- least privilege default
  created_at   timestamptz not null default now()
);

create table public.items (
  id                 bigint primary key generated by default as identity, -- stable, never renumbered
  name               text not null,
  brand              text,
  model_pn           text,
  qty                integer not null default 0,
  device_type        text,
  category           text,
  status             public.item_status not null default 'In Storage',
  location           text,
  assignment_purpose text,
  notes              text,
  value              numeric(12,2),
  serial             text,
  is_archived        boolean not null default false,
  custom_fields      jsonb not null default '{}'::jsonb,
  version            integer not null default 1,            -- optimistic locking (Phase 4)
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now()
);
create index items_custom_fields_gin on public.items using gin (custom_fields);

create table public.field_definitions (
  key        text primary key,
  label      text not null,
  type       text not null check (type in ('text','number','date','dropdown','boolean')),
  options    text[] not null default '{}',
  required   boolean not null default false,
  is_active  boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.change_log (
  id        bigint primary key generated always as identity,
  item_id   bigint references public.items(id),            -- RESTRICT: history can't be silently destroyed
  actor     uuid,                                          -- bare uuid (not FK) so audit survives user deletion
  action    text not null,
  field     text,
  old_value text,
  new_value text,
  ts        timestamptz not null default now()             -- UTC
);
create index change_log_item_id_idx on public.change_log(item_id);

-- ── 3. Role single-source function (SECURITY DEFINER avoids RLS recursion) ───
-- Returns ONLY the caller's own role; search_path locked to block hijacking.
create or replace function public.current_user_role()
returns public.app_role
language sql
stable
security definer
set search_path = ''
as $$
  select role from public.profiles where user_id = auth.uid()
$$;

-- ── 4. Enable RLS (default-deny: no policy => no access) ─────────────────────
alter table public.profiles          enable row level security;
alter table public.items             enable row level security;
alter table public.field_definitions enable row level security;
alter table public.change_log        enable row level security;

-- ── 5. Policies — least privilege, per-role AND per-operation, NO USING(true) ─

-- profiles: self-read OR admin; role management = admin only
create policy profiles_select_self_or_admin on public.profiles
  for select to authenticated
  using (user_id = auth.uid() or public.current_user_role() = 'admin');
create policy profiles_admin_insert on public.profiles
  for insert to authenticated
  with check (public.current_user_role() = 'admin');
create policy profiles_admin_update on public.profiles
  for update to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');
create policy profiles_admin_delete on public.profiles
  for delete to authenticated
  using (public.current_user_role() = 'admin');

-- items: read = any authenticated; write = editor/admin; NO delete (archive only)
create policy items_select_auth on public.items
  for select to authenticated
  using (auth.uid() is not null);
create policy items_insert_editor_admin on public.items
  for insert to authenticated
  with check (public.current_user_role() in ('editor','admin'));
create policy items_update_editor_admin on public.items
  for update to authenticated
  using (public.current_user_role() in ('editor','admin'))
  with check (public.current_user_role() in ('editor','admin'));

-- field_definitions: read = authenticated; write = admin only
create policy fd_select_auth on public.field_definitions
  for select to authenticated
  using (auth.uid() is not null);
create policy fd_admin_insert on public.field_definitions
  for insert to authenticated
  with check (public.current_user_role() = 'admin');
create policy fd_admin_update on public.field_definitions
  for update to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');
create policy fd_admin_delete on public.field_definitions
  for delete to authenticated
  using (public.current_user_role() = 'admin');

-- change_log: SELECT for editor/admin only (viewer NOT). NO insert/update/delete
-- policies at all -> clients cannot write it; the SECURITY DEFINER trigger does.
create policy change_log_select_editor_admin on public.change_log
  for select to authenticated
  using (public.current_user_role() in ('editor','admin'));

-- ── 6. Audit trigger: writes who/what/when (field-level before->after) ───────
create or replace function public.log_item_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  k    text;
  oldj jsonb;
  newj jsonb;
begin
  if tg_op = 'INSERT' then
    insert into public.change_log(item_id, actor, action)
    values (new.id, auth.uid(), 'INSERT');
    return new;
  elsif tg_op = 'UPDATE' then
    oldj := to_jsonb(old);
    newj := to_jsonb(new);
    for k in select jsonb_object_keys(newj) loop
      if k not in ('updated_at','version') and (oldj -> k) is distinct from (newj -> k) then
        insert into public.change_log(item_id, actor, action, field, old_value, new_value)
        values (new.id, auth.uid(), 'UPDATE', k, oldj ->> k, newj ->> k);
      end if;
    end loop;
    return new;
  end if;
  return null;
end
$$;
create trigger items_audit
  after insert or update on public.items
  for each row execute function public.log_item_change();

-- ── 7. updated_at + version bump (scaffolds Phase 4 optimistic locking) ──────
create or replace function public.touch_item()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  new.version := old.version + 1;
  return new;
end
$$;
create trigger items_touch
  before update on public.items
  for each row execute function public.touch_item();

-- ── 8. Immutability guard on change_log (raises even for privileged contexts) ─
create or replace function public.block_change_log_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception 'change_log is append-only and immutable (% blocked)', tg_op;
end
$$;
create trigger change_log_no_update
  before update on public.change_log
  for each row execute function public.block_change_log_mutation();
create trigger change_log_no_delete
  before delete on public.change_log
  for each row execute function public.block_change_log_mutation();

commit;
