namespace Zeta.Core

open System.Collections.Generic

/// **`E8LieAlgebra` — rung 4 of the chain: the 248-dimensional Lie algebra `e₈`, GENERATED from the
/// root system rather than tabulated.**
///
/// The chain this module continues, and where it stood before this file existed:
///
/// | rung | object | in-tree before this module |
/// |---|---|---|
/// | 1 | `[8,4,4]` extended Hamming code — doubly-even, self-dual | `AdinkraCode` — proven exhaustively |
/// | 2 | Construction A lattice `L_A(C)` (Conway–Sloane, *SPLAG* ch. 5) | `E8Lattice`, `ConstructionATheta` |
/// | 3 | root system: 240 minimal vectors, simple system, W(E8) as versors | `E8Lattice.roots`, `CliffordE8Roots` |
/// | **4** | **the Lie algebra `e₈`, `dim = 248`** | **NOTHING — only the integer tuple `(8, 240)` in `CliffordPeriodicity`** |
/// | 5 | the compact Lie group E8 | nothing (see `compactFormKillingDiagonal` for what is honestly reachable) |
///
/// **248 IS NOT A MEASUREMENT.** `dim g = |Φ| + rank = 240 + 8 = 248` is true *by construction* — the
/// basis is literally one vector per root plus one per Cartan direction, so a "check" that the
/// dimension is 248 is counting the basis you just wrote down. It cannot fail and is therefore not
/// evidence (`.claude/rules/numerology-vs-number-theory.md`). The dimension is recorded here as a
/// definition. **What is measured** — every one of these can fail, and each fails under a sign error:
///
///   • **Jacobi** on all `C(248,3)` unordered basis triples. This is the falsifier for the structure
///     constants; the classical failure mode for `e₈` is an inconsistent sign choice, and an
///     inconsistent choice breaks Jacobi and nothing else.
///   • **Serre relations** — `[hᵢ,hⱼ]=0`, `[eᵢ,fⱼ]=δᵢⱼhᵢ`, `[hᵢ,eⱼ]=aⱼᵢeⱼ`, `ad(eᵢ)^{1−aᵢⱼ}(eⱼ)=0`.
///   • **Generation** — the subalgebra generated by the 24 Chevalley generators `{eᵢ,fᵢ,hᵢ}` is the
///     whole 248 dimensions. Without this, "Chevalley–Serre presentation" is a label on a basis.
///   • **Killing form** `κ(x,y) = tr(ad x ∘ ad y)`, computed from the structure constants, never
///     from a formula: its block structure, its nondegeneracy (Cartan's criterion ⇒ semisimple),
///     and `κ|_h = 60·A`, which *derives* the dual Coxeter number `h^∨ = 30`.
///
/// **The sign rule is derived, not tabulated.** Structure constants come from an asymmetry function
/// `ε(α,β) = (−1)^{B(α,β)}` where `B` is a ℤ/2-bilinear form on the root lattice satisfying
/// `B(α,α) ≡ ⟨α,α⟩/2 (mod 2)`. `B` is written down on the simple roots from the Cartan matrix alone
/// and extended bimultiplicatively — so the 240×240 table of signs is a *consequence* of the Dynkin
/// diagram, not 57 600 tabulated numbers. (Frenkel–Kac 1980; Kac, *Infinite Dimensional Lie
/// Algebras* §7.8; Chevalley 1955 for the integral basis.)
///
/// **What identifies this algebra as `e₈` and not something else with the same dimension.** A count
/// never identifies (`numerology-vs-number-theory`). 248 is shared by no other *simple* Lie algebra,
/// but a *semisimple* algebra could reach 248 as a sum, so the count alone excludes nothing. The
/// identification is:
///
///   1. `κ` nondegenerate ⇒ **semisimple** (Cartan's criterion).
///   2. the Dynkin diagram of the derived simple system is **connected** ⇒ the root system is
///      irreducible ⇒ the algebra is **simple**, not a sum.
///   3. **rank 8** (the Cartan subalgebra is 8-dimensional, and `det A = 1` pins the lattice).
///   4. simple + rank 8 + dim 248 ⇒ `e₈` **uniquely**: the rank-8 simple algebras are
///      `A₈`(80), `B₈`(136), `C₈`(136), `D₈`(120), `E₈`(248), and only one of those is 248.
///
///   Step 4 is Killing–Cartan: simple Lie algebras are classified by their Dynkin diagram — by
///   *structure*, never by dimension. The dimension is the last step, and it is only allowed to
///   speak after simplicity and rank have been established.
///
/// Anchors (checked, not merely cited — `.claude/rules/anchor-to-human-prior-art.md`):
///   • **C. Chevalley**, *Sur certains groupes simples* (Tôhoku Math. J. 1955) — the integral basis
///     with structure constants `±1` for simply-laced types, which is what makes every computation
///     in this file exact integer arithmetic (byte-lockable, DST-replayable).
///   • **J.-P. Serre** — the presentation by generators and relations that `serreRelations` checks.
///   • **I. Frenkel & V. Kac**, *Basic representations of affine Lie algebras and dual resonance
///     models* (Invent. Math. 62, 1980) — the ε-cocycle used here for the signs.
///   • **W. Killing / É. Cartan** — the classification; the reason step 4 above is legitimate.
///   • **Conway & Sloane**, *SPLAG* ch. 5 — Construction A, the rung this one stands on.
[<RequireQualifiedAccess>]
module E8LieAlgebra =

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §0  The root system, inherited from rung 3 (NOT re-derived here)
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// The 240 roots, in the ambient integer frame of `E8Lattice` (Construction A scale: `‖α‖² = 4`).
    let roots : int[][] = E8Lattice.roots |> List.toArray

    /// `|Φ| = 240`.
    let rootCount = roots.Length

    /// The rank — the dimension of the Cartan subalgebra.
    let rank = 8

    /// `dim g = |Φ| + rank`. **Definitional, not measured** — see the module header.
    let dimension = rootCount + rank

    /// The **normalised** inner product `⟨·,·⟩`, on which roots have norm 2. `E8Lattice` works at the
    /// Construction-A scale where `α·α = 4`; the Lie theory wants `⟨α,α⟩ = 2`, i.e. the `1/√2`
    /// rescaling that turns `L_A(C)` into the E8 lattice proper. The halving is exact on the whole
    /// lattice: `x·y ≡ |supp(x mod 2) ∩ supp(y mod 2)| ≡ 0 (mod 2)` because the code is self-dual, so
    /// every pair of codewords is orthogonal over GF(2). Self-duality is doing real work here, not
    /// decoration.
    let ip (a: int[]) (b: int[]) : int = (Array.fold2 (fun s x y -> s + x * y) 0 a b) / 2

    // ── root indexing ───────────────────────────────────────────────────────────────────────────
    // Every root coordinate lies in {-2,-1,0,1,2}, so a base-5 pack is a perfect hash.

    let private packKey (x: int[]) : int =
        let mutable k = 0
        for i in 0 .. rank - 1 do
            k <- k * 5 + (x.[i] + 2)
        k

    let private rootIndexTable : int[] =
        let t = Array.create 390625 -1
        roots |> Array.iteri (fun i r -> t.[packKey r] <- i)
        t

    /// Index of a root in `roots`, or `-1` if the vector is not a root. Total; no exceptions.
    let rootIndex (x: int[]) : int =
        if x.Length <> rank then -1
        else
            let mutable ok = true
            for i in 0 .. rank - 1 do
                if x.[i] < -2 || x.[i] > 2 then ok <- false
            if not ok then -1 else rootIndexTable.[packKey x]

    /// Index of `−α` given the index of `α`.
    let negIndex : int[] =
        Array.init rootCount (fun i -> rootIndex (roots.[i] |> Array.map (fun v -> -v)))

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §1  Simple system, Cartan matrix, and simple-root coordinates
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// The simple system, inherited from `CliffordE8Roots` (derived there by Cartan-matrix search
    /// over `E8Lattice.roots`, not hardcoded).
    let simpleRoots : int[][] = CliffordE8Roots.simpleSystem |> List.toArray

    /// The Cartan matrix `Aᵢⱼ = ⟨αᵢ, αⱼ^∨⟩`. Simply-laced, so `αᵢ^∨ = αᵢ` under `⟨·,·⟩` and
    /// `A` is symmetric with 2 on the diagonal and 0/−1 off it.
    let cartanMatrix : int[][] =
        Array.init rank (fun i -> Array.init rank (fun j -> ip simpleRoots.[i] simpleRoots.[j]))

    /// Exact integer determinant by Bareiss fraction-free elimination (no floats, no division that
    /// is not exact).
    let private bareissDet (m: int64[][]) : int64 =
        let n = m.Length
        let a = m |> Array.map Array.copy
        let mutable sign = 1L
        let mutable prev = 1L
        let mutable zero = false
        for k in 0 .. n - 2 do
            if not zero then
                if a.[k].[k] = 0L then
                    let mutable swap = -1
                    for i in k + 1 .. n - 1 do
                        if swap < 0 && a.[i].[k] <> 0L then swap <- i
                    if swap < 0 then zero <- true
                    else
                        let t = a.[k]
                        a.[k] <- a.[swap]
                        a.[swap] <- t
                        sign <- -sign
                if not zero then
                    for i in k + 1 .. n - 1 do
                        for j in k + 1 .. n - 1 do
                            a.[i].[j] <- (a.[i].[j] * a.[k].[k] - a.[i].[k] * a.[k].[j]) / prev
                    prev <- a.[k].[k]
        if zero then 0L else sign * a.[n - 1].[n - 1]

    /// `det A`. For E8 this is **1**, and that single integer carries two facts: the root lattice
    /// equals the weight lattice (so the group has trivial centre and is simultaneously simply
    /// connected and adjoint), and `A⁻¹` is an **integer** matrix — which is why `simpleCoords`
    /// below needs no rational arithmetic.
    let cartanDeterminant : int =
        int (bareissDet (cartanMatrix |> Array.map (Array.map int64)))

    /// `A⁻¹`, exactly, via the adjugate. Integral because `det A = 1`.
    let cartanInverse : int[][] =
        let n = rank
        let d = int64 cartanDeterminant
        Array.init n (fun i ->
            Array.init n (fun j ->
                // adj(A)_{ij} = cofactor C_{ji} = (-1)^{i+j} * minor_{ji}
                let minor =
                    [| for r in 0 .. n - 1 do
                         if r <> j then
                             yield [| for c in 0 .. n - 1 do
                                        if c <> i then yield int64 cartanMatrix.[r].[c] |] |]
                let sgn = if (i + j) % 2 = 0 then 1L else -1L
                int (sgn * bareissDet minor / d)))

    /// A root's coordinates in the simple-root basis. `vᵢ = ⟨α, αᵢ⟩` gives `v = A c`, so `c = A⁻¹ v`
    /// — integral, exact, no floats.
    let simpleCoords (alpha: int[]) : int[] =
        let v = Array.init rank (fun i -> ip alpha simpleRoots.[i])
        Array.init rank (fun i ->
            let mutable s = 0
            for j in 0 .. rank - 1 do
                s <- s + cartanInverse.[i].[j] * v.[j]
            s)

    /// Simple-root coordinates of every root, precomputed.
    let rootCoords : int[][] = roots |> Array.map simpleCoords

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §2  The asymmetry function ε — the SIGN RULE, derived from the Cartan matrix
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// The ℤ/2-bilinear form `B` on the root lattice, in simple-root coordinates:
    ///
    ///     B(a,b) = Σᵢ aᵢbᵢ + Σ_{i>j} aᵢbⱼ·Aᵢⱼ   (mod 2)
    ///
    /// The one property that matters is `B(α,α) ≡ ⟨α,α⟩/2 (mod 2)`, and it holds identically:
    /// `⟨α,α⟩/2 = Σᵢ aᵢ² + Σ_{i>j} aᵢaⱼAᵢⱼ`, whose reduction mod 2 is exactly `B(a,a)`. The diagonal
    /// term is `Aᵢᵢ/2 = 1` and the off-diagonal terms are `Aᵢⱼ mod 2`, which is 1 precisely on the
    /// **edges of the Dynkin diagram**. So the sign rule is a function of the diagram — nothing is
    /// tabulated.
    let bilinearMod2 (a: int[]) (b: int[]) : int =
        let mutable s = 0
        for i in 0 .. rank - 1 do
            s <- s + a.[i] * b.[i]
            for j in 0 .. i - 1 do
                s <- s + a.[i] * b.[j] * cartanMatrix.[i].[j]
        ((s % 2) + 2) % 2

    /// `ε(α,β) = (−1)^{B(α,β)} ∈ {+1,−1}` — bimultiplicative by construction, with
    /// `ε(α,α) = (−1)^{⟨α,α⟩/2} = −1` on roots. That single identity is what forces
    /// `ε(α,β)ε(β,α) = (−1)^{⟨α,β⟩}`, which is the compatibility Jacobi needs.
    let epsilonCoords (a: int[]) (b: int[]) : int =
        if bilinearMod2 a b = 0 then 1 else -1

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §3  The Chevalley basis and the bracket
    // ═══════════════════════════════════════════════════════════════════════════════════════════
    //
    // Basis indices:  0 .. 239  →  e_α  (α = roots.[i])
    //                240 .. 247 →  h_i  (= αᵢ^∨, the simple coroots)
    //
    // Brackets:
    //   [hᵢ, hⱼ] = 0
    //   [hᵢ, e_α] = ⟨α, αᵢ^∨⟩ e_α = ⟨α, αᵢ⟩ e_α
    //   [e_α, e_{−α}] = h_α  (= Σ cᵢ hᵢ where c = simpleCoords α)
    //   [e_α, e_β] = ε(α,β) e_{α+β}   when α+β ∈ Φ  (⟺ ⟨α,β⟩ = −1, simply-laced)
    //   [e_α, e_β] = 0                when α+β ∉ Φ ∪ {0}
    //
    // Nothing above is asserted to be right. `jacobiViolations` is the check, and
    // `jacobiViolationsWithSignFlip` is the control that proves the check can fail.

    /// Basis index of `h_i`.
    let cartanBasisIndex (i: int) : int = rootCount + i

    /// `[bᵢ, bⱼ]` as a sparse list of `(basis index, integer coefficient)`. Precomputed for all
    /// 248² ordered pairs; the table is the module's single source of structure constants.
    let private bracketTable : (int * int)[][] =
        let t = Array.zeroCreate (dimension * dimension)
        // [h_i, h_j] = 0
        for i in 0 .. rank - 1 do
            for j in 0 .. rank - 1 do
                t.[(cartanBasisIndex i) * dimension + (cartanBasisIndex j)] <- [||]
        // [h_i, e_a] and [e_a, h_i]
        for i in 0 .. rank - 1 do
            for a in 0 .. rootCount - 1 do
                let c = ip roots.[a] simpleRoots.[i]
                let hi = cartanBasisIndex i
                t.[hi * dimension + a] <- if c = 0 then [||] else [| (a, c) |]
                t.[a * dimension + hi] <- if c = 0 then [||] else [| (a, -c) |]
        // [e_a, e_b]
        for a in 0 .. rootCount - 1 do
            for b in 0 .. rootCount - 1 do
                let entry =
                    if negIndex.[a] = b then
                        // −h_α, in the simple-coroot basis. THE MINUS IS NOT A CONVENTION CHOICE —
                        // it is forced, and Jacobi is what forced it. With `ε` fixed as above,
                        // Jacobi on the triple `(e_α, e_{−α}, e_γ)` reads
                        //   τ·⟨α,γ⟩ + ε(−α,γ)·ε(γ−α,α) = 0
                        // and bimultiplicativity gives ε(−α,γ)ε(γ−α,α) = −ε(α,γ)ε(γ,α)
                        //   = −(−1)^{⟨α,γ⟩} = +1 when ⟨α,γ⟩ = 1. Hence τ = −1.
                        // `+h_α` was tried first (it is what most write-ups of the Frenkel–Kac
                        // bracket appear to say) and produced 13 440 violating triples out of
                        // 2 532 596 — a 0.53% failure rate, which is exactly why a spot check
                        // would have missed it and the full sweep did not.
                        // The cost is one relabeling: the Chevalley generator is `fᵢ = −e_{−αᵢ}`,
                        // so that `[eᵢ, fᵢ] = +hᵢ` in the standard presentation. That rescaling is
                        // inside ε's own sign freedom and changes no invariant.
                        rootCoords.[a]
                        |> Array.mapi (fun i c -> (cartanBasisIndex i, -c))
                        |> Array.filter (fun (_, c) -> c <> 0)
                    else
                        let sum = Array.init rank (fun k -> roots.[a].[k] + roots.[b].[k])
                        let s = rootIndex sum
                        if s < 0 then [||]
                        else [| (s, epsilonCoords rootCoords.[a] rootCoords.[b]) |]
                t.[a * dimension + b] <- entry
        t

    /// `[bᵢ, bⱼ]` — the bracket of two basis elements, sparse.
    let bracket (i: int) (j: int) : (int * int)[] = bracketTable.[i * dimension + j]

    /// The Chevalley generators. `eᵢ = e_{αᵢ}` and `hᵢ` are basis elements; **`fᵢ = −e_{−αᵢ}`** —
    /// the basis index is `chevalleyF.[i]` and the scalar is `chevalleyFSign`. See the `−h_α` note
    /// in `bracketTable` for why the sign lives here.
    let chevalleyE : int[] = Array.init rank (fun i -> rootIndex simpleRoots.[i])
    let chevalleyF : int[] = Array.init rank (fun i -> negIndex.[chevalleyE.[i]])
    let chevalleyH : int[] = Array.init rank cartanBasisIndex

    /// The scalar on `fᵢ` relative to the basis vector `e_{−αᵢ}`.
    [<Literal>]
    let chevalleyFSign = -1

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §4  Jacobi — the falsifier for the structure constants
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// Counts basis triples `i < j < k` violating `[[bᵢ,bⱼ],b_k] + [[bⱼ,b_k],bᵢ] + [[b_k,bᵢ],bⱼ] = 0`,
    /// under an arbitrary bracket table. Parameterised so a **mutated** table can be fed in and shown
    /// to fail — a Jacobi check that only ever runs against the real table is a check that has not
    /// been shown to be able to fail.
    ///
    /// Antisymmetry `[x,y] = −[y,x]` makes Jacobi invariant under permutation of the triple and
    /// vacuous when two indices coincide, so `i < j < k` is the complete set of distinct constraints:
    /// `C(248,3) = 2 532 596`.
    let jacobiViolationsOf (br: int -> int -> (int * int)[]) : int =
        let n = dimension
        let acc = Array.zeroCreate<int64> n
        let touched = Array.zeroCreate<int> (3 * n)
        let tcount = Array.zeroCreate<int> 1
        let mutable violations = 0
        // [[x,y],z] accumulated into acc; `tcount.[0]` is the count of dirtied acc slots
        let addTriple (x: int) (y: int) (z: int) =
            for (u, cu) in br x y do
                for (v, cv) in br u z do
                    if acc.[v] = 0L then
                        touched.[tcount.[0]] <- v
                        tcount.[0] <- tcount.[0] + 1
                    acc.[v] <- acc.[v] + int64 cu * int64 cv
        for i in 0 .. n - 1 do
            for j in i + 1 .. n - 1 do
                for k in j + 1 .. n - 1 do
                    tcount.[0] <- 0
                    addTriple i j k
                    addTriple j k i
                    addTriple k i j
                    let mutable bad = false
                    for t in 0 .. tcount.[0] - 1 do
                        let v = touched.[t]
                        if acc.[v] <> 0L then bad <- true
                        acc.[v] <- 0L
                    if bad then violations <- violations + 1
        violations

    /// Jacobi violations of the real bracket. **Must be 0.**
    let jacobiViolations () : int = jacobiViolationsOf bracket

    /// **Mutation control.** The same sweep against a table in which the structure constant of one
    /// single pair `[e_{α₀}, e_{β₀}]` has its sign flipped — the exact classical failure mode
    /// (an inconsistent ε choice). If this returns 0, `jacobiViolations` is vacuous.
    let jacobiViolationsWithSignFlip (a: int) (b: int) : int =
        let mutated i j =
            let orig = bracket i j
            if (i = a && j = b) || (i = b && j = a) then orig |> Array.map (fun (u, c) -> (u, -c))
            else orig
        jacobiViolationsOf mutated

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §5  Serre relations, and generation
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// A dense element of `g` (length `dimension`, integer coefficients).
    type Elt = int[]

    let private zeroElt () : Elt = Array.zeroCreate dimension

    let private basisElt (i: int) : Elt =
        let e = zeroElt ()
        e.[i] <- 1
        e

    /// `[x, y]` for dense elements, bilinear over the basis table.
    let bracketElt (x: Elt) (y: Elt) : Elt =
        let r = zeroElt ()
        for i in 0 .. dimension - 1 do
            if x.[i] <> 0 then
                for j in 0 .. dimension - 1 do
                    if y.[j] <> 0 then
                        for (u, c) in bracket i j do
                            r.[u] <- r.[u] + x.[i] * y.[j] * c
        r

    let private isZeroElt (x: Elt) = x |> Array.forall (fun v -> v = 0)

    /// The Serre relations, each reported separately so a failure names itself.
    /// `aᵢⱼ = ⟨αⱼ, αᵢ^∨⟩ = cartanMatrix.[i].[j]`.
    type SerreReport =
        { CartanCommutes: bool
          EFDelta: bool
          HActsByCartan: bool
          AdNilpotentE: bool
          AdNilpotentF: bool }

        member this.AllHold =
            this.CartanCommutes && this.EFDelta && this.HActsByCartan && this.AdNilpotentE && this.AdNilpotentF

    let serreRelations () : SerreReport =
        let mutable cartanCommutes = true
        for i in 0 .. rank - 1 do
            for j in 0 .. rank - 1 do
                if (bracket chevalleyH.[i] chevalleyH.[j]).Length <> 0 then cartanCommutes <- false

        // [e_i, f_j] = δ_ij h_i
        let mutable efDelta = true
        for i in 0 .. rank - 1 do
            for j in 0 .. rank - 1 do
                // f_j = chevalleyFSign · e_{−α_j}, so [e_i, f_j] = chevalleyFSign · bracket(e_i, e_{−α_j})
                let b =
                    bracket chevalleyE.[i] chevalleyF.[j]
                    |> Array.map (fun (u, c) -> (u, chevalleyFSign * c))
                if i = j then
                    // h_{α_i} in simple-coroot coordinates is the i-th basis vector
                    let expected = [| (chevalleyH.[i], 1) |]
                    if b <> expected then efDelta <- false
                else if b.Length <> 0 then efDelta <- false

        // [h_i, e_j] = a_ij e_j  and  [h_i, f_j] = -a_ij f_j
        let mutable hActs = true
        for i in 0 .. rank - 1 do
            for j in 0 .. rank - 1 do
                let a = cartanMatrix.[i].[j]
                let be = bracket chevalleyH.[i] chevalleyE.[j]
                let bf = bracket chevalleyH.[i] chevalleyF.[j]
                let expE = if a = 0 then [||] else [| (chevalleyE.[j], a) |]
                let expF = if a = 0 then [||] else [| (chevalleyF.[j], -a) |]
                if be <> expE || bf <> expF then hActs <- false

        // ad(e_i)^{1 - a_ij} (e_j) = 0 for i <> j
        let adNilpotent (gens: int[]) =
            let mutable ok = true
            for i in 0 .. rank - 1 do
                for j in 0 .. rank - 1 do
                    if i <> j then
                        let n = 1 - cartanMatrix.[i].[j]
                        let mutable v = basisElt gens.[j]
                        for _ in 1 .. n do
                            v <- bracketElt (basisElt gens.[i]) v
                        if not (isZeroElt v) then ok <- false
            ok

        { CartanCommutes = cartanCommutes
          EFDelta = efDelta
          HActsByCartan = hActs
          AdNilpotentE = adNilpotent chevalleyE
          AdNilpotentF = adNilpotent chevalleyF }

    // ── rank over a prime field: a SOUND LOWER BOUND on the rational rank ───────────────────────
    // rank_{F_p} M ≤ rank_ℚ M always, so "rank_{F_p} = 248" proves "rank_ℚ = 248". The direction
    // that could be wrong (p dividing a minor) can only make the answer too SMALL, never too large
    // — so a full-rank verdict from this routine is never a false positive.

    [<Literal>]
    let private Prime = 2147483647L

    let private rankModP (rows: int64[][]) (width: int) : int =
        let m = rows |> Array.map (Array.map (fun v -> ((v % Prime) + Prime) % Prime))
        let mutable r = 0
        let mutable col = 0
        while col < width && r < m.Length do
            let mutable piv = -1
            for i in r .. m.Length - 1 do
                if piv < 0 && m.[i].[col] <> 0L then piv <- i
            if piv >= 0 then
                let t = m.[r]
                m.[r] <- m.[piv]
                m.[piv] <- t
                // modular inverse by Fermat
                let mutable inv = 1L
                let mutable b = m.[r].[col]
                let mutable e = Prime - 2L
                while e > 0L do
                    if e &&& 1L = 1L then inv <- inv * b % Prime
                    b <- b * b % Prime
                    e <- e >>> 1
                for j in col .. width - 1 do
                    m.[r].[j] <- m.[r].[j] * inv % Prime
                for i in 0 .. m.Length - 1 do
                    if i <> r && m.[i].[col] <> 0L then
                        let f = m.[i].[col]
                        for j in col .. width - 1 do
                            m.[i].[j] <- ((m.[i].[j] - f * m.[r].[j]) % Prime + Prime) % Prime
                r <- r + 1
            col <- col + 1
        r

    /// The dimension of the Lie subalgebra **generated** by the 24 Chevalley generators
    /// `{eᵢ, fᵢ, hᵢ}` — closure under bracket, then rank. **Must be 248.** Without this, calling the
    /// basis a "Chevalley–Serre presentation" would be a label rather than a fact: the relations
    /// could hold on a proper subalgebra and say nothing about the other 224 dimensions.
    /// The closure is computed in a **shape-closed** representation rather than on dense
    /// 248-vectors, and the shape-closure is why it is exact rather than a sampling: starting from
    /// basis elements, every bracket lands back in `{scalar·e_α} ∪ {Cartan vector}` —
    /// `[e_α,e_β] = ±e_{α+β}`, `[e_α,e_{−α}] = h_α`, `[h,e_α] = ⟨α,h⟩e_α`, `[h,h'] = 0`. So the
    /// generated subalgebra is exactly `span{e_α : α ∈ R} ⊕ (Cartan span)` for the reached root set
    /// `R`, and its dimension is `|R| + rank(Cartan span)`. No linear algebra is being skipped —
    /// on this generating set there is none to do.
    let generatedDimension () : int =
        let reached = Array.create rootCount false
        let cartanRows = ResizeArray<int64[]>()
        for i in 0 .. rank - 1 do
            reached.[chevalleyE.[i]] <- true
            reached.[chevalleyF.[i]] <- true
            cartanRows.Add(Array.init rank (fun k -> if k = i then 1L else 0L))
        let mutable changed = true
        while changed do
            changed <- false
            let current = [| for a in 0 .. rootCount - 1 do if reached.[a] then yield a |]
            for a in current do
                for b in current do
                    if negIndex.[a] = b then
                        cartanRows.Add(rootCoords.[a] |> Array.map int64)
                    else
                        let sum = Array.init rank (fun k -> roots.[a].[k] + roots.[b].[k])
                        let s = rootIndex sum
                        if s >= 0 && not reached.[s] then
                            reached.[s] <- true
                            changed <- true
        let rootDim = reached |> Array.sumBy (fun b -> if b then 1 else 0)
        rootDim + rankModP (cartanRows.ToArray()) rank

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §6  The Killing form — computed from the structure constants, never from a formula
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// `κᵢⱼ = tr(ad bᵢ ∘ ad bⱼ)`. Full 248×248, exact integers, computed from the structure
    /// constants alone — no closed form for `κ` is used anywhere, which is what lets
    /// `cartanKillingScale` below *derive* the dual Coxeter number instead of confirming it.
    ///
    /// `(ad bᵢ)_{m,u}` = the coefficient of `b_m` in `[bᵢ, b_u]`, i.e. column `u` of `ad bᵢ` is
    /// exactly `bracket i u`. The trace is `Σ_{u,m} (ad bᵢ)_{m,u} (ad bⱼ)_{u,m}`; `ad bᵢ` is stored
    /// sparsely (≤ 8 nonzeros per column) and `ad bⱼ` densely, one `j` at a time.
    let killingForm : int64[][] =
        let n = dimension
        let k = Array.init n (fun _ -> Array.zeroCreate<int64> n)
        // sparse (m, u, c) triples of ad b_i
        let sparseAd =
            Array.init n (fun i ->
                [| for u in 0 .. n - 1 do
                     for (m, c) in bracket i u -> struct (m, u, int64 c) |])
        // dense.[row * n + col] = (ad b_j)_{row, col} = coefficient of b_row in [b_j, b_col]
        let dense = Array.zeroCreate<int64> (n * n)
        for j in 0 .. n - 1 do
            System.Array.Clear(dense, 0, dense.Length)
            for col in 0 .. n - 1 do
                for (row, c) in bracket j col do
                    dense.[row * n + col] <- dense.[row * n + col] + int64 c
            for i in 0 .. n - 1 do
                let mutable tr = 0L
                for struct (m, u, c) in sparseAd.[i] do
                    tr <- tr + c * dense.[u * n + m]
                k.[i].[j] <- tr
        k

    /// The Killing form restricted to the Cartan subalgebra, as an 8×8 integer matrix.
    let killingOnCartan : int64[][] =
        Array.init rank (fun i -> Array.init rank (fun j -> killingForm.[cartanBasisIndex i].[cartanBasisIndex j]))

    /// `κ|_h = c · A` for a single integer `c`, or `None` if the two matrices are not proportional.
    /// For a simple Lie algebra `κ = 2h^∨⟨·,·⟩`, so `c = 2h^∨`. **This is how the dual Coxeter number
    /// is derived here** — measured off structure constants, not looked up.
    let cartanKillingScale : int64 option =
        let c = killingOnCartan.[0].[0] / int64 cartanMatrix.[0].[0]
        let mutable ok = true
        for i in 0 .. rank - 1 do
            for j in 0 .. rank - 1 do
                if killingOnCartan.[i].[j] <> c * int64 cartanMatrix.[i].[j] then ok <- false
        if ok then Some c else None

    /// `h^∨`, derived from `κ|_h = 2h^∨·A`. Independent of the `|Φ|/rank` route to the (ordinary)
    /// Coxeter number, and for a simply-laced algebra the two coincide — which makes their agreement
    /// a cross-check rather than a restatement.
    let dualCoxeterNumber : int64 option = cartanKillingScale |> Option.map (fun c -> c / 2L)

    /// Ordinary Coxeter number by the classical count `h = |Φ| / rank`. A *different* route from
    /// `dualCoxeterNumber`: this one never touches a structure constant.
    let coxeterNumberFromRootCount : int = rootCount / rank

    /// The **block structure** of `κ`: `κ(hᵢ, e_α) = 0`, and `κ(e_α, e_β) = 0` unless `β = −α`.
    /// Verified rather than assumed — the vanishing is what makes the nondegeneracy argument below
    /// a two-line determinant instead of a 248×248 elimination.
    let killingBlockStructureHolds : bool =
        let mutable ok = true
        for a in 0 .. rootCount - 1 do
            for i in 0 .. rank - 1 do
                if killingForm.[a].[cartanBasisIndex i] <> 0L then ok <- false
                if killingForm.[cartanBasisIndex i].[a] <> 0L then ok <- false
            for b in 0 .. rootCount - 1 do
                if b <> negIndex.[a] && killingForm.[a].[b] <> 0L then ok <- false
        ok

    /// `κ(e_α, f_α)` for each root, in the **Chevalley normalisation** `f_α = chevalleyFSign·e_{−α}`.
    /// Constant across all 240 roots, and equal to `2h^∨ · 2/⟨α,α⟩ = 60` — the same 60 that
    /// `cartanKillingScale` reports, reached through the root spaces instead of the Cartan.
    let killingRootPairing : int64[] =
        Array.init rootCount (fun a -> int64 chevalleyFSign * killingForm.[a].[negIndex.[a]])

    /// Nondegeneracy of `κ`, from the block structure: `det(κ|_h) ≠ 0` and every root pairing
    /// nonzero. **Cartan's criterion**: `κ` nondegenerate ⟺ the algebra is semisimple.
    let killingNondegenerate : bool =
        killingBlockStructureHolds
        && bareissDet killingOnCartan <> 0L
        && killingRootPairing |> Array.forall (fun v -> v <> 0L)

    /// Is the Dynkin diagram connected? (Adjacency = non-orthogonality of simple roots.) A connected
    /// diagram means an irreducible root system, which for a semisimple algebra means **simple** —
    /// not a direct sum. This is the step that stops `dim = 248` from being satisfiable by a sum of
    /// smaller algebras, and it is the reason the dimension is allowed to speak at all.
    let dynkinConnected : bool =
        let seen = Array.create rank false
        let stack = System.Collections.Generic.Stack<int>()
        stack.Push 0
        seen.[0] <- true
        let mutable count = 1
        while stack.Count > 0 do
            let i = stack.Pop()
            for j in 0 .. rank - 1 do
                if not seen.[j] && i <> j && cartanMatrix.[i].[j] <> 0 then
                    seen.[j] <- true
                    count <- count + 1
                    stack.Push j
        count = rank

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §7  Rung 5 — what is honestly reachable about the compact GROUP
    // ═══════════════════════════════════════════════════════════════════════════════════════════
    //
    // A 248-dimensional compact Lie group cannot be "constructed" the way a finite object can: it is
    // an uncountable manifold, and no finite computation enumerates it. Saying "rung 5 done" on the
    // strength of a dimension count would be exactly the vacuity this repo treats as a defect.
    //
    // What IS reachable, and what it buys:
    //
    //   (a) **The compact real form, and its Killing signature.** Weyl's theorem: a real semisimple
    //       Lie algebra whose Killing form is negative definite is the Lie algebra of a compact
    //       group, and the associated simply-connected group is compact (Weyl 1925-26; the
    //       finiteness of the fundamental group is the substance). So exhibiting the compact real
    //       form `k = span_ℝ{ i·h } ⊕ span{ e_α − e_{−α} } ⊕ span{ i(e_α + e_{−α}) }` and MEASURING
    //       its Killing form to be negative definite is a proof that the compact group exists, is
    //       248-dimensional, and has rank 8 — without constructing it.
    //   (b) **Trivial centre**: `det A = 1` ⟺ root lattice = weight lattice ⟺ the compact group is
    //       simultaneously simply connected and centreless. So "the" compact E8 is unambiguous.
    //   (c) **The Weyl group's invariants** — §8.
    //
    // This is a substitute, and it is labelled one. It is not the group.

    /// The Killing form of the compact real form, in the basis
    /// `{ i·hⱼ } ∪ { e_α − f_α } ∪ { i(e_α + f_α) }` over positive roots (Weyl's unitary trick).
    ///
    /// That basis is `κ`-orthogonal (a consequence of `killingBlockStructureHolds`), so the form is
    /// diagonal and definiteness is readable straight off the diagonal:
    ///   `κ(i hⱼ, i hⱼ) = −κ(hⱼ,hⱼ)`, and `κ(x_α,x_α) = κ(y_α,y_α) = −2κ(e_α, f_α)`.
    /// **Every entry must be negative.** It can fail, and it did: before the `−h_α` correction the
    /// diagonal held both `−120` and `+120`, i.e. the form was *indefinite* — which is the same
    /// defect Jacobi reported, seen through a second instrument.
    let compactFormKillingDiagonal : int64[] =
        let positives =
            [| for a in 0 .. rootCount - 1 do
                 // "positive" = first nonzero simple coordinate is positive
                 let c = rootCoords.[a]
                 let mutable lead = 0
                 let mutable k = 0
                 while lead = 0 && k < rank do
                     if c.[k] <> 0 then lead <- c.[k]
                     k <- k + 1
                 if lead > 0 then yield a |]
        [| for j in 0 .. rank - 1 -> -killingOnCartan.[j].[j]
           for a in positives -> -2L * killingRootPairing.[a]
           for a in positives -> -2L * killingRootPairing.[a] |]

    /// The compact real form's Killing form is negative definite ⇒ (Weyl) the corresponding
    /// simply-connected Lie group is **compact**.
    let compactFormIsNegativeDefinite : bool =
        compactFormKillingDiagonal.Length = dimension
        && compactFormKillingDiagonal |> Array.forall (fun v -> v < 0L)

    /// The centre of the simply-connected group is `P/Q`, of order `det A`. `det A = 1` ⇒ trivial
    /// centre ⇒ simply-connected and adjoint coincide, so "the compact E8" names one group.
    let centreOrder : int = abs cartanDeterminant

    // ═══════════════════════════════════════════════════════════════════════════════════════════
    // §8  The Weyl group: Coxeter element, exponents, order
    // ═══════════════════════════════════════════════════════════════════════════════════════════

    /// The Coxeter element `c = s₁s₂⋯s₈`, as an 8×8 integer matrix in the simple-root basis.
    let coxeterElement : int[][] =
        // s_i acting on simple-root coordinates: s_i(α_j) = α_j − A_ij α_i
        let applyRefl (i: int) (v: int[]) =
            let mutable c = 0
            for j in 0 .. rank - 1 do
                c <- c + v.[j] * cartanMatrix.[i].[j]
            let r = Array.copy v
            r.[i] <- r.[i] - c
            r
        // columns = images of the basis vectors
        let cols =
            Array.init rank (fun j ->
                let mutable v = Array.init rank (fun k -> if k = j then 1 else 0)
                for i in rank - 1 .. -1 .. 0 do
                    v <- applyRefl i v
                v)
        Array.init rank (fun r -> Array.init rank (fun c -> cols.[c].[r]))

    let private matMul (a: int[][]) (b: int[][]) : int[][] =
        Array.init rank (fun i ->
            Array.init rank (fun j ->
                let mutable s = 0
                for k in 0 .. rank - 1 do
                    s <- s + a.[i].[k] * b.[k].[j]
                s))

    let private identity : int[][] =
        Array.init rank (fun i -> Array.init rank (fun j -> if i = j then 1 else 0))

    /// The multiplicative order of the Coxeter element = the **Coxeter number `h`**. Computed by
    /// repeated multiplication; a route to `h` that never counts roots, so its agreement with
    /// `coxeterNumberFromRootCount` is a genuine cross-check.
    let coxeterOrder : int =
        let mutable m = Array.map Array.copy coxeterElement
        let mutable n = 1
        while m <> identity && n < 200 do
            m <- matMul m coxeterElement
            n <- n + 1
        n

    /// The 30th cyclotomic polynomial `Φ₃₀(t) = t⁸ + t⁷ − t⁵ − t⁴ − t³ + t + 1`, coefficients from
    /// degree 8 down to 0. Written out because it is the *prediction*, not a fitted result.
    let phi30 : int[] = [| 1; 1; 0; -1; -1; -1; 0; 1; 1 |]

    /// `Φ₃₀(c)` evaluated as a matrix polynomial. **Must be the zero matrix.**
    ///
    /// Why this and not "the characteristic polynomial equals Φ₃₀": evaluating the polynomial needs
    /// no division and no char-poly algorithm, so there is nothing to get subtly wrong. Combined
    /// with `coxeterPowersIndependent` (the powers `I, c, …, c⁷` are linearly independent, so the
    /// minimal polynomial has degree ≥ 8), it gives minpoly = charpoly = `Φ₃₀` — hence the
    /// eigenvalues are exactly the **primitive** 30th roots of unity, hence the exponents are the
    /// totatives of 30.
    let phi30OfCoxeter : int[][] =
        let mutable acc = Array.init rank (fun _ -> Array.zeroCreate rank)
        let mutable pow = identity
        for d in 0 .. 8 do
            let coeff = phi30.[8 - d]
            if coeff <> 0 then
                for i in 0 .. rank - 1 do
                    for j in 0 .. rank - 1 do
                        acc.[i].[j] <- acc.[i].[j] + coeff * pow.[i].[j]
            if d < 8 then pow <- matMul pow coxeterElement
        acc

    let coxeterAnnihilatedByPhi30 : bool =
        phi30OfCoxeter |> Array.forall (Array.forall (fun v -> v = 0))

    /// Are `I, c, c², …, c⁷` linearly independent as 64-vectors? Rank 8 ⇒ minimal polynomial has
    /// degree 8 ⇒ (with `coxeterAnnihilatedByPhi30`) charpoly = minpoly = `Φ₃₀`.
    let coxeterPowersIndependent : bool =
        let rows = ResizeArray<int64[]>()
        let mutable pow = identity
        for _ in 0 .. rank - 1 do
            rows.Add(pow |> Array.collect (Array.map int64))
            pow <- matMul pow coxeterElement
        rankModP (rows.ToArray()) (rank * rank) = rank

    /// The **exponents**, derived: once charpoly = `Φ_h`, the eigenvalues are `e^{2πi m/h}` for
    /// exactly the `m` coprime to `h`. So the exponents are the totatives of `h` — computed by gcd,
    /// not transcribed.
    let exponents : int[] =
        let h = coxeterOrder
        let rec gcd a b = if b = 0 then a else gcd b (a % b)
        [| for m in 1 .. h - 1 do
             if gcd m h = 1 then yield m |]

    /// The degrees `dᵢ = mᵢ + 1` of the basic invariants.
    let degrees : int[] = exponents |> Array.map (fun m -> m + 1)

    /// `|W| = Π dᵢ`.
    ///
    /// **This one is CITED, not derived.** Coxeter's theorem (Coxeter 1951; see also Shephard–Todd
    /// 1954, Solomon 1963) says the order of a finite reflection group is the product of the degrees
    /// of its basic invariants. The exponents above ARE computed here; the step from exponents to
    /// `|W|` is a theorem this module uses and does not prove. Enumerating W(E8) directly is out of
    /// reach — it has 696 729 600 elements — and the honest alternative (a Schreier–Sims order
    /// computation on the degree-240 permutation action) is not implemented here.
    let weylOrder : int64 = degrees |> Array.fold (fun acc d -> acc * int64 d) 1L
