namespace Zeta.Core

/// **MixCogen — the compiler-as-data and the compiler-generator (Futamura 2nd & 3rd, honestly).**
/// (Aaron 2026-07-03: "back to the ladder for mix(mix, mix) self-application.")
///
/// The mix-as-data slices reified everything ISA- and algorithm-specific into DATA (`spec`, `mixDef`,
/// `evalDef`, `loadDesc`). This module spends that to realize the upper Futamura projections as
/// first-class values:
///
///   - **2nd projection — the compiler-as-data.** `mix(mix, interpreter) = a compiler`. Here a
///     compiler for ISA X is a `DynamicValue` **template** `{spec, load, mixDef, evalDef}` — the mix
///     with everything fixed except the program (the hole). `cogen spec load` produces it; `compile`
///     runs it on a program. The compiler is a byte-lockable value: it can be stored, shipped over the
///     bus, keyed by ZetaId, and **collected by Shiva when nothing references it** (a compiler is a
///     reified row in the database of intelligence).
///   - **3rd projection — cogen, the compiler-generator.** `mix(mix, mix) = cogen`. `cogen` is the
///     function `interpreter-spec → compiler`; applying it emits the compiler template. The
///     `gen(gen) == gen` fixpoint (already proven at the residual level in `MixIr`) holds here as
///     generation determinism: `cogen` on the same inputs emits the byte-identical compiler.
///
/// **The correctness law** (machine-checked, both ISAs):
///     compile (cogen spec load) program statics  =  IsaSpec.specializeMem spec … program statics
/// i.e. the GENERATED compiler produces exactly the residual the native partial evaluator does. The
/// three ladder rungs agree: `compile(cogen …)` = `MixIr.runFullyReifiedMix` = native `specializeMem`.
///
/// **HONEST BOUNDARY (named, not dressed up).** This is the projections realized **as data over the
/// reified configuration** — the compiler VALUE carries the ISA-specific config, and `compile` applies
/// the still-native universal DRIVER to it (bounded reify, Aaron's choice: the driver stays native).
/// It is NOT literal `mix(mix, mix)` in the sense of *mix being an ISA program the mix runs on
/// itself* — that needs the driver loop reified as an IR program (the unbounded slice we deliberately
/// did not build), and it would be the currying pun to claim otherwise. What IS real and new: a
/// compiler is now a first-class, byte-lockable, Shiva-collectible data value, generated by cogen,
/// proven to compile correctly. Anchors: Futamura (1971, the projections); Ershov; the parser-side
/// `Cogen` (`regenerate == direct`). Built on `MixIr` + `IsaSpec`. Consumes only `DynamicValue`.
[<RequireQualifiedAccess>]
module MixCogen =

    /// **cogen — the compiler-generator (3rd projection).** Emit the reified compiler for an ISA: a
    /// data template carrying the spec, the load descriptor, and the (universal) reified algorithm +
    /// abstract-eval. Deterministic: same inputs → byte-identical compiler.
    let cogen (spec: DynamicValue) (loadDesc: DynamicValue) : DynamicValue =
        DynamicValue.Object
            [ "kind", DynamicValue.String "compiler"
              "spec", spec
              "load", loadDesc
              "mixDef", MixIr.defaultMixDef
              "evalDef", MixIr.defaultEvalDef ]

    /// **compile — run a compiler-as-data on a program (2nd projection applied).** Fill the compiler's
    /// program hole and run the fully-reified mix. Returns the residual + folded static registers +
    /// folded static memory (a `{residual, knownRegs, knownMem}` data result), or an error.
    let compile (compiler: DynamicValue) (program: DynamicValue) (staticRegs: Map<int, int>) (staticMem: Map<int, int>) : Result<DynamicValue, string> =
        match DynamicValue.get "spec" compiler, DynamicValue.get "load" compiler, DynamicValue.get "mixDef" compiler, DynamicValue.get "evalDef" compiler with
        | Some spec, Some loadDesc, Some mixDef, Some evalDef ->
            match MixIr.runFullyReifiedMix mixDef evalDef spec loadDesc program staticRegs staticMem with
            | Ok(residual, knownRegs, knownMem) ->
                Ok(
                    DynamicValue.Object
                        [ "residual", residual
                          "knownRegs", DynamicValue.Array [ for KeyValue(k, v) in knownRegs -> DynamicValue.Object [ "k", DynamicValue.Int(int64 k); "v", DynamicValue.Int(int64 v) ] ]
                          "knownMem", DynamicValue.Array [ for KeyValue(k, v) in knownMem -> DynamicValue.Object [ "k", DynamicValue.Int(int64 k); "v", DynamicValue.Int(int64 v) ] ] ]
                )
            | Error e -> Error e
        | _ -> Error "mixcogen: malformed compiler (needs spec, load, mixDef, evalDef)"

    /// The residual program out of a `compile` result.
    let residualOf (result: DynamicValue) : DynamicValue option = DynamicValue.get "residual" result
