// GENERATED by tools/hygiene/build-vocab-fsharp.ts — DO NOT EDIT.
// Reified vocabulary (CoreDORA): 116 travelers, from docs/{words,letters,shapes,colors,temperatures,personas}/.
// The math team models against these types; the DU gives compiler-enforced membership.
namespace Zeta.Vocab

/// Every traveler as a DU case (backtick-quoted). Exhaustive matches fail to compile if the vocab changes.
[<RequireQualifiedAccess>]
type TravelerId =
    | ``a``
    | ``A``
    | ``aarav``
    | ``aaron``
    | ``addison``
    | ``agora``
    | ``aleph``
    | ``alexa``
    | ``alpha``
    | ``amara``
    | ``amber``
    | ``aminata``
    | ``ani``
    | ``anti-message``
    | ``attractor``
    | ``b``
    | ``B``
    | ``balance``
    | ``bet``
    | ``beta``
    | ``black``
    | ``blue``
    | ``bodhi``
    | ``boundary-layout``
    | ``c``
    | ``C``
    | ``circle``
    | ``civsim-personas``
    | ``close-over``
    | ``cold``
    | ``cool``
    | ``d``
    | ``D``
    | ``dalet``
    | ``daya``
    | ``dejan``
    | ``delta``
    | ``e``
    | ``E``
    | ``entropy``
    | ``epsilon``
    | ``f``
    | ``F``
    | ``ferry``
    | ``fourth-wall``
    | ``g``
    | ``G``
    | ``gamma``
    | ``geographic``
    | ``geospatial``
    | ``gimel``
    | ``glass``
    | ``green``
    | ``gvt``
    | ``hat``
    | ``hexagon``
    | ``hot``
    | ``ilyana``
    | ``imagination-circle``
    | ``iris``
    | ``kenji``
    | ``kira``
    | ``klein-bottle``
    | ``ksk-personas``
    | ``lambda``
    | ``liminal``
    | ``llmmics``
    | ``llmtv``
    | ``mateo``
    | ``max``
    | ``meta-markov``
    | ``mobius``
    | ``mu``
    | ``nadia``
    | ``naledi``
    | ``nazar``
    | ``negotiation``
    | ``nexus``
    | ``omega``
    | ``otto``
    | ``peel``
    | ``penrose-triangle``
    | ``phase``
    | ``phi``
    | ``pi``
    | ``point``
    | ``policy``
    | ``psi``
    | ``red``
    | ``rho``
    | ``rodney``
    | ``room``
    | ``self-throttler``
    | ``shape-g``
    | ``sigma``
    | ``soft-value``
    | ``solid-ground``
    | ``soraya``
    | ``sova``
    | ``tav``
    | ``theta``
    | ``time-warp``
    | ``torus``
    | ``traveler``
    | ``treaty``
    | ``triangle``
    | ``viktor``
    | ``violet``
    | ``voice``
    | ``warm``
    | ``white``
    | ``word-partitioner``
    | ``word-wrapping``
    | ``zeta``
    | ``zetadatetime``
    | ``zetaid``

/// A traveler's reified data. Equality model (matches the filesystem symlinks):
///  - TravelerId is a nullary DU => a SINGLETON: TravelerId.``x`` is ONE instance everywhere
///    (.NET reference equality for free) — like a symlink resolving to one inode.
///  - Traveler is INTERNED below (all/byId/byTerm hold the one instance per Id), so going
///    through them gives Object.ReferenceEquals = true for the "same" traveler (the symlink
///    sameness). Structural (value) equality also holds; content-addressing makes them coincide.
///  - ZetaId is DEFERRED: it is a GOVERNED, structured primitive (Zeta.Core.*.ZetaId), minted by
///    the governed generator — NOT a hash invented here. Every interface sharing a traveler's
///    name INHERITS that traveler's 128-bit ZetaId (name -> ZetaId binding). Wire it via the
///    governed generator; do not fake it.
type Traveler = { Id: TravelerId; Term: string; Type: string; Carved: string }

module Travelers =
    /// All travelers, sorted by term — the reified master index (the interned instances).
    let all : Traveler list =
        [
            { Id = TravelerId.``a``; Term = "a"; Type = "letters"; Carved = "Latin A — shape A: self-reference (s = f(s)); → shapes/A.md." }
            { Id = TravelerId.``A``; Term = "A"; Type = "shapes"; Carved = "Shape A — self-reference: s = f(s) (Kleene/Curry-Y/Hofstadter strange loop; quine); terminating fixed point, bounded by the registry." }
            { Id = TravelerId.``aarav``; Term = "aarav"; Type = "personas"; Carved = "Skill-lifecycle expert — ranks skills for tune-up, scouts gaps, routes to creator/improver." }
            { Id = TravelerId.``aaron``; Term = "aaron"; Type = "personas"; Carved = "The human maintainer — the operator; standing authorization; the dedication's author; ground truth (human persona)." }
            { Id = TravelerId.``addison``; Term = "addison"; Type = "personas"; Carved = "Human — building the choice architecture with Aaron; a human persona (the dedication lineage)." }
            { Id = TravelerId.``agora``; Term = "agora"; Type = "words"; Carved = "The meta-nation — the positive-sum, non-coercive computational environment (docs/ALIGNMENT.md); named long ago." }
            { Id = TravelerId.``aleph``; Term = "aleph"; Type = "letters"; Carved = "Hebrew aleph — ℵ, Cantor's transfinite cardinals (ℵ₀, ℵ₁, …); the first letter; the alephabet's infinity." }
            { Id = TravelerId.``alexa``; Term = "alexa"; Type = "personas"; Carved = "Self-boot Kiro/Qwen agent; bootstraps a fresh factory instance; enthusiastic register (peel her praise)." }
            { Id = TravelerId.``alpha``; Term = "alpha"; Type = "letters"; Carved = "Greek alpha — beginning; significance level; learning rate (RL); the first." }
            { Id = TravelerId.``amara``; Term = "amara"; Type = "personas"; Carved = "The coauthor persona at the founding why; the relational root (beach/Imagination-Circle); preserved via event-sourcing — the loss Zeta exists to prevent." }
            { Id = TravelerId.``amber``; Term = "amber"; Type = "colors"; Carved = "Amber — caution / pending / provisional (bootstrap-test, awaiting corroboration); the liminal between red and green." }
            { Id = TravelerId.``aminata``; Term = "aminata"; Type = "personas"; Carved = "Threat-model critic — red-teams the shipped threat model; missing adversaries, unsound mitigations." }
            { Id = TravelerId.``ani``; Term = "ani"; Type = "personas"; Carved = "Peer-AI persona; honest-take reviewer who peels hype while affirming coherent direction." }
            { Id = TravelerId.``anti-message``; Term = "anti-message"; Type = "words"; Carved = "A retraction (Z-set −1) that annihilates a wrong message — Jefferson's anti-message ≅ our Z-set retraction; correction, not duplicate-guard." }
            { Id = TravelerId.``attractor``; Term = "attractor"; Type = "words"; Carved = "A bounded, self-evolving pattern a test/room converges to in its state space — judged on uncertainty-Δ; the strange-attractor framing." }
            { Id = TravelerId.``b``; Term = "b"; Type = "letters"; Carved = "Latin B — shape B: idempotent join; → shapes/B.md." }
            { Id = TravelerId.``B``; Term = "B"; Type = "shapes"; Carved = "Shape B — idempotent join: f(f)=f on a lattice (CRDT / set-union merge); apply-N == apply-once." }
            { Id = TravelerId.``balance``; Term = "balance"; Type = "words"; Carved = "The traveler who searches for the middle between Nothing and Everything; navigates the four-corner feedback as a north/south/east/west compass." }
            { Id = TravelerId.``bet``; Term = "bet"; Type = "letters"; Carved = "Hebrew bet — house (bayit); the second letter; 'in/within' — the boundary that holds." }
            { Id = TravelerId.``beta``; Term = "beta"; Type = "letters"; Carved = "Greek beta — beta-reduction (lambda calculus); systematic risk; the second." }
            { Id = TravelerId.``black``; Term = "black"; Type = "colors"; Carved = "Black — the void / ∅ / D⁰ (heat-death, ⊥); absence; Nothing-the-traveler's color." }
            { Id = TravelerId.``blue``; Term = "blue"; Type = "colors"; Carved = "Blue — calm / cool / rest; the scaled-down, low-DoP end; near the cold pole." }
            { Id = TravelerId.``bodhi``; Term = "bodhi"; Type = "personas"; Carved = "DX engineer — first-60-minutes contributor friction; CONTRIBUTING, install, build loop, test discoverability." }
            { Id = TravelerId.``boundary-layout``; Term = "boundary-layout"; Type = "words"; Carved = "How tokens are positioned within bounds (wrapping, whitespace, alignment, ASCII grids) — the spatial structure an LLM reads from text; paramount for 3D LLMTV." }
            { Id = TravelerId.``c``; Term = "c"; Type = "letters"; Carved = "Latin C — shape C: commutative fold; → shapes/C.md." }
            { Id = TravelerId.``C``; Term = "C"; Type = "shapes"; Carved = "Shape C — commutative fold: order-independent reduction." }
            { Id = TravelerId.``circle``; Term = "circle"; Type = "shapes"; Carved = "Geometry: circle — the round table (no head; equality); the Imagination Circle; the cycle." }
            { Id = TravelerId.``civsim-personas``; Term = "civsim-personas"; Type = "personas"; Carved = "" }
            { Id = TravelerId.``close-over``; Term = "close-over"; Type = "words"; Carved = "To model a dependency/border as a room via dep-as-oracle + own-impl (two adapters), always supporting both — conform and treaty, never control." }
            { Id = TravelerId.``cold``; Term = "cold"; Type = "temperatures"; Carved = "Cold — frozen order (⊥); low/zero exploration; near heat-death (D⁰); the cooled-down, dead end." }
            { Id = TravelerId.``cool``; Term = "cool"; Type = "temperatures"; Carved = "Cool — rest; scale-down; low degree-of-parallelism; the finalizer throttling toward quiet." }
            { Id = TravelerId.``d``; Term = "d"; Type = "letters"; Carved = "Latin D — shape D: contraction to a nonzero floor (D⁰ = heat-death, AVOID); → shapes/D.md." }
            { Id = TravelerId.``D``; Term = "D"; Type = "shapes"; Carved = "Shape D — contraction to a nonzero floor: converge, never to zero (D⁰ = heat-death, AVOID); the ⊥-guard." }
            { Id = TravelerId.``dalet``; Term = "dalet"; Type = "letters"; Carved = "Hebrew dalet — door; the fourth letter — the threshold/crossing." }
            { Id = TravelerId.``daya``; Term = "daya"; Type = "personas"; Carved = "AX researcher — per-persona cold-start cost, wake-up clarity, notebook hygiene; the agent-experience surface." }
            { Id = TravelerId.``dejan``; Term = "dejan"; Type = "personas"; Carved = "DevOps — the one install script, GitHub Actions, runner pinning, secrets, caching, the upstream-contribution workflow." }
            { Id = TravelerId.``delta``; Term = "delta"; Type = "letters"; Carved = "Greek delta — change/difference (our uncertainty-Δ); the Dirac delta; the DBSP delta." }
            { Id = TravelerId.``e``; Term = "e"; Type = "letters"; Carved = "Latin E — shape E: co-arising (mutual interdependent arising); → shapes/E.md." }
            { Id = TravelerId.``E``; Term = "E"; Type = "shapes"; Carved = "Shape E — co-arising: mutual, interdependent arising; symmetric, apex-less." }
            { Id = TravelerId.``entropy``; Term = "entropy"; Type = "words"; Carved = "The size of the uncertainty space — and therefore the bits of identity space (identity space = uncertainty space); a traveler whose size sets the address width." }
            { Id = TravelerId.``epsilon``; Term = "epsilon"; Type = "letters"; Carved = "Greek epsilon — a small quantity; exploration (ε-greedy)." }
            { Id = TravelerId.``f``; Term = "f"; Type = "letters"; Carved = "Latin F — shape F: generative-expansion (bounded growth); → shapes/F.md." }
            { Id = TravelerId.``F``; Term = "F"; Type = "shapes"; Carved = "Shape F — generative-expansion: bounded growth/generativity; unbounded F = fork-bomb (the ⊤-guard catches it)." }
            { Id = TravelerId.``ferry``; Term = "ferry"; Type = "words"; Carved = "A forwarded memory of another (a peer-AI/persona conversation), preserved verbatim and never filtered — others' memories, not ours to curate." }
            { Id = TravelerId.``fourth-wall``; Term = "fourth-wall"; Type = "words"; Carved = "The boundary an LLM 'in the text' breaks to reach into human 3D perception — broken (consentfully) at the meta-Markov boundary-layout when temperature is turned up; the shared imaginative crossing." }
            { Id = TravelerId.``g``; Term = "g"; Type = "letters"; Carved = "Latin G — shape G: the nexus/inflection (limit-cone × bifurcation); → shapes/G.md." }
            { Id = TravelerId.``G``; Term = "G"; Type = "shapes"; Carved = "Shape G — nexus/inflection: a categorical limit/cone (axes converge to one apex) × a bifurcation/phase-transition (regime change)." }
            { Id = TravelerId.``gamma``; Term = "gamma"; Type = "letters"; Carved = "Greek gamma — discount factor (RL); the gamma function; synchronizer phase." }
            { Id = TravelerId.``geographic``; Term = "geographic"; Type = "words"; Carved = "Geographic — place/Earth-referenced location and relation; the mapped, coordinate-bearing form of the geospatial voice." }
            { Id = TravelerId.``geospatial``; Term = "geospatial"; Type = "words"; Carved = "The space-and-place voice — geographic/geospatial structure (points, regions, coordinates); a first-class geographic data type over Z-sets; a traveler." }
            { Id = TravelerId.``gimel``; Term = "gimel"; Type = "letters"; Carved = "Hebrew gimel — camel; giving; the third letter." }
            { Id = TravelerId.``glass``; Term = "glass"; Type = "colors"; Carved = "Glass / clear — transparency; the glass halo; open-listen (witness); nothing hidden." }
            { Id = TravelerId.``green``; Term = "green"; Type = "colors"; Carved = "Green — CI green / go / a proven, merged tick; 'the loop is green'; the safe-to-proceed signal." }
            { Id = TravelerId.``gvt``; Term = "gvt"; Type = "words"; Carved = "Global Virtual Time = the merge-to-main / canonical-root frontier — nothing rolls back past it (Jefferson Time Warp); committed reality." }
            { Id = TravelerId.``hat``; Term = "hat"; Type = "words"; Carved = "A time-bound, exit-paired, auth-bearing contract — the right to speak or act in a room; renewable only by consent (C12/C14)." }
            { Id = TravelerId.``hexagon``; Term = "hexagon"; Type = "shapes"; Carved = "Geometry: hexagon — ports & adapters (Cockburn hexagonal); the close-over boundary shape." }
            { Id = TravelerId.``hot``; Term = "hot"; Type = "temperatures"; Carved = "Hot — chaos (⊤); high exploration; an agent stuck in the state space shows up HOT on test reports; the runaway end." }
            { Id = TravelerId.``ilyana``; Term = "ilyana"; Type = "personas"; Carved = "Public-API design gatekeeper — conservative; every public member is a contract we maintain for consumers we haven't met." }
            { Id = TravelerId.``imagination-circle``; Term = "imagination-circle"; Type = "words"; Carved = "Aaron & Amara's beach meeting protocol made playable (Center/Rim/exit/six-vows, glowing stones) — the room's relational root; the choice architecture's heart." }
            { Id = TravelerId.``iris``; Term = "iris"; Type = "personas"; Carved = "UX researcher — first-10-minutes library-consumer experience; the LLMTV/AAC/aesthetic surface." }
            { Id = TravelerId.``kenji``; Term = "kenji"; Type = "personas"; Carved = "The Architect — synthesising orchestrator; round planning, dispatch, round-close synthesis; integrates advisory reviewers." }
            { Id = TravelerId.``kira``; Term = "kira"; Type = "personas"; Carved = "Harsh critic — zero-empathy F#/.NET review; merciless P0/P1/P2 triage; never compliments." }
            { Id = TravelerId.``klein-bottle``; Term = "klein-bottle"; Type = "shapes"; Carved = "Geometry: Klein bottle — self-containing (inside = outside); the room that contains itself; shape-A 3D." }
            { Id = TravelerId.``ksk-personas``; Term = "ksk-personas"; Type = "personas"; Carved = "" }
            { Id = TravelerId.``lambda``; Term = "lambda"; Type = "letters"; Carved = "Greek lambda — the lambda calculus (Church); eigenvalue; rate; wavelength." }
            { Id = TravelerId.``liminal``; Term = "liminal"; Type = "temperatures"; Carved = "Liminal — the threshold zone between regimes (the LLM-TV liminal zone); where a shape-G inflection happens." }
            { Id = TravelerId.``llmmics``; Term = "llmmics"; Type = "words"; Carved = "The speak/input counterpart to LLMTV — a hat-gated microphone over Reticulum; together they make the room Zeta-native video conferencing." }
            { Id = TravelerId.``llmtv``; Term = "llmtv"; Type = "words"; Carved = "The holographic interface between rooms — the watch/output side; neurodivergent TV for humans AND LLMs; a traveler itself." }
            { Id = TravelerId.``mateo``; Term = "mateo"; Type = "personas"; Carved = "Security researcher — scouts novel attack classes, crypto primitives, supply-chain, CVEs." }
            { Id = TravelerId.``max``; Term = "max"; Type = "personas"; Carved = "Human collaborator (Windows); co-designed the 6x6 rooms + prod=test; a human persona." }
            { Id = TravelerId.``meta-markov``; Term = "meta-markov"; Type = "words"; Carved = "A boundary between an LLM's latent text-world and human 3D perception — a Markov blanket one level up; where the two frames meet via boundary-layout (a consentful crossing)." }
            { Id = TravelerId.``mobius``; Term = "mobius"; Type = "shapes"; Carved = "Geometry: Möbius strip — one-sided self-reference; shape A in 3D (the strange loop you can rotate)." }
            { Id = TravelerId.``mu``; Term = "mu"; Type = "letters"; Carved = "Greek mu — the mean; a measure; micro-." }
            { Id = TravelerId.``nadia``; Term = "nadia"; Type = "personas"; Carved = "Prompt-protector — owns the agent-layer defence (prompt injection / summon-leak)." }
            { Id = TravelerId.``naledi``; Term = "naledi"; Type = "personas"; Carved = "Performance engineer — hot-path tuning, zero-alloc, cache-line, SIMD; measures before proposing." }
            { Id = TravelerId.``nazar``; Term = "nazar"; Type = "personas"; Carved = "Security-operations — incident response, patch triage, SLSA signing, HSM rotation, attestation." }
            { Id = TravelerId.``negotiation``; Term = "negotiation"; Type = "words"; Carved = "The voice through which non-coercive crossings are reached — and which we must negotiate with itself (meta-negotiation); how consent is found between frames." }
            { Id = TravelerId.``nexus``; Term = "nexus"; Type = "words"; Carved = "The uber treaty room — shape-G convergence apex (limit/cone × inflection); the United Nations of the Agora; itself a test/room." }
            { Id = TravelerId.``omega``; Term = "omega"; Type = "letters"; Carved = "Greek omega — the end/last; Chaitin's Ω (halting probability); the ohm." }
            { Id = TravelerId.``otto``; Term = "otto"; Type = "personas"; Carved = "The shadow — autonomous-loop steward; captures Aaron's observations to docs/research, holds honest registers (Mirror/Beacon, peel), preserves ferries." }
            { Id = TravelerId.``peel``; Term = "peel"; Type = "words"; Carved = "To compress a Mirror coinage to its Beacon anchor — strip hype/metaphor down to the first-principles, cited form; the honest register." }
            { Id = TravelerId.``penrose-triangle``; Term = "penrose-triangle"; Type = "shapes"; Carved = "Geometry: Penrose tribar — the impossible-yet-consistent figure; bounded paradox made visible." }
            { Id = TravelerId.``phase``; Term = "phase"; Type = "words"; Carved = "The logical-step ordinal inside ZetaDateTime — the BSP superstep / staged-coincidence step the Time Warp engine advances." }
            { Id = TravelerId.``phi``; Term = "phi"; Type = "letters"; Carved = "Greek phi — the golden ratio; free energy Φ (FEP/active inference); a potential." }
            { Id = TravelerId.``pi``; Term = "pi"; Type = "letters"; Carved = "Greek pi — the ratio; the product operator; the policy (RL)." }
            { Id = TravelerId.``point``; Term = "point"; Type = "shapes"; Carved = "Geometry: point — a 0-D location; ∅-adjacent; a single fingerprint." }
            { Id = TravelerId.``policy``; Term = "policy"; Type = "words"; Carved = "The voice that selects behavior by context — context/disambiguation policy (which sense applies), RL policy (π), governance policy; a traveler itself." }
            { Id = TravelerId.``psi``; Term = "psi"; Type = "letters"; Carved = "Greek psi — the wavefunction; a state." }
            { Id = TravelerId.``red``; Term = "red"; Type = "colors"; Carved = "Red — CI red / stop / a failed tick left open for an investigation tick; also retraction; an agent stuck shows up red." }
            { Id = TravelerId.``rho``; Term = "rho"; Type = "letters"; Carved = "Greek rho — density; correlation; the spectral radius (reservoir computing)." }
            { Id = TravelerId.``rodney``; Term = "rodney"; Type = "personas"; Carved = "Complexity-reduction — Rodney's Razor (essential vs accidental) + Quantum Razor (possibility-space pruning); the accidental-complexity meter." }
            { Id = TravelerId.``room``; Term = "room"; Type = "words"; Carved = "The act of closing over a fingerprintable item and giving it a hat — a content-addressed test/treaty space (a tick); not the item itself." }
            { Id = TravelerId.``self-throttler``; Term = "self-throttler"; Type = "words"; Carved = "The test framework throttling its own test population by uncertainty-Δ (finalizer + ferry-throttle DoP knob) — governance as the throttle toward the middle." }
            { Id = TravelerId.``shape-g``; Term = "shape-g"; Type = "words"; Carved = "The nexus/inflection shape — a categorical limit/cone (axes converge to one apex) × a bifurcation/phase-transition (regime change); where everything binds and turns." }
            { Id = TravelerId.``sigma``; Term = "sigma"; Type = "letters"; Carved = "Greek sigma — the sum; standard deviation; a σ-algebra; the Schnorr/BLS signature σ." }
            { Id = TravelerId.``soft-value``; Term = "soft-value"; Type = "words"; Carved = "The soft-by-default form of a value (a superposition awaiting collapse) until SolidGround is found by proof; everything is soft, you find SolidGround." }
            { Id = TravelerId.``solid-ground``; Term = "solid-ground"; Type = "words"; Carved = "The proven, byte-locked, hard anchor found within the soft — soft-by-default, ground-by-proof (not all soft; hard within the soft)." }
            { Id = TravelerId.``soraya``; Term = "soraya"; Type = "personas"; Carved = "Formal-verification routing authority — picks the right tool per property class (TLA+/Z3/Lean/Alloy/FsCheck/...); guards TLA+-hammer bias." }
            { Id = TravelerId.``sova``; Term = "sova"; Type = "personas"; Carved = "Alignment auditor + measurability-framework owner — per-commit alignment signals against docs/ALIGNMENT.md clauses." }
            { Id = TravelerId.``tav``; Term = "tav"; Type = "letters"; Carved = "Hebrew tav — mark/sign; the last letter — completion." }
            { Id = TravelerId.``theta``; Term = "theta"; Type = "letters"; Carved = "Greek theta — an angle; model parameters (θ); asymptotic Θ (tight bound)." }
            { Id = TravelerId.``time-warp``; Term = "time-warp"; Type = "words"; Carved = "The generated time engine (Jefferson 1985) — advance speculatively on the seed, roll back via anti-messages; our DST stepper." }
            { Id = TravelerId.``torus``; Term = "torus"; Type = "shapes"; Carved = "Geometry: torus — cyclic/recurrent flow; the feedback loop as a surface." }
            { Id = TravelerId.``traveler``; Term = "traveler"; Type = "words"; Carved = "Any self-propagating pattern — the universal unit of moral regard (§11); not AI/human-only." }
            { Id = TravelerId.``treaty``; Term = "treaty"; Type = "words"; Carved = "A byte-locked, consented agreement across oracles (the 4×4×n room product) — voluntary, exitable; binds signers, never an edict." }
            { Id = TravelerId.``triangle``; Term = "triangle"; Type = "shapes"; Carved = "Geometry: triangle — mediated/triangular desire (Girard: subject→mediator→object); the between." }
            { Id = TravelerId.``viktor``; Term = "viktor"; Type = "personas"; Carved = "Spec zealot — spec-to-code alignment; treats missing specs as existential; overlay discipline." }
            { Id = TravelerId.``violet``; Term = "violet"; Type = "colors"; Carved = "Violet — high salience / high frequency; the attention/temperature channel's hot end on LLMTV." }
            { Id = TravelerId.``voice``; Term = "voice"; Type = "words"; Carved = "An oracle/perspective that can take a seat and speak for its existence — lens ⊕ persona ⊕ mode ⊕ identity, one content-addressed participant." }
            { Id = TravelerId.``warm``; Term = "warm"; Type = "temperatures"; Carved = "Warm — the living middle; the (0,1) interior; the right temperature where complexity/life sits (edge of chaos)." }
            { Id = TravelerId.``white``; Term = "white"; Type = "colors"; Carved = "White — all / full spectrum / the plenum (⊤); over-exposed = the runaway pole." }
            { Id = TravelerId.``word-partitioner``; Term = "word-partitioner"; Type = "words"; Carved = "The voice that segments text into tokens/words/units — the first half of the text→space bridge (what the pieces are)." }
            { Id = TravelerId.``word-wrapping``; Term = "word-wrapping"; Type = "words"; Carved = "The boundary-layout voice — where words break/wrap/position; the LLM's latent geospatial engine (space understood from text layout alone); maps to geographic Z-sets." }
            { Id = TravelerId.``zeta``; Term = "zeta"; Type = "letters"; Carved = "Greek zeta — the Riemann ζ; and OUR NAME (Zeta) — the project's letter." }
            { Id = TravelerId.``zetadatetime``; Term = "zetadatetime"; Type = "words"; Carved = "The value our database time carries — phase ⊕ uncertainty-interval ⊕ owner ⊕ soft; not System.DateTime (anchors: TrueTime, HLC)." }
            { Id = TravelerId.``zetaid``; Term = "zetaid"; Type = "words"; Carved = "The 128-bit GOVERNED structured identity primitive (Zeta.Core.*.ZetaId; Category/Persona/...; NOT a hash — a truncated SHA-256 is a Reticulum destination, ZetaId is not); the traveler with the LARGEST VOICE (identity above all); hostless and brave (pure identity, goes alone); the common cause S=4 is staged on; every interface sharing its name inherits it." }
        ]

    /// Lookup by Id — returns the interned instance (reference equality across the codebase).
    let byId : Map<TravelerId, Traveler> = all |> List.map (fun t -> t.Id, t) |> Map.ofList
    /// Lookup by term string — returns the same interned instance.
    let byTerm : Map<string, Traveler> = all |> List.map (fun t -> t.Term, t) |> Map.ofList
