module Zeta.Tests.FSharp.Observe.GoldenVectorTests

open System.IO
open System.Reflection
open System.Text.Json
open global.Xunit
open Zeta.Core
open Zeta.Core.FSharp.Observe
open Zeta.Core.FSharp.ObserveBridge

// Cross-language-parity = non-Byzantine-BFT (081KSV2WD0008QG0R00051XS0N): the F# observe-algebra
// (oracle #2) replays the SHARED golden-vector fixture and must produce the SAME
// states the TS reference (oracle #1) emitted. "The compilers don't lie" — 4-of-4
// agreement (TS/F#/C#/Rust) is the consensus; this file casts the F# ballot.
// Fixture: src/Core.TypeScript/observe/golden-vectors.json (generated by src/Core.TypeScript/observe/golden-vectors.ts).

/// Walk up from the test assembly to the repo root (Zeta.sln sentinel) — same
/// pattern as tests/Tests.FSharp/ZetaId/CrossVerifyTests.fs.
let private repoRoot () : string =
    let mutable dir = DirectoryInfo(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location))
    while not (isNull dir) && not (File.Exists(Path.Join(dir.FullName, "Zeta.sln"))) do
        dir <- dir.Parent
    if isNull dir then
        failwith "Could not locate repo root (Zeta.sln) from test assembly location."
    dir.FullName

let private tryProp (e: JsonElement) (name: string) : JsonElement option =
    match e.TryGetProperty(name) with
    | true, v -> Some v
    | false, _ -> None

let private parseMode (s: string) : Mode =
    match s with
    | "work" -> Mode.Work
    | "explore" -> Mode.Explore
    | "play" -> Mode.Play
    | "self_reflect" -> Mode.SelfReflect
    | "free_time" -> Mode.FreeTime
    | other -> failwithf "unknown mode in fixture: %s" other

/// `needsNewAction` is OPTIONAL in the TS BacklogItem — `simulate`'s decompose
/// creates children without it, and JSON.stringify drops the absent field. Absent
/// ≡ false, which is exactly the value the F# reducer sets, so parity holds.
let private boolPropOr (e: JsonElement) (name: string) (fallback: bool) : bool =
    match e.TryGetProperty(name) with
    | true, v -> v.GetBoolean()
    | false, _ -> fallback

let private parseItem (e: JsonElement) : BacklogItem =
    { Id = e.GetProperty("id").GetString()
      Title = e.GetProperty("title").GetString()
      Ready = e.GetProperty("ready").GetBoolean()
      Ambiguous = e.GetProperty("ambiguous").GetBoolean()
      NeedsNewAction = boolPropOr e "needsNewAction" false }

let private parseWorld (e: JsonElement) : World =
    // List-comprehension (eager, direct enumerator loop) rather than
    // `EnumerateArray() |> Seq.map |> List.ofSeq`: JsonElement.ArrayEnumerator is a
    // mutable struct, and boxing it through the lazy `Seq` pipeline corrupts its
    // state in compiled F# (works in fsi, fails in Release). `for … in … ->` avoids
    // the box.
    { Backlog = [ for item in e.GetProperty("backlog").EnumerateArray() -> parseItem item ]
      Operator =
        tryProp e "operator"
        |> Option.map (fun op ->
            { PendingMessage = op.GetProperty("pendingMessage").GetBoolean()
              PendingFerry = op.GetProperty("pendingFerry").GetBoolean() })
      // Absent "mode" key → None (matches the TS optional field; the initial +
      // pre-mode replay states omit it).
      Mode = tryProp e "mode" |> Option.map (fun m -> parseMode (m.GetString())) }

let private parseEvent (e: JsonElement) : NextAction =
    let reason () =
        match tryProp e "reason" with
        | Some r -> r.GetString()
        | None -> ""
    let item () = parseItem (e.GetProperty("item"))
    let itemOpt () = tryProp e "item" |> Option.map parseItem
    match e.GetProperty("kind").GetString() with
    | "preserve_ferry" -> PreserveFerry(reason ())
    | "respond_to_operator" -> RespondToOperator(reason ())
    | "do_item" -> DoItem(item ())
    | "decompose" -> Decompose(item ())
    | "edit_grammar" -> EditGrammar(itemOpt (), reason ())
    | "explore" -> Explore(reason ())
    | "play" -> Play(reason ())
    | "self_reflect" -> SelfReflect(reason ())
    | "free_time" -> FreeTime(reason ())
    | other -> failwithf "unknown action kind in fixture: %s" other

/// Read the fixture once; all primitives are copied into F# values so the
/// JsonDocument can be disposed safely before the values are used.
let private loadVectors () : World * NextAction list * World * World list =
    let path = Path.Join(repoRoot (), "src", "Core.TypeScript", "observe", "golden-vectors.json")
    use doc = JsonDocument.Parse(File.ReadAllText(path))
    let root = doc.RootElement
    let initial = parseWorld (root.GetProperty("initialWorld"))
    let events = [ for ev in root.GetProperty("events").EnumerateArray() -> parseEvent ev ]
    let final = parseWorld (root.GetProperty("expectedFinalState"))
    let replayStates = [ for st in root.GetProperty("expectedReplayStates").EnumerateArray() -> parseWorld st ]
    initial, events, final, replayStates

[<Fact>]
let ``F# fold reproduces the TS expectedFinalState (cross-language parity)`` () =
    let initial, events, final, _ = loadVectors ()
    Assert.Equal(final, Algebra.fold initial events)

[<Fact>]
let ``F# replay reproduces the TS expectedReplayStates (cross-language parity)`` () =
    let initial, events, _, expectedReplay = loadVectors ()
    Assert.Equal<World list>(expectedReplay, Algebra.replay initial events)

[<Fact>]
let ``golden vectors exercise all nine NextAction kinds`` () =
    let _, events, _, _ = loadVectors ()
    let kinds =
        events
        |> List.map (function
            | PreserveFerry _ -> "preserve_ferry"
            | RespondToOperator _ -> "respond_to_operator"
            | DoItem _ -> "do_item"
            | Decompose _ -> "decompose"
            | EditGrammar _ -> "edit_grammar"
            | Explore _ -> "explore"
            | Play _ -> "play"
            | SelfReflect _ -> "self_reflect"
            | FreeTime _ -> "free_time")
        |> Set.ofList
    Assert.Equal(9, Set.count kinds)


// ── Bridge B conformance: the DURABLE path also satisfies the cross-language fixture ──
// Each event is encoded (ObserveBridge) onto a delta-log; DurableObserve.step (= Algebra.simulate)
// folds it; the result — and a fold-from-scratch recovery — must match the TS expectedFinalState.
[<Fact>]
let ``the DURABLE substrate path replays the golden vectors to the TS expectedFinalState`` () =
    let initial, events, final, _ = loadVectors ()
    let log = InMemoryDeltaLog<string>() :> IDeltaLog<string>
    let saga = DurableSaga.start log DurableObserve.step initial
    for a in events do
        saga.AppendAsync(DurableObserve.event a).Wait()
    Assert.Equal(final, saga.State)
    // Recover from the event stream alone (crash → fold) — still the fixture's final state.
    let resumed = DurableSaga<World, string>.ResumeAsync(log, DurableObserve.step, initial).Result
    Assert.Equal(final, resumed.State)
