/**
 * EvidenceSourceManifestPage — GitHub Pages finite provenance table.
 * Design: source-owned catalog order and fixed locator display only; no fetch or validation.
 */
import { EVIDENCE_SOURCE_COMMIT, evidenceSourceBlob, evidenceSourceUrl, SPECTRUM } from "@/components/EvidenceSeamPanel";

const labelStyle = { color: "var(--muted-foreground)", fontSize: "0.5rem", letterSpacing: "0.12em", textTransform: "uppercase" as const };

export default function EvidenceSourceManifestPage() {
  return <main style={{ background: "var(--background)", color: "var(--foreground)", fontFamily: "'JetBrains Mono', monospace", minHeight: "100vh", padding: "clamp(0.55rem, 1.5vw, 1.25rem)" }}><div className="evidence-room-shell" style={{ margin: "0 auto", maxWidth: 1120 }}>
    <nav aria-label="Evidence navigation" className="grid grid-cols-1 items-center gap-x-4 gap-y-2 border-b border-border pb-2 sm:grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)]" style={{ marginBottom: "1.2rem" }}><a href="#/evidence-seam" className="sm:justify-self-start" style={{ color: "var(--amber-dim)", fontSize: "0.56rem", letterSpacing: "0.08em", textDecoration: "none" }}>← EVIDENCE ROOM</a><div style={{ display: "grid", gap: "0.22rem", justifyItems: "center" }}><span className="evidence-room-wordmark">ZETA//IDENTITY-SPACE::PROOF-ENGINE</span><span style={{ color: "var(--muted-foreground)", fontSize: "0.42rem", letterSpacing: "0.15em" }}>SOURCE MANIFEST · FINITE MAPPING TABLE</span></div><span className="sm:justify-self-end sm:text-right" style={{ color: "var(--muted-foreground)", fontSize: "0.5rem", letterSpacing: "0.07em" }}>PAGES MIRROR · NO DOCUMENT FETCH</span></nav>
    <section aria-labelledby="manifest-title" style={{ background: "oklch(0.052 0.008 265)", border: "1px solid var(--border)", overflow: "hidden", position: "relative" }}><div style={{ padding: "clamp(1.1rem, 4vw, 3rem)" }}><div style={{ ...labelStyle, color: "var(--teal)" }}>finite provenance index · source-owned locators</div><h1 id="manifest-title" style={{ color: "var(--amber)", fontSize: "clamp(1.9rem, 5.5vw, 4.6rem)", letterSpacing: "-0.085em", lineHeight: 0.86, margin: "0.65rem 0 0.9rem" }}>SOURCE MANIFEST</h1><p style={{ color: "var(--muted-foreground)", fontSize: "0.67rem", lineHeight: 1.65, margin: 0, maxWidth: "70ch" }}>Bounded receipts. Pinned locators. No source-content judgment.</p>
      <div style={{ background: "var(--border)", display: "grid", gap: "1px", gridTemplateColumns: "repeat(auto-fit, minmax(150px, 1fr))", margin: "1.1rem 0" }}>{[["declared receipts", String(SPECTRUM.length).padStart(2, "0")], ["catalog order", "RETAINED"], ["pinned commit", EVIDENCE_SOURCE_COMMIT.slice(0, 12)], ["document fetch", "REFUSED"]].map(([label, value], index) => <div key={label} style={{ background: "oklch(0.06 0.009 265)", padding: "0.65rem 0.75rem" }}><div style={labelStyle}>{label}</div><div style={{ color: index === 0 ? "var(--amber)" : index === 3 ? "var(--teal)" : "var(--foreground)", fontSize: index === 0 ? "1.15rem" : "0.58rem", fontWeight: 900, letterSpacing: "0.07em", marginTop: "0.28rem" }}>{value}</div></div>)}</div>
      <div style={{ background: "var(--border)", display: "grid", gap: "1px" }}>{SPECTRUM.map((receipt, index) => { const sourceUrl = evidenceSourceUrl(receipt.sourcePath); const sourceBlob = evidenceSourceBlob(receipt.sourcePath); return <article key={receipt.id} className="grid grid-cols-1 gap-x-4 gap-y-3 md:grid-cols-[minmax(0,0.9fr)_minmax(0,1.2fr)_minmax(0,1.9fr)]" style={{ background: "oklch(0.06 0.009 265)", borderLeft: index % 3 === 0 ? "3px solid var(--amber)" : "3px solid var(--cold)", padding: "0.8rem" }}><div><div style={labelStyle}>manifest row · {String(index + 1).padStart(2, "0")}</div><a href={`#/evidence-seam/receipt/${receipt.id}`} style={{ color: receipt.tone, display: "inline-block", fontSize: "0.62rem", fontWeight: 800, letterSpacing: "0.055em", marginTop: "0.32rem", textDecoration: "none" }}>{receipt.id}</a><div style={{ color: "var(--muted-foreground)", fontSize: "0.55rem", lineHeight: 1.45, marginTop: "0.25rem" }}>{receipt.lane}</div></div><div style={{ minWidth: 0 }}><div style={labelStyle}>repository source path</div><div style={{ color: "var(--foreground)", fontSize: "0.53rem", lineHeight: 1.45, marginTop: "0.35rem", overflowWrap: "anywhere" }}>{receipt.sourcePath ?? "NOT DECLARED"}</div></div><div style={{ minWidth: 0 }}><div style={labelStyle}>pinned Git object</div><div style={{ color: "var(--muted-foreground)", fontSize: "0.5rem", lineHeight: 1.55, marginTop: "0.35rem", overflowWrap: "anywhere" }}>COMMIT · {EVIDENCE_SOURCE_COMMIT}</div><div style={{ color: sourceBlob === undefined ? "var(--teal)" : "var(--muted-foreground)", fontSize: "0.5rem", lineHeight: 1.55, overflowWrap: "anywhere" }}>BLOB SHA-1 · {sourceBlob ?? "NOT DECLARED"}</div>{sourceUrl === undefined ? null : <a href={sourceUrl} target="_blank" rel="noopener noreferrer" style={{ color: "var(--amber-dim)", display: "inline-block", fontSize: "0.48rem", fontWeight: 800, letterSpacing: "0.08em", marginTop: "0.35rem", textDecoration: "none" }}>OPEN PINNED SOURCE ↗</a>}</div></article>; })}</div>
    </div></section>
  </div></main>;
}
