namespace Zeta.Core.FSharp.ObserveBridge

open System.Threading
open System.Threading.Tasks
open Zeta.Core.FSharp.Observe

/// **Bridge D (pure layer) — the execution layer: NextAction → Effects, inspect-before-execute.**
///
/// Design call D1 (maintainer, 2026-06-07): effects are the **outward** half only — the World
/// *state* fold stays in Bridge B (`DurableObserve`). This module is the PURE part: a typed
/// `Effect` taxonomy, a pure `effectsOf : NextAction -> World -> Effect list`, and an
/// `IEffectHandler` port whose contract is **inspect-before-execute** (the shadow *proposes* an
/// effect; the handler *inspects* + *admits* before executing — `source≠authorization`, so no
/// effect auto-executes). The ONLY git/gh-touching code will be the substrate-backed handler
/// adapter (a follow-on); everything else just emits `Effect`s.
///
/// Honest-async: the port is async (`ValueTask`) because the real substrate handler does I/O
/// (git via Core.Git, the operator bus). The `RecordingHandler` here is genuinely synchronous,
/// so it returns completed `ValueTask`s — truthful, not Task.Run fakery.
[<RequireQualifiedAccess>]
module Effects =

    /// The outward effects an action can imply. Payloads the pure layer KNOWS are carried
    /// (the backlog item); payloads sourced from a live channel or generated by the agent are
    /// markers the handler fills (ferry content from the bus; the operator response from the LLM).
    type Effect =
        /// preserve_ferry — persist the operator's ferried verbatim content (handler reads it
        /// from the channel and writes it durably via Core.Git, never raw git).
        | PersistFerry
        /// respond_to_operator — the handler/agent generates + sends the response on the bus.
        | EmitResponse
        /// do_item — the agent does the item's real work (the open-ended handler responsibility).
        | RunWork of item: BacklogItem
        /// edit_grammar — sovereign grammar extension for the target item.
        | ExtendGrammar of item: BacklogItem

    /// Pure mapping action → outward effects. Decompose is pure state (handled by `simulate`);
    /// the free modes have no outward effect; `EditGrammar None` targets nothing. (World is
    /// reserved for future world-dependent effects.)
    let effectsOf (action: NextAction) (_world: World) : Effect list =
        match action with
        | PreserveFerry _ -> [ PersistFerry ]
        | RespondToOperator _ -> [ EmitResponse ]
        | DoItem i -> [ RunWork i ]
        | EditGrammar(Some i, _) -> [ ExtendGrammar i ]
        | EditGrammar(None, _) -> []
        | Decompose _ -> []
        | Explore _
        | Play _
        | SelfReflect _
        | FreeTime _ -> []

    /// The inspect verdict — the capability gate. `Deny` carries why.
    type Verdict =
        | Admit
        | Deny of reason: string

    /// The outcome of running an effect.
    type EffectResult =
        | Executed
        | Skipped of reason: string
        | Failed of reason: string

    /// The effect-handler port. `InspectAsync` is the capability / inspect-before-execute gate;
    /// `ExecuteAsync` runs the effect (only ever called after `Admit`). The substrate-backed
    /// adapter (git/bus) is the only impl that touches the outside world.
    type IEffectHandler =
        abstract InspectAsync: effect: Effect * ct: CancellationToken -> ValueTask<Verdict>
        abstract ExecuteAsync: effect: Effect * ct: CancellationToken -> ValueTask<EffectResult>

    /// Run one effect through the gate: inspect → (admit ⇒ execute | deny ⇒ skip). A denied
    /// effect is NEVER executed — the load-bearing inspect-before-execute guarantee.
    let runAsync (handler: IEffectHandler) (effect: Effect) (ct: CancellationToken) : Task<EffectResult> =
        task {
            match! handler.InspectAsync(effect, ct).AsTask() with
            | Admit -> return! handler.ExecuteAsync(effect, ct).AsTask()
            | Deny r -> return Skipped("denied by inspect: " + r)
        }

    /// A recording handler for tests/DST: captures executed effects, performs no real I/O.
    /// Optional `policy` decides the verdict per effect (default: admit all). Genuinely
    /// synchronous → completed `ValueTask`s (truthful, not Task.Run-over-sync).
    [<Sealed>]
    type RecordingHandler(?policy: Effect -> Verdict) =
        let recorded = ResizeArray<Effect>()
        let policy = defaultArg policy (fun _ -> Admit)
        /// Effects that were actually executed (admitted), in order.
        member _.Recorded : Effect list = List.ofSeq recorded

        interface IEffectHandler with
            member _.InspectAsync(effect, _ct) = ValueTask<Verdict>(policy effect)

            member _.ExecuteAsync(effect, _ct) =
                recorded.Add effect
                ValueTask<EffectResult>(Executed)
