/**
 * build-clifford-e8-page.ts — emit the browser bundle the viewable page loads.
 *
 *     bun src/Core.TypeScript/research/build-clifford-e8-page.ts
 *
 * Bundles `clifford-e8-browser-entry.ts` — and through it the whole rung 1-7 ladder — into
 * `demo/clifford-e8/clifford-e8-substrate.js` as a classic IIFE script, so the page works
 * from a plain `file://` open as well as from GitHub Pages.
 *
 * ## Why the page carries CODE and not GEOMETRY
 *
 * The alternative was to precompute the buffers and ship them. The numbers say not to:
 *
 * | shipped as | bytes |
 * |---|---|
 * | 60,480 triangles as `float32` positions | 2,177,280 |
 * | the same, as 8-bit vertex indices + 240 points | 184,320 |
 * | **the derivation that produces them** | **the size of this bundle** |
 *
 * The derivation is smaller than any encoding of its own output, and it is the only form
 * that stays true when a rung changes. It also keeps the repo's proof lineage textual with
 * nothing to argue about: a committed geometry blob would be a golden vector nothing
 * checks, whereas committed *source* is read by a bundler and by a reviewer alike.
 *
 * The generated bundle is text, diffable, and reproducible from committed sources by
 * re-running this script — the three conditions `no-binary-in-proof-lineage` asks of any
 * generated artefact that lives in the tree.
 */

import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";

/** Where the page and its bundle live, relative to the repository root. */
export const PAGE_DIRECTORY = join("demo", "clifford-e8");

/** The generated bundle's file name. */
export const BUNDLE_FILE = "clifford-e8-substrate.js";

/** The banner prepended to the bundle so a reader lands on the provenance, not on minified code. */
export const BUNDLE_BANNER = [
  "// GENERATED by src/Core.TypeScript/research/build-clifford-e8-page.ts -- do not edit.",
  "// This is the Clifford/E8 rung 1-7 TypeScript with its types erased and its modules",
  "// linked. Every vertex, face and shading level the page draws is computed HERE, in the",
  "// browser, by the same functions the test suite runs. Nothing is precomputed and no",
  "// coordinate is authored. Regenerate with:",
  "//   bun src/Core.TypeScript/research/build-clifford-e8-page.ts",
].join("\n");

/** Bundle the browser entry and return the script text, banner included. */
export async function buildBundle(repositoryRoot: string): Promise<string> {
  const entry = join(repositoryRoot, "src", "Core.TypeScript", "research", "clifford-e8-browser-entry.ts");
  const built = await Bun.build({
    entrypoints: [entry],
    target: "browser",
    format: "iife",
    minify: false,
    sourcemap: "none",
  });
  if (!built.success) throw new Error(`bundle failed: ${built.logs.map((l) => String(l)).join("; ")}`);
  const output = built.outputs[0];
  if (output === undefined) throw new Error("bundle produced no output");
  return `${BUNDLE_BANNER}\n${await output.text()}`;
}

if (import.meta.main) {
  const root = join(dirname(new URL(import.meta.url).pathname), "..", "..", "..");
  const target = join(root, PAGE_DIRECTORY, BUNDLE_FILE);
  await mkdir(join(root, PAGE_DIRECTORY), { recursive: true });
  const text = await buildBundle(root);
  await Bun.write(target, text);
  process.stdout.write(`wrote ${target} (${text.length} bytes)\n`);
}
