#!/usr/bin/env bun
// oracle-stack-evidence — generate 081KTZ4EF0008QG0R0035FW7HY's evidence appendix from AgencySignature trailers.
// The trailers live in SQUASH BODIES on main; every factory commit carries one (10 fields), so
// the paper's evidence table is MECHANICAL: parse, filter to the oracle-stack window, group by
// register/intent, emit markdown with PR links. Reusable for any future writeup window.
//
// Usage: bun src/Core.TypeScript/research/oracle-stack-evidence.ts [--since "2026-06-10 00:00"] [--until now]
// (explicit times: git approxidate mis-parses some bare dates — found on first run)

import { execSync } from "node:child_process";

const args = new Map<string, string>();
for (let i = 2; i < process.argv.length; i += 2) {
  const k = process.argv[i];
  const v = process.argv[i + 1];
  if (k?.startsWith("--") && v) args.set(k.slice(2), v);
}
const since = args.get("since") ?? "2026-06-10 00:00";
const until = args.get("until") ?? "now";

const SEP = "COMMIT";
const raw = execSync(
  `git log origin/main --since="${since}" --until="${until}" --format='${SEP}%H%x09%ad%x09%s%n%b' --date=short`,
  { encoding: "utf8", maxBuffer: 64 * 1024 * 1024 },
);

interface Entry {
  sha: string;
  date: string;
  subject: string;
  pr: string | null;
  fields: Record<string, string>;
}

const entries: Entry[] = [];
for (const chunk of raw.split(SEP)) {
  if (!chunk.trim()) continue;
  const headerEnd = chunk.indexOf("\n");
  const header = headerEnd === -1 ? chunk : chunk.slice(0, headerEnd);
  const body = headerEnd === -1 ? "" : chunk.slice(headerEnd + 1);
  const [sha, date, subject] = header.split("\t");
  if (!sha || !date || subject === undefined) continue;
  const sigIdx = body.indexOf("AgencySignature-v1:");
  if (sigIdx === -1) continue;
  const fields: Record<string, string> = {};
  for (const line of body.slice(sigIdx).split("\n").slice(1)) {
    const m = line.match(/^\s{2}([a-z-]+):\s*(.+)$/);
    if (!m) break; // trailer block ends at the first non-field line
    const key = m[1];
    const value = m[2];
    if (key !== undefined && value !== undefined) fields[key] = value;
  }
  const prMatch = subject.match(/\(#(\d+)\)\s*$/);
  entries.push({ sha: sha.slice(0, 9), date, subject, pr: prMatch?.[1] ?? null, fields });
}

// group by date, then list — the appendix's spine; per-entry: PR, intent, register, build line
const byDate = new Map<string, Entry[]>();
for (const e of entries) {
  const bucket = byDate.get(e.date) ?? [];
  bucket.push(e);
  byDate.set(e.date, bucket);
}

const lines: string[] = [
  "# 081KTZ4EF0008QG0R0035FW7HY evidence appendix — generated from AgencySignature trailers",
  "",
  `Window: ${since}..${until} · ${entries.length} signed commits on origin/main · generated by`,
  "`src/Core.TypeScript/research/oracle-stack-evidence.ts` (re-run any time; the appendix is mechanical, never hand-curated).",
  "",
];
for (const [date, bucket] of [...byDate.entries()].sort()) {
  lines.push(`## ${date} (${bucket.length} signed commits)`, "");
  for (const e of bucket) {
    const pr = e.pr ? `#${e.pr}` : e.sha;
    lines.push(`- **${pr}** ${e.subject.replace(/\s*\(#\d+\)\s*$/, "")}`);
    if (e.fields["intent"]) lines.push(`  - intent: ${e.fields["intent"]}`);
    if (e.fields["register"]) lines.push(`  - register: ${e.fields["register"]}`);
    if (e.fields["build"]) lines.push(`  - build: ${e.fields["build"]}`);
  }
  lines.push("");
}
console.log(lines.join("\n"));
