# full-ai-cluster/nixos/modules/longhorn-disks.nix
#
# Declarative wiring between local filesystem mounts and the
# Longhorn node-level data-path catalog.
#
# Usage in a per-host config (already auto-wired by the
# disko-shapes/longhorn-node.nix shape):
#
#     zeta.longhorn.dataDisks = [
#       "/var/lib/longhorn-disk1"
#       "/var/lib/longhorn-disk2"
#     ];
#
# What this module does:
#
#   1. Ensures the mount directories exist with permissions Longhorn
#      expects (0755 root:root).
#   2. Emits a Longhorn Node CR annotation file per host under
#      /etc/longhorn/node-disks-<host>.yaml that the cluster-side
#      Longhorn deployment can pick up to extend the Node CR with
#      the extra data paths (the default chart only knows about
#      `/var/lib/longhorn`; multi-path nodes need explicit `disks`
#      entries on the Node CR).
#   3. Adds the K3S node label `zeta.io/longhorn-disks=<N>` so the
#      scheduler can target high-capacity nodes.
#
# Cluster-side companion: the longhorn Application under
# k8s/applications/longhorn/ runs a small post-install Job that
# reads /etc/longhorn/node-disks-*.yaml from each node (via a
# DaemonSet that mounts /etc/longhorn) and patches the Node CRs.
# (TODO once first physical node is up — for now, run
# `kubectl -n longhorn-system edit node <hostname>` to add the
# extra disks; the YAML on disk is the documented intent.)

{ config, lib, pkgs, ... }:

let
  cfg = config.zeta.longhorn;
in
{
  options.zeta.longhorn = {
    dataDisks = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ "/var/lib/longhorn" ];
      description = ''
        Filesystem paths that Longhorn should use as data paths on
        this node. Each path must already be a mountpoint backed by
        a real partition (typically declared via the disko-shape).
        The first entry IS Longhorn's defaultDataPath; additional
        entries get added to the Node CR as named disks.
      '';
      example = [ "/var/lib/longhorn-disk1" "/var/lib/longhorn-disk2" ];
    };
  };

  config = lib.mkIf (cfg.dataDisks != [ ]) {
    # 1. Make sure each mount directory exists with the right perms
    #    before kubelet / Longhorn try to access them.
    systemd.tmpfiles.rules = lib.concatMap (path: [
      "d ${path} 0755 root root - -"
    ]) cfg.dataDisks;

    # 2. Drop the documented intent on disk for the cluster-side
    #    Job to consume. The data the cluster-side companion needs
    #    is just "hostname -> list of mount paths" — keep it simple.
    environment.etc."longhorn/node-disks.yaml".text = ''
      # Auto-generated by zeta.longhorn module — do not edit by hand.
      # The cluster-side longhorn application reads this to patch
      # Node CRs with the multi-disk catalog.
      apiVersion: longhorn.io/v1beta2
      kind: NodeDiskCatalog
      metadata:
        name: ${config.networking.hostName}
      spec:
        host: ${config.networking.hostName}
        disks:
      ${lib.concatMapStrings (path: ''
            - path: ${path}
              allowScheduling: true
              storageReserved: 0
              tags: []
      '') cfg.dataDisks}
    '';

    # 3. K3S node label so the scheduler can target high-capacity
    #    nodes. extraFlags uses mkAfter to compose with whatever
    #    the host config already passes.
    services.k3s.extraFlags = lib.mkAfter [
      "--node-label=zeta.io/longhorn-disks=${toString (lib.length cfg.dataDisks)}"
    ];
  };
}
