apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: flowdent-web
  namespace: flowdent-web
  labels:
    app.kubernetes.io/name: flowdent-web
    app.kubernetes.io/part-of: flowdent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: flowdent-web
