using System;
using System.Collections.Generic;
using System.Text;

namespace Zeta.Core.CSharp;

/// <summary>
/// Emits Rust <c>struct</c> source from the SAME <see cref="TypeSchema"/> IR that
/// <see cref="SchemaCodegen"/> renders to C# — the concrete demonstration of "one IR, a typed
/// surface per language oracle." The field-type vocabulary in the schema is the neutral baseline
/// (C#-shaped: <c>string</c>, <c>int</c>, <c>int?</c>, <c>long</c>, <c>bool</c>, <c>double</c>, …);
/// this codegen maps it to Rust idioms — nullable <c>T?</c> → <c>Option&lt;T&gt;</c>, and
/// PascalCase field names → <c>snake_case</c> per Rust convention — while the struct name stays
/// PascalCase. Pure + deterministic (explicit <c>\n</c> line endings → byte-lockable), no F# dep.
/// </summary>
public static class RustSchemaCodegen
{
    // Neutral (C#-baseline) type token -> Rust type. Nullable tokens map to Option&lt;T&gt;.
    private static readonly Dictionary<string, string> RustTypes = new(StringComparer.Ordinal)
    {
        ["string"] = "String",
        ["int"] = "i32",
        ["int?"] = "Option<i32>",
        ["long"] = "i64",
        ["long?"] = "Option<i64>",
        ["bool"] = "bool",
        ["bool?"] = "Option<bool>",
        ["double"] = "f64",
        ["double?"] = "Option<f64>",
    };

    /// <summary>Generate a Rust <c>struct</c> declaration for the schema's type.</summary>
    /// <param name="schema">The type schema (IR) to render — the same value <see cref="SchemaCodegen"/> consumes.</param>
    /// <returns>Compilable Rust source for the struct, prefixed with a generated header.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="schema"/> is <see langword="null"/>.</exception>
    /// <exception cref="NotSupportedException">A field carries a type token outside the neutral vocabulary.</exception>
    public static string Generate(TypeSchema schema)
    {
        ArgumentNullException.ThrowIfNull(schema);

        var sb = new StringBuilder();
        sb.Append("// @generated by Zeta.Core.CSharp.RustSchemaCodegen from a zeta type schema. Do not edit.\n");
        sb.Append("#[derive(Debug, Clone, PartialEq)]\n");
        sb.Append("pub struct ").Append(schema.TypeName).Append(" {\n");

        foreach (SchemaField field in schema.Fields)
        {
            if (!RustTypes.TryGetValue(field.CsType, out string? rustType))
            {
                throw new NotSupportedException(
                    $"No Rust mapping for type token '{field.CsType}' (field '{field.Name}'). Extend RustSchemaCodegen.RustTypes.");
            }

            sb.Append("    pub ").Append(ToSnakeCase(field.Name)).Append(": ").Append(rustType).Append(",\n");
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    /// <summary>PascalCase / camelCase identifier to Rust <c>snake_case</c> (e.g. <c>BirthYear</c> → <c>birth_year</c>).</summary>
    private static string ToSnakeCase(string name)
    {
        var sb = new StringBuilder(name.Length + 4);
        for (var i = 0; i < name.Length; i++)
        {
            char c = name[i];
            if (char.IsUpper(c))
            {
                if (i > 0)
                {
                    sb.Append('_');
                }

                sb.Append(char.ToLowerInvariant(c));
            }
            else
            {
                sb.Append(c);
            }
        }

        return sb.ToString();
    }
}
