using System;
using System.Text;

namespace Zeta.Core.CSharp;

/// <summary>
/// Emits C# <c>record</c> source from a <see cref="TypeSchema"/> — the C#-native "codegen from IR"
/// leg of the typed-surface story (approach B). It mirrors the TypeScript <c>codegen-from-ir</c>
/// harness: the same language-neutral schema generalizes to a typed surface per oracle, so every
/// language gets the same generative feature. Unlike a Roslyn source generator (approach A) this is
/// a plain library — no <c>FSharp.TypeProviders.SDK</c>, no <c>Microsoft.CodeAnalysis</c>, no
/// netstandard2.0 / design-time-assembly constraints — and the emitted <c>.cs</c> is C#-consumable
/// with no F# dependency.
/// <para>
/// Pure + deterministic: the same schema produces byte-identical source. Line endings are explicit
/// <c>\n</c> (not <see cref="Environment.NewLine"/>) so the output is byte-lockable across machines.
/// </para>
/// </summary>
public static class SchemaCodegen
{
    /// <summary>Generate a C# <c>sealed record</c> declaration for the schema's type.</summary>
    /// <param name="schema">The type schema (IR) to render.</param>
    /// <returns>Compilable C# source for the record, prefixed with an auto-generated header.</returns>
    /// <exception cref="ArgumentNullException"><paramref name="schema"/> is <see langword="null"/>.</exception>
    public static string Generate(TypeSchema schema)
    {
        ArgumentNullException.ThrowIfNull(schema);

        var sb = new StringBuilder();
        sb.Append("// <auto-generated/> Generated by Zeta.Core.CSharp.SchemaCodegen from a zeta type schema. Do not edit.\n");
        sb.Append("#nullable enable\n");
        sb.Append("namespace ").Append(schema.Namespace).Append(";\n\n");
        sb.Append("public sealed record ").Append(schema.TypeName).Append('(');

        for (var i = 0; i < schema.Fields.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            SchemaField field = schema.Fields[i];
            sb.Append(field.CsType).Append(' ').Append(field.Name);
        }

        sb.Append(");\n");
        return sb.ToString();
    }
}
