#!/usr/bin/env bash
# tools/backlog/generate-index.sh
#
# Regenerates docs/BACKLOG.md from per-row files at
# docs/backlog/P<tier>/B-<NNNN>-<slug>.md. Walks those files,
# parses YAML frontmatter, emits a short-pointer index
# sorted by (priority, id).
#
# Origin: maintainer Otto-181 directive to split BACKLOG.md.
# See docs/research/backlog-split-design-otto-181.md for the
# design spec.
#
# Usage:
#   tools/backlog/generate-index.sh              # writes docs/BACKLOG.md
#   tools/backlog/generate-index.sh --check      # exits 2 if drift vs committed
#   tools/backlog/generate-index.sh --stdout     # prints to stdout, no write
#
# Exit codes:
#   0  success
#   1  environment / dependency error
#   2  drift detected (--check mode only)
#
# Dependencies: bash 4+, POSIX awk, sort, diff, find, mktemp.
# No external `yq` required; inline awk parser handles the
# flat frontmatter schema. `yq` integration is a Phase 1b
# upgrade path if nested frontmatter queries become needed.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
BACKLOG_DIR="${REPO_ROOT}/docs/backlog"
INDEX_PATH="${REPO_ROOT}/docs/BACKLOG.md"

mode="write"
while (( $# > 0 )); do
  case "$1" in
    --check)  mode="check"; shift ;;
    --stdout) mode="stdout"; shift ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

# Extract a frontmatter field from a markdown file using
# awk. Simple: reads the first YAML block (between two
# `---` lines) and grabs `field: value`. Doesn't handle
# nested structures — that's fine, our schema is flat.
extract_field() {
  local file="$1"
  local field="$2"
  awk -v field="$field" '
    BEGIN { state = 0; found = "" }   # 0=before, 1=inside, 2=after
    /^---$/ {
      if (state == 0) { state = 1; next }
      if (state == 1) { state = 2; next }    # Codex P1: stop after closing
    }
    state == 1 && $1 == field ":" {
      sub(/^[^:]+:[[:space:]]*/, "")
      # Copilot P1: POSIX-awk compatibility — use octal \047 (single-quote)
      # rather than hex \x27 which is not portable across POSIX awk
      # implementations (notably macOS awk).
      gsub(/^"|"$|^[[:space:]]*\047|\047[[:space:]]*$/, "")  # Codex P1: handle both " and '\''
      # Codex P2: trim trailing whitespace so `status: closed   ` still
      # matches the `closed)` case in generate().
      sub(/[[:space:]]+$/, "")
      found = $0
    }
    END { print found }
  ' "$file"
}

# Build index content.
# Output pattern per priority section:
#
#   ## P2 — research-grade
#
#   - [ ] **[B-0042](backlog/P2/B-0042-slug.md)** Title from frontmatter
#   - ...

generate() {
  cat <<'HEADER'
# Backlog Index

<!-- AUTO-GENERATED by tools/backlog/generate-index.sh.
     Do NOT edit this file directly. Edit the per-row file
     under docs/backlog/P<tier>/B-<NNNN>-<slug>.md and
     regenerate. -->

_Each entry below is a link to a per-row file under
`docs/backlog/`. Entries with `- [ ]` are open; `- [x]`
are closed (status: closed in frontmatter)._

HEADER

  # Stable section order
  for tier in P0 P1 P2 P3; do
    section_dir="${BACKLOG_DIR}/${tier}"
    [ -d "$section_dir" ] || continue
    # Codex P2: iterate via NUL-delimited find+sort | while read to avoid
    # shell word-splitting on whitespace in filenames. Handles paths
    # containing spaces without breaking into multiple tokens.
    has_files=0
    section_label=""
    case "$tier" in
      P0) section_label="## P0 — critical / blocking" ;;
      P1) section_label="## P1 — within 2-3 rounds" ;;
      P2) section_label="## P2 — research-grade" ;;
      P3) section_label="## P3 — convenience / deferred" ;;
    esac

    while IFS= read -r -d '' file; do
      if [ "$has_files" -eq 0 ]; then
        echo ""
        echo "$section_label"
        echo ""
        has_files=1
      fi

      link_path="backlog/${tier}/$(basename "$file")"

      id=$(extract_field "$file" "id")
      status=$(extract_field "$file" "status")
      title=$(extract_field "$file" "title")

      case "$status" in
        closed)                     checkbox="[x]" ;;
        superseded-by-*)            checkbox="[x]" ;;
        *)                          checkbox="[ ]" ;;
      esac

      printf -- "- %s **[%s](%s)** %s\n" \
        "$checkbox" "$id" "$link_path" "$title"
    done < <(find "$section_dir" -maxdepth 1 -name 'B-*.md' -type f -print0 2>/dev/null | sort -z)
  done

  cat <<'FOOTER'

<!-- END AUTO-GENERATED -->
FOOTER
}

# Generate into a temp file in the same directory as the
# target so mv is a same-filesystem atomic rename. Copilot
# P1: /tmp may be a different filesystem → mv falls back to
# copy+unlink, not atomic.
tmpout="$(mktemp "${INDEX_PATH}.tmp.XXXXXX")"
trap 'rm -f "$tmpout"' EXIT
generate > "$tmpout"

case "$mode" in
  stdout)
    cat "$tmpout"
    ;;
  check)
    if [ ! -f "$INDEX_PATH" ]; then
      echo "drift: $INDEX_PATH does not exist" >&2
      exit 2
    fi
    if ! diff -q "$tmpout" "$INDEX_PATH" >/dev/null; then
      echo "drift: $INDEX_PATH differs from generator output" >&2
      echo "diff:" >&2
      diff "$tmpout" "$INDEX_PATH" >&2 || true
      exit 2
    fi
    echo "ok: $INDEX_PATH matches generator output"
    ;;
  write)
    # Phase-1a safety guard: refuse to overwrite an
    # existing BACKLOG.md that has substantial content
    # (i.e. the pre-split monolithic backlog that
    # Phase 2 will migrate). Until Phase 2 migrates
    # content into per-row files, generator --write
    # would destroy the real backlog.
    #
    # Override with BACKLOG_WRITE_FORCE=1 when Phase 2
    # migration PR intentionally regenerates the index.
    if [ -f "$INDEX_PATH" ] && [ "${BACKLOG_WRITE_FORCE:-0}" != "1" ]; then
      existing_lines=$(wc -l < "$INDEX_PATH" | tr -d ' ')
      if [ "$existing_lines" -gt 50 ]; then
        cat >&2 <<'GUARDMSG'
generate-index.sh: refusing to overwrite existing
docs/BACKLOG.md — file has substantial content
(Phase-1a guard). Phase 2 content-migration PR should
set BACKLOG_WRITE_FORCE=1 to authorize the overwrite
once per-row files have been populated.

Use --stdout to preview, --check to compare against
committed, or set BACKLOG_WRITE_FORCE=1 to force.
GUARDMSG
        exit 1
      fi
    fi
    mv "$tmpout" "$INDEX_PATH"
    trap - EXIT
    echo "wrote $INDEX_PATH"
    ;;
esac
