// Falsifiers for the shared check-arity census substrate.
//
// Every test here exists because the property it pins was ABSENT while the coupling red-lined
// `main` on 2026-08-26. Two of them reproduce artefacts that were live on `main` at the moment this
// file was written: a duplicated key that `JSON.parse` swallowed, and a raise that the fix command
// must refuse to perform.
//
// The controls matter as much as the positives. A `--write` that silently accepted every raise
// would pass a "the fix command clears the check" test perfectly, and would be a silencer. So the
// refusal is asserted as loudly as the application.

import { describe, expect, test } from "bun:test";
import {
  annotation,
  censusDrift,
  censusNote,
  corpusTouched,
  isCanonical,
  planWrite,
  readCensusText,
  serializeCensus,
  tally,
} from "./check-arity-census.ts";

describe("canonical form -- the detector JSON.parse cannot be", () => {
  test("THE LIVE INSTANCE: a duplicated key is invisible to JSON.parse and caught by the round-trip", () => {
    // Verbatim shape of `registry/check-arity-nonequality-census.json` lines 50/52 on `c6e264ba`:
    // `f208f60a` (#15662) and `0054459b33` (#15646) each added this row by hand, hours apart.
    const text = `{
  "note": "n",
  "counts": {
    "a.test.ts": 3,
    "b.test.ts": 5,
    "a.test.ts": 3
  }
}
`;
    const read = readCensusText(text);
    expect(read.ok).toBe(true);
    if (!read.ok) return;
    // The counts parse CORRECTLY -- which is exactly why the audit passed for hours while the
    // checked-in artefact was not the artefact the audit describes.
    expect(read.census.counts).toEqual({ "a.test.ts": 3, "b.test.ts": 5 });
    // And the round-trip is what sees it.
    expect(read.canonical).toBe(false);
  });

  test("a row inserted OUT OF ORDINAL ORDER is caught -- the other hand-edit failure mode", () => {
    const text = `{
  "note": "n",
  "counts": {
    "z.test.ts": 1,
    "a.test.ts": 1
  }
}
`;
    const read = readCensusText(text);
    expect(read.ok).toBe(true);
    if (read.ok) expect(read.canonical).toBe(false);
  });

  test("the canonical rendering of a census round-trips as canonical", () => {
    const text = serializeCensus("n", { "b.test.ts": 2, "a.test.ts": 1 });
    const read = readCensusText(text);
    expect(read.ok).toBe(true);
    if (read.ok) expect(read.canonical).toBe(true);
  });

  test("serialization is ORDINAL, never locale-aware -- the same tree must emit the same bytes everywhere", () => {
    // `localeCompare` orders "Z" before "a" in many locales; UTF-16 code units never do.
    // .claude/rules/culture-invariant-by-default.md; live failure 081KT07NV0008QG0R001YDB73K.
    const keys = Object.keys(JSON.parse(serializeCensus("n", { "a.ts": 1, "Z.ts": 1, "B.ts": 1 })).counts);
    expect(keys).toEqual(["B.ts", "Z.ts", "a.ts"]);
  });

  test("the trailing newline is part of the artefact -- prettier emits one and would fight a writer that does not", () => {
    expect(serializeCensus("n", { "a.ts": 1 }).endsWith("}\n")).toBe(true);
  });

  test("a malformed census is a FAILURE, never an empty one -- an unreadable census must not read as a clean tree", () => {
    expect(readCensusText("not json").ok).toBe(false);
    expect(readCensusText('{"note":"n"}').ok).toBe(false);
    expect(readCensusText('{"counts":{"a.ts":-1}}').ok).toBe(false);
    expect(readCensusText('{"counts":{"a.ts":"three"}}').ok).toBe(false);
  });

  test("isCanonical compares against the census's OWN note, so a note change is drift not a silent rewrite", () => {
    const text = serializeCensus("old note", { "a.ts": 1 });
    expect(isCanonical(text, { note: "old note", counts: { "a.ts": 1 } })).toBe(true);
    expect(isCanonical(text, { note: "new note", counts: { "a.ts": 1 } })).toBe(false);
  });

  test("the note names the command that produced the file", () => {
    expect(censusNote("audit-check-arity.ts")).toBe("generated by audit-check-arity.ts --emit-census");
  });
});

describe("the ratchet fires in BOTH directions", () => {
  test("a new site rises", () => {
    const d = censusDrift({}, { "a.ts": 1 });
    expect(d.rose).toEqual([{ path: "a.ts", was: 0, now: 1 }]);
    expect(d.fell).toEqual([]);
  });

  test("a removed site falls -- a row nobody lowers converges on a suppression list", () => {
    const d = censusDrift({ "a.ts": 1 }, {});
    expect(d.fell).toEqual([{ path: "a.ts", was: 1, now: 0 }]);
    expect(d.rose).toEqual([]);
  });

  test("an unchanged count is silent", () => {
    const d = censusDrift({ "a.ts": 1 }, { "a.ts": 1 });
    expect(d.rose).toEqual([]);
    expect(d.fell).toEqual([]);
  });

  test("drift is reported in ordinal path order, so the message is diffable across machines", () => {
    const d = censusDrift({}, { "z.ts": 1, "a.ts": 1, "B.ts": 1 });
    expect(d.rose.map((x) => x.path)).toEqual(["B.ts", "a.ts", "z.ts"]);
  });
});

describe("the fix command may NOT silence a finding -- the guard, asserted as loudly as the fix", () => {
  test("`--write` LOWERS and REMOVES freely: neither carries a judgement", () => {
    const p = planWrite({ "a.ts": 3, "b.ts": 1 }, { "a.ts": 1 }, false);
    expect(p.next).toEqual({ "a.ts": 1 });
    expect(p.applied.map((d) => d.path).sort()).toEqual(["a.ts", "b.ts"]);
    expect(p.refused).toEqual([]);
  });

  test("`--write` REFUSES a raise, and leaves the OLD value so the ratchet still fires next run", () => {
    const p = planWrite({ "a.ts": 1 }, { "a.ts": 4 }, false);
    expect(p.refused).toEqual([{ path: "a.ts", was: 1, now: 4 }]);
    expect(p.accepted).toEqual([]);
    // THE LOAD-BEARING ASSERTION. If the refusal wrote the new value anyway, the finding would be
    // silenced by a different door and this whole guard would be decoration.
    expect(p.next["a.ts"]).toBe(1);
  });

  test("`--write` refuses a BRAND-NEW row and does not create it", () => {
    const p = planWrite({}, { "new.ts": 2 }, false);
    expect(p.refused).toHaveLength(1);
    expect(p.next).toEqual({});
  });

  test("`--write --accept-raises` records the judgement -- the deliberate, separately spelled half", () => {
    const p = planWrite({ "a.ts": 1 }, { "a.ts": 4 }, true);
    expect(p.accepted).toEqual([{ path: "a.ts", was: 1, now: 4 }]);
    expect(p.refused).toEqual([]);
    expect(p.next["a.ts"]).toBe(4);
  });

  test("a lower and a raise in one run: the lower applies, the raise does not", () => {
    const p = planWrite({ "down.ts": 5, "up.ts": 1 }, { "down.ts": 2, "up.ts": 9 }, false);
    expect(p.next).toEqual({ "down.ts": 2, "up.ts": 1 });
    expect(p.applied.map((d) => d.path)).toEqual(["down.ts"]);
    expect(p.refused.map((d) => d.path)).toEqual(["up.ts"]);
  });

  test("a zero-count row is never written back -- absence is the canonical spelling of zero", () => {
    expect(planWrite({ "a.ts": 0 }, {}, false).next).toEqual({});
  });
});

describe("annotations carry the finding into the check-run", () => {
  // Every 2026-08-26 episode of this job showed exactly `Process completed with exit code 1` and
  // nothing else; the finding lived only in the step log.
  test("file, line and title are all present", () => {
    const a = annotation({ file: "a/b.test.ts", line: 73, title: "R2: 1 site", message: "count rose 0 -> 1" });
    expect(a).toBe("::error file=a/b.test.ts,line=73,title=R2%3A 1 site::count rose 0 -> 1");
  });

  test("a MULTI-LINE message survives -- unescaped, GitHub truncates at the first newline", () => {
    const a = annotation({ title: "t", message: "line one\nline two" });
    expect(a).toContain("line one%0Aline two");
    expect(a.split("\n")).toHaveLength(1);
  });

  test("`%` is escaped first, so an escape sequence cannot be produced by the payload itself", () => {
    expect(annotation({ title: "t", message: "100%0Anot-a-newline" })).toContain("100%250Anot-a-newline");
  });

  test("`:` and `,` are escaped in PROPERTIES -- they are the field separators", () => {
    const a = annotation({ file: "a,b:c.ts", title: "x,y:z", message: "m" });
    expect(a).toContain("file=a%2Cb%3Ac.ts");
    expect(a).toContain("title=x%2Cy%3Az");
  });

  test("line is omitted when unknown rather than faked to 1 -- a wrong line is worse than none", () => {
    expect(annotation({ file: "a.ts", title: "t", message: "m" })).toBe("::error file=a.ts,title=t::m");
  });
});

describe("self-scoping keeps the preflight guard cheap enough to survive", () => {
  const isCorpus = (p: string): boolean => p.startsWith("tests/") && p.endsWith(".fs");

  test("a change touching no corpus file and no own path is SKIPPED", () => {
    expect(corpusTouched(["README.md", "src/Core/Foo.fs"], isCorpus, ["registry/c.json"])).toEqual([]);
  });

  test("a corpus file is caught", () => {
    expect(corpusTouched(["tests/A.Tests.fs", "README.md"], isCorpus, [])).toEqual(["tests/A.Tests.fs"]);
  });

  test("the census and the audit itself are own paths -- editing the deriver must re-check", () => {
    expect(corpusTouched(["registry/c.json"], isCorpus, ["registry/c.json"])).toEqual(["registry/c.json"]);
  });

  test("windows separators normalize, so the guard is not silently disabled on one platform", () => {
    expect(corpusTouched(["tests\\A.Tests.fs"], isCorpus, [])).toEqual(["tests/A.Tests.fs"]);
  });

  test("blank lines in a changed-file list are not paths", () => {
    expect(corpusTouched(["", "  "], isCorpus, [])).toEqual([]);
  });
});

describe("tally", () => {
  test("counts sites per path", () => {
    expect(tally([{ path: "a" }, { path: "a" }, { path: "b" }])).toEqual({ a: 2, b: 1 });
  });

  test("an empty site list is an empty census, not a census of zeroes", () => {
    expect(tally([])).toEqual({});
  });
});
